### ISSUE TITLE
SOC doesn't updated

### ISSUE THREAD

**Issue by Minecrawler1990** [flobz/psa_car_controller#1016]
Hallo,

I have a problem with the SOC of my car. 
Installation and Login to my Opel account works fine.

But I can't updated the SOC with the manual button.
I always get the following Errors or Warnings in the Logfile:

2024-12-30 16:38:58,484 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:38:58] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:39:08,615 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:39:08] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:39:10,540 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:39:10] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:39:10,547 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:39:10] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 -
2024-12-30 16:39:10,554 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:39:10] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 -
2024-12-30 16:39:45,523 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:39:45] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:40:06,420 :: INFO :: Connected with result code {'session present': 0}
2024-12-30 16:40:06,421 :: INFO :: subscribe to psa/RemoteServices/to/cid/OV-ACNT200008410820/#
2024-12-30 16:40:06,421 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/xxx
2024-12-30 16:40:06,423 :: WARNING :: Disconnected with result code 5
2024-12-30 16:40:06,423 :: WARNING :: The connection was refused.
2024-12-30 16:40:16,054 :: ERROR :: Can't refresh remote token, please redo otp procedure
Traceback (most recent call last):

When I do the OTP procedure the the SOC of the car updated one time:

2024-12-30 16:40:16,055 :: ERROR :: Can't configure MQTT Client
2024-12-30 16:40:16,059 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:16] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:40:18,390 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:18] "[37mGET / HTTP/1.1[0m" 200 -
2024-12-30 16:40:19,037 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:19] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-12-30 16:40:19,043 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:19] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2024-12-30 16:40:19,209 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:19] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:40:19,458 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:19] "[37mGET /control?header=false HTTP/1.1[0m" 200 -
2024-12-30 16:40:22,658 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:22] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:40:25,668 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:25] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:40:25,675 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:25] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:40:25,682 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:25] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:40:25,688 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:25] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 -
2024-12-30 16:40:25,694 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:25] "[37mGET /style.json HTTP/1.1[0m" 200 -
2024-12-30 16:40:25,699 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:25] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-12-30 16:40:25,854 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:25] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2024-12-30 16:40:26,216 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:26] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:40:30,727 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:30] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:40:32,479 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:32] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:40:32,485 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:32] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 -
2024-12-30 16:40:32,492 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:40:32] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 -
2024-12-30 16:40:49,794 :: INFO :: charging status of xxx is InProgress, battery level: 65
2024-12-30 16:40:49,795 :: INFO :: charging status of xxx is InProgress, battery level: 65
2024-12-30 16:40:49,795 :: INFO :: charging status of xxx is InProgress, battery level: 65
2024-12-30 16:41:00,534 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:41:00] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:41:00,821 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:41:00] "[37mGET /control?header=false HTTP/1.1[0m" 200 -
2024-12-30 16:41:04,583 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:41:04] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:41:04,590 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:41:04] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:41:07,601 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:41:07] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:41:07,608 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:41:07] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:41:07,615 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:41:07] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 -
2024-12-30 16:41:07,621 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:41:07] "[37mGET /style.json HTTP/1.1[0m" 200 -
2024-12-30 16:41:07,627 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:41:07] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-12-30 16:41:07,633 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:41:07] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2024-12-30 16:41:08,180 :: INFO :: 192.168.1.188 - - [30/Dec/2024 16:41:08] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-12-30 16:41:31,107 :: INFO :: ask wakeup to xxx
2024-12-30 16:41:31,108 :: INFO :: topic: psa/RemoteServices/from/cid/OV-ACNT200008410820/VehCharge/state: {'action': 'state'}
2024-12-30 16:41:31,109 :: ERROR :: Can't refresh remote token, please redo otp procedure
Traceback (most recent call last):

But only on time.
Then I have to do the OTP procedure again.

Can you please help me?

Thank you!

Greets Daniel

**Comment by Minecrawler1990** [comment]
Here another part of the log:

2024-12-30 16:54:49,822 :: ERROR :: force_update:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/charge_control.py", line 70, in force_update
self.psacc.remote_client.wakeup(self.vin)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
raise RateLimitException
psa_car_controller.common.utils.RateLimitException
