### ISSUE TITLE
[New Car model] my model

### ISSUE THREAD

**Issue by riddik14** [flobz/psa_car_controller#111]
I have a "Can't get car model" error.
Information to add my car model to the app:
- Brand: Peugeot
- Model: 2008 allure pack 3d nav
- First ten letter of my VIN:  V
- Useable Electric capacity in kw: no- gasoline
- Fuel capacity in liter: 44

**Comment by riddik14** [comment]
i have this error if i set IT country
MyPeugeot password: 
What is your country code ? (ex: FR, GB, DE, ES...)
IT
Traceback (most recent call last):
  File "app_decoder.py", line 84, in <module>
    token = res.json()["accessToken"]
KeyError: 'accessToken'
HOST_BRANDID : https://id-dcr.peugeot.com/mobile-services sitecode: AP_IT_ESP
{"returnCode":"AUTHENTICATION_FAILED"}

**Comment by riddik14** [comment]
if i use FR

this is error

What is your country code ? (ex: FR, GB, DE, ES...)
FR
Traceback (most recent call last):
  File "app_decoder.py", line 84, in <module>
    token = res.json()["accessToken"]
KeyError: 'accessToken'
HOST_BRANDID : https://id-dcr.peugeot.com/mobile-services sitecode: AP_FR_ESP

why? i am registered on psa api develop, in app iphone i receive info about car

**Comment by flobz** [comment]
I close the issue because you don't fill correctly "First ten letter of my VIN"

**Comment by riddik14** [comment]
Sorry FOR vin
Information to add my car model to the app:

Brand: Peugeot
Model: 2008 allure pack 3d nav
First ten letter of my VIN: VR3USHNSKM
engine 1.2 130hp
Useable Electric capacity in kw: no- gasoline
Fuel capacity in liter: 44
