### ISSUE TITLE
Internal Server Error / Traceback when executing charge control comands

### ISSUE THREAD

**Issue by hurzhurz** [flobz/psa_car_controller#127]
**Describe the bug**
Internal Server Error / Traceback when executing charge control commands (e.g. /charge_now/...) if time is set to "00:00" in app.
In this case, the next_delayed_time string is "PT0S", which is not covered by the regular expression at https://github.com/flobz/psa_car_controller/blob/master/my_psacc.py#L340

**Environment (please complete the following information):**
 - Docker container from 2 days ago
 - MyOpel Android App v1.29.3
 - Opel Corsa-e

**Additional context**
```
2021-05-16 11:03:57,821 :: ERROR :: Can't get charge hour: PT0S
Traceback (most recent call last):
  File "/psa_car_controller/my_psacc.py", line 344, in __get_charge_hour
    hour_minute = re.findall(reg, hour_str)[0]
IndexError: list index out of range
Exception on /charge_now/VXKUHZKXZLxxxxxx/0 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/psa_car_controller/web/views.py", line 139, in charge_now
    return jsonify(myp.charge_now(vin, charge != 0))
  File "/psa_car_controller/my_psacc.py", line 374, in charge_now
    hour, minute = self.__get_charge_hour(vin)
TypeError: cannot unpack non-iterable NoneType object
192.168.x.x - - [16/May/2021 11:03:57] "GET /charge_now/VXKUHZKXZLxxxxxx/0 HTTP/1.1" 500 -
```

**Comment by flobz** [comment]
Thanks for reporting this bug, it should be fixed with : d2864ea
