### ISSUE TITLE
issues with starting the server under Windows and also on the Pi

### ISSUE THREAD

**Issue by mitch1101** [flobz/psa_car_controller#135]
**Describe the bug**
1)certificate verification failure: it seems that the webpage cannot be confirmed:
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verif
y failed: unable to get local issuer certificate (_ssl.c:1131)
2)UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 22: invalid start byte

**To Reproduce**
1. what command did you use
python server.py -f test.json -c charge_config1.json / python3 server.py -f test.json -c charge_config1.json
2. when the bug append ?
3. Does it persist after restarting the program? yes

**Config file**
{
    "abrp": {
        "abrp_enable_vin": [],
        "token": ""
    },
    "client_id": "xxx",
    "client_secret": "yyy",
    "co2_signal_api": null,
    "country_code": "DE",
    "customer_id": "AP-ACNTzzz",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2CPeugeot",
    "refresh_token": "xxx",
    "remote_refresh_token": "yyy,
    "weather_api": null

**Environment (please complete the following information):**
 - OS: [e.g. Windows] 1) Windows 7 (64bit) / 2) Raspbian GNU/Linux 10 (buster)
 - Android app Version [e.g. 26.0] 1.27.1
 - Brand and model of car Peugeot e-2008
 - Application version (commit number, branch) 

**Additional context**

**Comment by flobz** [comment]
Can you give more details about the bugs?

**Comment by mitch1101** [comment]
which kind of details do you need? i am not sure if it is a bug within your scripts.
I would assume more that something might be wrong with the python installation or system variables, which are needed to run the script successful.

**Comment by mitch1101** [comment]
ok, here the full error messages:

1)C:\Users\User\Documents\psa_car_controller-master>python server.py -f test.json
-c charge_config1.json
2021-05-20 13:15:48,263 :: INFO :: server start
2021-05-20 13:15:48,813 :: INFO :: save config change
2021-05-20 13:15:49,487 :: INFO :: ["{'vin': 'VR3xxx', 'vehicle_id':
'yyy', 'label': 'e
-2008', 'brand': 'Peugeot', 'abrp_name': 'peugeot:e2008:20:48', 'battery_power':
 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"
]
2021-05-20 13:15:49,974 :: INFO :: save config change
Traceback (most recent call last):
  File "server.py", line 78, in <module>
    web.app.myp.start_mqtt()
  File "C:\Users\User\Documents\psa_car_controller-master\my_psacc.py", line 325
, in start_mqtt
    self.mqtt_client.connect(MQTT_SERVER, 8885, 60)
  File "C:\Users\User\Documents\Python\Python38-32\lib\site-packages\paho\mqtt\c
lient.py", line 941, in connect
    return self.reconnect()
  File "C:\Users\User\Documents\Python\Python38-32\lib\site-packages\paho\mqtt\c
lient.py", line 1104, in reconnect
    sock.do_handshake()
  File "C:\Users\User\Documents\Python\Python38-32\lib\ssl.py", line 1309, in do
_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verif
y failed: unable to get local issuer certificate (_ssl.c:1131)

2) python3 server.py -f test.json -c charge_config1.json
2021-05-21 11:48:03,456 :: INFO :: server start
Traceback (most recent call last):
  File "server.py", line 60, in <module>
    Charging.elec_price = ElecPrice.read_config()
  File "/home/pi/psa_car_controller-master/libs/elec_price.py", line 76, in read_config
    if len(config.read(name)) == 0:
  File "/usr/lib/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.7/configparser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 22: invalid start byte
2021-05-21 11:48:03,463 :: INFO :: save config change

**Comment by flobz** [comment]
1. Look like a windows issue, please search on internet
2. There is a bad character in config.ini file, it can happen if you edit the file on windows and move it on the raspberry. Delete config.ini and retry

**Comment by mitch1101** [comment]
the error is gone after deleting the config.ini

but the server is still not starting: now i am getting this error:

python3 server.py -f test.json -c charge_config1.json
2021-05-25 12:27:38,921 :: INFO :: server start
2021-05-25 12:27:39,610 :: INFO :: save config change
2021-05-25 12:27:40,545 :: INFO :: ["{'vin': 'VR3UKZKXZMJ631789', 'vehicle_id': '1566c497a565574615331686154556f324d7a45334f446b6a493249794f545a6d4d4745314d57526c5a6a46694e6d59784d4456685a6a4e6b4e325130597a63354f5751324d4445775a4451774e4467785a6a4d354e7a51334e4452694d6d526a4d474d77596a6b7a5954566c4e444d3d', 'label': 'e-2008', 'brand': 'Peugeot', 'abrp_name': 'peugeot:e2008:20:48', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
2021-05-25 12:27:43,386 :: INFO :: save config change
Traceback (most recent call last):
  File "server.py", line 78, in <module>
    web.app.myp.start_mqtt()
  File "/home/pi/psa_car_controller-master/my_psacc.py", line 325, in start_mqtt
    self.mqtt_client.connect(MQTT_SERVER, 8885, 60)
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/home/pi/.local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
