### ISSUE TITLE
Error authorization.denied.cvs.response.no.matching.service.key

### ISSUE THREAD

**Issue by iamrellah** [flobz/psa_car_controller#136]
**Describe the bug**
Error seems to occur after requesting the car to do something like turning on airconditioning

**To Reproduce**
1. Use the URL to access the preconditioning "GET /preconditioning/VIN/1"

**Config file**
```
{
    "abrp": {
        "abrp_enable_vin": [],
        "token": ""
    },
    "client_id": "ID",
    "client_secret": "Secret",
    "co2_signal_api": null,
    "country_code": "NL",
    "customer_id": "OP-ACNT200007423544",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2COpel",
    "refresh_token": "token",
    "remote_refresh_token": "token",
    "weather_api": null
}
```

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Android app Version: 1.27.1
 - Brand and model of car: Opel Corsa-E
 - Application version: d32d3bdf5f6fb144d7dd7a5b1333898ed3ba4df2

**Additional context**

```
~/psa_car_controller$ python3 server.py -f test.json -c charge_config1.json -l IP -r -d
2021-05-20 20:45:59,212 :: INFO :: server start
2021-05-20 20:45:59,529 :: INFO :: save config change
2021-05-20 20:46:00,181 :: INFO :: ["{'vin': 'VIN', 'vehicle_id': '1566c684c56556861533168615444517a4d7a6b784f44556a493251304f4749344e544935595455304f445931596a4178595467794e324e695a574d794e544d314d5467785a5467784f574e6a59546c6d4d54426c4e574535597a5a684e7a517a596a6c685a6a41784f44497a5a6a633d', 'label': 'corsa-e', 'brand': 'C', 'abrp_name': 'opel:corsae:20:50', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
2021-05-20 20:46:00,443 :: INFO :: save config change
2021-05-20 20:46:00,705 :: DEBUG :: refresh_remote_token: {'scope': 'psaCustomerId psaMqttService', 'expires_in': 899, 'token_type': 'Bearer', 'access_token': 'e890cb89-efa1-42bd-b6c7-8dce5813d719', 'refresh_token': '4b35e613-b75c-410b-a63d-deff8720bf79'}
2021-05-20 20:46:00,767 :: INFO :: ask state to VIN
2021-05-20 20:46:00,957 :: INFO :: Connected with result code {'session present': 0}
2021-05-20 20:46:00,958 :: INFO :: subscribe to psa/RemoteServices/to/cid/OV-ACNT200007423544/#
2021-05-20 20:46:00,958 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VIN
2021-05-20 20:46:01,093 :: INFO :: save config change
2021-05-20 20:46:01,094 :: INFO :: {"access_token": "e890cb89-efa1-42bd-b6c7-8dce5813d719", "customer_id": "OV-ACNT200007423544", "correlation_id": "363698ccd2a546ba9eb5f88f66ae03bf20210520184601094", "req_date": "2021-05-20T18:46:01Z", "vin": "VIN", "req_parameters": {"action": "state"}}
2021-05-20 20:46:01,721 :: INFO :: mqtt msg psa/RemoteServices/to/cid/OV-ACNT200007423544/VehicleState b'{"resp_date":"2021-05-20T18:46:01Z","vin":"VIN","correlation_id":"363698ccd2a546ba9eb5f88f66ae03bf20210520184601094","return_code":"400","reason":"[authorization.denied.cvs.response.no.matching.service.key]"}'
2021-05-20 20:46:02,070 :: INFO :: save config change
2021-05-20 20:46:02,361 :: DEBUG :: refresh_remote_token: {'scope': 'psaCustomerId psaMqttService', 'expires_in': 899, 'token_type': 'Bearer', 'access_token': 'e580d3f3-7758-4079-bfad-20987757165d', 'refresh_token': '4b35e613-b75c-410b-a63d-deff8720bf79'}
2021-05-20 20:46:02,362 :: ERROR :: retry last request, token was expired
2021-05-20 20:46:02,511 :: INFO :: update_data
2021-05-20 20:46:04,586 :: DEBUG :: No trips yet
2021-05-20 20:46:04,588 :: DEBUG :: No chargings yet
2021-05-20 20:46:04,592 :: DEBUG :: Create new layout
 * Running on http://IP:5000/ (Press CTRL+C to quit)
2021-05-20 20:46:26,804 :: INFO :: ask state to VIN
2021-05-20 20:46:27,159 :: INFO :: save config change
2021-05-20 20:46:27,160 :: INFO :: {"access_token": "e580d3f3-7758-4079-bfad-20987757165d", "customer_id": "OV-ACNT200007423544", "correlation_id": "ac9ed3048bfe47a5a859701c77cf149520210520184627160", "req_date": "2021-05-20T18:46:27Z", "vin": "VIN", "req_parameters": {"action": "state"}}
2021-05-20 20:46:28,082 :: INFO :: mqtt msg psa/RemoteServices/to/cid/OV-ACNT200007423544/VehicleState b'{"resp_date":"2021-05-20T18:46:28Z","vin":"VIN","correlation_id":"ac9ed3048bfe47a5a859701c77cf149520210520184627160","return_code":"400","reason":"[authorization.denied.cvs.response.no.matching.service.key]"}'
2021-05-20 20:46:28,444 :: INFO :: save config change
2021-05-20 20:46:28,715 :: DEBUG :: refresh_remote_token: {'scope': 'psaCustomerId psaMqttService', 'expires_in': 899, 'token_type': 'Bearer', 'access_token': '7a22eb52-07c6-4a46-b35c-b2fe083df01a', 'refresh_token': '4b35e613-b75c-410b-a63d-deff8720bf79'}
2021-05-20 20:46:28,718 :: ERROR :: retry last request, token was expired
2021-05-20 20:46:29,429 :: INFO :: save config change
2021-05-20 20:46:29,430 :: INFO :: {"access_token": "7a22eb52-07c6-4a46-b35c-b2fe083df01a", "customer_id": "OV-ACNT200007423544", "correlation_id": "96427ee5a7e04360815a2bacdc7b3d3520210520184629430", "req_date": "2021-05-20T18:46:29Z", "vin": "VIN", "req_parameters": {"asap": "activate", "programs": {"program1": {"day": [0, 0, 0, 0, 0, 0, 0], "hour": 34, "minute": 7, "on": 0}, "program2": {"day": [0, 0, 0, 0, 0, 0, 0], "hour": 34, "minute": 7, "on": 0}, "program3": {"day": [0, 0, 0, 0, 0, 0, 0], "hour": 34, "minute": 7, "on": 0}, "program4": {"day": [0, 0, 0, 0, 0, 0, 0], "hour": 34, "minute": 7, "on": 0}}}}
IP - - [20/May/2021 20:46:29] "GET /preconditioning/VIN/1 HTTP/1.1" 200 -
2021-05-20 20:46:37,950 :: DEBUG :: vin:VIN longitude:LONG latitude:LATI date:2021-04-02 09:13:51+00:00 mileage:8027.8 level:88.0 charge_date:2021-05-20 18:45:59+00:00 level_fuel:None moving:False
2021-05-20 20:46:37,953 :: DEBUG :: position already saved
2021-05-20 20:46:37,954 :: DEBUG :: No abrp token provided
2021-05-20 20:46:37,955 :: DEBUG :: battery table is probably empty :
Traceback (most recent call last):
  File "/home/paul/psa_car_controller/libs/charging.py", line 63, in record_charging
    "DESC limit 1", (car.vin,)).fetchone()
TypeError: 'NoneType' object is not iterable
2021-05-20 20:46:37,956 :: DEBUG :: charging_status:Disconnected 
IP - - [20/May/2021 20:46:37] "GET /get_vehicleinfo/VIN HTTP/1.1" 200 -
2021-05-20 20:46:37,960 :: INFO :: <Request 'http://IP:5000/charge_control?vin=VIN&%3Falways_check=true' [GET]>
2021-05-20 20:46:37,962 :: INFO :: save config change
IP - - [20/May/2021 20:46:37] "GET /charge_control?vin=VIN&?always_check=true HTTP/1.1" 200 -
2021-05-20 20:46:54,136 :: INFO :: mqtt msg psa/RemoteServices/to/cid/OV-ACNT200007423544/ThermalPrecond/ProcessManagement b'{"process_date":"2021-05-20T18:46:54Z","vin":"VIN","correlation_id":"96427ee5a7e04360815a2bacdc7b3d3520210520184629430","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2021-05-20 20:46:54,137 :: DEBUG :: mqtt msg hasn't return code
2021-05-20 20:46:54,271 :: INFO :: mqtt msg psa/RemoteServices/to/cid/OV-ACNT200007423544/ThermalPrecond/ProcessManagement b'{"process_date":"2021-05-20T18:46:54Z","vin":"VIN","correlation_id":"96427ee5a7e04360815a2bacdc7b3d3520210520184629430","process_code":"903","process_message":"[process.903.request.forwarded.to.vehicle.key]"}'
2021-05-20 20:46:54,272 :: DEBUG :: mqtt msg hasn't return code
2021-05-20 20:46:54,410 :: INFO :: mqtt msg psa/RemoteServices/to/cid/OV-ACNT200007423544/ThermalPrecond b'{"resp_date":"2021-05-20T18:46:54Z","vin":"VIN","correlation_id":"96427ee5a7e04360815a2bacdc7b3d3520210520184629430","return_code":"404","resp_data":{"error":1}}'
2021-05-20 20:46:54,410 :: ERROR :: mqtt message:
Traceback (most recent call last):
  File "/home/paul/psa_car_controller/my_psacc.py", line 301, in __on_mqtt_message
    logger.error('%s : %s', data["return_code"], data["reason"])
KeyError: 'reason'
2021-05-20 20:47:03,820 :: INFO :: mqtt msg psa/RemoteServices/to/cid/OV-ACNT200007423544/ThermalPrecond b'{"resp_date":"2021-05-20T18:47:03Z","vin":"VIN","correlation_id":"30eff54536b44fd99e475b363d3c512220210520184228542","return_code":"404","resp_data":{"error":1}}'
2021-05-20 20:47:03,822 :: ERROR :: mqtt message:
Traceback (most recent call last):
  File "/home/paul/psa_car_controller/my_psacc.py", line 301, in __on_mqtt_message
    logger.error('%s : %s', data["return_code"], data["reason"])
KeyError: 'reason'
2021-05-20 20:47:10,607 :: INFO :: mqtt msg psa/RemoteServices/to/cid/OV-ACNT200007423544/VehicleState b'{"resp_date":"2021-05-20T18:47:10Z","vin":"VIN","correlation_id":"3bf9e2b250f9463fb55f0050af6fe7c320210520184315534","return_code":"400","reason":"[authorization.denied.cvs.response.no.matching.service.key]"}'
2021-05-20 20:47:10,869 :: INFO :: save config change
2021-05-20 20:47:11,175 :: DEBUG :: refresh_remote_token: {'scope': 'psaCustomerId psaMqttService', 'expires_in': 899, 'token_type': 'Bearer', 'access_token': 'cb96f901-fe03-4477-92ef-2156f2a60915', 'refresh_token': '4b35e613-b75c-410b-a63d-deff8720bf79'}
2021-05-20 20:47:11,179 :: ERROR :: retry last request, token was expired
2021-05-20 20:47:37,911 :: DEBUG :: vin:VIN longitude:LONG latitude:LATI date:2021-04-02 09:13:51+00:00 mileage:8027.8 level:88.0 charge_date:2021-05-20 18:46:59+00:00 level_fuel:None moving:False
2021-05-20 20:47:37,914 :: DEBUG :: position already saved
2021-05-20 20:47:37,916 :: DEBUG :: No abrp token provided
2021-05-20 20:47:37,917 :: DEBUG :: battery table is probably empty :
Traceback (most recent call last):
  File "/home/paul/psa_car_controller/libs/charging.py", line 63, in record_charging
    "DESC limit 1", (car.vin,)).fetchone()
TypeError: 'NoneType' object is not iterable
2021-05-20 20:47:37,919 :: DEBUG :: charging_status:Disconnected 
IP - - [20/May/2021 20:47:37] "GET /get_vehicleinfo/VIN HTTP/1.1" 200 -
2021-05-20 20:47:37,924 :: INFO :: <Request 'http://IP:5000/charge_control?vin=VIN&%3Falways_check=true' [GET]>
IP - - [20/May/2021 20:47:37] "GET /charge_control?vin=VIN&?always_check=true HTTP/1.1" 200 -

```

Also tried to re-run the decoded script and deleted the otp.bin to recreate the token again.

**Comment by flobz** [comment]
I had the same issue at the same time as you but now it seems ok....
It seems that they updated the MQTT server, message aren't the same. 
Maybe a good news for #50 ?

**Comment by iamrellah** [comment]
@flobz you're currently not experiencing this? I just retried this again but i get the same message. Deleted the OTP.bin file to trigger the token process again

**Comment by CalicodesIles** [comment]
Regarding #50 still nothing new. I used twice my car today for more than 2 hours (one this morning, another one at the end of the afternoon) but no improvement about trip reporting in services like Tronity.io

**Comment by hurzhurz** [comment]
I get the "authorization.denied.cvs.response.no.matching.service.key" error, too.
@flobz How did you learn about the topic "psa/RemoteServices/to/cid/xxx/VehicleState"?
It doesn't look like the myOpel-App isn't using it at all. 

In case of preconditioning, where also the information about the existing programs is needed, it looks like the app gets this info via https://api.groupe-psa.com/connectedcar/v4/user/vehicles/xxx/status?client_id=xxx

I also noticed that the preconditioning data is also included in messages on the event topic.
But it looks like only the charge info is used from these messages?: https://github.com/flobz/psa_car_controller/blob/master/my_psacc.py#L306
A workaround (if the VehicleState topic is dead forever) could be to trigger a wakeup to get such event messages...
Or using above API url instead to get most of the data?

**Comment by flobz** [comment]
Sorry you right, VehicleState is dead. So code needs to be updated to use  event topic as you said.

> @flobz How did you learn about the topic "psa/RemoteServices/to/cid/xxx/VehicleState"?
It's not used by android app even if it's in the android app source code but it's useful for psa_car_controller so I use it.
I'm not sure we can trigger an event topic... but we can make a "wakeup" and receive a response.

**Comment by thommierother** [comment]
I have the same issue with 208 GT. After deletion of otp.bin and re-authentication with SMS code and Mypeugeot PIN the API reguests are running again, so the access token was gone, I assume
