### ISSUE TITLE
don't download data from app with by using --remote-disable argument.

### ISSUE THREAD

**Issue by riddik14** [flobz/psa_car_controller#138]
sorry, work but don't download data from app with by using --remote-disable argument.
web page are empty.

manual command:

/usr/local/bin/psa_car_controller -f /home/psa_remote/config.json -c /home/psa_remote/charge_config.json --mail mymail@icloud.com --password password --remote-disable -l 192.168.1.41 -R 1 -r

output: 

(.env) psa_remote@debian:/usr/local/src/psa_car_controller$ /usr/local/bin/psa_car_controller -f /home/psa_remote/config.json -c /home/psa_remote/charge_config.json --mail mail@icloud.com --password pass --remote-disable -l 192.168.1.41 -R 10 -r -d
2021-05-21 20:52:33,536 :: INFO :: server start
2021-05-21 20:52:35,123 :: INFO :: save config change
2021-05-21 20:52:36,822 :: INFO :: ["{'vin': 'VR3USHNSK', 'vehicle_id': 'myid', 'label': '2008', 'brand': 'Peugeot', 'abrp_name': None, 'battery_power': 0, 'fuel_capacity': 46, 'max_elec_consumption': 70, 'max_fuel_consumption': 30}"]
2021-05-21 20:52:36,822 :: INFO :: mqtt disabled
2021-05-21 20:52:37,782 :: INFO :: update_data
2021-05-21 20:52:39,416 :: DEBUG :: No trips yet
2021-05-21 20:52:39,419 :: DEBUG :: No chargings yet
2021-05-21 20:52:39,420 :: DEBUG :: Create new layout
 * Running on http://192.168.1.41:5000/ (Press CTRL+C to quit)
192.168.1.40 - - [21/May/2021 20:52:54] "GET / HTTP/1.1" 200 -
192.168.1.40 - - [21/May/2021 20:52:55] "GET /assets/clientside.js?m=1621207248.2707653 HTTP/1.1" 304 -
192.168.1.40 - - [21/May/2021 20:52:55] "GET /_dash-layout HTTP/1.1" 200 -
192.168.1.40 - - [21/May/2021 20:52:55] "GET /_dash-dependencies HTTP/1.1" 200 -
192.168.1.40 - - [21/May/2021 20:52:56] "GET /_favicon.ico?v=1.20.0 HTTP/1.1" 200 -
192.168.1.40 - - [21/May/2021 20:52:56] "GET /assets/images/consumption.svg HTTP/1.1" 304 -
192.168.1.40 - - [21/May/2021 20:52:56] "GET /assets/images/pollution.svg HTTP/1.1" 304 -
192.168.1.40 - - [21/May/2021 20:52:56] "GET /assets/images/battery-charge-line.svg HTTP/1.1" 304 -
192.168.1.40 - - [21/May/2021 20:52:56] "GET /assets/images/electricity%20bill.svg HTTP/1.1" 304 -
192.168.1.40 - - [21/May/2021 20:52:56] "GET /_dash-component-suites/dash_table/async-highlight.js HTTP/1.1" 200 -
192.168.1.40 - - [21/May/2021 20:52:56] "GET /_dash-component-suites/dash_table/async-table.js HTTP/1.1" 200 -
192.168.1.40 - - [21/May/2021 20:52:56] "POST /_dash-update-component HTTP/1.1" 200 -
192.168.1.40 - - [21/May/2021 20:52:56] "POST /_dash-update-component HTTP/1.1" 200 -
192.168.1.40 - - [21/May/2021 20:52:56] "POST /_dash-update-component HTTP/1.1" 204 -
192.168.1.40 - - [21/May/2021 20:52:56] "POST /_dash-update-component HTTP/1.1" 200 -
192.168.1.40 - - [21/May/2021 20:52:57] "GET /style.json HTTP/1.1" 200 -
192.168.1.40 - - [21/May/2021 20:52:57] "GET /assets/sprites/osm-liberty@2x.json HTTP/1.1" 304 -
192.168.1.40 - - [21/May/2021 20:52:57] "GET /assets/sprites/osm-liberty@2x.png HTTP/1.1" 304 -

why no trip?

**Comment by riddik14** [comment]
2021-05-21 21:38:24,089 :: DEBUG :: refresh_vehicle_info
2021-05-21 21:38:24,877 :: ERROR :: get_vehicle_info: ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'X-Backside-Transport': 'OK OK', 'Connection': 'close', 'Content-Type': 'application/hal+json', 'Date': 'Fri, 21 May 2021 19:38:24 GMT', 'X-Global-Transaction-ID': '08f333a560a80c300ca8989f', 'Cache-Control': 'no-store, no-cache, must-revalidate, private', 'Expires': '0', 'Access-Control-Expose-Headers': 'APIm-Debug-Trans-Id, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-Global-Transaction-ID', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET', 'Set-Cookie': 'rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Thu, 20-May-2021 19:38:24 GMT, JSESSIONID=0COTGorGM0vOSqRvTXYDYaqlqft_o8_ZXsQLX1XJ; path=/, PSACountry=IT;Domain=.groupe-psa.com;Path=/', 'X-RateLimit-Limit': 'name=rate-limit-1,150;', 'X-RateLimit-Remaining': 'name=rate-limit-1,0;'})
HTTP response body: {"uuid":"a73a52cd-dbcd-4f64-bea9-demo","code":40400,"message":"Not Found: We didn't find the status for this vehicule."}

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/src/psa_car_controller/my_psacc.py", line 144, in get_vehicle_info
    res = self.api().get_vehicle_status(car.vehicle_id, extension=["odometer"])
  File "/usr/local/src/psa_car_controller/psa_connectedcar/api/vehicles_api.py", line 1229, in get_vehicle_status
    (data) = self.get_vehicle_status_with_http_info(id, **kwargs)  # noqa: E501
  File "/usr/local/src/psa_car_controller/psa_connectedcar/api/vehicles_api.py", line 1307, in get_vehicle_status_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/src/psa_car_controller/libs/oauth.py", line 77, in call_api
    raise e
  File "/usr/local/src/psa_car_controller/libs/oauth.py", line 64, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/src/psa_car_controller/psa_connectedcar/api_client.py", line 161, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/src/psa_car_controller/psa_connectedcar/api_client.py", line 351, in request
    headers=headers)
  File "/usr/local/src/psa_car_controller/psa_connectedcar/rest.py", line 238, in GET
    query_params=query_params)
  File "/usr/local/src/psa_car_controller/psa_connectedcar/rest.py", line 228, in request
    raise ApiException(http_resp=r)
psa_connectedcar.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'X-Backside-Transport': 'OK OK', 'Connection': 'close', 'Content-Type': 'application/hal+json', 'Date': 'Fri, 21 May 2021 19:38:24 GMT', 'X-Global-Transaction-ID': '08f333a560a80c300ca8989f', 'Cache-Control': 'no-store, no-cache, must-revalidate, private', 'Expires': '0', 'Access-Control-Expose-Headers': 'APIm-Debug-Trans-Id, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-Global-Transaction-ID', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET', 'Set-Cookie': 'rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Thu, 20-May-2021 19:38:24 GMT, JSESSIONID=0COTGorGM0vOSqRvTXYDYaqlqft_o8_ZXsQLX1XJ; path=/, PSACountry=IT;Domain=.groupe-psa.com;Path=/', 'X-RateLimit-Limit': 'name=rate-limit-1,150;', 'X-RateLimit-Remaining': 'name=rate-limit-1,0;'})
HTTP response body: {"uuid":"a73a52cd-dbcd-4f64-bea9-dem","code":40400,"message":"Not Found: We didn't find the status for this vehicule."}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/src/psa_car_controller/my_psacc.py", line 162, in refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/usr/local/src/psa_car_controller/my_psacc.py", line 152, in get_vehicle_info
    logger.debug(exc_info=True)
TypeError: debug() missing 1 required positional argument: 'msg'

**Comment by flobz** [comment]
First issue -> read the FAQ no data to show
Second issue -> duplicated, rate limit problem

**Comment by riddik14** [comment]
Rate limit? In my webpage no date are download, why?
