### ISSUE TITLE
Error "missing 1 required positional argument: 'backend' "

### ISSUE THREAD

**Issue by Tiph60** [flobz/psa_car_controller#19]
Error "missing 1 required positional argument: 'backend' " at the end of app_decoder.py script

`APK loading...
APK loaded !
mypeugeot email: tiphaine_c@icloud.com
mypeugeot password: Elea2016
What is the car api realm : clientsB2CPeugeot, clientsB2CCitroen, clientsB2CDS, clientsB2COpel, clientsB2CVauxhall
clientsB2CPeugeot
What is your country code ? (ex: FR, GB, DE, ES...)
FR
Traceback (most recent call last):
  File "app_decoder.py", line 98, in <module>
    save_key_to_pem(pfx_cert,"")
  File "app_decoder.py", line 46, in save_key_to_pem
    private_key, certificate, additional_certificates = pkcs12.load_key_and_certificates(pfx_data, bytes.fromhex(pfx_password))
TypeError: load_key_and_certificates() missing 1 required positional argument: 'backend'`

**Comment by flobz** [comment]
https://stackoverflow.com/questions/63738152/deserializing-public-key-with-pythons-cryptography-module

**Comment by Tiph60** [comment]
Merci!
j'ai tenté "python -m pip install -U cryptography" mais toujours pareil :-/

**Comment by flobz** [comment]
sudo python -m pip install cryptography

**Comment by Tiph60** [comment]
>sudo python -m pip install cryptography
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: cryptography in /usr/lib/python2.7/dist-packages (2.6.1)


>pip freeze | grep cryptography
/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import x509
cryptography==3.3.1

**Comment by flobz** [comment]
Use python3

**Comment by Tiph60** [comment]
Same...

>python3 app_decoder.py /home/pi/Downloads/psa/MYPEUGEOT.apk

APK loading...
APK loaded !
mypeugeot email: ********
mypeugeot password: ********
What is the car api realm : clientsB2CPeugeot, clientsB2CCitroen, clientsB2CDS, clientsB2COpel, clientsB2CVauxhall
clientsB2CPeugeot
What is your country code ? (ex: FR, GB, DE, ES...)
FR
Traceback (most recent call last):
  File "app_decoder.py", line 98, in <module>
    save_key_to_pem(pfx_cert,"")
  File "app_decoder.py", line 46, in save_key_to_pem
    private_key, certificate, additional_certificates = pkcs12.load_key_and_certificates(pfx_data, bytes.fromhex(pfx_password))
TypeError: load_key_and_certificates() missing 1 required positional argument: 'backend'

**Comment by flobz** [comment]
sudo python3 -m pip install cryptography>=3.1
python3 app_decoder.py /home/pi/Downloads/psa/MYPEUGEOT.apk

**Comment by Tiph60** [comment]
merci mais pareil, même erreur, j'essaierai demain avec une autre distrib (raspbian buster 10 actuellement)

**Comment by flobz** [comment]
Don't bother, I make the code compatible with older version of the library can you test it ?

**Comment by Tiph60** [comment]
Of course! Thank you!

**Comment by Tiph60** [comment]
`Traceback (most recent call last):
  File "app_decoder.py", line 98, in <module>
    save_key_to_pem(pfx_cert,"")
  File "app_decoder.py", line 46, in save_key_to_pem
    private_key, certificate, additional_certificates = pkcs12.load_key_and_certificates(pfx_data, bytes.fromhex(pfx_password),None)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/serialization/pkcs12.py", line 9, in load_key_and_certificates
    return backend.load_key_and_certificates_from_pkcs12(data, password)
AttributeError: 'NoneType' object has no attribute 'load_key_and_certificates_from_pkcs12'`

**Comment by flobz** [comment]
Ok I did another correction can you retry ?

**Comment by Tiph60** [comment]
Success !!!

**Comment by Tiph60** [comment]
Great job ! Thank you !!!

**Comment by flobz** [comment]
Your welcome

**Comment by Tiph60** [comment]
Now for server.py (probably need the same modifications)

`python3 server.py -f test.json -c charge_config1.json
2021-01-29 10:12:09,087 :: INFO :: server start
Traceback (most recent call last):
  File "server.py", line 47, in <module>
    if args.record_position:
AttributeError: 'Namespace' object has no attribute 'record_position'
2021-01-29 10:12:09,090 :: INFO :: save config change`

**Comment by flobz** [comment]
No, it's an error in my code, it should be ok now.

**Comment by Tiph60** [comment]
Works! But some errors:

> python3 server.py -f test.json -c charge_config1.json
2021-01-29 10:56:59,191 :: INFO :: server start
mypeugeot email: **********
mypeugeot password: **********
2021-01-29 10:57:15,637 :: INFO :: {'**********': {'id': '1566c497a56557461533168615**********e3255784f444e6a5a44526b597a55325a5464694d546c69595759795a54593d'}}
2021-01-29 10:57:16,304 :: ERROR :: can't refresh_remote_token: {'error': 'invalid_grant', 'error_description': 'grant is invalid'}
 Create a new one
2021-01-29 10:57:16,692 :: INFO :: update_data
2021-01-29 10:57:16,695 :: ERROR :: update_trips: Traceback (most recent call last):
  File "/home/pi/Downloads/psa/web/callback.py", line 117, in update_trips
    trips = MyPSACC.get_trips()
  File "/home/pi/Downloads/psa/MyPSACC.py", line 544, in get_trips
    start = res[0]
IndexError: list index out of range

2021-01-29 10:57:16,696 :: ERROR :: Failed to generate figure, there is probably not enough data yet
2021-01-29 10:57:16,697 :: ERROR :: Traceback (most recent call last):
  File "/home/pi/Downloads/psa/web/callback.py", line 127, in <module>
    min_date = trips[0].start_at
TypeError: 'NoneType' object is not subscriptable

 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-01-29 10:57:18,060 :: INFO :: Connected with result code {'session present': 0}
2021-01-29 10:57:18,061 :: INFO :: subscribe to psa/RemoteServices/to/cid/AP-ACNT200004208157/#
2021-01-29 10:57:18,061 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VR3UKZKXZLJ727163/#
2021-01-29 10:57:18,407 :: INFO :: charging status of VR3UK**********63 is InProgress, battery level: 97.0
2021-01-29 10:57:18,408 :: INFO :: ask wakeup to VR3UK**********63
2021-01-29 10:57:18,690 :: INFO :: {"access_token": "7ecc**********-9735fc949f42", "customer_id": "AP-AC**********08157", "correlation_id": "f5143**********57534e0ec620210129095718690", "req_date": "2021-01-29T09:57:18Z", "vin": "VR3U**********63", "req_parameters": {"action": "state"}}
2021-01-29 10:57:18,693 :: INFO :: save config change
2021-01-29 10:57:19,322 :: INFO :: mqtt msg psa/RemoteServices/to/cid/AP-ACNT200004208157/VehCharge/state/ProcessManagement b'{"process_date":"2021-01-29T09:57:19Z","vin":"VR3UK**********63","correlation_id":"f5143a3**********e57534e0ec620210129095718690","process_code":"900","process_message":"Your request has been accepted and is being processed"}'
2021-01-29 10:57:20,104 :: INFO :: mqtt msg psa/RemoteServices/to/cid/AP-ACN**********8157/VehCharge/state/ProcessManagement b'{"process_date":"2021-01-29T09:57:20Z","vin":"VR3UKZK**********63","correlation_id":"f5143a3bb02**********e57534e0ec620210129095718690","process_code":"901","process_message":"The BTA is not connected, a request was sent to wake it up"}'

**Comment by flobz** [comment]
Yes, it's due to the fact that there is no saved data yet.
I fixed it.
