### ISSUE TITLE
Numpy failure

### ISSUE THREAD

**Issue by atze09** [flobz/psa_car_controller#20]
On Raspbian i get the following error with the lastest version:

`pi@raspberrypi:~/psa_car_controller-master $ python3 app_decoder.py myOpel\ the\ official\ app\ for\ all\ Opel\ drivers_v1.27.0_apkpure.com.apk 
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_decoder.py", line 11, in <module>
    from ChargeControl import ChargeControl, ChargeControls
  File "/home/pi/psa_car_controller-master/ChargeControl.py", line 11, in <module>
    from MyPSACC import MyPSACC
  File "/home/pi/psa_car_controller-master/MyPSACC.py", line 21, in <module>
    from ecomix import Ecomix
  File "/home/pi/psa_car_controller-master/ecomix.py", line 5, in <module>
    import reverse_geocode
  File "/home/pi/.local/lib/python3.7/site-packages/reverse_geocode/__init__.py", line 12, in <module>
    from scipy.spatial import cKDTree as KDTree
  File "/home/pi/.local/lib/python3.7/site-packages/scipy/__init__.py", line 61, in <module>
    from numpy import show_config as show_numpy_config
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/bin/python3"
  * The NumPy version is: "1.19.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
`
I already tried deintsall numpy and reinstall it and it gives me the following error:
`pi@raspberrypi:~/psa_car_controller-master $ pip3 install numpy==1.16.5
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting numpy==1.16.5
  Using cached https://www.piwheels.org/simple/numpy/numpy-1.16.5-cp37-cp37m-linux_armv7l.whl
Installing collected packages: numpy
  The scripts f2py, f2py3 and f2py3.7 are installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed numpy-1.16.5
`

Maybe you can help me

**Comment by flobz** [comment]
This isn't a problem with my progam.
When you have No such file or directory error try to find a package that contains that file:
https://packages.debian.org/search?searchon=contents&keywords=libf77blas.so.3&mode=path&suite=stable&arch=any
and install it.

**Comment by atze09** [comment]
> This isn't a problem with my progam.
> When you have No such file or directory error try to find a package that contains that file:
> https://packages.debian.org/search?searchon=contents&keywords=libf77blas.so.3&mode=path&suite=stable&arch=any
> and install it.

You are right, i solved it with `sudo apt-get install libatlas-base-dev`.
Sorry that was too much text for me, i read over this.

**Comment by atze09** [comment]
But now on PC i have another failure.
`python3 app_decoder.py .\myOpel.apk
APK loading...
Requested API level 29 is larger than maximum we have, returning API level 28 instead.
APK loaded !
Traceback (most recent call last):
  File "C:\Users\schmi\Desktop\psa_car_controller-master\app_decoder.py", line 98, in <module>
    token = res.json()["accessToken"]
KeyError: 'accessToken'`

**Comment by flobz** [comment]
I add verbosity to the app_decoder.py, can you retry and give me the result ? It should print more information about the error.

**Comment by flobz** [comment]
I must be related to a difference between peugeot and opel android app. Also use the 1.27 version.

**Comment by atze09** [comment]
> I add verbosity to the app_decoder.py, can you retry and give me the result ? It should print more information about the error.

I did it with verbose, but no failure and too much text for here.
I can send you the txt?

**Comment by flobz** [comment]
No failure?
You can join it to your message.

**Comment by atze09** [comment]
[verbose.txt](https://github.com/flobz/psa_car_controller/files/5898515/verbose.txt)

dont't think so.

**Comment by flobz** [comment]
We misunderstood, don't use the verbose option of python.
Just do a git pull and try again.

**Comment by atze09** [comment]
Sorry, now I got it.
Traceback (most recent call last):
  File "app_decoder.py", line 101, in <module>
    token = res.json()["accessToken"]
KeyError: 'accessToken'
HOST_BRANDID : https://id-dcr.opel.com/mobile-services sitecode: AP_DE_ESP
{"returnCode":"NEED_CREATION"}

**Comment by langepil** [comment]
> Sorry, now I got it.
> Traceback (most recent call last):
> File "app_decoder.py", line 101, in 
> token = res.json()["accessToken"]
> KeyError: 'accessToken'
> HOST_BRANDID : https://id-dcr.opel.com/mobile-services sitecode: AP_DE_ESP
> {"returnCode":"NEED_CREATION"}

Same here.

**Comment by flobz** [comment]
Sorry I can try the app with Opel server because I don't have an Opel...
I fix the "site_code" variable can you retry ?

**Comment by atze09** [comment]
Hello thanks for optimization , now the failure is need_activation
What is the car api realm : clientsB2CPeugeot clientsB2CCitroen clientsB2CDS clientsB2COpel clientsB2CVauxhall
clientsB2COpel
What is your country code ? (ex: FR, GB, DE, ES...)
DE
Traceback (most recent call last):
  File "app_decoder.py", line 103, in <module>
    token = res.json()["accessToken"]
KeyError: 'accessToken'
HOST_BRANDID : https://id-dcr.opel.com/mobile-services sitecode: 0V_DE_ESP
{"returnCode":"NEED_ACTIVATION"}

**Comment by langepil** [comment]
> Hello thanks for optimization , now the failure is need_activation
> What is the car api realm : clientsB2CPeugeot clientsB2CCitroen clientsB2CDS clientsB2COpel clientsB2CVauxhall
> clientsB2COpel
> What is your country code ? (ex: FR, GB, DE, ES...)
> DE
> Traceback (most recent call last):
> File "app_decoder.py", line 103, in 
> token = res.json()["accessToken"]
> KeyError: 'accessToken'
> HOST_BRANDID : https://id-dcr.opel.com/mobile-services sitecode: 0V_DE_ESP
> {"returnCode":"NEED_ACTIVATION"}

Same here ;)

**Comment by flobz** [comment]
can you retry with the last version of my code ?

**Comment by langepil** [comment]
Unfortunately also does not work
<img width="885" alt="Bildschirmfoto 2021-01-31 um 20 11 15" src="https://user-images.githubusercontent.com/50093063/106395099-b4bd1400-6400-11eb-8de1-e685cbbf9bad.png">

**Comment by atze09** [comment]
Now with error success.
![image](https://user-images.githubusercontent.com/6229866/106395434-8b9d8300-6402-11eb-8719-1129283949eb.png)

**Comment by flobz** [comment]
And now ?
You don't have the same error that's strange.
If it still doesn't work, I can't help you more without network traffic capture.

**Comment by langepil** [comment]
Unfortunately no!
But I had success with the one with the old branch.
I have only once changed the word Peugeot to Opel.
![Unbenannt](https://user-images.githubusercontent.com/50093063/106416499-cc70b880-6451-11eb-92f6-950b4f915ecc.PNG)

**Comment by flobz** [comment]
Hello, 
With the old branch you don't get the customerid.
I have change something can you retry.

**Comment by atze09** [comment]
Still the same:
![image](https://user-images.githubusercontent.com/6229866/106429532-dbb03000-646a-11eb-9f9e-295acc8c6f14.png)

**Comment by flobz** [comment]
Replace culture=fr_FR by culture=de_DE in line 115 ?

**Comment by flobz** [comment]
Also try to delete line 112 and 113 and add this instead:
```
if client_realm == "clientsB2COpel":
    site_code = "0V_" + country_code + "_ESP"
```

**Comment by atze09** [comment]
did both (edit 115 and uncommented 112+113)

![image](https://user-images.githubusercontent.com/6229866/106430993-f08dc300-646c-11eb-85c3-f673eb5d7389.png)

**Comment by atze09** [comment]
When i use FR as countrycode i get the follwing.
![image](https://user-images.githubusercontent.com/6229866/106431319-609c4900-646d-11eb-8a85-31d7d4e2d833.png)

**Comment by flobz** [comment]
There is a difference between the line I gave you and the commented line, it is 0V not OV.

**Comment by atze09** [comment]
> There is a difference between the line I gave you and the commented line, it is 0V not OV. Pleas copy and replace

Ok, i paste this before. so the same issue.

**Comment by flobz** [comment]
Well it would need a network capture of the android app.

**Comment by atze09** [comment]
> Well it would need a network capture of the android app.

https://github.com/flobz/psa_car_controller/issues/20#issuecomment-770663507

**Comment by flobz** [comment]
Good news ! 
I find the problem, it was the url.
It should work now

**Comment by atze09** [comment]
app_decoder works like a charm thank you.
But with server start next error occured:
`2021-02-01 11:18:14,520 :: ERROR :: can't refresh_remote_token: {'error': 'invalid_grant', 'error_description': 'grant is invalid'}
 Create a new one
2021-02-01 11:18:14,726 :: INFO :: update_data
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-02-01 11:18:18,556 :: INFO :: charging status of VIN is InProgress, battery level: 74.0
2021-02-01 11:18:18,557 :: INFO :: ask wakeup to VIN
2021-02-01 11:18:18,893 :: INFO :: {"access_token": "acces token", "customer_id": "customer_id", "correlation_id": "correlation_id", "req_date": "2021-02-01T10:18:18Z", "vin": "vin", "req_parameters": {"action": "state"}}
2021-02-01 11:18:18,898 :: INFO :: save config change
2021-02-01 11:18:19,330 :: INFO :: Connected with result code {'session present': 0}
2021-02-01 11:18:19,331 :: INFO :: subscribe to psa/RemoteServices/to/cid/customer_id/#
2021-02-01 11:18:19,331 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VIN/#
2021-02-01 11:18:19,333 :: WARNING :: Disconnected with result code 1
2021-02-01 11:18:19,334 :: WARNING :: Out of memory.
2021-02-01 11:18:20,730 :: INFO :: Connected with result code {'session present': 0}
2021-02-01 11:18:20,730 :: INFO :: subscribe to psa/RemoteServices/to/cid/customer_id/#
2021-02-01 11:18:20,731 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VIN/#
127.0.0.1 - - [01/Feb/2021 11:18:41] "←[37mGET / HTTP/1.1←[0m" 200 -
127.0.0.1 - - [01/Feb/2021 11:18:42] "←[37mGET /_dash-layout HTTP/1.1←[0m" 200 -
127.0.0.1 - - [01/Feb/2021 11:18:42] "←[37mGET /_dash-dependencies HTTP/1.1←[0m" 200 -
2021-02-01 11:20:19,455 :: INFO :: charging status of VIN2 is InProgress, battery level: 74.0
2021-02-01 11:20:19,456 :: INFO :: ask wakeup to VIN
2021-02-01 11:20:19,899 :: INFO :: {"access_token": "acces token", "customer_id": "customer_id", "correlation_id": "correlation_id", "req_date": "2021-02-01T10:20:19Z", "vin": "vin", "req_parameters": {"action": "state"}}
2021-02-01 11:20:19,934 :: WARNING :: Disconnected with result code 1
2021-02-01 11:20:19,935 :: WARNING :: Out of memory.
2021-02-01 11:20:22,904 :: INFO :: Connected with result code {'session present': 0}
2021-02-01 11:20:22,905 :: INFO :: subscribe to psa/RemoteServices/to/cid/customer_id/#
2021-02-01 11:20:22,906 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VIN/#
2021-02-01 11:20:49,035 :: INFO :: save config change`

**Comment by flobz** [comment]
Is something doesn't work ? 
This error is normal.

**Comment by langepil** [comment]
Works perfect! Thanks

**Comment by flobz** [comment]
```i was confused by the dashboard, but recording is currently disabled.```
What do you mean ?

**Comment by atze09** [comment]
![image](https://user-images.githubusercontent.com/6229866/106453850-31e09b80-648a-11eb-889b-e91b71e74f21.png)
With no data to show, i tgought it dows not work, but "get_vehicleinfo" dows work.
