### ISSUE TITLE
refresh_vehicle_info error

### ISSUE THREAD

**Issue by aleblack** [flobz/psa_car_controller#215]
Sometimes happens that, when I'm using the car, psa_car_controller stop working, so I can't use abrp anymore when I'm travelling and also Home Assistant doesn't show any data from the car. After restarting the psa_car_controller system service, everything seems fine.
I'm running on an rpi4, not using docker.
That's what's in the logfile:

> 2021-09-02 12:45:30,975 :: INFO :: <Request 'http://192.168.x.x:5000/charge_control?vin=VR3UHZKX000000000&%3Falways_check=true' [GET]>
2021-09-02 12:46:01,855 :: DEBUG :: refresh_vehicle_info
2021-09-02 12:46:02,558 :: DEBUG :: vin:VR3UHZKX000000000 longitude:None latitude:None date:2021-09-02 10:45:26+00:00 mileage:19130.5 level:60.0 charge_date:2021-09-02 10:45:26+00:00 level_fuel:0.0 moving:None
2021-09-02 12:46:02,573 :: INFO :: level_fuel unfixed for VR3UHZKX000000000
2021-09-02 12:46:07,584 :: ERROR :: refresh_vehicle_info:
Traceback (most recent call last):
  File "/opt/psa_car_controller/my_psacc.py", line 170, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/opt/psa_car_controller/my_psacc.py", line 156, in get_vehicle_info
    self.record_info(car)
  File "/opt/psa_car_controller/my_psacc.py", line 479, in record_info
    level_fuel, moving)
  File "/opt/psa_car_controller/web/db.py", line 257, in record_position
    (date, vin, longitude, latitude, altitude, mileage, level, level_fuel, moving, temp))
sqlite3.OperationalError: database is locked

**Comment by flobz** [comment]
Use Google!

**Comment by aleblack** [comment]
yeah, according to google: 

> Python’s SQLite wrapper has a default timeout value that determines how long the second thread is allowed to wait on the lock before it times out and raises the OperationalError: database is locked error.
If you’re getting this error, you can solve it by:
   -  Switching to another database backend. At a certain point SQLite becomes too “lite” for real-world applications, and these sorts of concurrency errors indicate you’ve reached that point.
   -  Rewriting your code to reduce concurrency and ensure that database transactions are short-lived.
   - Increase the default timeout value by setting the timeout database option

So what? do I need to increase timeout value in psa_car_controller? How do I do this?
