### ISSUE TITLE
Problems when updating från 2.4.4 to 2.4.5, Type and dashboard errors (not starting)

### ISSUE THREAD

**Issue by DreamT80** [flobz/psa_car_controller#220]
Hi,

I get this when updating to v2.4.5 from v2.4.4.Haven't tested a fresh install yet, but I believe that the problem would be the same. Does this has to do with mileage as well?

`Containerised psa_car_controller loading...
/usr/local/lib/python3.7/dist-packages/dash_bootstrap_components/_table.py:5: UserWarning: 
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
2021-09-10 10:49:29,116 :: INFO :: save config change
2021-09-10 10:49:30,102 :: INFO :: ["{'vin': '...', 'vehicle_id': '...', 'label': 'Grandland X Hybrid', 'brand': 'C', 'abrp_name': None, 'battery_power': 13.2, 'fuel_capacity': 43, 'max_elec_consumption': 70, 'max_fuel_consumption': 30}"]
2021-09-10 10:49:30,587 :: INFO :: save config change
2021-09-10 10:49:30,587 :: ERROR :: remote_refresh_token isn't defined
2021-09-10 10:49:30,593 :: WARNING :: Can't get language
/psa_car_controller/web/views.py:7: UserWarning: 
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
/psa_car_controller/web/figures.py:4: UserWarning: 
The dash_table package is deprecated. Please replace
`import dash_table` with `from dash import dash_table`
Also, if you're using any of the table format helpers (e.g. Group), replace 
`from dash_table.Format import Group` with 
`from dash.dash_table.Format import Group`
  import dash_table
2021-09-10 10:49:31,581 :: INFO :: update_data
2021-09-10 10:49:31,854 :: ERROR :: Bad value : 
Traceback (most recent call last):
  File "/psa_car_controller/trip.py", line 163, in get_trips
    distance = end["mileage"] - start["mileage"]
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/psa_car_controller/web/app.py", line 46, in start_app
    run(config_flask(*args, **kwargs))
  File "/psa_car_controller/web/app.py", line 76, in config_flask
    importlib.import_module(view)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/psa_car_controller/web/views.py", line 397, in <module>
    update_trips()
  File "/psa_car_controller/web/views.py", line 246, in update_trips
    trips_by_vin = Trips.get_trips(Cars([car]))
  File "/psa_car_controller/trip.py", line 173, in get_trips
    if TripParser.is_low_speed(speed_average, duration) or trip_parser.is_refuel(start, end, distance):
UnboundLocalError: local variable 'duration' referenced before assignment`

**Comment by DreamT80** [comment]
Hmm...I tested a fresh install, and then it worked. Hard to say what the problem was.

**Comment by flobz** [comment]
Its because you had a none mileage value in your DB. It will be fixed in the next release.

**Comment by DreamT80** [comment]
I get the same error when restarting the add-on. So right now I have to reinstall it at every restart.

No big problem for me, but can be good to know.
