### ISSUE TITLE
ERROR :: get_vehicles:

### ISSUE THREAD

**Issue by DavidFFerreira** [flobz/psa_car_controller#222]
After put my credencials to Citroen and Country = PT I've got those error
I've got an e-C4

2021-09-16 12:57:59,146 :: ERROR :: get_vehicles:
Traceback (most recent call last):
  File "/psa_car_controller/my_psacc.py", line 192, in get_vehicles
    res = self.api().get_vehicles_by_device()
  File "/psa_car_controller/psa_connectedcar/api/vehicles_api.py", line 1331, in get_vehicles_by_device
    (data) = self.get_vehicles_by_device_with_http_info(**kwargs)  # noqa: E501
  File "/psa_car_controller/psa_connectedcar/api/vehicles_api.py", line 1414, in get_vehicles_by_device_with_http_info
    collection_formats=collection_formats)
  File "/psa_car_controller/libs/oauth.py", line 77, in call_api
    raise e
  File "/psa_car_controller/libs/oauth.py", line 64, in call_api
    _preload_content, _request_timeout)
  File "/psa_car_controller/psa_connectedcar/api_client.py", line 161, in __call_api
    _request_timeout=_request_timeout)
  File "/psa_car_controller/psa_connectedcar/api_client.py", line 351, in request
    headers=headers)
  File "/psa_car_controller/psa_connectedcar/rest.py", line 238, in GET
    query_params=query_params)
  File "/psa_car_controller/psa_connectedcar/rest.py", line 228, in request
    raise ApiException(http_resp=r)
psa_connectedcar.rest.ApiException: (404)
Reason: Not Found

**Comment by flobz** [comment]
duplicate with #57

**Comment by DavidFFerreira** [comment]
not the same, my car is completly eletric not a thermal one

**Comment by DavidFFerreira** [comment]
@flobz
