### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by DavidFFerreira** [flobz/psa_car_controller#225]
Citroen e-c4

Dashboard dont show nothing. 
I gont info only one time when I restart the addon, after that it dont update anymore

I got this error:
Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/psa_car_controller/web/views.py", line 197, in get_charge_control
    charge_control = CONFIG.chc.get(vin)
AttributeError: 'Config' object has no attribute 'chc'

**Comment by flobz** [comment]
should be fixed with last version

**Comment by DavidFFerreira** [comment]
nop, still the same issue :S

**Comment by DavidFFerreira** [comment]
@flobz
