### ISSUE TITLE
Can't get preconditioning or charge hour to work

### ISSUE THREAD

**Issue by DreamT80** [flobz/psa_car_controller#226]
**Describe the bug**
It's not possible to start/stop preconditioning or changing charging hour.

**To Reproduce**
1. what command did you use

`http://172.30.33.5:5000/preconditioning/VIN/1`
`http://172.30.33.5:5000/preconditioning/VIN/0`
`http://172.30.33.5:5000/charge_control?vin=VIN&hour=5&minute=0`

2. when the bug append ?
When I run the commands above.

3. Does it persist after restarting the program?
Yes.

4. Does it persist after recreate config by going to http://server_address:port/log/config? 
I don't know how to reach the url other than by Terminal (running containerised inside HassOS).

**Config file**
I don't know how to reach the url other than by Terminal (running containerised inside HassOS).

**Environment (please complete the following information):**
 - OS: Home Assistant OS 6.4
 - Brand and model of car: Opel Grandland X Hybrid 2020
 - Application version v2.5.1
 - Log from http://server_address:port/log and browser console log
 Can't get log from from  http://server_address:port/log, browse console log says the following:
 
charge hour:

 `2021-09-21 17:12:54,091 :: WARNING :: charge begin but API isn't updated
2021-09-21 17:12:54,091 :: WARNING :: charge begin but API isn't updated
172.30.32.1 - - [21/Sep/2021 17:13:30] "GET /get_vehicleinfo/VIN?from_cache=1 HTTP/1.1" 200 -
2021-09-21 17:13:30,800 :: INFO :: <Request 'http://172.30.33.5:5000/charge_control?vin=VIN&%3Falways_check=true' [GET]>
2021-09-21 17:13:30,800 :: INFO :: <Request 'http://172.30.33.5:5000/charge_control?vin=VIN&%3Falways_check=true' [GET]>
172.30.32.1 - - [21/Sep/2021 17:13:30] "GET /charge_control?vin=VIN&?always_check=true HTTP/1.1" 200 -
2021-09-21 17:13:39,579 :: INFO :: level_fuel unfixed for VIN
2021-09-21 17:13:39,579 :: INFO :: level_fuel unfixed for VIN
2021-09-21 17:13:39,834 :: INFO :: new position recorded for VIN
2021-09-21 17:13:39,834 :: INFO :: new position recorded for VIN
2021-09-21 17:13:39,836 :: INFO :: update_data
2021-09-21 17:13:39,836 :: INFO :: update_data
2021-09-21 17:13:40,193 :: INFO :: charging status of VIN is Disconnected, battery level: 71
2021-09-21 17:13:40,193 :: INFO :: charging status of VIN is Disconnected, battery level: 71
2021-09-21 17:13:44,518 :: INFO :: <Request 'http://172.30.33.5:5000/charge_control?vin=VIN&hour=5&minute=0' [GET]>
2021-09-21 17:13:44,518 :: INFO :: <Request 'http://172.30.33.5:5000/charge_control?vin=VIN&hour=5&minute=0' [GET]>
2021-09-21 17:13:44,520 :: INFO :: save config change
2021-09-21 17:13:44,520 :: INFO :: save config change
172.30.32.1 - - [21/Sep/2021 17:13:44] "GET /charge_control?vin=VIN&hour=5&minute=0 HTTP/1.1" 200 -
2021-09-21 17:13:54,150 :: INFO :: ask wakeup to VIN
2021-09-21 17:13:54,150 :: INFO :: ask wakeup to VIN
2021-09-21 17:13:54,641 :: INFO :: save config change
2021-09-21 17:13:54,641 :: INFO :: save config change
2021-09-21 17:13:54,642 :: INFO :: {"access_token": "ACCESS_TOKEN", "customer_id": "CUSTOMER_ID", "correlation_id": "CORRELATION_ID", "req_date": "2021-09-21T15:13:54Z", "vin": "VIN", "req_parameters": {"action": "state"}}
2021-09-21 17:13:54,642 :: INFO :: {"access_token": "ACCESS_TOKEN", "customer_id": "CUSTOMER_ID", "correlation_id": "CORRELATION_ID", "req_date": "2021-09-21T15:13:54Z", "vin": "VIN", "req_parameters": {"action": "state"}}
2021-09-21 17:13:54,644 :: WARNING :: Disconnected with result code 1
2021-09-21 17:13:54,644 :: WARNING :: Disconnected with result code 1
2021-09-21 17:13:55,016 :: INFO :: save config change
2021-09-21 17:13:55,016 :: INFO :: save config change
2021-09-21 17:13:56,756 :: INFO :: Connected with result code {'session present': 0}
2021-09-21 17:13:56,756 :: INFO :: Connected with result code {'session present': 0}
2021-09-21 17:13:56,757 :: INFO :: subscribe to psa/RemoteServices/to/cid/CUSTOMER_ID/#
2021-09-21 17:13:56,757 :: INFO :: subscribe to psa/RemoteServices/to/cid/CUSTOMER_ID/#
2021-09-21 17:13:56,758 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VIN
2021-09-21 17:13:56,758 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VIN`

preconditioning:
`2021-09-21 21:26:41,823 :: INFO :: preconditioning: {"access_token": "ACCESTOKEN", "customer_id": "CUID", "correlation_id": "CORRID", "req_date": "2021-09-21T19:26:41Z", "vin": "VIN", "req_parameters": {"asap": "deactivate", "programs": {"program1": {"hour": 7, "minute": 40, "on": 0, "day": [0, 1, 0, 0, 0, 0, 0]}, "program2": {"hour": 7, "minute": 30, "on": 0, "day": [0, 0, 0, 0, 1, 0, 0]}, "program3": {"hour": 34, "minute": 7, "on": 0, "day": [0, 0, 0, 0, 0, 0, 0]}, "program4": {"hour": 34, "minute": 7, "on": 0, "day": [0, 0, 0, 0, 0, 0, 0]}}}}
172.30.33.3 - - [21/Sep/2021 21:26:41] "GET /preconditioning/VIN/0 HTTP/1.1" 200 -
2021-09-21 21:27:01,097 :: INFO :: level_fuel unfixed for VIN
2021-09-21 21:27:01,221 :: INFO :: new position recorded for VIN
2021-09-21 21:27:01,222 :: INFO :: update_data
2021-09-21 21:27:01,223 :: ERROR :: refresh_vehicle_info: 
Traceback (most recent call last):
  File "/psa_car_controller/my_psacc.py", line 174, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/psa_car_controller/my_psacc.py", line 161, in get_vehicle_info
    self.record_info(car)
  File "/psa_car_controller/my_psacc.py", line 491, in record_info
    level_fuel, moving)
  File "/psa_car_controller/web/db.py", line 262, in record_position
    conn.close()
  File "/psa_car_controller/web/db.py", line 45, in close
    self.execute_callbacks()
  File "/psa_car_controller/web/db.py", line 41, in execute_callbacks
    callback()
  File "/psa_car_controller/web/view/views.py", line 245, in update_trips
    trips_by_vin = Trips.get_trips(Cars([car]))
  File "/psa_car_controller/trip.py", line 179, in get_trips
    distance = next_el["mileage"] - end["mileage"]  # km
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'`

**Additional context**
When testning now in the evening I actually manager to activate preconditoning twice. But, between the tries the container stopped working, I had to restart it.

Haven't been able to turn it of though, and changing charge hour hasn't worked at all.

**Comment by DreamT80** [comment]
Closing this since I have done some testing, will create a new issue tomorrow.
