### ISSUE TITLE
More of a question: 500 from vehicleinfo, nothing useful from chargecontrol

### ISSUE THREAD

**Issue by alexhalford** [flobz/psa_car_controller#228]
Hi, this is an amazing project, thank you. I'm trying to set it up in homeassistant, and the error logs are:
```
Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 196, in get_charge_control
    charge_control = CONFIG.chc.get(vin)
AttributeError: 'Config' object has no attribute 'chc'
```
I have tried doing a direct curl on that endpoint, and it gives a 500 error.

The response of get_vehicleinfo are also looking a bit strange from curl:
```
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta charset="UTF-8">
        <title>My car info</title>
        <link rel="icon" type="image/x-icon" href="/_favicon.ico?v=2.0.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    </head>
    <body>

<div id="react-entry-point">
    <div class="_dash-loading">
        Loading...
    </div>
</div>

        <footer>
            <script id="_dash-config" type="application/json">{"props_check":false,"requests_pathname_prefix":"/","show_undo_redo":false,"suppress_callback_exceptions":true,"ui":false,"update_title":"Updating...","url_base_pathname":null}</script>
            <script src="https://unpkg.com/@babel/polyfill@7.12.1/dist/polyfill.min.js"></script>
<script src="https://unpkg.com/react@16.14.0/umd/react.production.min.js"></script>
<script src="https://unpkg.com/react-dom@16.14.0/umd/react-dom.production.min.js"></script>
<script src="https://unpkg.com/prop-types@15.7.2/prop-types.min.js"></script>
<script src="https://unpkg.com/dash-bootstrap-components@0.13.0/dist/dash_bootstrap_components.min.js"></script>
<script src="https://unpkg.com/dash-daq@0.5.0/dash_daq/dash_daq.min.js"></script>
<script src="/assets/clientside.js?m=1632161517.0"></script>
<script src="https://unpkg.com/dash-renderer@1.10.0/build/dash_renderer.min.js"></script>
<script src="https://unpkg.com/dash-core-components@2.0.0/dash_core_components/dash_core_components.js"></script>
<script src="https://unpkg.com/dash-core-components@2.0.0/dash_core_components/dash_core_components-shared.js"></script>
<script src="https://unpkg.com/dash-html-components@2.0.0/dash_html_components/dash_html_components.min.js"></script>
<script src="https://unpkg.com/dash-table@5.0.0/dash_table/bundle.js"></script>
            <script id="_dash-renderer" type="application/javascript">var renderer = new DashRenderer();</script>
        </footer>
    </body>
```

Have I simply misconfigured something?

**Comment by flobz** [comment]
Close as it doesn't follow the bug template
