### ISSUE TITLE
Application dies(?) when trying to run preconditioning/charging

### ISSUE THREAD

**Issue by DreamT80** [flobz/psa_car_controller#239]
**Describe the bug**
When I run http://localhost:5000/preconditioning/[VIN]/1 (for example) the web server stops to respond, and I have to restart the docker.

**To Reproduce**
1. Run a working command, for example http://127.0.0.1:5000/get_vehicleinfo/[VIN]?from_cache=1
2. Run one of the failing commands,  f.ex. http://127.0.0.1:5000/preconditioning/[VIN]/1 -> The web server isn't responding and seems to timeout.
3. Run the working command again -> The web server doesn't respond on this command either.

1. what command did you use
http://127.0.0.1:5000/preconditioning/[VIN]/1 
http://127.0.0.1:5000/preconditioning/[VIN]/10
http://127.0.0.1:5000/charge_hour?vin=[VIN]&hour=02&min=00

2. when the bug append ?
It happens right after the commands are run.

3. Does it persist after restarting the program?
Yes.

4. Does it persist after recreate config by going to http://server_address:port/log/config? 
Yes.

**Config file**
`{
    "abrp": {
        "abrp_enable_vin": [],
        "token": ""
    },
    "client_id": ...",
    "client_secret": "...",
    "co2_signal_api": null,
    "country_code": "SE",
    "customer_id": "...",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2COpel",
    "refresh_token": "...",
    "remote_refresh_token": "...",
    "weather_api": null
}
`

**Environment (please complete the following information):**
 - OS:MacOS
 - Car:Opel Grandland X
 - Version:v2.5.1
 - Log from http://server_address:port/log and browser console log
`2021-10-06 20:25:22,069 :: INFO :: save config change
2021-10-06 20:25:22,996 :: INFO :: ["{'vin': '...', 'vehicle_id': '...', 'label': 'Grandland X Hybrid', 'brand': 'C', 'abrp_name': None, 'battery_power': 13.2, 'fuel_capacity': 43, 'max_elec_consumption': 70, 'max_fuel_consumption': 30}"]
2021-10-06 20:25:23,412 :: INFO :: save config change
2021-10-06 20:25:24,063 :: INFO :: ask wakeup to ...
2021-10-06 20:25:24,211 :: INFO :: Connected with result code {'session present': 0}
2021-10-06 20:25:24,211 :: INFO :: subscribe to psa/RemoteServices/to/cid/.../#
2021-10-06 20:25:24,212 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/...
2021-10-06 20:25:24,483 :: INFO :: save config change
2021-10-06 20:25:24,484 :: INFO :: {"access_token": "...", "customer_id": "...", "correlation_id": "...", "req_date": "2021-10-06T20:25:24Z", "vin": "...", "req_parameters": {"action": "state"}}
2021-10-06 20:25:24,490 :: WARNING :: Can't get language
2021-10-06 20:25:25,122 :: INFO :: update_data
2021-10-06 20:25:25,136 :: INFO :: charging status of ... is Stopped, battery level: 59
2021-10-06 20:25:25,180 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/.../VehCharge/state/ProcessManagement b'{"process_date":"2021-10-06T20:25:25Z","vin":"...","correlation_id":"...","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2021-10-06 20:25:25,425 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/.../VehCharge/state/ProcessManagement b'{"process_date":"2021-10-06T20:25:25Z","vin":"...","correlation_id":"...","process_code":"901","process_message":"[process.901.vehicle.asleep.key]"}'
2021-10-06 20:25:43,871 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/... b'{"date":"2021-10-06T20:25:36Z","etat_res_elec":0,"precond_state":{"available":1,"programs":{"program1":{"hour":7,"minute":40,"on":0,"day":[0,1,0,0,0,0,0]},"program2":{"hour":7,"minute":30,"on":0,"day":[0,0,0,0,1,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0,"aff":1},"charging_state":{"program":{"hour":2,"minute":0},"available":1,"remaining_time":285,"rate":0,"cable_detected":0,"soc_batt":66,"autonomy_zev":18,"type":1,"aff":1,"hmi_state":3,"mode":0},"stolen_state":0,"vin":"...","reason":4,"signal_quality":3,"sev_stop_date":"2021-10-06T19:30:12Z","fds":["NBM01","NCG01","NAO02","NAS01"],"sev_state":0,"obj_counter":2,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2021-10-06 20:25:43,871 :: WARNING :: charge begin but API isn't updated
2021-10-06 20:26:02,238 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
  File "/psa_car_controller/web/view/control.py", line 33, in get_control_tabs
    value=str(int(car.status.timed_odometer.mileage)))],
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-10-06 20:26:43,891 :: INFO :: ask wakeup to ...
2021-10-06 20:26:44,254 :: INFO :: save config change
2021-10-06 20:26:44,255 :: INFO :: {"access_token": "...", "customer_id": "...", "correlation_id": "4030938def6e40beb21ac8416043570020211006202644255", "req_date": "2021-10-06T20:26:44Z", "vin": "...", "req_parameters": {"action": "state"}}
2021-10-06 20:26:44,257 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/... b'{"date":"2021-10-06T20:25:33Z","etat_res_elec":0,"precond_state":{"available":1,"programs":{"program1":{"hour":7,"minute":40,"on":0,"day":[0,1,0,0,0,0,0]},"program2":{"hour":7,"minute":30,"on":0,"day":[0,0,0,0,1,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0,"aff":1},"charging_state":{"program":{"hour":2,"minute":0},"available":1,"remaining_time":285,"rate":0,"cable_detected":0,"soc_batt":66,"autonomy_zev":18,"type":1,"aff":1,"hmi_state":3,"mode":0},"stolen_state":0,"vin":"...","reason":0,"signal_quality":3,"sev_stop_date":"2021-10-06T19:30:12Z","fds":["NBM01","NCG01","NAO02","NAS01"],"sev_state":0,"obj_counter":1,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2021-10-06 20:26:44,258 :: WARNING :: charge begin but API isn't updated
2021-10-06 20:27:25,585 :: INFO :: charging status of ... is Stopped, battery level: 59
2021-10-06 20:27:44,258 :: INFO :: ask wakeup to ...
2021-10-06 20:27:44,652 :: INFO :: save config change
2021-10-06 20:27:44,654 :: INFO :: {"access_token": "...", "customer_id": "...", "correlation_id": "2800a7983e4e4a76b453840f2299c7df20211006202744653", "req_date": "2021-10-06T20:27:44Z", "vin": "...", "req_parameters": {"action": "state"}}
2021-10-06 20:27:44,655 :: WARNING :: Disconnected with result code 1
2021-10-06 20:27:45,154 :: INFO :: save config change
2021-10-06 20:27:46,914 :: INFO :: Connected with result code {'session present': 0}
2021-10-06 20:27:46,915 :: INFO :: subscribe to psa/RemoteServices/to/cid/.../#
2021-10-06 20:27:46,915 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/...
2021-10-06 20:29:26,129 :: INFO :: charging status of ... is Stopped, battery level: 59
2021-10-06 20:29:43,190 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
  File "/psa_car_controller/web/view/control.py", line 33, in get_control_tabs
    value=str(int(car.status.timed_odometer.mileage)))],
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-10-06 20:32:52,718 :: INFO :: save config change
2021-10-06 20:32:53,641 :: INFO :: ["{'vin': '...', 'vehicle_id': '...', 'label': 'Grandland X Hybrid', 'brand': 'C', 'abrp_name': None, 'battery_power': 13.2, 'fuel_capacity': 43, 'max_elec_consumption': 70, 'max_fuel_consumption': 30}"]
2021-10-06 20:32:54,008 :: INFO :: save config change
2021-10-06 20:32:55,052 :: INFO :: ask wakeup to ...
2021-10-06 20:32:55,226 :: INFO :: Connected with result code {'session present': 0}
2021-10-06 20:32:55,226 :: INFO :: subscribe to psa/RemoteServices/to/cid/.../#
2021-10-06 20:32:55,227 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/...
2021-10-06 20:32:55,484 :: INFO :: save config change
2021-10-06 20:32:55,485 :: INFO :: {"access_token": "...", "customer_id": "...", "correlation_id": "...", "req_date": "2021-10-06T20:32:55Z", "vin": "...", "req_parameters": {"action": "state"}}
2021-10-06 20:32:55,494 :: WARNING :: Can't get language
2021-10-06 20:32:55,791 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/.../VehCharge/state/ProcessManagement b'{"process_date":"2021-10-06T20:32:55Z","vin":"...","correlation_id":"...","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2021-10-06 20:32:55,848 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/.../VehCharge/state/ProcessManagement b'{"process_date":"2021-10-06T20:32:55Z","vin":"...","correlation_id":"...","process_code":"901","process_message":"[process.901.vehicle.asleep.key]"}'
2021-10-06 20:32:55,988 :: INFO :: charging status of ... is Stopped, battery level: 59
2021-10-06 20:32:56,461 :: INFO :: update_data
2021-10-06 20:33:15,678 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
  File "/psa_car_controller/web/view/control.py", line 33, in get_control_tabs
    value=str(int(car.status.timed_odometer.mileage)))],
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-10-06 20:33:15,748 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/... b'{"date":"2021-10-06T20:33:06Z","etat_res_elec":0,"precond_state":{"available":1,"programs":{"program1":{"hour":7,"minute":40,"on":0,"day":[0,1,0,0,0,0,0]},"program2":{"hour":7,"minute":30,"on":0,"day":[0,0,0,0,1,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0,"aff":1},"charging_state":{"program":{"hour":2,"minute":0},"available":1,"remaining_time":285,"rate":0,"cable_detected":0,"soc_batt":66,"autonomy_zev":18,"type":1,"aff":1,"hmi_state":3,"mode":0},"stolen_state":0,"vin":"...","reason":3,"signal_quality":3,"sev_stop_date":"2021-10-06T19:30:12Z","fds":["NBM01","NCG01","NAO02","NAS01"],"sev_state":0,"obj_counter":2,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2021-10-06 20:33:15,749 :: WARNING :: charge begin but API isn't updated
2021-10-06 20:33:20,166 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
  File "/psa_car_controller/web/view/control.py", line 33, in get_control_tabs
    value=str(int(car.status.timed_odometer.mileage)))],
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-10-06 20:34:15,765 :: INFO :: ask wakeup to ...
2021-10-06 20:34:16,329 :: INFO :: save config change
2021-10-06 20:34:16,330 :: INFO :: {"access_token": "...", "customer_id": "...", "correlation_id": "...", "req_date": "2021-10-06T20:34:16Z", "vin": "...", "req_parameters": {"action": "state"}}
2021-10-06 20:34:16,331 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/... b'{"date":"2021-10-06T20:33:08Z","etat_res_elec":0,"precond_state":{"available":1,"programs":{"program1":{"hour":7,"minute":40,"on":0,"day":[0,1,0,0,0,0,0]},"program2":{"hour":7,"minute":30,"on":0,"day":[0,0,0,0,1,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0,"aff":1},"charging_state":{"program":{"hour":2,"minute":0},"available":1,"remaining_time":285,"rate":0,"cable_detected":0,"soc_batt":66,"autonomy_zev":18,"type":1,"aff":1,"hmi_state":0,"mode":0},"stolen_state":0,"vin":"...","reason":4,"signal_quality":3,"sev_stop_date":"2021-10-06T19:30:12Z","fds":["NBM01","NCG01","NAO02","NAS01"],"sev_state":0,"obj_counter":4,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2021-10-06 20:34:16,332 :: WARNING :: charge begin but API isn't updated
2021-10-06 20:34:56,574 :: INFO :: level_fuel unfixed for ...
2021-10-06 20:34:56,588 :: INFO :: new position recorded for ...
2021-10-06 20:34:56,594 :: INFO :: update_data
2021-10-06 20:34:56,933 :: INFO :: charging status of ... is Stopped, battery level: 59
2021-10-06 20:35:16,353 :: INFO :: ask wakeup to ...
2021-10-06 20:35:16,704 :: INFO :: save config change
2021-10-06 20:35:16,705 :: INFO :: {"access_token": "...", "customer_id": "...", "correlation_id": "...", "req_date": "2021-10-06T20:35:16Z", "vin": "...", "req_parameters": {"action": "state"}}
2021-10-06 20:35:16,706 :: WARNING :: Disconnected with result code 1
2021-10-06 20:35:17,115 :: INFO :: save config change
2021-10-06 20:35:18,824 :: INFO :: Connected with result code {'session present': 0}
2021-10-06 20:35:18,826 :: INFO :: subscribe to psa/RemoteServices/to/cid/.../#
2021-10-06 20:35:18,827 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/...
2021-10-06 20:36:57,494 :: INFO :: level_fuel unfixed for ...
2021-10-06 20:36:57,500 :: INFO :: new position recorded for ...
2021-10-06 20:36:57,504 :: INFO :: update_data
2021-10-06 20:36:57,779 :: INFO :: charging status of ... is Stopped, battery level: 59
`

**Additional context**
Sometimes the condition is executed, i.e. the preconditioning starts. Sometimes it's not executed.
Can this be cause the PSA API takes long time to respond/times out?

**Comment by flobz** [comment]
Try in debug mode, you will have more logs.

**Comment by DreamT80** [comment]
> Try in debug mode, you will have more logs.

Ok. How do I activate debug mode when  running in Docker? I can see that there is an environment variable called "PSACC_OPTIONS" with the value "-c -r --web-conf" and I believe that -d should be added to it, but I don't know how..

**Comment by DreamT80** [comment]
Nevermind, I solved it ;)

**Comment by DreamT80** [comment]
So, I tried by adding the -d option, and there were more debug output. However, I didn't get anything that helped. There really isn't anything logged after the application hangs (unless I can see it in a web server log or similar?). Below you can see the log output. I've marked where the application died with [RESTART] (at this point I stopped and started the container again since nothing happened)

`File "/psa_car_controller/libs/charging.py", line 60, in record_charging start_at, stop_at, start_level = conn.execute( TypeError: cannot unpack non-iterable NoneType object
2021-11-07 15:11:43,674 :: DEBUG :: battery table is probably empty : Traceback (most recent call last): File "/psa_car_controller/libs/charging.py", line 60, in record_charging start_at, stop_at, start_level = conn.execute( TypeError: cannot unpack non-iterable NoneType object
2021-11-07 15:11:43,676 :: DEBUG :: charging_status:Stopped
2021-11-07 15:11:43,676 :: DEBUG :: charging_status:Stopped
2021-11-07 15:11:43,676 :: INFO :: charging status of [VIN] is Stopped, battery level: 97
2021-11-07 15:11:43,676 :: INFO :: charging status of [VIN] is Stopped, battery level: 97
2021-11-07 15:13:43,695 :: DEBUG :: refresh_vehicle_info
2021-11-07 15:13:43,695 :: DEBUG :: refresh_vehicle_info
2021-11-07 15:13:44,288 :: DEBUG :: vin:[VIN] longitude:None latitude:None date:2021-11-07 15:09:42+00:00 mileage:None level:97.0 charge_date:2021-11-07 15:09:42+00:00 level_fuel:0.0 moving:None
2021-11-07 15:13:44,288 :: DEBUG :: vin:[VIN] longitude:None latitude:None date:2021-11-07 15:09:42+00:00 mileage:None level:97.0 charge_date:2021-11-07 15:09:42+00:00 level_fuel:0.0 moving:None
2021-11-07 15:13:44,290 :: DEBUG :: position already saved
2021-11-07 15:13:44,290 :: DEBUG :: position already saved
2021-11-07 15:13:44,291 :: DEBUG :: No abrp token provided
2021-11-07 15:13:44,291 :: DEBUG :: No abrp token provided
2021-11-07 15:13:44,291 :: DEBUG :: battery table is probably empty : Traceback (most recent call last): File "/psa_car_controller/libs/charging.py", line 60, in record_charging start_at, stop_at, start_level = conn.execute( TypeError: cannot unpack non-iterable NoneType object
2021-11-07 15:13:44,291 :: DEBUG :: battery table is probably empty : Traceback (most recent call last): File "/psa_car_controller/libs/charging.py", line 60, in record_charging start_at, stop_at, start_level = conn.execute( TypeError: cannot unpack non-iterable NoneType object
2021-11-07 15:13:44,292 :: DEBUG :: charging_status:Stopped
2021-11-07 15:13:44,292 :: DEBUG :: charging_status:Stopped
2021-11-07 15:13:44,292 :: INFO :: charging status of [VIN] is Stopped, battery level: 97
2021-11-07 15:13:44,292 :: INFO :: charging status of [VIN] is Stopped, battery level: 97

[RESTART]

2021-11-07 15:15:44,270 :: DEBUG :: refresh_vehicle_info
2021-11-07 15:15:44,270 :: DEBUG :: refresh_vehicle_info
2021-11-07 15:15:44,817 :: DEBUG :: vin:[VIN] longitude:None latitude:None date:2021-11-07 15:15:34+00:00 mileage:None level:97.0 charge_date:2021-11-07 15:15:34+00:00 level_fuel:0.0 moving:None
2021-11-07 15:15:44,817 :: DEBUG :: vin:[VIN] longitude:None latitude:None date:2021-11-07 15:15:34+00:00 mileage:None level:97.0 charge_date:2021-11-07 15:15:34+00:00 level_fuel:0.0 moving:None
2021-11-07 15:15:44,819 :: INFO :: level_fuel unfixed for [VIN]
2021-11-07 15:15:44,819 :: INFO :: level_fuel unfixed for [VIN]
2021-11-07 15:15:44,826 :: INFO :: new position recorded for [VIN]
2021-11-07 15:15:44,826 :: INFO :: new position recorded for [VIN]
2021-11-07 15:15:44,826 :: DEBUG :: Delete duplicate line
2021-11-07 15:15:44,826 :: DEBUG :: Delete duplicate line
2021-11-07 15:15:44,832 :: INFO :: update_data
2021-11-07 15:15:44,832 :: INFO :: update_data
2021-11-07 15:15:44,835 :: DEBUG :: Bad mileage value in DB
2021-11-07 15:15:44,835 :: DEBUG :: Bad mileage value in DB
2021-11-07 15:15:44,836 :: DEBUG :: No trips yet
2021-11-07 15:15:44,836 :: DEBUG :: No trips yet
2021-11-07 15:15:45,094 :: DEBUG :: No chargings yet
2021-11-07 15:15:45,094 :: DEBUG :: No chargings yet
2021-11-07 15:15:45,096 :: DEBUG :: No abrp token provided
2021-11-07 15:15:45,096 :: DEBUG :: No abrp token provided
2021-11-07 15:15:45,099 :: DEBUG :: battery table is probably empty : Traceback (most recent call last): File "/psa_car_controller/libs/charging.py", line 60, in record_charging start_at, stop_at, start_level = conn.execute( TypeError: cannot unpack non-iterable NoneType object
2021-11-07 15:15:45,099 :: DEBUG :: battery table is probably empty : Traceback (most recent call last): File "/psa_car_controller/libs/charging.py", line 60, in record_charging start_at, stop_at, start_level = conn.execute( TypeError: cannot unpack non-iterable NoneType object
2021-11-07 15:15:45,101 :: DEBUG :: charging_status:Stopped
2021-11-07 15:15:45,101 :: DEBUG :: charging_status:Stopped
2021-11-07 15:15:45,104 :: INFO :: charging status of [VIN] is Stopped, battery level: 97
2021-11-07 15:15:45,104 :: INFO :: charging status of [VIN] is Stopped, battery level: 97
2021-11-07 15:16:23,041 :: INFO :: save config change
2021-11-07 15:16:23,670 :: INFO :: ["{'vin': '[VIN]', 'vehicle_id': '|[VID]', 'label': 'Grandland X Hybrid', 'brand': 'C', 'abrp_name': None, 'battery_power': 13.2, 'fuel_capacity': 43, 'max_elec_consumption': 70, 'max_fuel_consumption': 30}"]
2021-11-07 15:16:24,096 :: INFO :: save config change
2021-11-07 15:16:24,492 :: DEBUG :: refresh_remote_token: {'scope': 'psaCustomerId psaMqttService', 'expires_in': 899, 'token_type': 'Bearer', 'access_token': '[ACCESS_TOKEN]', 'refresh_token': '[REFRESH_TOKEN]'}
2021-11-07 15:16:24,659 :: INFO :: ask wakeup to [VIN]
2021-11-07 15:16:24,844 :: INFO :: Connected with result code {'session present': 0}
2021-11-07 15:16:24,846 :: INFO :: subscribe to psa/RemoteServices/to/cid/OV-[ACNT]/#
2021-11-07 15:16:24,847 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/[VIN]
2021-11-07 15:16:25,052 :: INFO :: save config change
2021-11-07 15:16:25,053 :: INFO :: {"access_token": "[ACCESS_TOKEN]", "customer_id": "OV-[ACNT]", "correlation_id": "[CID]", "req_date": "2021-11-07T15:16:25Z", "vin": "[VIN]", "req_parameters": {"action": "state"}}
2021-11-07 15:16:25,055 :: DEBUG :: refresh_vehicle_info
2021-11-07 15:16:25,062 :: WARNING :: Can't get language
2021-11-07 15:16:25,523 :: DEBUG :: vin:[VIN] longitude:None latitude:None date:2021-11-07 15:15:34+00:00 mileage:None level:97.0 charge_date:2021-11-07 15:15:34+00:00 level_fuel:0.0 moving:None
2021-11-07 15:16:25,532 :: DEBUG :: position already saved
2021-11-07 15:16:25,549 :: DEBUG :: No abrp token provided
2021-11-07 15:16:25,577 :: DEBUG :: battery table is probably empty : Traceback (most recent call last): File "/psa_car_controller/libs/charging.py", line 60, in record_charging start_at, stop_at, start_level = conn.execute( TypeError: cannot unpack non-iterable NoneType object
2021-11-07 15:16:25,595 :: DEBUG :: charging_status:Stopped
2021-11-07 15:16:25,595 :: INFO :: charging status of [VIN] is Stopped, battery level: 97
2021-11-07 15:16:25,775 :: INFO :: update_data
2021-11-07 15:16:25,777 :: DEBUG :: Bad mileage value in DB
2021-11-07 15:16:25,777 :: DEBUG :: No trips yet
2021-11-07 15:16:26,518 :: DEBUG :: No chargings yet
2021-11-07 15:16:26,671 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-[ACNT]/VehCharge/state/ProcessManagement b'{"process_date":"2021-11-07T15:16:26Z","vin":"[VIN]","correlation_id":"[CID]","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2021-11-07 15:16:26,671 :: DEBUG :: mqtt msg hasn't return code
2021-11-07 15:16:26,742 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-[ACNT]/VehCharge/state/ProcessManagement b'{"process_date":"2021-11-07T15:16:26Z","vin":"[VIN]","correlation_id":"[CID]","process_code":"903","process_message":"[process.903.request.forwarded.to.vehicle.key]"}'
2021-11-07 15:16:26,743 :: DEBUG :: mqtt msg hasn't return code
2021-11-07 15:16:27,861 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-[ACNT]/VehCharge/state b'{"resp_date":"2021-11-07T15:16:27Z","vin":"[VIN]","correlation_id":"[CID]","return_code":"0"}'
2021-11-07 15:16:30,511 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/[VIN] b'{"date":"2021-11-07T15:16:21Z","etat_res_elec":0,"precond_state":{"available":1,"programs":{"program1":{"hour":6,"minute":45,"on":0,"day":[0,0,0,0,1,0,0]},"program2":{"hour":19,"minute":50,"on":0,"day":[0,0,0,1,0,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0,"aff":1},"charging_state":{"program":{"hour":1,"minute":30},"available":1,"remaining_time":40,"rate":0,"cable_detected":0,"soc_batt":97,"autonomy_zev":30,"type":1,"aff":1,"hmi_state":3,"mode":0},"stolen_state":0,"vin":"[VIN]","reason":4,"signal_quality":4,"sev_stop_date":"2021-11-07T14:19:54Z","fds":`

**Comment by kurim** [comment]
it also crash for me

```log
2021-11-08 18:52:41,509 :: DEBUG :: refresh_vehicle_info
2021-11-08 18:52:41,997 :: DEBUG :: vin:VXKUHXXXXXXXXXXXX longitude:None latitude:None date:2021-11-08 17:51:47+00:00 mileage:4097.3 level:78.0 charge_date:2021-11-08 17:51:47+00:00 level_fuel:0.0 moving:None
2021-11-08 18:52:42,004 :: INFO :: level_fuel unfixed for VXKUHXXXXXXXXXXXX
2021-11-08 18:52:42,020 :: INFO :: new position recorded for VXKUHXXXXXXXXXXXX
2021-11-08 18:52:42,022 :: INFO :: update_data
2021-11-08 18:52:43,629 :: DEBUG :: min_date:2021-07-20 14:39:03+00:00 - max_date:2021-11-08 16:08:48+00:00
2021-11-08 18:52:45,343 :: DEBUG :: {"status": "ok", "missing": "Missing telemetry: power, speed, lat, lon, "}
2021-11-08 18:52:45,348 :: ERROR :: Can't find country for None None
2021-11-08 18:52:45,349 :: WARNING :: Using country of origin : DE (wrong co2 when traveling abroad)
2021-11-08 18:52:45,371 :: INFO :: update_data
2021-11-08 18:52:46,898 :: DEBUG :: min_date:2021-07-20 14:39:03+00:00 - max_date:2021-11-08 16:08:48+00:00
2021-11-08 18:52:48,285 :: DEBUG :: charging_status:InProgress**
2021-11-08 18:57:48,369 :: DEBUG :: refresh_vehicle_info
2021-11-08 18:57:48,868 :: DEBUG :: vin:VXKUHXXXXXXXXXXXX longitude:None latitude:None date:2021-11-08 17:51:47+00:00 mileage:4097.3 level:78.0 charge_date:2021-11-08 17:51:47+00:00 level_fuel:0.0 moving:None
2021-11-08 18:57:48,875 :: DEBUG :: position already saved
2021-11-08 18:57:49,181 :: DEBUG :: {"status": "ok", "missing": "Missing telemetry: power, speed, lat, lon, "}
2021-11-08 18:57:49,186 :: DEBUG :: level already stored
2021-11-08 18:57:49,188 :: ERROR :: Can't find country for None None
2021-11-08 18:57:49,190 :: WARNING :: Using country of origin : DE (wrong co2 when traveling abroad)
2021-11-08 18:57:50,000 :: DEBUG :: charging_status:InProgress
```
@2021-11-08 18:52:48,285  it stop working

**Comment by abmantis** [comment]
I also have this issue. The app does not actually lock, it is only the HTTP server that stops replying. I can still see normal logs showing up by the app. There does not seem to be anything out of the ordinary on the logs.
Also, if you wait (sometimes 20 minutes), the http server will start to work again.

**Comment by flobz** [comment]
Do you call the wakeup endpoint often ?
I make some change in the develop branch if you want to try. It might give you the error in the log.
Also I create a docker image from develop branch with tag: "edge".

**Comment by abmantis** [comment]
@flobz I've tried that one but I get a 500 InternalServerError (from the app, not from the cloud) when calling the charge_now api.

**Comment by flobz** [comment]
Can you give me the log?

**Comment by flobz** [comment]
Do you call the wakeup endpoint often ?

**Comment by flobz** [comment]
I reproduce the error by calling three times the charge_now api in a row.
Don't call too often remote control api (wakeup, precond, charge...).
I think that I fixed the problem this morning.

**Comment by flobz** [comment]
New version and new docker image with "edge" tag. 
If you could give me feedback, it would be nice ! :)

**Comment by DreamT80** [comment]
I've done some testing on the "edge" version. Much is working better now, great work!!

/preconditioning/[vin]/1 or 0: Seems to work now! I've had two occasions where /0 (off) didn't "do" anything (the preconditioning continued), but I think this is related to the API itself?

charge_hour?vin=[vin]&hour=22&min=30
Gives me bad request (HTTP 400). Error, or could it mean that my car doesn't support the operation? (in the app I can set the time for when the charging should start, so I guess it's supported?)
`172.17.0.1 - - [12/Nov/2021 17:19:33] "GET /charge_hour?vin=[vin]&hour=22 HTTP/1.1" 400 -`

/charge_now/[vin]/1 or 0
Works!

However, worth mentioning is that I get an occasional error 500 error (internal server error). I've seen in the discussion above that it may have to do with too frequent calls to the API. But, in my case (regarding to the logs) it seems to do with mileage (my car doesn't support that, it's empty in the response). I know that there has been other fixes for this. It has occurred on charge_now and get_vehicle_info. Tell me if I should open a separate issue for it. See log below.
`Exception on /charge_now/[VIN]/0 [GET]

Traceback (most recent call last):

File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app

response = self.full_dispatch_request()

File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request

rv = self.handle_user_exception(e)

File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception

reraise(exc_type, exc_value, tb)

File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise

raise value

File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request

rv = self.dispatch_request()

File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request

return self.view_functions[rule.endpoint](**req.view_args)

File "/psa_car_controller/web/view/views.py", line 162, in charge_now

return jsonify(CONFIG.myp.charge_now(vin, charge != 0))

File "/psa_car_controller/my_psacc.py", line 381, in charge_now

hour, minute = self.__get_charge_hour(vin)

File "/psa_car_controller/my_psacc.py", line 353, in __get_charge_hour

data = self.get_vehicle_info(vin)

File "/psa_car_controller/my_psacc.py", line 140, in get_vehicle_info

self.record_info(car)

File "/psa_car_controller/my_psacc.py", line 481, in record_info

Charging.record_charging(car, charging_status, charge_date, level, latitude, longitude, self.country_code,

File "/psa_car_controller/libs/charging.py", line 72, in record_charging

conn.close()

File "/psa_car_controller/web/db.py", line 45, in close

self.execute_callbacks()

File "/psa_car_controller/web/db.py", line 41, in execute_callbacks

callback()

File "/psa_car_controller/web/view/views.py", line 254, in update_trips

trips_by_vin = Trips.get_trips(Cars([car]))

File "/psa_car_controller/trip.py", line 177, in get_trips

distance = next_el["mileage"] - end["mileage"] # km

TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'`

**Comment by abmantis** [comment]
> Can you give me the log?

It wasn't even logging anything for that command, I think the HTTP server wasn't even handling it. But with the latest edge version it is working fine!



> Do you call the wakeup endpoint often ?

I had a HA script that would call it twice with a 2s delay, because it seemed that if the auth token was expired, it needed a second call to refresh it. I've removed that for now.

**Comment by flobz** [comment]
retry is done automatically now.
