### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by farom57** [flobz/psa_car_controller#24]
Error occurs when calling http://localhost:5000/position/YOURVIN

`Traceback (most recent call last):
  File "/home/farom/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/farom/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/farom/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/farom/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/farom/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/farom/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/farom/Dev/e208/psa_car_controller/web/callback.py", line 80, in get_position
    longitude, latitude = res.last_position.geometry.coordinates
ValueError: too many values to unpack (expected 2)
`

**Comment by jlayec** [comment]
Hello

I don't have the same issue as you. it works fine for me.

When trying your fix i have the following error
`ValueError: not enough values to unpack (expected 3, got 2)`

seems that there is a dependancy somehwere else. Maybe version of a library? Python?

```
python3 -V
Python 3.7.3

pip3 list
Package                   Version
------------------------- -----------
...
geojson                   2.5.0
...
```

**Comment by farom57** [comment]
My versions:
Python 3.8.5
geojson                   2.5.0 

get_vehicleinfo/YOURVIN returns the longitude, latitude and altitude for me. It may be different for you.

[
![Screenshot_20210207_225921](https://user-images.githubusercontent.com/7573799/107160764-8ad39680-6998-11eb-8502-abd28eaf3143.png)
](url)

**Comment by jlayec** [comment]
Exactly!

mine is 

`"last_position": {"type": "Feature", "geometry": {"coordinates": [2.xxxx, 48.xxxx], "type": "Point"}`

the fix should detect if altitude is present or not
