### ISSUE TITLE
psa_car_controller v2.5.2 don't start

### ISSUE THREAD

**Issue by italoc** [flobz/psa_car_controller#252]
**Describe the bug**
app don't run, i start from a fresh installation

**To Reproduce**
insstall psa_car_controller on RPI home assistant or another linux/mac host

**Environment (please complete the following information):**
 - linux
 - Brand and model of car
 - 2.5.2
 - log
Also, if you're using any of the table format helpers (e.g. Group), replace 
`from dash_table.Format import Group` with 
`from dash.dash_table.Format import Group`
  import dash_table
2021-10-16 09:48:04,174 :: INFO :: update_data
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/psa_car_controller/web/app.py", line 45, in start_app
    run(config_flask(*args, **kwargs))
  File "/psa_car_controller/web/app.py", line 78, in config_flask
    importlib.import_module(view)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/psa_car_controller/web/view/views.py", line 387, in <module>
    update_trips()
  File "/psa_car_controller/web/view/views.py", line 249, in update_trips
    car = CONFIG.myp.vehicles_list[0]  # todo handle multiple car
AttributeError: 'Config' object has no attribute 'myp'

**Additional context**

**Comment by fabiomaticus** [comment]
Hi, i have same problem with fresh installation of 2.5.2

**Comment by Whitytom** [comment]
Same for me as documented in my question:
https://github.com/flobz/psa_car_controller/discussions/242
I tried it on 2 Win10 machines, on Ubuntu and on Raspi, everywhere the same result.
