### ISSUE TITLE
Can't start on raspberry pi 

### ISSUE THREAD

**Issue by dakoal** [flobz/psa_car_controller#255]
Hi.

prerequisits are done.
sudo apt-get update
sudo apt-get upgrade
are also done.

I got this error on starting the first time.
`python3 server.py --web-conf
/home/pi/psa/psa_car_controller-2.5.1/web/view/views.py:8: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
/home/pi/psa/psa_car_controller-2.5.1/web/utils.py:4: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
/home/pi/psa/psa_car_controller-2.5.1/web/figures.py:7: UserWarning:
The dash_table package is deprecated. Please replace
`import dash_table` with `from dash import dash_table`

Also, if you're using any of the table format helpers (e.g. Group), replace
`from dash_table.Format import Group` with
`from dash.dash_table.Format import Group`
  from dash_table.Format import Format, Scheme, Symbol
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/psa/psa_car_controller-2.5.1/web/app.py", line 45, in start_app
    run(config_flask(*args, **kwargs))
  File "/home/pi/psa/psa_car_controller-2.5.1/web/app.py", line 75, in config_flask
    importlib.import_module(view)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/psa/psa_car_controller-2.5.1/web/view/views.py", line 24, in <module>
    from web.view.config_views import config_layout, config_otp_layout, log_layout
  File "/home/pi/psa/psa_car_controller-2.5.1/web/view/config_views.py", line 19, in <module>
    dbc.FormGroup([
  File "/home/pi/.local/lib/python3.7/site-packages/dash_bootstrap_components/__init__.py", line 53, in __getattr__
    f"{name} was deprecated in dash-bootstrap-components version "
AttributeError: FormGroup was deprecated in dash-bootstrap-components version 1.0.0. You are using 1.0.0. For more details please see the migration guide: https://dbc-v1.herokuapp.com/migration-guide/`

**Comment by FlHinrichsen** [comment]
Same here, after doing an apt upgrade the service did not start any more:

>  /opt/psa_car_controller/web/figures.py:4: UserWarning:
> The dash_table package is deprecated. Please replace
> `import dash_table` with `from dash import dash_table`
> 
> Also, if you're using any of the table format helpers (e.g. Group), replace
> `from dash_table.Format import Group` with
> `from dash.dash_table.Format import Group`
>  import dash_table
> Exception in thread Thread-4:
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.7/threading.py", line 865, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/psa_car_controller/web/app.py", line 45, in start_app
>     run(config_flask(*args, **kwargs))
>   File "/opt/psa_car_controller/web/app.py", line 75, in config_flask
>     importlib.import_module(view)
>   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/opt/psa_car_controller/web/view/views.py", line 23, in <module>
>     from web.view.config_views import config_layout, config_otp_layout, log_layout
>   File "/opt/psa_car_controller/web/view/config_views.py", line 19, in <module>
>     dbc.FormGroup([
>   File "/usr/local/lib/python3.7/dist-packages/dash_bootstrap_components/__init__.py", line 53, in __getattr__
>     f"{name} was deprecated in dash-bootstrap-components version "
> AttributeError: FormGroup was deprecated in dash-bootstrap-components version 1.0.0. You are using 1.0.0. For more details > please see the migration guide: https://dbc-v1.herokuapp.com/migration-guide/
