### ISSUE TITLE
NEED_CREATION error

### ISSUE THREAD

**Issue by DavidFFerreira** [flobz/psa_car_controller#259]
**Describe the bug**
After update or unistall and reinstall I got an Error after trying do a config

**To Reproduce**
1. Update the app in Home Assistant \ Reinstall
2. The bug appears when I try to do a config
3. it persist after restarting the program
4. it persist after recreate config by going to http://server_address:port/config? (it happens in this process)

**Config file**
Give the anonymize content of the config file
![image](https://user-images.githubusercontent.com/32928749/138598054-35f1a500-0a4e-4c06-beae-966136b96b48.png)

**Environment (please complete the following information):**
 - Debian 11 ( Home Assistant Supervisor)
 - Citroen e-C4
 - v2.5.3
 - 
 `2021-10-24 15:10:46,258 :: WARNING :: Can't get language
2021-10-24 15:10:49,282 :: INFO :: update_data`

 `  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 200, in get_charge_control
    charge_control = CONFIG.chc.get(vin)
AttributeError: 'Config' object has no attribute 'chc'
172.30.32.1 - - [24/Oct/2021 15:12:01] "GET /charge_control?vin=[vin]&?always_check=true HTTP/1.1" 500 -
Exception on /get_vehicleinfo/[vin][GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 136, in get_vehicle_info
    response=json.dumps(CONFIG.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'Config' object has no attribute 'myp'
172.30.32.1 - - [24/Oct/2021 15:12:01] "GET /get_vehicleinfo/[vin]?from_cache=1 HTTP/1.1" 500 -
172.30.32.1 - - [24/Oct/2021 15:13:01] "GET /position?vin=[vin] HTTP/1.1" 200 -
2021-10-24 15:13:01,985 :: INFO :: <Request 'http://172.30.33.9:5000/charge_control?vin=[vin]&%3Falways_check=true' [GET]>
Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 200, in get_charge_control
    charge_control = CONFIG.chc.get(vin)
AttributeError: 'Config' object has no attribute 'chc'
172.30.32.1 - - [24/Oct/2021 15:13:01] "GET /charge_control?vin=[vin]?always_check=true HTTP/1.1" 500 -
Exception on /get_vehicleinfo/[vin] [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 136, in get_vehicle_info
    response=json.dumps(CONFIG.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'Config' object has no attribute 'myp'
172.30.32.1 - - [24/Oct/2021 15:13:02] "GET /get_vehicleinfo/[vin]?from_cache=1 HTTP/1.1" 500 -
172.30.32.1 - - [24/Oct/2021 15:14:01] "GET /position?vin=[vin] HTTP/1.1" 200 -
2021-10-24 15:14:01,968 :: INFO :: <Request 'http://172.30.33.9:5000/charge_control?vin=VR7BCZKXCME028469&%3Falways_check=true' [GET]>
172.30.32.1 - - [24/Oct/2021 15:14:01] "GET /charge_control?vin=[vin]&?always_check=true HTTP/1.1" 500 -
172.30.32.1 - - [24/Oct/2021 15:14:01] "GET /get_vehicleinfo/[vin]?from_cache=1 HTTP/1.1" 500 -
Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 200, in get_charge_control
    charge_control = CONFIG.chc.get(vin)
AttributeError: 'Config' object has no attribute 'chc'
Exception on /get_vehicleinfo/[vin] [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 136, in get_vehicle_info
    response=json.dumps(CONFIG.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'Config' object has no attribute 'myp'`

**Additional context**

**Comment by DavidFFerreira** [comment]
sill no changes, ive got same error until now

**Comment by flobz** [comment]
can you try last version

**Comment by DavidFFerreira** [comment]
ok

**Comment by DavidFFerreira** [comment]
still same probleme....

**Comment by DavidFFerreira** [comment]
@flobz now with new version, the error as gone, but another one came
![image](https://user-images.githubusercontent.com/32928749/143868287-c3a1d3c1-64e0-4309-a3da-cd81f766d015.png)

**Comment by flobz** [comment]
which version and which error ?

**Comment by DavidFFerreira** [comment]
right now...i got the same error NEED_CREATION 
Last version

**Comment by DavidFFerreira** [comment]
fixed finally
