### ISSUE TITLE
Chargecontrol Error

### ISSUE THREAD

**Issue by atze09** [flobz/psa_car_controller#27]
`2021-02-19 20:38:47,406 :: INFO :: <Request 'http://192.168.17.2:5000/charge_control?vin=vin&percentage=80' [GET]>
Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/psa_car_controller/web/callback.py", line 90, in charge_control
    charge_control = chc.get(vin)
AttributeError: 'NoneType' object has no attribute 'get'
192.168.17.7 - - [19/Feb/2021 20:38:47] "GET /charge_control?vin=con&percentage=80 HTTP/1.1" 500 -
`
I use the latest version of your server on a raspberry pi

**Comment by jlayec** [comment]
I've the same issue.
Should be fixed by https://github.com/flobz/psa_car_controller/pull/26/commits/4fb6c44ad26d7bfcf5fec7f498a8045be0fb3cf3
Should be fixed by https://github.com/flobz/psa_car_controller/pull/26

**Comment by flobz** [comment]
I apply your fix jlayec. 
Thanks
