### ISSUE TITLE
Add-on loading some data, but gui seems incomplete / standalone webpage not reachable

### ISSUE THREAD

**Issue by jeroenvdd** [flobz/psa_car_controller#278]
**Describe the bug**
Car data loads verry partially, config button doesn't work (the one in the corner)
and the webpage isn't available,
when i restart the application i also see that the webinterfaces started at 0.0.0.0:5000

I can open the tab in openhab, also see that it found my car but no data is shown,
but i cant acces http://192.168.0.140:5000/get_vehicleinfo/VXKUKZKXZMWxxxxx

with in my case 0.140 beeing the adres of my homeassistant server running the add-on

**To Reproduce**
1. what command did you use
no command yet, only the http request / trying to open config
2. when the bug append ?
from start
3. Does it persist after restarting the program? 
yes
4. Does it persist after recreate config by going to http://server_address:port/config? 
can't acces that one
**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
 - OS: VM on windows machine running the full ha 
 - Brand and model of car Opel mokka E
 - Application version (commit number, branch or tag)
 V2.5.4 from the repo psacc-ha
 - Log from http://server_address:port/log and browser console log
`2021-11-19 12:26:11,251 :: INFO :: Connected with result code {'session present': 0}
2021-11-19 12:26:11,253 :: INFO :: subscribe to psa/RemoteServices/to/cid/OV-ACNT200007854310/#
2021-11-19 12:26:11,254 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VXKUKZKXZMW056818
172.30.32.1 - - [19/Nov/2021 12:45:17] "GET / HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:17] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:17] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:17] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:17] "GET /control?header=false HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:17] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:17] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:17] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:17] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [19/Nov/2021 12:45:17] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:17] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:17] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:17] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:17] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [19/Nov/2021 12:45:17] "GET /style.json HTTP/1.1" 200 -
2021-11-19 12:45:17,890 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
  File "/psa_car_controller/web/view/control.py", line 27, in get_control_tabs
    preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
AttributeError: 'NoneType' object has no attribute 'preconditionning'
172.30.32.1 - - [19/Nov/2021 12:45:17] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:19] "GET / HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:20] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:20] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:20] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:20] "GET /control?header=false HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:20] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:20] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:20] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:20] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [19/Nov/2021 12:45:20] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:20] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:20] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [19/Nov/2021 12:45:20] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:20] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:45:20] "GET /style.json HTTP/1.1" 200 -
2021-11-19 12:45:20,456 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
  File "/psa_car_controller/web/view/control.py", line 27, in get_control_tabs
    preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
AttributeError: 'NoneType' object has no attribute 'preconditionning'
172.30.32.1 - - [19/Nov/2021 12:45:20] "POST /_dash-update-component HTTP/1.1" 200 -
2021-11-19 12:49:11,835 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/VXKUKZKXZMW056818 b'{"date":"2021-11-19T11:49:08Z","etat_res_elec":5,"precond_state":{"available":1,"programs":{"program1":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program2":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0},"charging_state":{"program":{"hour":0,"minute":1},"available":1,"remaining_time":635,"rate":0,"cable_detected":1,"soc_batt":45,"autonomy_zev":104,"type":0,"hmi_state":0,"mode":2},"stolen_state":0,"vin":"VXKUKZKXZMW056818","reason":0,"signal_quality":5,"sev_stop_date":"2021-11-19T11:08:41Z","fds":["NDR01","NBM01","NCG01","NAO01","NAS01"],"sev_state":1,"obj_counter":1,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2021-11-19 12:49:11,839 :: WARNING :: charge begin but API isn't updated
2021-11-19 12:50:11,894 :: INFO :: ask wakeup to VXKUKZKXZMW056818
2021-11-19 12:50:12,232 :: INFO :: save config change
2021-11-19 12:50:12,234 :: INFO :: {"access_token": "d3b632e8-c4cb-4db3-976a-26f5a4ee754f", "customer_id": "OV-ACNT200007854310", "correlation_id": "b9cf3305a284440ab1351e96e6808f5e20211119115012234", "req_date": "2021-11-19T11:50:12Z", "vin": "VXKUKZKXZMW056818", "req_parameters": {"action": "state"}}
2021-11-19 12:50:12,235 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/VXKUKZKXZMW056818 b'{"date":"2021-11-19T11:49:11Z","etat_res_elec":5,"precond_state":{"available":1,"programs":{"program1":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program2":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0},"charging_state":{"program":{"hour":0,"minute":1},"available":1,"remaining_time":635,"rate":0,"cable_detected":1,"soc_batt":45,"autonomy_zev":104,"type":0,"hmi_state":0,"mode":2},"stolen_state":0,"vin":"VXKUKZKXZMW056818","reason":4,"signal_quality":5,"sev_stop_date":"2021-11-19T11:08:41Z","fds":["NDR01","NBM01","NCG01","NAO01","NAS01"],"sev_state":1,"obj_counter":2,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2021-11-19 12:50:12,237 :: WARNING :: charge begin but API isn't updated
2021-11-19 12:51:12,292 :: INFO :: ask wakeup to VXKUKZKXZMW056818
2021-11-19 12:51:12,703 :: INFO :: save config change
2021-11-19 12:51:12,703 :: INFO :: {"access_token": "d3b632e8-c4cb-4db3-976a-26f5a4ee754f", "customer_id": "OV-ACNT200007854310", "correlation_id": "a261102240194221a564dfb08334a85a20211119115112703", "req_date": "2021-11-19T11:51:12Z", "vin": "VXKUKZKXZMW056818", "req_parameters": {"action": "state"}}
2021-11-19 12:51:12,704 :: WARNING :: Disconnected with result code 1
2021-11-19 12:51:12,987 :: INFO :: save config change
2021-11-19 12:51:14,626 :: INFO :: Connected with result code {'session present': 0}
2021-11-19 12:51:14,627 :: INFO :: subscribe to psa/RemoteServices/to/cid/OV-ACNT200007854310/#
2021-11-19 12:51:14,627 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VXKUKZKXZMW056818
2021-11-19 12:52:19,945 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/VXKUKZKXZMW056818 b'{"date":"2021-11-19T11:52:17Z","etat_res_elec":0,"precond_state":{"available":1,"programs":{"program1":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program2":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0},"charging_state":{"program":{"hour":0,"minute":1},"available":1,"remaining_time":635,"rate":0,"cable_detected":1,"soc_batt":45,"autonomy_zev":106,"type":0,"hmi_state":0,"mode":2},"stolen_state":0,"vin":"VXKUKZKXZMW056818","reason":0,"signal_quality":5,"sev_stop_date":"2021-11-19T11:50:19Z","fds":["NDR01","NBM01","NCG01","NAO01","NAS01"],"sev_state":0,"obj_counter":1,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2021-11-19 12:52:19,947 :: WARNING :: charge begin but API isn't updated
172.30.32.1 - - [19/Nov/2021 12:52:51] "GET / HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:52:51] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:52:51] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:52:51] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:52:51] "GET /control?header=false HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:52:51] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:52:51] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:52:51] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:52:51] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [19/Nov/2021 12:52:51] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:52:51] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:52:51] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:52:51] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:52:51] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [19/Nov/2021 12:52:51] "GET /style.json HTTP/1.1" 200 -
2021-11-19 12:52:52,056 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
  File "/psa_car_controller/web/view/control.py", line 27, in get_control_tabs
    preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
AttributeError: 'NoneType' object has no attribute 'preconditionning'
172.30.32.1 - - [19/Nov/2021 12:52:52] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:52:56] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:52:56] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:52:56] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [19/Nov/2021 12:52:56] "POST /_dash-update-component HTTP/1.1" 204 -
2021-11-19 12:53:20,008 :: INFO :: ask wakeup to VXKUKZKXZMW056818
2021-11-19 12:53:20,319 :: INFO :: save config change
2021-11-19 12:53:20,321 :: INFO :: {"access_token": "2f182f10-0d77-429f-a5d2-ff1a56a446b7", "customer_id": "OV-ACNT200007854310", "correlation_id": "87ba10a2f6444fe288073b89d7f519af20211119115320321", "req_date": "2021-11-19T11:53:20Z", "vin": "VXKUKZKXZMW056818", "req_parameters": {"action": "state"}}
2021-11-19 12:53:20,324 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/VXKUKZKXZMW056818 b'{"date":"2021-11-19T11:52:20Z","etat_res_elec":0,"precond_state":{"available":1,"programs":{"program1":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program2":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0},"charging_state":{"program":{"hour":0,"minute":1},"available":1,"remaining_time":635,"rate":0,"cable_detected":1,"soc_batt":45,"autonomy_zev":106,"type":0,"hmi_state":0,"mode":2},"stolen_state":0,"vin":"VXKUKZKXZMW056818","reason":4,"signal_quality":5,"sev_stop_date":"2021-11-19T11:50:19Z","fds":["NDR01","NBM01","NCG01","NAO01","NAS01"],"sev_state":0,"obj_counter":2,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2021-11-19 12:53:20,325 :: WARNING :: charge begin but API isn't updated
2021-11-19 13:10:12,239 :: INFO :: ask wakeup to VXKUKZKXZMW056818
2021-11-19 13:10:12,578 :: INFO :: save config change
2021-11-19 13:10:12,580 :: INFO :: {"access_token": "2f182f10-0d77-429f-a5d2-ff1a56a446b7", "customer_id": "OV-ACNT200007854310", "correlation_id": "940111095d704ccfb43fb1894b158ee320211119121012580", "req_date": "2021-11-19T12:10:12Z", "vin": "VXKUKZKXZMW056818", "req_parameters": {"action": "state"}}
2021-11-19 13:10:12,583 :: WARNING :: Disconnected with result code 1
2021-11-19 13:10:12,879 :: INFO :: save config change
2021-11-19 13:10:14,502 :: INFO :: Connected with result code {'session present': 0}
2021-11-19 13:10:14,504 :: INFO :: subscribe to psa/RemoteServices/to/cid/OV-ACNT200007854310/#
2021-11-19 13:10:14,506 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VXKUKZKXZMW056818`
**Additional context**

**Comment by azcn2503** [comment]
I am experiencing the same issue under the following environment:

* OS: HomeAssistant OS v6.3
* Brand and model of car: Vauxhall Corsa-e
* Application version (commit number, branch or tag): v2.5.4 from the repo psacc-ha

**Comment by azcn2503** [comment]
Unfortunately since getting the error, I tried uninstalling and reinstalling the add-on, now cannot progress past the initial login due to an error: `Invalid password or PKCS12 data`.

**Comment by flobz** [comment]
Use last version : 2.6.0

**Comment by azcn2503** [comment]
Unfortunately I get the same error on 2.6.0. Here is the associated log:

```
Containerised psa_car_controller loading...
2021-12-02 08:11:56,855 :: WARNING :: Can't get language
2021-12-02 08:11:58,767 :: INFO :: update_data
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
172.30.32.1 - - [02/Dec/2021 08:31:46] "GET / HTTP/1.1" 200 -
172.30.32.1 - - [02/Dec/2021 08:31:46] "GET /assets/clientside.js HTTP/1.1" 200 -
172.30.32.1 - - [02/Dec/2021 08:31:46] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [02/Dec/2021 08:31:46] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [02/Dec/2021 08:31:46] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [02/Dec/2021 08:31:46] "GET /config_login HTTP/1.1" 200 -
172.30.32.1 - - [02/Dec/2021 08:31:46] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [02/Dec/2021 08:31:46] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [02/Dec/2021 08:31:46] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [02/Dec/2021 08:31:46] "GET /assets/images/settings.svg HTTP/1.1" 200 -
172.30.32.1 - - [02/Dec/2021 08:31:46] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [02/Dec/2021 08:31:46] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [02/Dec/2021 08:31:47] "POST /_dash-update-component HTTP/1.1" 200 -
Requested API level 29 is larger than maximum we have, returning API level 28 instead.
172.30.32.1 - - [02/Dec/2021 08:32:08] "POST /_dash-update-component HTTP/1.1" 200 -
```

**Comment by flobz** [comment]
Ah yeah sorry but last time I checked. My Vauxhall android app v1.33 wasn't released and I need it for the app. Please wait :)

**Comment by flobz** [comment]
myVauxhall updated ! it should work for you.

**Comment by azcn2503** [comment]
Reporting back just to confirm that this is working, thank you!
