### ISSUE TITLE
get_vehicle_info: ApiException: (404) Reason: Not Found

### ISSUE THREAD

**Issue by riddik14** [flobz/psa_car_controller#279]
i receive this error log and no data download in web page. there is problem whit my vin and model car?
   my car in car model.py there is, but is a peugeot 2008 second series no electric but gasoline.

"
    CarModel("2008", 0, 44, reg=r"VR3USHNS.*"),  # VR3USHNSKM 
    CarModel("2008 II", 0, 45, reg=r"VR3USHNK.*"),  # VR3USHNKKL

"

my hassio log, with psa option "-r --web-conf  --remote-disable"

thanks you

Containerised psa_car_controller loading...
2021-11-20 12:09:22,217 :: INFO :: save config change
2021-11-20 12:09:22,875 :: INFO :: ["{'vin': 'VR3USHNSxxxxxxxx', 'vehicle_id': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'label': '2008', 'brand': 'Peugeot', 'abrp_name': None, 'battery_power': 0, 'fuel_capacity': 44, 'max_elec_consumption': 70, 'max_fuel_consumption': 30}"]
2021-11-20 12:09:22,877 :: INFO :: mqtt disabled
2021-11-20 12:09:22,899 :: WARNING :: Can't get language
2021-11-20 12:09:28,880 :: INFO :: update_data
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2021-11-20 12:10:22,278 :: INFO :: <Request 'http://192.168.1.247:5000/charge_control?vin=VR3USHNSxxxxxxxx&%3Falways_check=true' [GET]>
Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 200, in get_charge_control
    charge_control = CONFIG.chc.get(vin)
AttributeError: 'Config' object has no attribute 'chc'
192.168.1.247 - - [20/Nov/2021 12:10:22] "GET /charge_control?vin=VR3USHNSxxxxxxxx&?always_check=true HTTP/1.1" 500 -
2021-11-20 12:10:23,051 :: ERROR :: get_vehicle_info: ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'X-Backside-Transport': 'OK OK', 'Connection': 'close', 'Content-Type': 'application/hal+json', 'Date': 'Sat, 20 Nov 2021 11:10:23 GMT', 'X-Global-Transaction-ID': '945fb68f6198d79e04b1fb4d', 'Cache-Control': 'no-store, no-cache, must-revalidate, private', 'Expires': '0', 'Access-Control-Expose-Headers': 'APIm-Debug-Trans-Id, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-Global-Transaction-ID', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET', 'Set-Cookie': 'rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Fri, 19-Nov-2021 11:10:22 GMT, JSESSIONID=cxivIKdiQM6BvPLxVtD1fwJnLJbFbtDKyTmOeZ5t; path=/, PSACountry=IT;Domain=.groupe-psa.com;Path=/'})
HTTP response body: {"uuid":"cf629917-ecc7-4351-bd4e-a3697a0e3408","code":40400,"message":"Not Found: We didn't find the status for this vehicule."}
2021-11-20 12:10:23,580 :: ERROR :: get_vehicle_info: ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'X-Backside-Transport': 'OK OK', 'Connection': 'close', 'Content-Type': 'application/hal+json', 'Date': 'Sat, 20 Nov 2021 11:10:23 GMT', 'X-Global-Transaction-ID': '08f333a56198d79f21336a7f', 'Cache-Control': 'no-store, no-cache, must-revalidate, private', 'Expires': '0', 'Access-Control-Expose-Headers': 'APIm-Debug-Trans-Id, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-Global-Transaction-ID', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET', 'Set-Cookie': 'rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Fri, 19-Nov-2021 11:10:23 GMT, JSESSIONID=Lb48jLWsTdrUNG5A1gZTQADMHGC8ca3faqWJa14K; path=/, PSACountry=IT;Domain=.groupe-psa.com;Path=/'})
HTTP response body: {"uuid":"348ac354-cde9-4496-bff0-aef1c8a0d134","code":40400,"message":"Not Found: We didn't find the status for this vehicule."}
Exception on /get_vehicleinfo/VR3USHNSxxxxxxxx [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 136, in get_vehicle_info
    response=json.dumps(CONFIG.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'NoneType' object has no attribute 'to_dict'
192.168.1.247 - - [20/Nov/2021 12:10:23] "GET /get_vehicleinfo/VR3USHNSxxxxxxxx?from_cache=1 HTTP/1.1" 500 -

**Comment by flobz** [comment]
duplicate with #57
