### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'chc'

### ISSUE THREAD

**Issue by dreimer1986** [flobz/psa_car_controller#282]
**Describe the bug**
Log flooding

**To Reproduce**
Steps to reproduce the behavior: Just start the addin and check the log. Or try to change the charge threshold to force it
1. what command did you use: Nothing which is not addin default
2. when the bug append ? I noticed it today, but the log in report #279 shows the same thing already.
3. Does it persist after restarting the program? yes
4. Does it persist after recreate config by going to http://server_address:port/config? 

**Config file**
Give the anonymize content of the config file: On Addin I guess not...

**Environment (please complete the following information):**
 - OS: HASSOS
 - Brand and model of car: Peugeot e208
 - Application version (commit number, branch or tag): v2.5.5
 - Log from http://server_address:port/log and browser console log: See below the addin Log output.

**Additional context**

```
2021-11-26 08:41:58,026 :: INFO :: <Request 'http://192.168.181.42:5000/charge_control?vin=VR3UXZKXZMT0XX15X&percentage=95' [GET]>
Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 200, in get_charge_control
    charge_control = CONFIG.chc.get(vin)
AttributeError: 'Config' object has no attribute 'chc'
192.168.181.42 - - [26/Nov/2021 08:41:58] "GET /charge_control?vin=VR3UXZKXZMT0XX15X&percentage=95 HTTP/1.1" 500 -
```

**Comment by aferraz** [comment]
@dreimer1986 you should remove car VIN from the logs for your privacy and security

**Comment by flobz** [comment]
Does wakeup request works?

**Comment by dreimer1986** [comment]
@aferraz don't panic, I obfuscated it from the very beginning. ^^
@flobz 

```
192.168.181.42 - - [26/Nov/2021 10:53:41] "GET /get_vehicleinfo/VR3UXZKXZMT0XX15X?from_cache=1 HTTP/1.1" 200 -
2021-11-26 10:53:41,478 :: INFO :: <Request 'http://192.168.181.42:5000/charge_control?vin=VR3UXZKXZMT0XX15X&%3Falways_check=true' [GET]>
Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 200, in get_charge_control
    charge_control = CONFIG.chc.get(vin)
AttributeError: 'Config' object has no attribute 'chc'
192.168.181.42 - - [26/Nov/2021 10:53:41] "GET /charge_control?vin=VR3UXZKXZMT0XX15X&?always_check=true HTTP/1.1" 500 -
2021-11-26 10:54:03,959 :: INFO :: ask wakeup to VR3UXZKXZMT0XX15X
2021-11-26 10:54:04,441 :: INFO :: save config change
2021-11-26 10:54:04,442 :: INFO :: {"access_token": "5bbb2e39-8c5e-4905-acbe-3395f0f23d68", "customer_id": "AP-ACNT200005711219", "correlation_id": "ba66934df9e04bcdab5eadb44faef7e320211126095404442", "req_date": "2021-11-26T09:54:04Z", "vin": "VR3UXZKXZMT0XX15X", "req_parameters": {"action": "state"}}
192.168.181.42 - - [26/Nov/2021 10:54:04] "GET /wakeup/VR3UXZKXZMT0XX15X HTTP/1.1" 200 -
2021-11-26 10:54:04,789 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-ACNT200005711219/VehCharge/state b'{"resp_date":"2021-11-26T09:54:04Z","vin":"VR3UXZKXZMT0XX15X","correlation_id":"ba66934df9e04bcdab5eadb44faef7e320211126095404442","return_code":"400","reason":"[authorization.denied.cvs.from.uin.response.ko.key]"}'
2021-11-26 10:54:05,133 :: INFO :: save config change
2021-11-26 10:54:05,540 :: ERROR :: retry last request, token was expired
2021-11-26 10:54:07,154 :: INFO :: ask wakeup to VR3UXZKXZMT0XX15X
2021-11-26 10:54:07,511 :: INFO :: save config change
2021-11-26 10:54:07,512 :: INFO :: {"access_token": "5beb4c85-0e63-4bdc-8390-4144cd25e513", "customer_id": "AP-ACNT200005711219", "correlation_id": "a20343f2e06d4741ac6351772d5a517320211126095407512", "req_date": "2021-11-26T09:54:07Z", "vin": "VR3UXZKXZMT0XX15X", "req_parameters": {"action": "state"}}
192.168.181.42 - - [26/Nov/2021 10:54:07] "GET /wakeup/VR3UXZKXZMT0XX15X HTTP/1.1" 200 -
2021-11-26 10:54:07,801 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-ACNT200005711219/VehCharge/state/ProcessManagement b'{"process_date":"2021-11-26T09:54:07Z","vin":"VR3UXZKXZMT0XX15X","correlation_id":"a20343f2e06d4741ac6351772d5a517320211126095407512","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2021-11-26 10:54:07,858 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-ACNT200005711219/VehCharge/state/ProcessManagement b'{"process_date":"2021-11-26T09:54:07Z","vin":"VR3UXZKXZMT0XX15X","correlation_id":"a20343f2e06d4741ac6351772d5a517320211126095407512","process_code":"901","process_message":"[process.901.vehicle.asleep.key]"}'
```

Good question... Reading the log I would say... sometimes? My car has much fun to chill in deep sleep all the time. It's almost impossible to start the heater from app or get any charging information while on charger via app, so likely it does work as expected?

**Comment by dreimer1986** [comment]
Things are getting more crazy. I thought a reset of the config aka reset of the addin might be an idea. A bad idea...

![image](https://user-images.githubusercontent.com/29841368/143575566-e0aac644-f9bb-4bc2-a86b-b3f96d8a9be6.png)

**Comment by dreimer1986** [comment]
Things are getting more and more .... strange? I used the fork and change version trick to revert to 2.5.4... Here I get this:

![image](https://user-images.githubusercontent.com/29841368/143623964-4f94a959-9162-4ef7-8c0b-1351d61893d9.png)

```
172.30.32.1 - - [26/Nov/2021 20:32:02] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [26/Nov/2021 20:32:02] "POST /_dash-update-component HTTP/1.1" 204 -
Exception on /get_vehicleinfo/VR3UXZKXZMT0XX15X [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 136, in get_vehicle_info
    response=json.dumps(CONFIG.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'Config' object has no attribute 'myp'
192.168.181.42 - - [26/Nov/2021 20:32:13] "GET /get_vehicleinfo/VR3UXZKXZMT0XX15X?from_cache=1 HTTP/1.1" 500 -
2021-11-26 20:32:13,698 :: INFO :: <Request 'http://192.168.181.42:5000/charge_control?vin=VR3UXZKXZMT0XX15X&%3Falways_check=true' [GET]>
Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 200, in get_charge_control
    charge_control = CONFIG.chc.get(vin)
AttributeError: 'Config' object has no attribute 'chc'
192.168.181.42 - - [26/Nov/2021 20:32:13] "GET /charge_control?vin=VR3UXZKXZMT0XX15X&?always_check=true HTTP/1.1" 500 -
172.30.32.1 - - [26/Nov/2021 20:32:20] "GET / HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:21] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:21] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:21] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:21] "GET /config_login HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:21] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:21] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:21] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:21] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:21] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [26/Nov/2021 20:32:21] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [26/Nov/2021 20:32:22] "GET / HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:22] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:22] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:22] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:22] "GET /config_login HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:22] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:22] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:22] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:22] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:32:22] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [26/Nov/2021 20:32:22] "POST /_dash-update-component HTTP/1.1" 204 -
Requested API level 30 is larger than maximum we have, returning API level 28 instead.
172.30.32.1 - - [26/Nov/2021 20:32:43] "POST /_dash-update-component HTTP/1.1" 200 -
Exception on /get_vehicleinfo/VR3UXZKXZMT0XX15X [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 136, in get_vehicle_info
    response=json.dumps(CONFIG.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'Config' object has no attribute 'myp'
192.168.181.42 - - [26/Nov/2021 20:33:13] "GET /get_vehicleinfo/VR3UXZKXZMT0XX15X?from_cache=1 HTTP/1.1" 500 -
2021-11-26 20:33:13,699 :: INFO :: <Request 'http://192.168.181.42:5000/charge_control?vin=VR3UXZKXZMT0XX15X&%3Falways_check=true' [GET]>
Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 200, in get_charge_control
    charge_control = CONFIG.chc.get(vin)
AttributeError: 'Config' object has no attribute 'chc'
192.168.181.42 - - [26/Nov/2021 20:33:13] "GET /charge_control?vin=VR3UXZKXZMT0XX15X&
```

Here a full log of the official 2.5.5:

```
Containerised psa_car_controller loading...
2021-11-26 20:37:02,043 :: WARNING :: Can't get language
2021-11-26 20:37:02,694 :: INFO :: update_data
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
172.30.32.1 - - [26/Nov/2021 20:37:04] "GET / HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:37:04] "GET /assets/clientside.js HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:37:04] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:37:04] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:37:04] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:37:04] "GET /config_login HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:37:04] "GET /assets/images/settings.svg HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:37:04] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:37:04] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:37:04] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:37:04] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 20:37:04] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [26/Nov/2021 20:37:04] "POST /_dash-update-component HTTP/1.1" 204 -
Exception on /get_vehicleinfo/VR3UXZKXZMT0XX15X [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 136, in get_vehicle_info
    response=json.dumps(CONFIG.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'Config' object has no attribute 'myp'
192.168.181.42 - - [26/Nov/2021 20:37:13] "GET /get_vehicleinfo/VR3UXZKXZMT0XX15X?from_cache=1 HTTP/1.1" 500 -
2021-11-26 20:37:13,707 :: INFO :: <Request 'http://192.168.181.42:5000/charge_control?vin=VR3UXZKXZMT0XX15X&%3Falways_check=true' [GET]>
Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 200, in get_charge_control
    charge_control = CONFIG.chc.get(vin)
AttributeError: 'Config' object has no attribute 'chc'
192.168.181.42 - - [26/Nov/2021 20:37:13] "GET /charge_control?vin=VR3UXZKXZMT0XX15X&?always_check=true HTTP/1.1" 500 -
Requested API level 30 is larger than maximum we have, returning API level 28 instead.
2021-11-26 20:37:53,204 :: ERROR :: Traceback (most recent call last):
  File "/psa_car_controller/app_decoder.py", line 109, in firstLaunchConfig
    customer_id = BRAND[package_name]["brand_code"] + "-" + res_dict["id"]
KeyError: 'id'
{"success":{"language":"fr","country":"FR","profile":{"email":""},"dealers":{},"vehicles":[],"settings_update":1637772830,"terms_service":{"cguForValidation":"496","lastCguAlreadyValidated":"496"},"early_adopter":["REMOTELEV"],"service_state":[],"cgu_validation":false}}
172.30.32.1 - - [26/Nov/2021 20:37:53] "POST /_dash-update-component HTTP/1.1" 200 -
Exception on /get_vehicleinfo/VR3UXZKXZMT0XX15X [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 136, in get_vehicle_info
    response=json.dumps(CONFIG.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'Config' object has no attribute 'myp'
192.168.181.42 - - [26/Nov/2021 20:38:13] "GET /get_vehicleinfo/VR3UXZKXZMT0XX15X?from_cache=1 HTTP/1.1" 500 -
2021-11-26 20:38:13,706 :: INFO :: <Request 'http://192.168.181.42:5000/charge_control?vin=VR3UXZKXZMT0XX15X&%3Falways_check=true' [GET]>
Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 200, in get_charge_control
    charge_control = CONFIG.chc.get(vin)
AttributeError: 'Config' object has no attribute 'chc'
192.168.181.42 - - [26/Nov/2021 20:38:13] "GET /charge_control?vin=VR3UXZKXZMT0XX15X&?always_check=true HTTP/1.1" 500 -
```

**Comment by dreimer1986** [comment]
Sorry for the mess caused. Did not see the other report had the same problem. Installed the new version. Yes. The non french login problem is fixed here, too. The main reason for the report still persists though. I will send a recent log when I am back home. Btw, i get all information as before, so might be just a charge control problem.

**Comment by show2go** [comment]
Hey,
now the Home Assistant Addon is working, but i also have no charge control.
here is the log:

`2021-11-27 13:51:37,198 :: INFO :: <Request 'http://192.168.xxx.xxx:5000/charge_control?vin=VXEVxxxxxxxxxxx&%3Falways_check=true' [GET]>
Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 200, in get_charge_control
    charge_control = CONFIG.chc.get(vin)
AttributeError: 'Config' object has no attribute 'chc'`

---------------------------------------------------------------------------------------------------
i also tested it on a RPI3, but i cant even log in:

message from webgui after first hit on submit:

`'latin-1' codec can't encode character '\u20ac' in position 11: ordinal not in range(256)`

message from webgui after second hit on submit:

`'Electricity config'`


second time i start the server, message in terminal:

`python3 server.py -l 0.0.0.0 --web-conf
Traceback (most recent call last):
  File "server.py", line 22, in <module>
    conf.load_app()
  File "/home/pi/psa_car_controller-master/libs/config.py", line 82, in load_app
    Charging.elec_price = ElecPrice.read_config()
  File "/home/pi/psa_car_controller-master/libs/elec_price.py", line 79, in read_config
    elec_config = config["Electricity config"]
  File "/usr/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'Electricity config'
2021-11-27 13:49:05,911 :: INFO :: save config change
`

Thank you so much for your work!
if i could help, please let me know!
J

**Comment by andyvee69** [comment]
I had this error CONFIG.chc.get(vin) AttributeError: 'Config' object has no attribute 'chc' - I added the -c command line switch to the PSACC options under Supervisor > PSACC > Options

**Comment by flobz** [comment]
You right. I add the - c as a default option now.

**Comment by dreimer1986** [comment]
Confirmed fixing the problems. No errors at all and a clean log. Thanks to everyone involved 😊
