### ISSUE TITLE
Invalid password or PKCS12 data

### ISSUE THREAD

**Issue by JohannCR** [flobz/psa_car_controller#285]
Hi,
I've got a blank "My car info" page.
User config gives error
'Invalid password or PKCS12 data'
Logins are double checked.
FR country code.

Here is the log
```
2021-11-29 14:41:24,377 :: INFO :: []
2021-11-29 14:41:24,378 :: INFO :: mqtt disabled
2021-11-29 14:41:24,380 :: WARNING :: Can't get language
2021-11-29 14:41:35,525 :: INFO :: update_data
2021-11-29 14:46:25,097 :: INFO :: save config change
2021-11-29 14:46:25,668 :: ERROR :: get_vehicles:
Traceback (most recent call last):
File "/psa_car_controller/my_psacc.py", line 197, in get_vehicles
res = self.api().get_vehicles_by_device()
File "/psa_car_controller/psa_connectedcar/api/vehicles_api.py", line 1331, in get_vehicles_by_device
(data) = self.get_vehicles_by_device_with_http_info(**kwargs) # noqa: E501
File "/psa_car_controller/psa_connectedcar/api/vehicles_api.py", line 1400, in get_vehicles_by_device_with_http_info
return self.api_client.call_api(
File "/psa_car_controller/libs/oauth.py", line 77, in call_api
raise e
File "/psa_car_controller/libs/oauth.py", line 59, in call_api
return self._ApiClient__call_api(resource_path, method,
File "/psa_car_controller/psa_connectedcar/api_client.py", line 157, in __call_api
response_data = self.request(
File "/psa_car_controller/psa_connectedcar/api_client.py", line 347, in request
return self.rest_client.GET(url,
File "/psa_car_controller/psa_connectedcar/rest.py", line 234, in GET
return self.request("GET", url,
File "/psa_car_controller/psa_connectedcar/rest.py", line 228, in request
raise ApiException(http_resp=r)
psa_connectedcar.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'X-Backside-Transport': 'FAIL FAIL', 'Connection': 'close', 'Cache-Control': 'no-store, no-cache, must-revalidate, private', 'Content-Type': 'application/hal+json', 'Date': 'Mon, 29 Nov 2021 14:46:25 GMT', 'Expires': '0', 'X-Global-Transaction-ID': '08f333a561a4e7c15f475a7f', 'Access-Control-Expose-Headers': 'APIm-Debug-Trans-Id, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-Global-Transaction-ID', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET', 'Set-Cookie': 'rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Sun, 28-Nov-2021 14:46:25 GMT, JSESSIONID=mRIxAoohHj3iff3e6_3sBD98xJ9dLDApv48-UvNn; path=/, PSACountry=FR;Domain=.groupe-psa.com;Path=/'})
HTTP response body: {"uuid":"9b39d7b8-842f-4e9e-89a8-c6f1e5145853","code":40410,"message":"No vehicule found"}
```

**Comment by aferraz** [comment]
Hi,
 I think the problem is the apk. You can try to delete the apk.

Regards
 Alessandro

**Comment by JohannCR** [comment]
Ok now user config works, but OTP doesn't... 
I've tried --remote-disable but same thing. The app shows several trips so something is missing here.
Thanks for your help !
