### ISSUE TITLE
I get no info´s

### ISSUE THREAD

**Issue by nuiler** [flobz/psa_car_controller#293]
2021-12-06 12:15:08,992 :: WARNING :: Can't get language
2021-12-06 12:15:16,414 :: INFO :: update_data
2021-12-06 12:18:30,609 :: INFO :: save config change
2021-12-06 12:18:31,481 :: INFO ::
Your vehicles: ["{'vin': 'xxxxxxx', 'vehicle_id': '1567a4257576a524552316f33545459344d7a55794e54516a49324a6a5a475132595455784e445a684f4759794e4759344e7a51774e6d59314e4441784e5459794d475668596d4d31597a4a6d4d446b7a4e6a4e695a6d4a694d32526b4d57566c4f5459324f544a6a5a6a4d775a54513d', 'label': 'Grandland X Hybrid', 'brand': 'C', 'abrp_name': None, 'battery_power': 13.2, 'fuel_capacity': 43, 'max_elec_consumption': 70, 'max_fuel_consumption': 30}"]
2021-12-06 12:18:31,483 :: INFO :: save config change
2021-12-06 12:18:33,476 :: INFO :: ["{'vin': 'XXXXXX', 'vehicle_id': '1567a4257576a524552316f33545459344d7a55794e54516a49324a6a5a475132595455784e445a684f4759794e4759344e7a51774e6d59314e4441784e5459794d475668596d4d31597a4a6d4d446b7a4e6a4e695a6d4a694d32526b4d57566c4f5459324f544a6a5a6a4d775a54513d', 'label': 'Grandland X Hybrid', 'brand': 'C', 'abrp_name': None, 'battery_power': 13.2, 'fuel_capacity': 43, 'max_elec_consumption': 70, 'max_fuel_consumption': 30}"]
2021-12-06 12:18:33,480 :: INFO :: save config change
2021-12-06 12:19:37,217 :: ERROR :: Error during activation: {'newversion': '2.0.0', 'newversionurl': 'http://m.inwebo.com/', 'err': 'NOK:ACCESS'}
2021-12-06 12:19:37,570 :: ERROR :: remote_refresh_token isn't defined
2021-12-06 12:19:38,118 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'}
2021-12-06 12:19:38,131 :: ERROR :: get_otp_code:
Traceback (most recent call last):
File "/psa_car_controller/libs/psa/RemoteClient.py", line 186, in get_otp_code
otp_code = self.otp.get_otp_code()
File "/psa_car_controller/otp/otp.py", line 277, in get_otp_code
raise ConfigException("Can't get otp code")
otp.otp.ConfigException: Can't get otp code
2021-12-06 12:19:38,136 :: ERROR :: Please redo otp config
2021-12-06 12:19:38,703 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'}
2021-12-06 12:19:38,705 :: ERROR :: start_remote_control failed redo otp config
2021-12-06 12:19:42,880 :: WARNING :: Failed to generate figure, there is probably not enough data yet
2021-12-06 12:19:43,204 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
File "/psa_car_controller/web/view/control.py", line 35, in get_control_tabs
preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
AttributeError: 'NoneType' object has no attribute 'preconditionning'
2021-12-06 12:20:05,737 :: INFO :: save config change
2021-12-06 12:20:09,934 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
File "/psa_car_controller/web/view/control.py", line 35, in get_control_tabs
preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
AttributeError: 'NoneType' object has no attribute 'preconditionning'
2021-12-06 12:20:32,618 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
File "/psa_car_controller/web/view/control.py", line 35, in get_control_tabs
preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
AttributeError: 'NoneType' object has no attribute 'preconditionning'
2021-12-06 12:21:05,741 :: INFO :: save config change
2021-12-06 12:23:22,773 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
File "/psa_car_controller/web/view/control.py", line 35, in get_control_tabs
preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
AttributeError: 'NoneType' object has no attribute 'preconditionning'
2021-12-06 12:23:38,244 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
File "/psa_car_controller/web/view/control.py", line 35, in get_control_tabs
preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
AttributeError: 'NoneType' object has no attribute 'preconditionning'
2021-12-06 13:07:47,780 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
File "/psa_car_controller/web/view/control.py", line 35, in get_control_tabs
preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
AttributeError: 'NoneType' object has no attribute 'preconditionning'
2021-12-06 13:07:49,579 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
File "/psa_car_controller/web/view/control.py", line 35, in get_control_tabs
preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
AttributeError: 'NoneType' object has no attribute 'preconditionning'
2021-12-06 13:24:45,604 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
File "/psa_car_controller/web/view/control.py", line 35, in get_control_tabs
preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
AttributeError: 'NoneType' object has no attribute 'preconditionning'
2021-12-06 18:09:27,538 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
File "/psa_car_controller/web/view/control.py", line 35, in get_control_tabs
preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
AttributeError: 'NoneType' object has no attribute 'preconditionning'
2021-12-06 18:12:52,875 :: INFO :: ["{'vin': 'W0VZ4DGZ7M6835254', 'vehicle_id': '1567a4257576a524552316f33545459344d7a55794e54516a49324a6a5a475132595455784e445a684f4759794e4759344e7a51774e6d59314e4441784e5459794d475668596d4d31597a4a6d4d446b7a4e6a4e695a6d4a694d32526b4d57566c4f5459324f544a6a5a6a4d775a54513d', 'label': 'Grandland X Hybrid', 'brand': 'C', 'abrp_name': None, 'battery_power': 13.2, 'fuel_capacity': 43, 'max_elec_consumption': 70, 'max_fuel_consumption': 30}"]
2021-12-06 18:12:53,522 :: ERROR :: remote_refresh_token isn't defined
2021-12-06 18:12:54,231 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'}
2021-12-06 18:12:54,234 :: ERROR :: get_otp_code:
Traceback (most recent call last):
File "/psa_car_controller/libs/psa/RemoteClient.py", line 186, in get_otp_code
otp_code = self.otp.get_otp_code()
File "/psa_car_controller/otp/otp.py", line 277, in get_otp_code
raise ConfigException("Can't get otp code")
otp.otp.ConfigException: Can't get otp code
2021-12-06 18:12:54,241 :: ERROR :: Please redo otp config
2021-12-06 18:12:54,792 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'}
2021-12-06 18:12:54,794 :: ERROR :: start_remote_control failed redo otp config
2021-12-06 18:12:54,796 :: INFO :: save config change
2021-12-06 18:12:55,312 :: WARNING :: Can't get language
2021-12-06 18:13:12,487 :: INFO :: update_data
2021-12-07 10:13:56,897 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
File "/psa_car_controller/web/view/control.py", line 35, in get_control_tabs
preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
AttributeError: 'NoneType' object has no attribute 'preconditionning'
2021-12-07 10:17:41,998 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
File "/psa_car_controller/web/view/control.py", line 35, in get_control_tabs
preconditionning_state = car.status.preconditionning.air_conditioning.status != "Disabled"
AttributeError: 'NoneType' object has no attribute 'preconditionning'

Containerised psa_car_controller loading...
2021-12-07 10:34:33,214 :: INFO :: ["{'vin': 'W0VZ4DGZ7M6835254', 'vehicle_id': '1567a4257576a524552316f33545459344d7a55794e54516a49324a6a5a475132595455784e445a684f4759794e4759344e7a51774e6d59314e4441784e5459794d475668596d4d31597a4a6d4d446b7a4e6a4e695a6d4a694d32526b4d57566c4f5459324f544a6a5a6a4d775a54513d', 'label': 'Grandland X Hybrid', 'brand': 'C', 'abrp_name': None, 'battery_power': 13.2, 'fuel_capacity': 43, 'max_elec_consumption': 70, 'max_fuel_consumption': 30}"]
2021-12-07 10:34:33,607 :: ERROR :: remote_refresh_token isn't defined
2021-12-07 10:34:34,246 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'}
2021-12-07 10:34:34,247 :: ERROR :: get_otp_code:
Traceback (most recent call last):
  File "/psa_car_controller/libs/psa/RemoteClient.py", line 186, in get_otp_code
    otp_code = self.otp.get_otp_code()
  File "/psa_car_controller/otp/otp.py", line 277, in get_otp_code
    raise ConfigException("Can't get otp code")
otp.otp.ConfigException: Can't get otp code
2021-12-07 10:34:34,251 :: ERROR :: Please redo otp config
2021-12-07 10:34:34,985 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'}
2021-12-07 10:34:34,987 :: ERROR :: start_remote_control failed redo otp config
2021-12-07 10:34:34,988 :: INFO :: save config change
2021-12-07 10:34:35,005 :: WARNING :: Can't get language
2021-12-07 10:34:42,746 :: INFO :: update_data
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

**Describe the bug**

**To Reproduce**
1. what command did you use
2. when the bug append ?
3. Does it persist after restarting the program? 
4. Does it persist after recreate config by going to http://server_address:port/config? 

**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Brand and model of car
 - Application version (commit number, branch or tag)
 - Log from http://server_address:port/log and browser console log

**Additional context**

**Comment by dreimer1986** [comment]
You did ignore the report template completely. I recommend you edit your report and fill in the missing information first!

Ah and copying your whole log with your VIN is a bad idea.
