### ISSUE TITLE
Data update stopped working

### ISSUE THREAD

**Issue by AjubaGit** [flobz/psa_car_controller#296]
**Describe the bug**
v2.5.1 worked fine for 2 months but stopped updating data some days ago

**To Reproduce**
1. what command did you use
No command used. Fhem home automation was getting data via HTTPMOD as usual.
2. when the bug append ?
Dec 3, 2021
3. Does it persist after restarting the program? 
Before restarting login on frontend was refused with message "local variable 'customer_id' referenced before assignment".
Restarting and re-installation of v2.5.1 did not help.  Tried also v2.6.0 but is does not start at all (starts and stops immediately).
After re-installation of v2.5.1 Login on Web-Frontend refuses login with message "Invalid password or PKCS12 data" even that password is definitely correct and works in the myPeugeot App.

4. Does it persist after recreate config by going to http://server_address:port/config? 
After re-installation of v2.5.1 Login on Web-Frontend refuses login with message "Invalid password or PKCS12 data" even that password is definitely correct and works in the myPeugeot App.

**Config file**
Give the anonymize content of the config file
Sorry. I hove no idea where the config file is on a docker station and how to access.

**Environment (please complete the following information):**
 - OS: Docker in Container station on QNAP NAS
 - Brand and model of car: Peugeot e208
 - Application version (commit number, branch or tag): v2.5.1
 
- Log from http://server_address:port/log and browser console log
Exception on /get_vehicleinfo/***************************** [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 132, in get_vehicle_info
    response=json.dumps(CONFIG.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'Config' object has no attribute 'myp'
192.168.1.202 - - [08/Dec/2021 18:19:36] "GET /get_vehicleinfo/*****************************?from_cache=1 HTTP/1.0" 500 -
Exception on /get_vehicleinfo/***************************** [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 132, in get_vehicle_info
    response=json.dumps(CONFIG.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'Config' object has no attribute 'myp'
192.168.1.202 - - [08/Dec/2021 18:24:36] "GET /get_vehicleinfo/*****************************?from_cache=1 HTTP/1.0" 500 -
Exception on /get_vehicleinfo/***************************** [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 132, in get_vehicle_info
    response=json.dumps(CONFIG.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'Config' object has no attribute 'myp'
192.168.1.202 - - [08/Dec/2021 18:29:36] "GET /get_vehicleinfo/*****************************?from_cache=1 HTTP/1.0" 500 -
Exception on /get_vehicleinfo/***************************** [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 132, in get_vehicle_info
    response=json.dumps(CONFIG.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'Config' object has no attribute 'myp'
192.168.1.202 - - [08/Dec/2021 18:34:36] "GET /get_vehicleinfo/*****************************?from_cache=1 HTTP/1.0" 500 -
Exception on /get_vehicleinfo/***************************** [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/psa_car_controller/web/view/views.py", line 132, in get_vehicle_info
    response=json.dumps(CONFIG.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'Config' object has no attribute 'myp'
192.168.1.202 - - [08/Dec/2021 18:39:36] "GET /get_vehicleinfo/*****************************?from_cache=1 HTTP/1.0" 500 -
^CTraceback (most recent call last):
  File "/psa_car_controller/server.py", line 21, in <module>
    t1.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Containerised psa_car_controller loading...
/usr/local/lib/python3.7/dist-packages/dash_bootstrap_components/_table.py:5: UserWarning: 
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
2021-12-08 18:41:41,480 :: WARNING :: Can't get language
/psa_car_controller/web/view/views.py:8: UserWarning: 
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
/psa_car_controller/web/figures.py:4: UserWarning: 
The dash_table package is deprecated. Please replace
`import dash_table` with `from dash import dash_table`

Also, if you're using any of the table format helpers (e.g. Group), replace 
`from dash_table.Format import Group` with 
`from dash.dash_table.Format import Group`
  import dash_table
2021-12-08 18:41:42,758 :: INFO :: update_data
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://192.168.1.204:5000/ (Press CTRL+C to quit)

**Additional context**

My Network settings in the Docker station are:
Network mode: Bridge
Static IP adddress: 192.168.1.204

No other settings were set.

**Comment by calliou1234** [comment]
Hi,

I have the same Problem like AjubaGit discribed above.

My Docker-Installation is on a Synology NAS an it worked fine for months.

Since a few weeks it does not work anymore.

I pulled the latest Docker Version on the weekend, but it still not works.

**Comment by flobz** [comment]
I support only the last version, please upgrade.

**Comment by AjubaGit** [comment]
Dear flobz
Thank you for responding. As mentioned in original post, I already tried latest version which immediately stoppes again.
Now I tried again the latest version:
My docker setting on QNAP are the same like on old version which was running fine :
Network mode: Bridge
Static IP Address
I was not able to add any path (required at all ?)

Here is the docker console output:
```
Containerised psa_car_controller loading...
/usr/local/lib/python3.7/dist-packages/dash_bootstrap_components/_table.py:5: UserWarning: 
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
2021-12-16 21:15:53,408 :: WARNING :: Can't get language
/psa_car_controller/web/view/views.py:8: UserWarning: 
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
/psa_car_controller/web/figures.py:5: UserWarning: 
The dash_table package is deprecated. Please replace
`import dash_table` with `from dash import dash_table`

Also, if you're using any of the table format helpers (e.g. Group), replace 
`from dash_table.Format import Group` with 
`from dash.dash_table.Format import Group`
  import dash_table
2021-12-16 21:15:56,170 :: INFO :: update_data
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/psa_car_controller/web/app.py", line 45, in start_app
    run(config_flask(*args, **kwargs))
  File "/psa_car_controller/web/app.py", line 78, in config_flask
    importlib.import_module(view)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/psa_car_controller/web/view/views.py", line 387, in <module>
    update_trips()
  File "/psa_car_controller/web/view/views.py", line 249, in update_trips
    car = CONFIG.myp.vehicles_list[0]  # todo handle multiple car
AttributeError: 'Config' object has no attribute 'myp'
```

I kindly aks for your support to find the correct setting to make your great skript running again.
Thanks, Ajuba
