### ISSUE TITLE
KeyError: 'accessToken' 

### ISSUE THREAD

**Issue by Kayinwonderland** [flobz/psa_car_controller#307]
Hello,

 I have created a Developer account and done all the new App etc stuff. The issue is just that  whenever I enter my login data in the Home Assistant integration I get a error shown

Traceback (most recent call last): File "/psa_car_controller/libs/psa/setup/app_decoder.py", line 46, in firstLaunchConfig token = res.json()["accessToken"] KeyError: 'accessToken' HOST_BRANDID : https://id-dcr.peugeot.com/mobile-services sitecode: AP_DE_ESP{"returnCode":"AUTHENTICATION_FAILED"}

Log Information:

HOST_BRANDID : https://id-dcr.peugeot.com/mobile-services sitecode: AP_DE_ESP{"returnCode":"AUTHENTICATION_FAILED"}
2022-01-02 09:42:21,518 :: ERROR :: Traceback (most recent call last):
File "/psa_car_controller/libs/psa/setup/app_decoder.py", line 46, in firstLaunchConfig
token = res.json()["accessToken"]
KeyError: 'accessToken'

I btw wanted to mention in general as for someone who is new to this setting up stuff and also to Home Assistant it was hard to figureout what to do because there is barely a real documentation or a tutorial for setting up (meaning the whole setting the app up with exact steps) like many many others have done it. I had to search through 5 different pages to even get that far.

**Comment by flobz** [comment]
Close, already answered.

**Comment by Kayinwonderland** [comment]
Can you ease tell me where it was answered? I searched for it before opening and couldn't find it

**Comment by flobz** [comment]
https://github.com/flobz/psa_car_controller/issues/32
