### ISSUE TITLE
Error, and not showing position on map

### ISSUE THREAD

**Issue by jayarh** [flobz/psa_car_controller#309]
I cant use the map, and there is an error. I am sorry if this is a known bug, but I did have a map at some point.
i can precondition the car, and it works otherwise as expected in Home Assistant, but I get the following in the log (looks like a valid position to me) - thanks for any hint as to what can be wrong:

2022-01-07 14:07:47,492 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/XXXXXSERIALXXXXX b'{"date":"2022-01-07T13:06:36Z","etat_res_elec":0,"precond_state":{"available":1,"programs":{"program1":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program2":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0,"aff":1},"charging_state":{"program":{"hour":0,"minute":0},"available":1,"remaining_time":635,"rate":0,"cable_detected":1,"soc_batt":1,"autonomy_zev":0,"type":0,"aff":1,"hmi_state":0,"mode":0},"stolen_state":0,"vin":"XXXXXSERIALXXXXX","reason":6,"signal_quality":4,"sev_stop_date":"2022-01-07T13:06:35Z","location":{"dop":{"h":0.6,"p":1,"v":0.8,"valid_h":true,"valid_p":true,"valid_v":true},"dr":{"heading":147.479324,"latitude":55.555555,"longitude":5.555555,"speed":0,"valid_hdg":true,"valid_lat":true,"valid_lng":true,"valid_spd":true},"gnss":{"altitude":95.5,"error_altitude":2.5,"error_h_position":3.53,"error_v_speed":0.85,"fix_status":3,"heading":145.072906,"latitude":55.555555,"longitude":5.555555,"speed":1.080333,"timestamp":"2022-01-07T13:06:45Z","valid_alt":true,"valid_err_alt":true,"valid_err_hps":true,"valid_err_spd":true,"valid_hdg":true,"valid_lat":true,"valid_lng":true,"valid_spd":true},"satellites":{"tracked":28,"used":19,"valid_trk":true,"valid_usd":true,"valid_vis":true,"visible":30}},"fds":["NDR01","NBM01","NCG01","NAO02","NAS01"],"sev_state":0,"timestamp_gnss":1641560805,"obj_counter":12,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2022-01-07 14:07:47,494 :: WARNING :: charge begin but API isn't updated
2022-01-07 14:08:39,513 :: INFO :: <Request 'http://192.168.2.20:5000/charge_control?vin=XXXXXSERIALXXXXX&%3Falways_check=true' [GET]>
2022-01-07 14:08:47,555 :: INFO :: ask wakeup to XXXXXSERIALXXXXX
2022-01-07 14:08:47,556 :: INFO :: topic: psa/RemoteServices/from/cid/AP-ACNTXXXXMINEXXX/VehCharge/state: {'action': 'state'}
2022-01-07 14:08:47,560 :: WARNING :: Disconnected with result code 1
2022-01-07 14:08:48,238 :: INFO :: save config change
2022-01-07 14:08:49,534 :: INFO :: Connected with result code {'session present': 0}
2022-01-07 14:08:49,536 :: INFO :: subscribe to psa/RemoteServices/to/cid/AP-ACNTXXXXMINEXXX/#
2022-01-07 14:08:49,537 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/XXXXXSERIALXXXXX
2022-01-07 14:08:59,098 :: INFO :: level_fuel fixed with last real value 64.000000 for XXXXXSERIALXXXXX
2022-01-07 14:08:59,109 :: INFO :: new position recorded for XXXXXSERIALXXXXX
2022-01-07 14:08:59,110 :: INFO :: update_data
2022-01-07 14:08:59,130 :: ERROR :: refresh_vehicle_info:
Traceback (most recent call last):
File "/psa_car_controller/my_psacc.py", line 119, in __refresh_vehicle_info
self.get_vehicle_info(car.vin)
File "/psa_car_controller/my_psacc.py", line 106, in get_vehicle_info
self.record_info(car)
File "/psa_car_controller/my_psacc.py", line 191, in record_info
Database.record_position(self.weather_api, car.vin, mileage, latitude, longitude, altitude, date, level,
File "/psa_car_controller/web/db.py", line 264, in record_position
conn.close()
File "/psa_car_controller/web/db.py", line 45, in close
self.execute_callbacks()
File "/psa_car_controller/web/db.py", line 41, in execute_callbacks
callback()
File "/psa_car_controller/web/view/views.py", line 256, in update_trips
trips_by_vin = Trips.get_trips(Cars([car]))
File "/psa_car_controller/trip.py", line 177, in get_trips
distance = next_el["mileage"] - end["mileage"] # km
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
2022-01-07 14:09:39,517 :: INFO :: <Request 'http://192.168.2.20:5000/charge_control?vin=XXXXXSERIALXXXXX&%3Falways_check=true' [GET]>
2022-01-07 14:10:39,518 :: INFO :: <Request 'http://192.168.2.20:5000/charge_control?vin=XXXXXSERIALXXXXX&%3Falways_check=true' [GET]>

**Comment by flobz** [comment]
duplicate #306
