### ISSUE TITLE
Restarting the app, new login with errors

### ISSUE THREAD

**Issue by marcorizzi** [flobz/psa_car_controller#330]
I used this solution last year and then I stopped Raspberry PI for 3 months. Restarting Rasberry PI now I get the login page and if I try to login i receive this message: local variable 'customer_id' referenced before assignment

Error log
2022-02-25 19:27:28,229 :: ERROR :: Traceback (most recent call last):
File "/psa_car_controller/app_decoder.py", line 107, in firstLaunchConfig
res_dict = res2.json()["success"]
KeyError: 'success'
{"code":"495", "message": "Invalid or expired client certificate"}
2022-02-25 19:35:25,366 :: ERROR :: Can't refresh token ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-02-25 19:35:25,376 :: INFO :: save config change
2022-02-25 19:35:25,408 :: WARNING :: Can't get language
2022-02-25 19:35:28,579 :: INFO :: update_data
2022-02-25 20:04:29,273 :: ERROR :: Traceback (most recent call last):
File "/psa_car_controller/app_decoder.py", line 82, in firstLaunchConfig
token = res.json()["accessToken"]
KeyError: 'accessToken'

HOST_BRANDID : https://id-dcr.citroen.com/mobile-services sitecode: AC_IT_ESP{"returnCode":"ERROR"}
2022-02-25 20:05:07,783 :: ERROR :: Traceback (most recent call last):
File "/psa_car_controller/app_decoder.py", line 107, in firstLaunchConfig
res_dict = res2.json()["success"]
KeyError: 'success'
{"code":"495", "message": "Invalid or expired client certificate"}

**Comment by flobz** [comment]
https://github.com/flobz/psa_car_controller/search?q=Invalid+or+expired+client+certificate&type=issues
