### ISSUE TITLE
Initial config doesn't work

### ISSUE THREAD

**Issue by kolin82** [flobz/psa_car_controller#431]
Hello, I try first time with PSA_controller as well do it on my Win10 and docert for desktop. Seems first run doesn't work and can't find it in the instruction what to do and stuck

i got an error in the browser http://127.0.0.1:5000/config_login

Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 48, in firstLaunchConfig token = res.json()["accessToken"] KeyError: 'accessToken' HOST_BRANDID : https://id-dcr.citroen.com/mobile-services sitecode: AC_PL_ESP{"returnCode":"AUTHENTICATION_FAILED"}

where and how I should establish my phone number ?

error from the log

HOST_BRANDID : https://id-dcr.citroen.com/mobile-services sitecode: AC_GB_ESP{"returnCode":"AUTHENTICATION_FAILED"}
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 48, in firstLaunchConfig
token = res.json()["accessToken"]
KeyError: 'accessToken'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_views.py", line 133, in connectPSA
res = firstLaunchConfig(app_name, email, password, countrycode)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 57, in firstLaunchConfig
raise Exception(msg) from ex
Exception: Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 48, in firstLaunchConfig
token = res.json()["accessToken"]
KeyError: 'accessToken'

HOST_BRANDID : https://id-dcr.citroen.com/mobile-services sitecode: AC_GB_ESP{"returnCode":"AUTHENTICATION_FAILED"}

thanks for help in advance
Miko

**Comment by gerar19** [comment]
It's same:
![image](https://user-images.githubusercontent.com/11975151/202143232-128a65d6-1a34-4bd8-8f2c-8ed078920352.png)

**Comment by gerar19** [comment]
In userconfig, i have this errors JS:

Failed to load resource: the server responded with a status of 404 (Not Found)
/_favicon.ico?v=2.7.0:1          Failed to load resource: the server responded with a status of 404 (Not Found)
/api/hassio_ingress/WQBuqNIMHfLse0fqm1zm5PnIdFYdT0FalTJ4Zo5LRys/_dash-update-component:1          Failed to load resource: net::ERR_EMPTY_RESPONSE
dash_renderer.min.js:2 Error: Callback failed: the server did not respond.
    at b (dash_renderer.min.js:2:125184)
Ho @ dash_renderer.min.js:2
3d8b4dca.js:15 Uncaught (in promise) Object
43d8b4dca.js:15 Uncaught (in promise) 3
/_favicon.ico?v=2.7.0:1          Failed to load resource: the server responded with a status of 404 (Not Found)
/_favicon.ico?v=2.7.0:1          Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by flobz** [comment]
look at https://github.com/flobz/psa_car_controller/blob/master/FAQ.md#8-authentication_failed
