### ISSUE TITLE
OTP not received for Citroen account

### ISSUE THREAD

**Issue by maxdd** [flobz/psa_car_controller#445]
I've reached the point where the dashboard asks me to go to the "OTP Config" page but when i press "Send SMS" nothing is received.
From MyCitroen android apk i can login and i can see my phone number being there.
The country code i'm using is IT

Also what is the "PIN Code" where would i find it?

Here's a log

```
2022-12-12 11:29:31,002 :: INFO :: Namespace mapping (58, 422) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2022-12-12 11:29:31,003 :: INFO :: Namespace mapping (58, 422) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2022-12-12 11:29:31,005 :: INFO :: Namespace mapping (58, 422) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2022-12-12 11:29:31,006 :: INFO :: Namespace mapping (58, 422) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2022-12-12 11:29:31,009 :: INFO :: Namespace mapping (58, 422) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2022-12-12 11:29:31,009 :: INFO :: Namespace mapping (58, 422) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2022-12-12 11:29:31,013 :: INFO :: Namespace mapping (58, 422) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2022-12-12 11:29:31,013 :: INFO :: Namespace mapping (58, 422) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2022-12-12 11:29:31,014 :: INFO :: Namespace mapping (58, 422) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2022-12-12 11:29:31,015 :: INFO :: Namespace mapping (58, 422) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2022-12-12 11:29:31,038 :: WARNING :: Requested API level 31 is larger than maximum we have, returning API level 28 instead.
2022-12-12 11:29:37,149 :: INFO :: save config change
2022-12-12 11:29:37,587 :: ERROR :: get_vehicles:
Traceback (most recent call last):
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psacc\application\psa_client.py", line 137, in get_vehicles
    res = self.api().get_vehicles_by_device()
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psa\connected_car_api\api\vehicles_api.py", line 1331, in get_vehicles_by_device
    (data) = self.get_vehicles_by_device_with_http_info(**kwargs)  # noqa: E501
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psa\connected_car_api\api\vehicles_api.py", line 1400, in get_vehicles_by_device_with_http_info
    return self.api_client.call_api(
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psa\oauth.py", line 96, in call_api
    raise e
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psa\oauth.py", line 78, in call_api
    return self._ApiClient__call_api(resource_path, method,
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psa\connected_car_api\api_client.py", line 157, in __call_api
    response_data = self.request(
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psa\connected_car_api\api_client.py", line 347, in request
    return self.rest_client.GET(url,
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psa\connected_car_api\rest.py", line 234, in GET
    return self.request("GET", url,
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psa\connected_car_api\rest.py", line 228, in request
    raise ApiException(http_resp=r)
psa_car_controller.psa.connected_car_api.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'X-Backside-Transport': 'FAIL FAIL', 'Connection': 'close', 'Cache-Control': 'no-store, no-cache, must-revalidate, private', 'Content-Type': 'application/hal+json', 'Date': 'Mon, 12 Dec 2022 10:28:45 GMT', 'Expires': '0', 'X-Global-Transaction-ID': '945fb68f6397029142c7482d', 'Access-Control-Expose-Headers': 'APIm-Debug-Trans-Id, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-Global-Transaction-ID', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET', 'Set-Cookie': 'rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Sun, 11-Dec-2022 10:28:45 GMT, JSESSIONID=98BGtZlCISLiGAbhwZLkF-tecMLLO-x--_eA4vCv; path=/, PSACountry=IT; Domain=.groupe-psa.com; Path=/'})
HTTP response body: {"uuid":"0ad8dbeb-b6a0-4d35-9956-42f62395e62d","code":40410,"message":"No vehicule found"}

2022-12-12 11:29:37,589 :: INFO ::
Your vehicles: []
2022-12-12 11:29:37,592 :: INFO :: save config change
2022-12-12 11:29:38,277 :: ERROR :: get_vehicles:
Traceback (most recent call last):
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psacc\application\psa_client.py", line 137, in get_vehicles
    res = self.api().get_vehicles_by_device()
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psa\connected_car_api\api\vehicles_api.py", line 1331, in get_vehicles_by_device
    (data) = self.get_vehicles_by_device_with_http_info(**kwargs)  # noqa: E501
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psa\connected_car_api\api\vehicles_api.py", line 1400, in get_vehicles_by_device_with_http_info
    return self.api_client.call_api(
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psa\oauth.py", line 96, in call_api
    raise e
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psa\oauth.py", line 78, in call_api
    return self._ApiClient__call_api(resource_path, method,
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psa\connected_car_api\api_client.py", line 157, in __call_api
    response_data = self.request(
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psa\connected_car_api\api_client.py", line 347, in request
    return self.rest_client.GET(url,
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psa\connected_car_api\rest.py", line 234, in GET
    return self.request("GET", url,
  File "\AppData\Roaming\Python\Python39\site-packages\psa_car_controller\psa\connected_car_api\rest.py", line 228, in request
    raise ApiException(http_resp=r)
psa_car_controller.psa.connected_car_api.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'X-Backside-Transport': 'FAIL FAIL', 'Connection': 'close', 'Cache-Control': 'no-store, no-cache, must-revalidate, private', 'Content-Type': 'application/hal+json', 'Date': 'Mon, 12 Dec 2022 10:28:27 GMT', 'Expires': '0', 'X-Global-Transaction-ID': '08f333a56397029273af910d', 'Access-Control-Expose-Headers': 'APIm-Debug-Trans-Id, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-Global-Transaction-ID', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET', 'Set-Cookie': 'rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Sun, 11-Dec-2022 10:28:27 GMT, JSESSIONID=QFFh6Ee0IQfmM4-blHseSCv3WEaOJ9bjNNd8dwXp; path=/, PSACountry=IT; Domain=.groupe-psa.com; Path=/'})
HTTP response body: {"uuid":"5b129367-7b84-40dc-8103-16b76ce1a9b6","code":40410,"message":"No vehicule found"}

2022-12-12 11:29:38,279 :: INFO :: []
2022-12-12 11:29:38,285 :: INFO :: save config change
2022-12-12 11:29:38,286 :: INFO :: 127.0.0.1 - - [12/Dec/2022 11:29:38] "POST /_dash-update-component HTTP/1.1" 200 -
2022-12-12 11:29:44,480 :: INFO :: 127.0.0.1 - - [12/Dec/2022 11:29:44] "GET /config_otp HTTP/1.1" 200 -
2022-12-12 11:29:44,520 :: INFO :: 127.0.0.1 - - [12/Dec/2022 11:29:44] "←[36mGET /assets/clientside.js?m=1670837281.5683684 HTTP/1.1←[0m" 304 -
2022-12-12 11:29:44,813 :: INFO :: 127.0.0.1 - - [12/Dec/2022 11:29:44] "GET /_dash-layout HTTP/1.1" 200 -
2022-12-12 11:29:44,814 :: INFO :: 127.0.0.1 - - [12/Dec/2022 11:29:44] "GET /_dash-dependencies HTTP/1.1" 200 -
2022-12-12 11:29:44,838 :: INFO :: 127.0.0.1 - - [12/Dec/2022 11:29:44] "POST /_dash-update-component HTTP/1.1" 200 -
2022-12-12 11:29:44,870 :: INFO :: 127.0.0.1 - - [12/Dec/2022 11:29:44] "←[36mGET /assets/images/settings.svg HTTP/1.1←[0m" 304 -
2022-12-12 11:29:44,880 :: INFO :: 127.0.0.1 - - [12/Dec/2022 11:29:44] "POST /_dash-update-component HTTP/1.1" 200 -
2022-12-12 11:29:44,882 :: INFO :: 127.0.0.1 - - [12/Dec/2022 11:29:44] "←[35m←[1mPOST /_dash-update-component HTTP/1.1←[0m" 204 -
2022-12-12 11:29:44,884 :: INFO :: 127.0.0.1 - - [12/Dec/2022 11:29:44] "←[35m←[1mPOST /_dash-update-component HTTP/1.1←[0m" 204 -
2022-12-12 11:29:46,874 :: INFO :: 127.0.0.1 - - [12/Dec/2022 11:29:46] "POST /_dash-update-component HTTP/1.1" 200 -
2022-12-12 11:30:04,035 :: INFO :: 127.0.0.1 - - [12/Dec/2022 11:30:04] "POST /_dash-update-component HTTP/1.1" 200 -
```

**Comment by flobz** [comment]
please look at  : https://github.com/flobz/psa_car_controller/blob/master/FAQ.md#5-i-dont-receive-sms

**Comment by maxdd** [comment]
Hello @flobz, i still get this

"No data to show, there is probably no trips recorded yet"

here is my log

```
psa-car-controller --web-conf --remote-disable
2023-01-02 15:27:13,994 :: ERROR :: get_vehicles:
Traceback (most recent call last):
  File "c:\users\itsmaxdd\appdata\local\programs\python\python38\lib\site-packages\psa_car_controller\psacc\application\psa_client.py", line 137, in get_vehicles
    res = self.api().get_vehicles_by_device()
  File "c:\users\itsmaxdd\appdata\local\programs\python\python38\lib\site-packages\psa_car_controller\psa\connected_car_api\api\vehicles_api.py", line 1331, in get_vehicles_by_device
    (data) = self.get_vehicles_by_device_with_http_info(**kwargs)  # noqa: E501
  File "c:\users\itsmaxdd\appdata\local\programs\python\python38\lib\site-packages\psa_car_controller\psa\connected_car_api\api\vehicles_api.py", line 1400, in get_vehicles_by_device_with_http_info
    return self.api_client.call_api(
  File "c:\users\itsmaxdd\appdata\local\programs\python\python38\lib\site-packages\psa_car_controller\psa\oauth.py", line 96, in call_api
    raise e
  File "c:\users\itsmaxdd\appdata\local\programs\python\python38\lib\site-packages\psa_car_controller\psa\oauth.py", line 78, in call_api
    return self._ApiClient__call_api(resource_path, method,
  File "c:\users\itsmaxdd\appdata\local\programs\python\python38\lib\site-packages\psa_car_controller\psa\connected_car_api\api_client.py", line 157, in __call_api
    response_data = self.request(
  File "c:\users\itsmaxdd\appdata\local\programs\python\python38\lib\site-packages\psa_car_controller\psa\connected_car_api\api_client.py", line 347, in request
    return self.rest_client.GET(url,
  File "c:\users\itsmaxdd\appdata\local\programs\python\python38\lib\site-packages\psa_car_controller\psa\connected_car_api\rest.py", line 234, in GET
    return self.request("GET", url,
  File "c:\users\itsmaxdd\appdata\local\programs\python\python38\lib\site-packages\psa_car_controller\psa\connected_car_api\rest.py", line 228, in request
    raise ApiException(http_resp=r)
psa_car_controller.psa.connected_car_api.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'X-Backside-Transport': 'FAIL FAIL', 'Connection': 'close', 'Cache-Control': 'no-store, no-cache, must-revalidate, private', 'Content-Type': 'application/hal+json', 'Date': 'Mon, 02 Jan 2023 14:26:00 GMT', 'Expires': '0', 'X-Global-Transaction-ID': '08f333a563b2e9c2a2771ecf', 'Access-Control-Expose-Headers': 'APIm-Debug-Trans-Id, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-Global-Transaction-ID', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET', 'Set-Cookie': 'rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Sun, 01-Jan-2023 14:26:00 GMT, JSESSIONID=LC23LOJHLXOlfRkr4XB2tm41mfsOE8FvxxaPTdOS; path=/, PSACountry=IT; Domain=.groupe-psa.com; Path=/'})
HTTP response body: {"uuid":"d7025850-c66d-4610-950f-18481e3ed22c","code":40410,"message":"No vehicule found"}

2023-01-02 15:27:19,960 :: INFO :: []
2023-01-02 15:27:19,962 :: INFO :: mqtt disabled
2023-01-02 15:27:19,966 :: INFO :: save config change
2023-01-02 15:27:20,857 :: INFO :: update_data
2023-01-02 15:27:20,867 :: INFO :: ←[31m←[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.←[0m
 * Running on http://127.0.0.1:5000
2023-01-02 15:27:20,867 :: INFO :: ←[33mPress CTRL+C to quit←[0m
```
