### ISSUE TITLE
Adding new vehicle

### ISSUE THREAD

**Issue by zamzon** [flobz/psa_car_controller#454]
Hi 
I added a e-Jumpy, and I can see you did add the changes to the repo.
But it still dosen't work, I use it in a docker on home assistant, do you need to upload a new docker image also?

`ontainerised psa_car_controller loading...
2023-01-02 23:59:15,101 :: WARNING :: Can't get car model, please report an issue on github with your car model and first ten letter of your VIN : VF7V1ZKXZM
2023-01-02 23:59:15,979 :: WARNING :: Can't get car model, please report an issue on github with your car model and first ten letter of your VIN : VF7V1ZKXZM
2023-01-02 23:59:15,981 :: INFO :: ["{'vin': 'VF7V1ZKXZMxxxxxxx', 'vehicle_id': '1566b5933566a46615331686154566f774e444d794e44556a497a4d354d6d4d32595449784e446c6b4f474e684d6d5178597a63784d6a59324f5755795a57526a4d5749344e7a4d785a44646d4d5759304e6a6b354d44646d597a566b5a54646a596a526c4e4749784e4441794e47513d', 'label': 'unknown', 'brand': 'Citroën', 'abrp_name': None, 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 30}"]
2023-01-02 23:59:16,299 :: ERROR :: remote_refresh_token isn't defined
2023-01-02 23:59:16,836 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'}
2023-01-02 23:59:16,837 :: ERROR :: get_otp_code:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 193, in get_otp_code
    otp_code = self.otp.get_otp_code()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/otp/otp.py", line 276, in get_otp_code
    raise ConfigException("Can't get otp code")
psa_car_controller.psa.otp.otp.ConfigException: Can't get otp code
2023-01-02 23:59:16,840 :: ERROR :: Please redo otp config
2023-01-02 23:59:17,336 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'}
2023-01-02 23:59:17,337 :: ERROR :: start_remote_control failed redo otp config
2023-01-02 23:59:17,338 :: INFO :: save config change
2023-01-02 23:59:17,341 :: WARNING :: Can't get language
2023-01-02 23:59:18,066 :: INFO :: update_data
2023-01-02 23:59:19,104 :: INFO ::  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)`

**Comment by flobz** [comment]
yes wait for next release please
