### ISSUE TITLE
Charge list don't refresh

### ISSUE THREAD

**Issue by mememel** [flobz/psa_car_controller#475]
Sorry for my first post who doesn't follow the bug template.
I do it :
-->
**Describe the bug**
Everything work better since few weeks : now i've altitude and temperatures ! 
But the list of previous charge don't refresh since december.
Thanks,

**To Reproduce**
1. Plug in is working on a Docker on a Synology NAS
2. Since 10/12/2022
3. It persist after restart the plug in
4. When I use http://server_address:port/config? it respond me : `"local variable 'customer_id' referenced before assignment"`

**Config file**
`{
    "abrp": {
        "abrp_enable_vin": [
            "VR3********"
        ],
        "token": "b5448********"
    },
    "client_id": "1eebc********",
    "client_secret": "T5tP7iS********",
    "co2_signal_api": null,
    "country_code": "FR",
    "customer_id": "AP-ACN********",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2CPeugeot",
    "refresh_token": "97b1d155********",
    "remote_refresh_token": "40df405b-dfb7********",
    "weather_api": "698babf3b********"
}`

**Environment (please complete the following information):**
 - OS: Docker on NAS Synology
 - Peugeot E208 2021
 - Application version (commit number, branch or tag) Where I can find ?
 - Log from http://server_address:port/log : 
`2023-01-25 12:53:19,987 :: ERROR :: refresh_vehicle_info: 
Traceback (most recent call last):
  File "/psa_car_controller/my_psacc.py", line 174, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/psa_car_controller/my_psacc.py", line 161, in get_vehicle_info
    self.record_info(car)
  File "/psa_car_controller/my_psacc.py", line 499, in record_info
    charging_mode, charging_rate, autonomy)
  File "/psa_car_controller/libs/charging.py", line 68, in record_charging
    co2_per_kw = Ecomix.get_co2_per_kw(start_at, charge_date, latitude, longitude, country_code)
  File "/psa_car_controller/ecomix.py", line 120, in get_co2_per_kw
    co2_per_kw = Ecomix.get_data_france(start, end)
  File "/psa_car_controller/ecomix.py", line 46, in get_data_france
    valeur = next(valeurs)
StopIteration
2023-01-25 12:53:21,072 :: ERROR :: refresh_vehicle_info: 
Traceback (most recent call last):
  File "/psa_car_controller/my_psacc.py", line 174, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/psa_car_controller/my_psacc.py", line 161, in get_vehicle_info
    self.record_info(car)
  File "/psa_car_controller/my_psacc.py", line 499, in record_info
    charging_mode, charging_rate, autonomy)
  File "/psa_car_controller/libs/charging.py", line 68, in record_charging
    co2_per_kw = Ecomix.get_co2_per_kw(start_at, charge_date, latitude, longitude, country_code)
  File "/psa_car_controller/ecomix.py", line 120, in get_co2_per_kw
    co2_per_kw = Ecomix.get_data_france(start, end)
  File "/psa_car_controller/ecomix.py", line 46, in get_data_france
    valeur = next(valeurs)
StopIteration
2023-01-25 12:53:22,095 :: ERROR :: refresh_vehicle_info: 
Traceback (most recent call last):
  File "/psa_car_controller/my_psacc.py", line 174, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/psa_car_controller/my_psacc.py", line 161, in get_vehicle_info
    self.record_info(car)
  File "/psa_car_controller/my_psacc.py", line 499, in record_info
    charging_mode, charging_rate, autonomy)
  File "/psa_car_controller/libs/charging.py", line 68, in record_charging
    co2_per_kw = Ecomix.get_co2_per_kw(start_at, charge_date, latitude, longitude, country_code)
  File "/psa_car_controller/ecomix.py", line 120, in get_co2_per_kw
    co2_per_kw = Ecomix.get_data_france(start, end)
  File "/psa_car_controller/ecomix.py", line 46, in get_data_france
    valeur = next(valeurs)
StopIteration
2023-01-25 12:53:23,233 :: ERROR :: refresh_vehicle_info: 
Traceback (most recent call last):
  File "/psa_car_controller/my_psacc.py", line 174, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/psa_car_controller/my_psacc.py", line 161, in get_vehicle_info
    self.record_info(car)
  File "/psa_car_controller/my_psacc.py", line 499, in record_info
    charging_mode, charging_rate, autonomy)
  File "/psa_car_controller/libs/charging.py", line 68, in record_charging
    co2_per_kw = Ecomix.get_co2_per_kw(start_at, charge_date, latitude, longitude, country_code)
  File "/psa_car_controller/ecomix.py", line 120, in get_co2_per_kw
    co2_per_kw = Ecomix.get_data_france(start, end)
  File "/psa_car_controller/ecomix.py", line 46, in get_data_france
    valeur = next(valeurs)
StopIteration
2023-01-25 12:53:24,371 :: ERROR :: refresh_vehicle_info: 
Traceback (most recent call last):
  File "/psa_car_controller/my_psacc.py", line 174, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/psa_car_controller/my_psacc.py", line 161, in get_vehicle_info
    self.record_info(car)
  File "/psa_car_controller/my_psacc.py", line 499, in record_info
    charging_mode, charging_rate, autonomy)
  File "/psa_car_controller/libs/charging.py", line 68, in record_charging
    co2_per_kw = Ecomix.get_co2_per_kw(start_at, charge_date, latitude, longitude, country_code)
  File "/psa_car_controller/ecomix.py", line 120, in get_co2_per_kw
    co2_per_kw = Ecomix.get_data_france(start, end)
  File "/psa_car_controller/ecomix.py", line 46, in get_data_france
    valeur = next(valeurs)
StopIteration`
.

Thank you

**Comment by flobz** [comment]
should be fixed by last version
