### ISSUE TITLE
AttributeError: 'PSACarController' object has no attribute 'chc' 

### ISSUE THREAD

**Issue by shaman171** [flobz/psa_car_controller#505]
Hello all, 

I have an issue from FAQ:
**7. AttributeError: 'PSACarController' object has no attribute 'chc'**

But I am not able to solve it. I do not know how as the WEB interface on port 5000 does not start so I cannot make again this proces of otp and user config. 

Can you help me somehow how to start the web interface? When I try to start the plugin it does not start and write above mentioned error. 

Error come up after HA crashed and I restored backup from 24 hrs ago. 
I try many times to reinstall the addon restart the HA etcetera, but no results. 

Before it was all nicely working for approx 3 months. 

Full error log: 

> AttributeError: 'PSACarController' object has no attribute 'chc'
> 2023-04-04 20:52:29,890 :: ERROR :: Exception on /charge_control [GET]
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 215, in get_charge_control
>     charge_control = APP.chc.get(vin)

Thank you a lot for any help!

**Comment by ennoToUpper** [comment]
I have the exact same issue.
Installed yesterday and I wanted to set the threshold.
Response of the server is 500 and this is the log:

```
2023-04-05 08:00:47,010 :: INFO :: <Request 'http://localhost:5000/charge_control?vin=XYZ&percentage=80' [GET]>
2023-04-05 08:00:47,011 :: ERROR :: Exception on /charge_control [GET]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
```
Same message when checking the charge control

```
2023-04-05 08:07:50,249 :: INFO :: <Request 'http://127.0.0.1:5000/charge_control?vin=ZYX' [GET]>
2023-04-05 08:07:50,250 :: ERROR :: Exception on /charge_control [GET]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 215, in get_charge_control
charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'
```

I can access the server but it also doesn't show any data even though there has been data as HA did log states and such.
The error for charge controll shows up every minute, probably because HA checks for it once per minute.

**Comment by shaman171** [comment]
Hello, out of nothing after like two days it started working again -> I could open web interface -> make new user and OTP config and it work again :) 

Just if anybody would have same issues as well, maybe to take some time is the solution :) at least by me it was.
