### ISSUE TITLE
not working after update to 3.0.9

### ISSUE THREAD

**Issue by wifi75** [flobz/psa_car_controller#520]
hello after update not working see log:

![image](https://user-images.githubusercontent.com/31816231/231750580-03fafe09-804b-4960-8f0b-bf4880f0e540.png)

```
2023-04-13 13:48:24,194 :: INFO :: <Request 'http://192.168.1.52:5000/charge_control?vin=VR7BCZKXCNE062918' [GET]>
2023-04-13 13:48:24,195 :: INFO :: 192.168.1.52 - - [13/Apr/2023 13:48:24] "[37mGET /charge_control?vin=VR7BCZKXCNE062918 HTTP/1.1[0m" 200 -
2023-04-13 13:49:24,193 :: INFO :: 192.168.1.52 - - [13/Apr/2023 13:49:24] "[37mGET /get_vehicleinfo/VR7BCZKXCNE062918?from_cache=1 HTTP/1.1[0m" 200 -
2023-04-13 13:49:24,194 :: INFO :: <Request 'http://192.168.1.52:5000/charge_control?vin=VR7BCZKXCNE062918' [GET]>
2023-04-13 13:49:24,195 :: INFO :: 192.168.1.52 - - [13/Apr/2023 13:49:24] "[37mGET /charge_control?vin=VR7BCZKXCNE062918 HTTP/1.1[0m" 200 -
2023-04-13 13:49:53,715 :: INFO :: 172.30.32.1 - - [13/Apr/2023 13:49:53] "[37mGET / HTTP/1.1[0m" 200 -
2023-04-13 13:49:53,907 :: INFO :: 172.30.32.1 - - [13/Apr/2023 13:49:53] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2023-04-13 13:49:53,908 :: INFO :: 172.30.32.1 - - [13/Apr/2023 13:49:53] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2023-04-13 13:49:53,976 :: INFO :: 172.30.32.1 - - [13/Apr/2023 13:49:53] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2023-04-13 13:49:54,088 :: INFO :: 172.30.32.1 - - [13/Apr/2023 13:49:54] "[37mGET /control?header=false HTTP/1.1[0m" 200 -
2023-04-13 13:49:54,205 :: INFO :: 172.30.32.1 - - [13/Apr/2023 13:49:54] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2023-04-13 13:49:54,206 :: INFO :: 172.30.32.1 - - [13/Apr/2023 13:49:54] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2023-04-13 13:49:54,259 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/control.py", line 50, in get_control_tabs
buttons_row.extend([Button(REFRESH_SWITCH, car.vin,
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/tools/Button.py", line 21, in __init__
callback_id = create_callback_id(self._output)
TypeError: create_callback_id() missing 1 required positional argument: 'inputs'
2023-04-13 13:49:54,259 :: ERROR :: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/dash/dash.py", line 1283, in dispatch
ctx.run(
File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 450, in add_context
output_value = func(*func_args, **func_kwargs) # %% callback invoked %%
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 72, in display_page
page = get_control_tabs(APP)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/control.py", line 61, in get_control_tabs
buttons_row.append(Switch(ABRP_SWITCH, car.vin, "Send data to ABRP", myp.abrp.enable_abrp,
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/tools/Switch.py", line 14, in __init__
super().__init__(role, element_id, label, fct, prevent_initial_call)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/tools/Button.py", line 21, in __init__
callback_id = create_callback_id(self._output)
TypeError: create_callback_id() missing 1 required positional argument: 'inputs'
2023-04-13 13:49:54,259 :: ERROR :: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/dash/dash.py", line 1283, in dispatch
ctx.run(
File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 450, in add_context
output_value = func(*func_args, **func_kwargs) # %% callback invoked %%
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 72, in display_page
page = get_control_tabs(APP)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/control.py", line 61, in get_control_tabs
buttons_row.append(Switch(ABRP_SWITCH, car.vin, "Send data to ABRP", myp.abrp.enable_abrp,
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/tools/Switch.py", line 14, in __init__
super().__init__(role, element_id, label, fct, prevent_initial_call)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/tools/Button.py", line 21, in __init__
callback_id = create_callback_id(self._output)
TypeError: create_callback_id() missing 1 required positional argument: 'inputs'
2023-04-13 13:49:54,260 :: INFO :: 172.30.32.1 - - [13/Apr/2023 13:49:54] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
```

**Comment by bbr111** [comment]
same here

**Comment by aleblack** [comment]
+1

**Comment by PMax87** [comment]
Same here. 

`2023-04-13 12:41:04,176 :: ERROR :: get_control_tabs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/control.py", line 50, in get_control_tabs
    buttons_row.extend([Button(REFRESH_SWITCH, car.vin,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/tools/Button.py", line 21, in __init__
    callback_id = create_callback_id(self._output)
TypeError: create_callback_id() missing 1 required positional argument: 'inputs'
2023-04-13 12:41:04,189 :: ERROR :: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/dash/dash.py", line 1283, in dispatch
    ctx.run(
  File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 450, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 72, in display_page
    page = get_control_tabs(APP)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/control.py", line 61, in get_control_tabs
    buttons_row.append(Switch(ABRP_SWITCH, car.vin, "Send data to ABRP", myp.abrp.enable_abrp,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/tools/Switch.py", line 14, in __init__
    super().__init__(role, element_id, label, fct, prevent_initial_call)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/tools/Button.py", line 21, in __init__
    callback_id = create_callback_id(self._output)
TypeError: create_callback_id() missing 1 required positional argument: 'inputs'
2023-04-13 12:41:04,189 :: ERROR :: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/dash/dash.py", line 1283, in dispatch
    ctx.run(
  File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 450, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 72, in display_page
    page = get_control_tabs(APP)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/control.py", line 61, in get_control_tabs
    buttons_row.append(Switch(ABRP_SWITCH, car.vin, "Send data to ABRP", myp.abrp.enable_abrp,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/tools/Switch.py", line 14, in __init__
    super().__init__(role, element_id, label, fct, prevent_initial_call)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/tools/Button.py", line 21, in __init__
    callback_id = create_callback_id(self._output)
TypeError: create_callback_id() missing 1 required positional argument: 'inputs'
2023-04-13 12:41:04,193 :: INFO :: 192.168.32.1 - - [13/Apr/2023 12:41:04] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -`

**Comment by UU0113** [comment]
+1

**Comment by mdkeil** [comment]
@flobz the fix didnt work for me with 3.0.11 using the docker-version.

```
ERROR :: get_control_tabs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/control.py", line 50, in get_control_tabs
    buttons_row.extend([Button(REFRESH_SWITCH, car.vin,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/tools/Button.py", line 21, in __init__
    callback_id = create_callback_id(self._output)
TypeError: create_callback_id() missing 1 required positional argument: 'inputs'
2023-04-14 06:19:30,999 :: ERROR :: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/dash/dash.py", line 1283, in dispatch
    ctx.run(
  File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 450, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 72, in display_page
    page = get_control_tabs(APP)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/control.py", line 61, in get_control_tabs
    buttons_row.append(Switch(ABRP_SWITCH, car.vin, "Send data to ABRP", myp.abrp.enable_abrp,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/tools/Switch.py", line 14, in __init__
    super().__init__(role, element_id, label, fct, prevent_initial_call)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/tools/Button.py", line 21, in __init__
    callback_id = create_callback_id(self._output)
TypeError: create_callback_id() missing 1 required positional argument: 'inputs'
```

**Comment by Ilpo55** [comment]
Same here with version 3.0.11

**Comment by hublol** [comment]
Same problem with 3.0.11, same stack trace.

**Comment by robertjan** [comment]
@flobz issue is still there, I haven the same issue and it’s up to date. Version v3.0.11

**Comment by robertjan** [comment]
I did see the update V3.0.12 is released a couple of minutes ago and that solved the issue for me!
