### ISSUE TITLE
Error in car_models.yml in 3.0.10

### ISSUE THREAD

**Issue by unclej84** [flobz/psa_car_controller#524]
I guess [here](https://github.com/flobz/psa_car_controller/blob/483347330b4a9a9f1a9d73be255129d5d9f46b6d/psa_car_controller/psacc/resources/car_models.yml#L1) a minus is missing at the line beginning

Log:

Containerised psa_car_controller loading...
Traceback (most recent call last):
  File "/usr/local/bin/psa-car-controller", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/__main__.py", line 20, in main
    app.load_app()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/car_controller.py", line 76, in load_app
    self.myp = PSAClient.load_config(name=self.config_name)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 171, in load_config
    psacc = PSAClient(**config)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 52, in __init__
    self.vehicles_list = Cars.load_cars(CARS_FILE)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car.py", line 133, in load_cars
    cars = Cars.from_json(json.loads(json_str))
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car.py", line 113, in from_json
    cars = list(map(Car.from_json, data))
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car.py", line 57, in from_json
    return cls(**data)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car.py", line 17, in __init__
    model = CarModelRepository().find_model_by_name(label)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/utils/utils.py", line 37, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/repository/car_model.py", line 21, in __init__
    self.models: List[CarModel] = yaml.load(models)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/main.py", line 348, in load
    return constructor.get_single_data()
  File "/usr/lib/python3/dist-packages/ruamel/yaml/constructor.py", line 111, in get_single_data
    node = self.composer.get_single_node()
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 83, in get_single_node
    raise ComposerError(
ruamel.yaml.composer.ComposerError: expected a single document in the stream
  in "<unicode string>", line 1, column 1:
    !ElecModel
    ^ (line: 1)
but found another document
  in "<unicode string>", line 8, column 1:
    - !ElecModel
    ^ (line: 8)

**Comment by mdkeil** [comment]
fixed with 3.0.11, but maybe with additional new bugs.. If you don't need mileage/odometer at the moment, stay to 3.0.8.
