### ISSUE TITLE
Two tabs for one vehicle cause en error and no total mileage

### ISSUE THREAD

**Issue by TroisSix** [flobz/psa_car_controller#526]
Hi

Thank you for your great plugin, that's a really great plugin you developed, and I use it everyday now for a few months now :)

I discovered today after the update in 3.0.9 and 3.0.10 some issues:
- I haven't the total mileage anymore
- I have two tabs with the naming of my car, I should have only one tab with the name of my vehicle. I think the requests are now in double ? how could I clean it? After deleting the config files I found in my home, I have an error relating to "two configurations"

I also have issues with the other tabs: no map, no charge tab, etc, so I cannot use it for now.

**Environment (please complete the following information):**
 - OS: debian 11. I installed psa-car-controller with pip3
 - Brand and model of car: Opel corsa-e
 - Application version: 3.0.10

**Logs when starting with --web-conf**
`Traceback (most recent call last):
  File "/home/troissixdomo/.local/bin/psa-car-controller", line 8, in <module>
    sys.exit(main())
  File "/home/troissixdomo/.local/lib/python3.9/site-packages/psa_car_controller/__main__.py", line 20, in main
    app.load_app()
  File "/home/troissixdomo/.local/lib/python3.9/site-packages/psa_car_controller/psacc/application/car_controller.py", line 94, in load_app
    logger.info(str(self.myp.get_vehicles()))
  File "/home/troissixdomo/.local/lib/python3.9/site-packages/psa_car_controller/psacc/application/psa_client.py", line 139, in get_vehicles
    self.vehicles_list.add(Car(vehicle.vin, vehicle.id, vehicle.brand, vehicle.label))
  File "/home/troissixdomo/.local/lib/python3.9/site-packages/psa_car_controller/psacc/model/car.py", line 19, in __init__
    model = CarModelRepository().find_model_by_vin(self.vin)
  File "/home/troissixdomo/.local/lib/python3.9/site-packages/psa_car_controller/psacc/utils/utils.py", line 37, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/home/troissixdomo/.local/lib/python3.9/site-packages/psa_car_controller/psacc/repository/car_model.py", line 21, in __init__
    self.models: List[CarModel] = yaml.load(models)
  File "/home/troissixdomo/.local/lib/python3.9/site-packages/ruamel/yaml/main.py", line 434, in load
    return constructor.get_single_data()
  File "/home/troissixdomo/.local/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 119, in get_single_data
    node = self.composer.get_single_node()
  File "/home/troissixdomo/.local/lib/python3.9/site-packages/ruamel/yaml/composer.py", line 81, in get_single_node
    raise ComposerError(
ruamel.yaml.composer.ComposerError: expected a single document in the stream
  in "<unicode string>", line 1, column 1:
    !ElecModel
    ^ (line: 1)
but found another document
  in "<unicode string>", line 8, column 1:
    - !ElecModel
    ^ (line: 8)
`

Thank you all for your help.
First time the plugin is not working for me for several months now :'(

**Comment by mdkeil** [comment]
fixed with 3.0.11, but maybe with additional new bugs.. If you don't need mileage/odometer at the moment, stay to 3.0.8.

**Comment by TroisSix** [comment]
Thank you @flobz for your very quick release that perfectly resolve the bugs I got (double conf & total mileage) ^^

Also, do you have an idea why I still have nothing in the tabs Summary, Trips, Charge & Map? What should I do?

**Comment by TroisSix** [comment]
And preconditioning/VIN/1 is also not working, perhaps a known bug with 3.0.11?
Il will continue the shitty application MyOpel ^^
