### ISSUE TITLE
Refresh Vehicle Error

### ISSUE THREAD

**Issue by kasper-coding** [flobz/psa_car_controller#538]
Hi! I have the car controller running now for some time. Since some days (cannot reproduce) I receive this error and cannot refresh data anymore. I tried reauthentication with the serivce but it did not not work out. Historic data is still shown, but preconditioning and charge now are missing.

**To Reproduce**
1. what command did you use -> screen psa-car-controller -l 192.168.30.12 -c charge_config.json -f config.json -r
4. Does it persist after restarting the program?  -> yes
5. Does it persist after recreate config by going to http://server_address:port/config?  -> yes

**Config file**
`{
    "abrp": {
        "abrp_enable_vin": [],
        "token": ""
    },
    "client_id": "xxxxx",
    "client_secret": "xxxxx",
    "co2_signal_api": null,
    "country_code": "DE",
    "customer_id": "OP-ACNT2000xxxxxxxxx",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2COpel",
    "refresh_token": "xxxxxxxxxxxxxxxx",
    "remote_refresh_token": "xxxxxxx-xxxxxxxxxxx",
    "weather_api": null
}`

**Environment (please complete the following information):**
 - OS: linux container
 - Opel Corsa 
 - Application version (commit number, branch or tag)
 - Log from http://server_address:port/log and browser console log
 - `2023-04-19 14:11:07,569 :: INFO :: ["{'vin': 'VXKUHXXXXXXXXX', 'vehicle_id': 'XXXXXXXX8818f84736d1cf9a02a2991aa1efdf81f54de5dbef23dXXXXX1', 'label': 'corsa-e', 'brand': 'C', 'abrp_name': 'opel:corsae:20:50', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
2023-04-19 14:11:08,239 :: INFO :: save config change
2023-04-19 14:11:09,396 :: INFO :: ask wakeup to VXKUHZKXZNXXXXXXXX
2023-04-19 14:11:09,396 :: INFO :: topic: psa/RemoteServices/from/cid/OV-ACNT2XXXXXXXXX/VehCharge/state: {'action': 'state'}
2023-04-19 14:11:09,996 :: ERROR :: refresh_vehicle_info: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 125, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 104, in get_vehicle_info
    res = self.api().get_vehicle_status(car.vehicle_id, extension=["odometer"])
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1229, in get_vehicle_status
    (data) = self.get_vehicle_status_with_http_info(id, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1293, in get_vehicle_status_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 78, in call_api
    return self._ApiClient__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 169, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 241, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 626, in __deserialize_model
    instance = klass(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/models/position_properties.py", line 61, in __init__
    self.type = type
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/models/position_properties.py", line 131, in type
    raise ValueError(
ValueError: Invalid value for `type` (Acquire), must be one of ['Estimated', 'Acquired', 'Estimate', 'Aquire']
2023-04-19 14:11:10,000 :: WARNING :: Can't get language
2023-04-19 14:11:10,521 :: INFO :: Connected with result code {'session present': 0}
2023-04-19 14:11:10,522 :: INFO :: subscribe to psa/RemoteServices/to/cid/OV-ACNT200XXXXXXXX/#
2023-04-19 14:11:10,523 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VXKUXXXXXX
2023-04-19 14:11:10,559 :: INFO :: update_data
2023-04-19 14:11:11,373 :: INFO :: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://192.168.30.12:5000
2023-04-19 14:11:11,374 :: INFO :: Press CTRL+C to quit
2023-04-19 14:12:37,882 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-ACNT200XXXXXX/VehCharge/state b'{"resp_date":"2023-04-19T12:12:37Z","vin":"VXKUHZXXXXXXX","correlation_id":"0cc70a216faf408eXXXXXXXX","return_code":"300"}'
2023-04-19 14:12:37,882 :: ERROR :: 300 : ?
2023-04-19 14:13:09,977 :: ERROR :: refresh_vehicle_info:`

**Comment by flobz** [comment]
Update to last version
