### ISSUE TITLE
Error during activation

### ISSUE THREAD

**Issue by christof62** [flobz/psa_car_controller#539]
Get the following error during startup of PSA Car Controller  v3.0.12. 
Data is updated only once. Redo of OTP config does not resolve the problem, even if OTP config does not report an error. Deinstallation and fresh installation of the  newest version does not help. 

Here the trace:
Containerised psa_car_controller loading...
2023-04-20 08:36:36,250 :: INFO :: ["{'vin': 'VXKUH...', 'vehicle_id': '12e72...', 'label': 'corsa-e', 'brand': 'C', 'abrp_name': 'opel:corsae:20:50', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}", "{'vin': 'VXKUH...', 'vehicle_id': '12e72...', 'label': 'corsa-e', 'brand': 'C', 'abrp_name': 'opel:corsae:20:50', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
2023-04-20 08:36:36,510 :: ERROR :: remote_refresh_token isn't defined
2023-04-20 08:36:36,987 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'}
2023-04-20 08:36:36,988 :: ERROR :: get_otp_code:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 193, in get_otp_code
    otp_code = self.otp.get_otp_code()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/otp/otp.py", line 276, in get_otp_code
    raise ConfigException("Can't get otp code")
psa_car_controller.psa.otp.otp.ConfigException: Can't get otp code
2023-04-20 08:36:36,991 :: ERROR :: Please redo otp config
2023-04-20 08:36:37,443 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'}
2023-04-20 08:36:37,445 :: ERROR :: start_remote_control failed redo otp config
2023-04-20 08:36:37,448 :: INFO :: save config change
2023-04-20 08:36:37,454 :: WARNING :: Can't get language
2023-04-20 08:36:39,143 :: INFO :: update_data
2023-04-20 08:36:42,509 :: INFO ::  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2023-04-20 08:36:52,757 :: INFO :: new position recorded for VXKUH...
2023-04-20 08:36:52,760 :: INFO :: update_data
2023-04-20 08:36:54,124 :: INFO :: 172.30.32.1 - - [20/Apr/2023 08:36:54] "GET /get_vehicleinfo/VXKUH...?from_cache=1 HTTP/1.1" 200 -

**Comment by christof62** [comment]
Found instructions in FAQ
