### ISSUE TITLE
No vehicle data

### ISSUE THREAD

**Issue by dortmund50** [flobz/psa_car_controller#541]
**To Reproduce**
1. fresh installation (version 3.0.12) in Docker Compose

**Config file**
{
    "abrp": {
        "abrp_enable_vin": [],
        "token": ""
    },
    "client_id": "0736XXXX-XXXX-XXXX-XXXX-6b035ac2XXXX",
    "client_secret": "F2kK7lC5kFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX5iP5cNXXX",
    "co2_signal_api": null,
    "country_code": "DE",
    "customer_id": "OP-ACNT2XXXXXXXXXXX",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2COpel",
    "refresh_token": "0eaXXX-XXXX-XXXX-XXXX-3XXXXXXXX",
    "remote_refresh_token": "5dxXXXa9-XXXX-XXXX-XXXX-822XXXXXXX2",
    "weather_api": null
}

**Environment (please complete the following information):**
 - OS: Debian
 - Brand and model of car: Opel Corsa-e
 - Application version: 3.0.12
 - Log from http://server_address:port/log and browser console log:

`2023-04-22 21:26:15,075 :: INFO :: ["{'vin': 'VXXXXXXXXXXX', 'vehicle_id': 'XXXXXXXXXXXXXXXXXX', 'label': 'corsa-e', 'brand': 'C', 'abrp_name': 'opel:corsae:20:50', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
2023-04-22 21:26:15,743 :: INFO :: save config change
2023-04-22 21:26:15,852 :: INFO :: ask wakeup to XXXXXXXX
2023-04-22 21:26:15,853 :: INFO :: topic: psa/RemoteServices/from/cid/OV-ACNT2XXXXXXXXXX/VehCharge/state: {'action': 'state'}
2023-04-22 21:26:15,982 :: INFO :: Connected with result code {'session present': 0}
2023-04-22 21:26:15,982 :: INFO :: subscribe to psa/RemoteServices/to/cid/OV-ACNT2XXXXXXXX/#
2023-04-22 21:26:15,982 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VXXXXXXX
2023-04-22 21:26:16,194 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-ACNTXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2023-04-22T21:26:16Z","vin":"VXXXXXXXXXXXXXX","correlation_id":"e29c90062XXXXXXXXXXXXXX","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2023-04-22 21:26:16,218 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-ACNTXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2023-04-22T21:26:16Z","vin":"VXXXXXXXXXXXXXX","correlation_id":"e29c90062XXXXXXXXXXXXXX","process_code":"903","process_message":"[process.903.request.forwarded.to.vehicle.key]"}'
2023-04-22 21:26:16,510 :: ERROR :: refresh_vehicle_info:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 125, in __refresh_vehicle_info
self.get_vehicle_info(car.vin)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 104, in get_vehicle_info
res = self.api().get_vehicle_status(car.vehicle_id, extension=["odometer"])
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1229, in get_vehicle_status
(data) = self.get_vehicle_status_with_http_info(id, **kwargs) # noqa: E501
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1293, in get_vehicle_status_with_http_info
return self.api_client.call_api(
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 78, in call_api
return self._ApiClient__call_api(resource_path, method,
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 169, in __call_api
return_data = self.deserialize(response_data, response_type)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 241, in deserialize
return self.__deserialize(data, response_type)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 280, in __deserialize
return self.__deserialize_model(data, klass)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 624, in __deserialize_model
kwargs[attr] = self.__deserialize(value, attr_type)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 280, in __deserialize
return self.__deserialize_model(data, klass)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 624, in __deserialize_model
kwargs[attr] = self.__deserialize(value, attr_type)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 280, in __deserialize
return self.__deserialize_model(data, klass)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 626, in __deserialize_model
instance = klass(**kwargs)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/models/position_properties.py", line 61, in __init__
self.type = type
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/models/position_properties.py", line 131, in type
raise ValueError(
ValueError: Invalid value for `type` (Acquire), must be one of ['Estimated', 'Acquired', 'Estimate', 'Aquire']
2023-04-22 21:26:16,519 :: WARNING :: Can't get language
2023-04-22 21:26:16,519 :: WARNING :: Can't get language
2023-04-22 21:26:16,976 :: INFO :: update_data
2023-04-22 21:26:17,633 :: INFO :: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2023-04-22 21:26:17,876 :: INFO :: 192.168.178.33 - - [22/Apr/2023 21:26:17] "[37mGET /log HTTP/1.1[0m" 200 -
2023-04-22 21:26:17,991 :: INFO :: 192.168.178.33 - - [22/Apr/2023 21:26:17] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2023-04-22 21:26:17,998 :: INFO :: 192.168.178.33 - - [22/Apr/2023 21:26:17] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -`

**Additional context**
I can set up the application normally: Login and SMS confirmation work without problems. After that I do not receive any information. Reboots have not helped either, even an installation as Docker container does not work.

**Comment by mdkeil** [comment]
look at [here](https://github.com/flobz/psa_car_controller/issues/532#issuecomment-1509793937).. I think, that you do not use a clean 3.0.12-version..
