### ISSUE TITLE
Information not retrieved. Error in the log file

### ISSUE THREAD

**Issue by antro31** [flobz/psa_car_controller#543]
**Describe the bug**
Information are not correctly retreived. (For example still stating that car is charging whereas it is unplugged).

**To Reproduce**
Nothing specific, add on started. After a while, data are not updated any more. An error appears in the log. 

**Environment (please complete the following information):**
Home Assistant Add On - OS: [e.g. Windows]
DS - DS7 

```
2023-04-27 18:28:42,002 :: ERROR :: force_update:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/charge_control.py", line 70, in force_update
    self.psacc.remote_client.wakeup(self.vin)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 22, in wrapper
    raise RateLimitException
psa_car_controller.common.utils.RateLimitException

```

**Additional context**
Maybe we could setup a rate limiter to avoid this?

**Comment by flobz** [comment]
This is a rate limit in the code.

**Comment by flobz** [comment]
Don't query to much the API.
