### ISSUE TITLE
Internal Server Error on get_vehicleinfo

### ISSUE THREAD

**Issue by Dizzybacon** [flobz/psa_car_controller#558]
When calling the get_vehicleinfo API it returns a 500 Internal Server Error

**To Reproduce**
1. In brower myipaddress:5000
2. Follow log in process and OTP
3. myipaddress:5000/wakeup/myvin - returns true
4. myipaddress:5000/get_vehicleinfo/myvin - returns 500 Internal Server Error

**Config file**
Give the anonymize content of the config file
`{
    "abrp": {
        "abrp_enable_vin": [],
        "token": ""
    },
    "client_id": "XXXXXXXX",
    "client_secret": "XXXXXXXX",
    "co2_signal_api": null,
    "country_code": "GB",
    "customer_id": "XXXXXXXX",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2CPeugeot",
    "refresh_token": "XXXXXXXX",
    "remote_refresh_token": null,
    "weather_api": null
}`

**Environment (please complete the following information):**
 - OS: Docker install
 - Peugeot e-Rifter
 - flobz/psa_car_controller:latest
 - Log from http://server_address:port/log and browser console log
 
`2023-05-17 08:49:26,702 :: ERROR :: Exception on /get_vehicleinfo/XXXXXXXX [GET]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 146, in get_vehicle_info
response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 104, in get_vehicle_info
res = self.api().get_vehicle_status(car.vehicle_id, extension=["odometer"])
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1229, in get_vehicle_status
(data) = self.get_vehicle_status_with_http_info(id, **kwargs) # noqa: E501
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1293, in get_vehicle_status_with_http_info
return self.api_client.call_api(
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 78, in call_api
return self._ApiClient__call_api(resource_path, method,
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 169, in __call_api
return_data = self.deserialize(response_data, response_type)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 241, in deserialize
return self.__deserialize(data, response_type)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 280, in __deserialize
return self.__deserialize_model(data, klass)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 624, in __deserialize_model
kwargs[attr] = self.__deserialize(value, attr_type)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 280, in __deserialize
return self.__deserialize_model(data, klass)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 624, in __deserialize_model
kwargs[attr] = self.__deserialize(value, attr_type)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 280, in __deserialize
return self.__deserialize_model(data, klass)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 626, in __deserialize_model
instance = klass(**kwargs)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/models/position_properties.py", line 61, in __init__
self.type = type
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/models/position_properties.py", line 131, in type
raise ValueError(
ValueError: Invalid value for `type` (Acquire), must be one of ['Estimated', 'Acquired', 'Estimate', 'Aquire']
2023-05-17 08:49:26,702 :: ERROR :: Exception on /get_vehicleinfo/XXXXXXX [GET]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 146, in get_vehicle_info
response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 104, in get_vehicle_info
res = self.api().get_vehicle_status(car.vehicle_id, extension=["odometer"])
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1229, in get_vehicle_status
(data) = self.get_vehicle_status_with_http_info(id, **kwargs) # noqa: E501
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1293, in get_vehicle_status_with_http_info
return self.api_client.call_api(
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 78, in call_api
return self._ApiClient__call_api(resource_path, method,
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 169, in __call_api
return_data = self.deserialize(response_data, response_type)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 241, in deserialize
return self.__deserialize(data, response_type)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 280, in __deserialize
return self.__deserialize_model(data, klass)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 624, in __deserialize_model
kwargs[attr] = self.__deserialize(value, attr_type)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 280, in __deserialize
return self.__deserialize_model(data, klass)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 624, in __deserialize_model
kwargs[attr] = self.__deserialize(value, attr_type)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 280, in __deserialize
return self.__deserialize_model(data, klass)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 626, in __deserialize_model
instance = klass(**kwargs)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/models/position_properties.py", line 61, in __init__
self.type = type
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/models/position_properties.py", line 131, in type
raise ValueError(
ValueError: Invalid value for `type` (Acquire), must be one of ['Estimated', 'Acquired', 'Estimate', 'Aquire']
2023-05-17 08:49:26,709 :: INFO :: 192.168.1.156 - - [17/May/2023 08:49:26] "[35m[1mGET /get_vehicleinfo/XXXXXXXX HTTP/1.1[0m" 500 -`

**Additional context**
I tried all the other api calls in the README and they all work fine.

**Comment by flobz** [comment]
Upgrade to last version.
