### ISSUE TITLE
Application crash à la validation du formulaire

### ISSUE THREAD

**Issue by JulienADD** [flobz/psa_car_controller#573]
Bonjour,

**Describe the bug**
Application crash lors de la validation du modèle, mail, mot de passe, pays

**To Reproduce**
1. what command did you use : remplissage des informations du formulaire
2. when the bug append ? à la validation
3. Does it persist after restarting the program? oui
4. Does it persist after recreate config by going to http://server_address:port/config? c'est l'endroit ou cela plante

**Config file**
> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 215, in get_charge_control
    charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'
2023-06-21 16:42:26,130 :: INFO :: 192.168.X.X - - [21/Jun/2023 16:42:26] "GET /charge_control?vin=VIN&?always_check=true HTTP/1.1" 500 -
Exception on /get_vehicleinfo/VIN [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 146, in get_vehicle_info
    response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'PSACarController' object has no attribute 'myp'
2023-06-21 16:43:26,111 :: ERROR :: Exception on /get_vehicleinfo/VIN [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 146, in get_vehicle_info
    response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'PSACarController' object has no attribute 'myp'
2023-06-21 16:43:26,128 :: INFO :: 192.168.X.X - - [21/Jun/2023 16:43:26] "GET /get_vehicleinfo/VIN?from_cache=1 HTTP/1.1" 500 -
2023-06-21 16:43:26,143 :: INFO :: <Request 'http://192.168.X.X:5000/charge_control?vin=VIN&%3Falways_check=true' [GET]>
Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
2023-06-21 16:43:26,151 :: ERROR :: Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 215, in get_charge_control
    charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'
2023-06-21 16:43:26,165 :: INFO :: 192.168.X.X - - [21/Jun/2023 16:43:26] "GET /charge_control?vin=VIN&?always_check=true HTTP/1.1" 500 -
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 215, in get_charge_control
    charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'
2023-06-21 16:43:39,747 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:39] "GET / HTTP/1.1" 200 -
2023-06-21 16:43:40,063 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:40] "GET /_dash-layout HTTP/1.1" 200 -
2023-06-21 16:43:40,078 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:40] "GET /_dash-dependencies HTTP/1.1" 200 -
2023-06-21 16:43:40,220 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:40] "POST /_dash-update-component HTTP/1.1" 200 -
2023-06-21 16:43:40,409 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:40] "GET /config_login HTTP/1.1" 200 -
2023-06-21 16:43:40,615 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:40] "GET /_dash-layout HTTP/1.1" 200 -
2023-06-21 16:43:40,634 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:40] "GET /_dash-dependencies HTTP/1.1" 200 -
2023-06-21 16:43:40,851 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:40] "POST /_dash-update-component HTTP/1.1" 200 -
2023-06-21 16:43:41,679 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:41] "POST /_dash-update-component HTTP/1.1" 204 -
2023-06-21 16:43:41,718 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:41] "POST /_dash-update-component HTTP/1.1" 200 -
2023-06-21 16:43:41,737 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:41] "POST /_dash-update-component HTTP/1.1" 204 -
/init.sh: line 5:     9 Killed                  psa-car-controller $ARGS

**Environment (please complete the following information):**
 - OS: Home Assistant HAOS sur Raspberry PI
 - Brand and model of car : 3008 Hybrid
 - Application version (commit number, branch or tag) : v3.0.12
 - Log from http://server_address:port/log and browser console log

**Additional context**
J'ai migré le Raspberry vers un disque dur SSD

Merci pour votre aide

**Comment by flobz** [comment]
wrong language
