### ISSUE TITLE
ABRP can't receive info after an few min.

### ISSUE THREAD

**Issue by phoenix-blue** [flobz/psa_car_controller#582]
**Describe the bug**

The PSA car controller is running ok and have made the API connedtion to the ABRP what is in the beginning normal working.
But after a 3 to 5 min. ABRP is not getting some live date but can't see why in the log file of de PSA controller. 

**To Reproduce**
1. what command did you use -> -c -r --web-conf
2. when the bug append ? -> After an few min when the ABRP is connected with the PSA car controller
3. Does it persist after restarting the program?  -> Yes
4. Does it persist after recreate config by going to http://server_address:port/config? 

**Config file**
```
{
    "abrp": {
        "abrp_enable_vin": [
            "xx"
        ],
        "token": "xx"
    },
    "client_id": xx"",
    "client_secret": "xx",
    "co2_signal_api": null,
    "country_code": "NL",
    "customer_id": "xx",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2COpel",
    "refresh_token": "xx",
    "remote_refresh_token": "xx",
    "weather_api": null
}
```

**Environment (please complete the following information):**
 - OS: [e.g. Windows] -> Docker
 - Brand and model of car -> Opel Mokka-E
 - Application version (commit number, branch or tag) -> https://hub.docker.com/r/flobz/psa_car_controller
 - Log from http://server_address:port/log and browser console log:
 
 ```
2023-07-10 18:40:13,196 :: INFO :: ask wakeup to xx
2023-07-10 18:40:13,198 :: INFO :: topic: psa/RemoteServices/from/cid/xx/VehCharge/state: {'action': 'state'}
2023-07-10 18:40:13,201 :: WARNING :: Disconnected with result code 1
2023-07-10 18:40:13,752 :: INFO :: save config change
2023-07-10 18:40:14,940 :: INFO :: Connected with result code {'session present': 0}
2023-07-10 18:40:14,942 :: INFO :: subscribe to psa/RemoteServices/to/cid/xx/#
2023-07-10 18:40:14,944 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/xx

```
**Additional context**
THe first try i have done was inside Home Assistent, but with the same problems so i have for test made an clean docker VM environment

and not sure if this has to do with it, but after an reboot of the docker container i see an lot if this kind of errors:

```
2023-07-10 19:30:07,910 :: ERROR :: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/dash/dash.py", line 1273, in dispatch
ctx.run(
File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 440, in add_context
output_value = func(*func_args, **func_kwargs) # %% callback invoked %%
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/tools/Button.py", line 41, in call
self._fct(self._element_id)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 22, in wrapper
raise RateLimitException
psa_car_controller.common.utils.RateLimitException
2023-07-10 19:30:07,910 :: ERROR :: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/dash/dash.py", line 1273, in dispatch
ctx.run(
File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 440, in add_context
output_value = func(*func_args, **func_kwargs) # %% callback invoked %%
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/tools/Button.py", line 41, in call
self._fct(self._element_id)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 22, in wrapper
raise RateLimitException
psa_car_controller.common.utils.RateLimitException

```

**Comment by sircuri** [comment]
Do you actually witness that no data is being sent to ABRP? PSA does not update that frequently and this PsaCarController might be pushing the same data over and over. ABRP will report that it is not connected, but your data might just be stale.

First verify with WireShark or something that there is no data delivered to ABRP. As long as the update-date in the data stays the same, ABRP will report that it is not getting any new data.

**Comment by flobz** [comment]
state
