### ISSUE TITLE
Application crash at form validation

### ISSUE THREAD

**Issue by JulienADD** [flobz/psa_car_controller#591]
Hi,

Describe the bug
Application crash during model validation, mail, password, country

To Reproduce

what command did you use : Filling in the form information
when the bug append ? to validation
Does it persist after restarting the program? yes
Does it persist after recreate config by going to http://server_address:port/config? This is the place where it crashes
Config file

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](https://github.com/flobz/psa_car_controller/issues/**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 215, in get_charge_control
charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'
2023-06-21 16:42:26,130 :: INFO :: 192.168.X.X - - [21/Jun/2023 16:42:26] "GET /charge_control?vin=VIN&?always_check=true HTTP/1.1" 500 -
Exception on /get_vehicleinfo/VIN [GET]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](https://github.com/flobz/psa_car_controller/issues/**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 146, in get_vehicle_info
response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'PSACarController' object has no attribute 'myp'
2023-06-21 16:43:26,111 :: ERROR :: Exception on /get_vehicleinfo/VIN [GET]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](https://github.com/flobz/psa_car_controller/issues/**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 146, in get_vehicle_info
response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'PSACarController' object has no attribute 'myp'
2023-06-21 16:43:26,128 :: INFO :: 192.168.X.X - - [21/Jun/2023 16:43:26] "GET /get_vehicleinfo/VIN?from_cache=1 HTTP/1.1" 500 -
2023-06-21 16:43:26,143 :: INFO :: <Request 'http://192.168.x.x:5000/charge_control?vin=VIN&%3Falways_check=true' [GET]>
Exception on /charge_control [GET]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
2023-06-21 16:43:26,151 :: ERROR :: Exception on /charge_control [GET]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](https://github.com/flobz/psa_car_controller/issues/**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 215, in get_charge_control
charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'
2023-06-21 16:43:26,165 :: INFO :: 192.168.X.X - - [21/Jun/2023 16:43:26] "GET /charge_control?vin=VIN&?always_check=true HTTP/1.1" 500 -
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](https://github.com/flobz/psa_car_controller/issues/**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 215, in get_charge_control
charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'
2023-06-21 16:43:39,747 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:39] "GET / HTTP/1.1" 200 -
2023-06-21 16:43:40,063 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:40] "GET /_dash-layout HTTP/1.1" 200 -
2023-06-21 16:43:40,078 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:40] "GET /_dash-dependencies HTTP/1.1" 200 -
2023-06-21 16:43:40,220 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:40] "POST /_dash-update-component HTTP/1.1" 200 -
2023-06-21 16:43:40,409 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:40] "GET /config_login HTTP/1.1" 200 -
2023-06-21 16:43:40,615 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:40] "GET /_dash-layout HTTP/1.1" 200 -
2023-06-21 16:43:40,634 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:40] "GET /_dash-dependencies HTTP/1.1" 200 -
2023-06-21 16:43:40,851 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:40] "POST /_dash-update-component HTTP/1.1" 200 -
2023-06-21 16:43:41,679 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:41] "POST /_dash-update-component HTTP/1.1" 204 -
2023-06-21 16:43:41,718 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:41] "POST /_dash-update-component HTTP/1.1" 200 -
2023-06-21 16:43:41,737 :: INFO :: 172.30.32.1 - - [21/Jun/2023 16:43:41] "POST /_dash-update-component HTTP/1.1" 204 -
/init.sh: line 5: 9 Killed psa-car-controller $ARGS

Environment (please complete the following information):

OS: Home Assistant HAOS Raspberry PI
Brand and model of car : 3008 Hybrid
Application version (commit number, branch or tag) : v3.0.12
Log from http://server_address:port/log and browser console log
Additional context
I migrated the Raspberry to an SSD hard drive

Thanks for your help

**Comment by JulienADD** [comment]
I think I would have to delete all the files and do a clean install again but I don't know how to access it with my install.

**Comment by JulienADD** [comment]
I really tested everything
Removal of the addon on Home Assistant
Removal of the application on the phone side, after reinstallation, it asks me for mail + password + OTP, everything is fine
And in HA, once I enter the same email / password

`Containerised psa_car_controller loading...
2023-08-14 16:37:11,867 :: ERROR :: No config file
2023-08-14 16:37:11,896 :: WARNING :: Can't get language
2023-08-14 16:37:18,084 :: INFO :: update_data
2023-08-14 16:37:18,236 :: INFO ::  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2023-08-14 16:39:16,287 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:39:16] "GET / HTTP/1.1" 200 -
2023-08-14 16:39:16,726 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:39:16] "GET /_dash-layout HTTP/1.1" 200 -
2023-08-14 16:39:16,829 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:39:16] "GET /_dash-dependencies HTTP/1.1" 200 -
2023-08-14 16:39:16,950 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:39:16] "POST /_dash-update-component HTTP/1.1" 200 -
2023-08-14 16:39:17,069 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:39:17] "GET /config_login HTTP/1.1" 200 -
2023-08-14 16:39:17,262 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:39:17] "GET /_dash-layout HTTP/1.1" 200 -
2023-08-14 16:39:17,284 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:39:17] "GET /_dash-dependencies HTTP/1.1" 200 -
2023-08-14 16:39:17,416 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:39:17] "POST /_dash-update-component HTTP/1.1" 200 -
2023-08-14 16:39:17,568 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:39:17] "POST /_dash-update-component HTTP/1.1" 204 -
2023-08-14 16:39:17,581 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:39:17] "POST /_dash-update-component HTTP/1.1" 200 -
2023-08-14 16:39:17,654 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:39:17] "POST /_dash-update-component HTTP/1.1" 204 -
2023-08-14 16:54:27,942 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:54:27] "GET / HTTP/1.1" 200 -
2023-08-14 16:54:28,259 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:54:28] "GET /_dash-layout HTTP/1.1" 200 -
2023-08-14 16:54:28,366 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:54:28] "GET /_dash-dependencies HTTP/1.1" 200 -
2023-08-14 16:54:28,498 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:54:28] "POST /_dash-update-component HTTP/1.1" 200 -
2023-08-14 16:54:28,617 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:54:28] "GET /config_login HTTP/1.1" 200 -
2023-08-14 16:54:28,811 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:54:28] "GET /_dash-dependencies HTTP/1.1" 200 -
2023-08-14 16:54:28,823 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:54:28] "GET /_dash-layout HTTP/1.1" 200 -
2023-08-14 16:54:28,961 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:54:28] "POST /_dash-update-component HTTP/1.1" 200 -
2023-08-14 16:54:29,114 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:54:29] "POST /_dash-update-component HTTP/1.1" 204 -
2023-08-14 16:54:29,129 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:54:29] "POST /_dash-update-component HTTP/1.1" 200 -
2023-08-14 16:54:29,195 :: INFO :: 172.30.32.1 - - [14/Aug/2023 16:54:29] "POST /_dash-update-component HTTP/1.1" 204 -
/init.sh: line 5:    10 Killed                  psa-car-controller $ARGS`


Just after the validation of the form where I enter:
Peugeot
email
mdp
FR

**Comment by hrueger** [comment]
Same issue here. Is there anything else we can test / information we can provide?

**Comment by hrueger** [comment]
I just tried it with a development setup (outside of home assistant, just `psa-car-controller --web-conf` and it works just fine there... It is not working in Homeassistant, though.

**Comment by hrueger** [comment]
Never mind, my issue was different. I was probably running out of memory, since it worked on a 2 GB Pi 4. I was running a 1 GB Pi 3 before.

**Comment by JulienADD** [comment]
I have a Raspberry Pi 3 rpi3-64 with 1GB too

**Comment by hrueger** [comment]
Interesting. Then maybe it is related?
You could try running the docker container on a machine with more ram like your pc and see if it works there.

**Comment by JulienADD** [comment]
I don't know how do that, sorry 😣

**Comment by mostlysimon** [comment]
> I have a Raspberry Pi 3 rpi3-64 with 1GB too

I have the same issue that you have reported with exactly the same Raspberry Pi 3 1gb setup.

**Comment by JulienADD** [comment]
> If you want to try it, it is pretty easy. In the Readme, there's a section _Installation_. You can use docker (install [Docker Desktop](https://www.docker.com/products/docker-desktop/) before) and follow the steps, or - if you have python installed - you can follow the guide for direct installation).

Ok i try that, thanks for your help 😉

**Comment by DevAddInformatique** [comment]
`version: '3'

services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      # This is the required way to set a timezone on macOS and differs from the Linux compose file
      - TZ=Europe/Brussels
    volumes:
      - ./config:/config
    restart: always
    ports:
      # Also required for macOS since the network directive in docker-compose does not work
      - "8123:8123"

# Add this or docker-compose will complain that it did not find the key for locally mapped volume
volumes:
  config:`

I managed to install HA via Docker with this YAML, the problem is that I feel like it's the Core version, I don't have the add-ons, so I can't add the PSA module, am I doing something wrong ?

**Comment by JulienADD** [comment]
```
version: '3'

services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      - TZ=Europe/Brussels
    volumes:
      - ./config:/config
    restart: always
    ports:
      - "8123:8123"
      - 
volumes:
  config:
```

I managed to install HA via Docker with this YAML, the problem is that I feel like it's the Core version, I don't have the add-ons, so I can't add the PSA module, am I doing something wrong ?

**Comment by hrueger** [comment]
I'm not sure about that, but you can install psa_car_controller without homeassistant, see https://github.com/flobz/psa_car_controller/blob/master/docs/Docker.md

**Comment by JulienADD** [comment]
> I'm not sure about that, but you can install psa_car_controller without homeassistant, see https://github.com/flobz/psa_car_controller/blob/master/docs/Docker.md

Thanks, it's installed, it works perfectly fine... I don't know why with the same data it doesn't work on my RPI ... :(

**Comment by flobz** [comment]
It's probably memory related, you can stop other plugin during the setup and start them again after setup is finish maybe.
