### ISSUE TITLE
AttributeError: 'PSACarController' object has no attribute 'chc'

### ISSUE THREAD

**Issue by GeraldPape** [flobz/psa_car_controller#592]
```
2023-07-20 07:30:01,812 :: INFO :: 10.0.0.13 - - [20/Jul/2023 07:30:01] "[35m[1mGET /charge_control?vin=VR7A4DGZSPL022202&?always_check=true HTTP/1.1[0m" 500 -
2023-07-20 07:31:01,802 :: INFO :: 10.0.0.13 - - [20/Jul/2023 07:31:01] "[37mGET /get_vehicleinfo/**VIN**?from_cache=1 HTTP/1.1[0m" 200 -
2023-07-20 07:31:01,807 :: INFO :: <Request 'http://10.0.0.45:5000/charge_control?vin=**VIN**&%3Falways_check=true' [GET]>
2023-07-20 07:31:01,810 :: ERROR :: Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 215, in get_charge_control
    charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'
2023-07-20 07:31:01,810 :: ERROR :: Exception on /charge_control [GET]
```
**To Reproduce**
1. what command did you use
2. when the bug append ?
3. Does it persist after restarting the program? 
4. Does it persist after recreate config by going to http://server_address:port/config? 

**Config file**
Give the anonymize content of the config file
```
{
    "abrp": {
        "abrp_enable_vin": [],
        "token": ""
    },
    "client_id": "5364defc-80e6-447b-bec6-4af8d1542cae",
    "client_secret": "secret",
    "co2_signal_api": null,
    "country_code": "AT",
    "customer_id": "AC-ID",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2CCitroen",
    "refresh_token": "ttttttt-ccccc-token-xxxx-ggggggg",
    "remote_refresh_token": null,
    "weather_api": null
}j
```

**Environment (please complete the following information):**
 - OS: linux / debian - docker
 - Brand and model of car citroen C5 Aircross
 - Application version (commit number, branch or tag) latest docker image
 - Log from http://server_address:port/log and browser console log

reinstalled the raspberry os and psa-car-controller, copied config directory from backup und startet the image.

**Comment by martynhr** [comment]
Same Error for me too:

2023-07-22 13:45:42,362 :: ERROR :: Exception on /charge_control [GET]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 215, in get_charge_control
charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'

**Comment by thewhale21** [comment]
Same for me, I assume its something to do with HA core update. Any ideas how to fix?

**Comment by martynhr** [comment]
Had to log back in again then okSent from my Galaxy
-------- Original message --------From: thewhale21 ***@***.***> Date: 30/07/2023  08:54  (GMT+01:00) To: flobz/psa_car_controller ***@***.***> Cc: martynhr ***@***.***>, Manual ***@***.***> Subject: Re: [flobz/psa_car_controller] AttributeError: 'PSACarController' object has no attribute 'chc' (Issue #592) 
Same for me, I assume its something to do with HA core update. Any ideas how to fix?

**Comment by fschaal** [comment]
Same error here. Did anyone find a fix for this?

**Comment by thewhale21** [comment]
> Same error here. Did anyone find a fix for this?

Logout and log back in
