### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by d1ockers** [flobz/psa_car_controller#594]
Hi folks,

I have had PSA Car Controller working perfectly for a fair while. Every few months though, it logs out/stops working. When I try and login, it just hangs at the login screen (with the loading icon)...

Please could anyone tell me if I am missing something obvious? I thought DNS initially so reconfigured my DHCP server with new nameservers.

This is my log:
```

<snip> from console log
 This is usually not a problem but could indicate packers or broken AXML compilers.
2023-07-21 10:21:55,181 :: INFO :: Namespace mapping (60, 420) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2023-07-21 10:21:55,487 :: INFO :: APK file was successfully validated!
2023-07-21 10:21:55,601 :: WARNING :: Requested API level 31 is larger than maximum we have, returning API level 28 instead.
2023-07-21 10:22:28,427 :: ERROR :: No config file
2023-07-21 10:22:28,445 :: WARNING :: Can't get language
2023-07-21 10:22:28,445 :: WARNING :: Can't get language
2023-07-21 10:22:34,073 :: INFO :: update_data
2023-07-21 10:22:34,315 :: INFO :: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2023-07-21 13:28:37,551 :: INFO :: 172.30.32.1 - - [21/Jul/2023 13:28:37] "[37mGET / HTTP/1.1[0m" 200 -
2023-07-21 13:28:37,780 :: INFO :: 172.30.32.1 - - [21/Jul/2023 13:28:37] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2023-07-21 13:28:37,790 :: INFO :: 172.30.32.1 - - [21/Jul/2023 13:28:37] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2023-07-21 13:28:37,894 :: INFO :: 172.30.32.1 - - [21/Jul/2023 13:28:37] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2023-07-21 13:28:37,955 :: INFO :: 172.30.32.1 - - [21/Jul/2023 13:28:37] "[37mGET /config_login HTTP/1.1[0m" 200 -
2023-07-21 13:28:38,074 :: INFO :: 172.30.32.1 - - [21/Jul/2023 13:28:38] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2023-07-21 13:28:38,084 :: INFO :: 172.30.32.1 - - [21/Jul/2023 13:28:38] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -

```

`Containerised psa_car_controller loading...
2023-07-21 13:51:48,480 :: ERROR :: No config file
2023-07-21 13:51:48,503 :: WARNING :: Can't get language
2023-07-21 13:51:55,251 :: INFO :: update_data
2023-07-21 13:51:55,423 :: INFO ::  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)`

I've tried reinstalling PSA Car Controller a few times. I've left it several days/weeks. Same behaviour. This a HomeAssistant running on a RaspPi.

**Comment by bbr111** [comment]
Currently my installation is not working too.
But also the  Native App on Android is not getting any informations.
It looks like an PSA problem.

**Comment by zoic21** [comment]
Hello,
Same for me but native also... So it's a PSA server issue....

**Comment by Bogeyof** [comment]
Anyone could use psa-controller again? Opel App is working, but pas-controller not:
`root@solaranzeige:~# 2023-07-23 11:23:58,853 :: ERROR :: Please reconnect by going to config web page
Traceback (most recent call last):
  File "/usr/local/bin/psa-car-controller", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/psa_car_controller/__main__.py", line 20, in main
    app.load_app()
  File "/usr/local/lib/python3.7/dist-packages/psa_car_controller/psacc/application/car_controller.py", line 110, in load_app
    raise ConnectionError
ConnectionError
2023-07-23 11:23:58,858 :: INFO :: save config change
`
Do I really have to renew config or is API still not useable?

**Comment by d1ockers** [comment]
> Anyone could use psa-controller again? Opel App is working, but pas-controller not:
> 
> ```
> root@solaranzeige:~# 2023-07-23 11:23:58,853 :: ERROR :: Please reconnect by going to config web page
> Traceback (most recent call last):
>   File "/usr/local/bin/psa-car-controller", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/dist-packages/psa_car_controller/__main__.py", line 20, in main
>     app.load_app()
>   File "/usr/local/lib/python3.7/dist-packages/psa_car_controller/psacc/application/car_controller.py", line 110, in load_app
>     raise ConnectionError
> ConnectionError
> 2023-07-23 11:23:58,858 :: INFO :: save config change
> ```
> 
> Do I really have to renew config or is API still not useable?
> 
> Edit: No answer here, so I did new config. Working again. Backuped old database and restored afterwords. So I still have my data. Wonder why it stopped working...

How did you do a new config?

**Comment by Bogeyof** [comment]
If your webinterface still running, click the gear icon in upper right corner and you will find "user config" and "OTP config". If webinterface not running anymore, delete psa-controller data files in root and try new config like first time. If u want to save your data, backup info.db and restore afterwards...

**Comment by d1ockers** [comment]
> If your webinterface still running, click the gear icon in upper right corner and you will find "user config" and "OTP config". If webinterface not running anymore, delete psa-controller data files in root and try new config like first time. If u want to save your data, backup info.db before deleting files and restore afterwards...

Thank you for your reply. Apologies for my ignorance, but is there a way to access the root folder to delete these files? I cannot seem to find them using File editor or Studio Code Server. 

Thanks

**Comment by Bogeyof** [comment]
For me on my Raspberry Pi, these files are not in "/" (normaly named root folder), they are in "/root". May be it depends which user has installed it, dont know...

**Comment by flobz** [comment]
Close as it doesn't follow the bug template
