### ISSUE TITLE
AP_PL_ESP{"returnCode":"NEED_CREATION"

### ISSUE THREAD

**Issue by bartixmayo** [flobz/psa_car_controller#613]
**Describe the bug**
Fresh instalation, Current version: v3.0.12. At configuration page pasitng: Peugeot / e-mail / password / PL I get:

Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 48, in firstLaunchConfig token = res.json()["accessToken"] KeyError: 'accessToken' HOST_BRANDID : https://id-dcr.peugeot.com/mobile-services sitecode: AP_PL_ESP{"returnCode":"NEED_CREATION"}

How or what do correct?

**Comment by flobz** [comment]
can you retry ?

**Comment by edsub** [comment]
Having the same issue (v.3.5.3) after first time submitting brand/email/password/NL
Traceback (most recent call last): File "/home/pi/.local/lib/python3.10/site-packages/psa_car_controller/psa/setup/app_decoder.py", line 59, in __init__ self.token = res.json()["accessToken"] KeyError: 'accessToken' HOST_BRANDID : https://id-dcr.peugeot.com/mobile-services sitecode: AP_NL_ESP{"returnCode":"NEED_CREATION"}

**Comment by edsub** [comment]
OK, found&fixed. I appeared to be using the wrong email . . .  my bad.
