### ISSUE TITLE
Error during activation: {'err': 'NOK:FORBIDDEN'}

### ISSUE THREAD

**Issue by jeromegosio** [flobz/psa_car_controller#634]
Hi,

Since 3 Week , i have this error , and nothing information was go back up

2023-10-16 09:24:47,510 :: ERROR :: remote_refresh_token isn't defined
2023-10-16 09:24:48,013 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'}
2023-10-16 09:24:48,013 :: ERROR :: get_otp_code:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 193, in get_otp_code
    otp_code = self.otp.get_otp_code()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/otp/otp.py", line 276, in get_otp_code
    raise ConfigException("Can't get otp code")
psa_car_controller.psa.otp.otp.ConfigException: Can't get otp code
2023-10-16 09:24:48,018 :: ERROR :: Please redo otp config
2023-10-16 09:24:48,535 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'}
2023-10-16 09:24:48,539 :: ERROR :: start_remote_control failed redo otp config
2023-10-16 09:24:48,542 :: INFO :: save config change
2023-10-16 09:24:48,547 :: WARNING :: Can't get language
2023-10-16 09:24:49,758 :: INFO :: update_data
2023-10-16 09:24:51,635 :: INFO ::  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

**Comment by flobz** [comment]
look at https://github.com/flobz/psa_car_controller/issues?q=is%3Aissue+NOK%3AFORBIDDEN
