### ISSUE TITLE
[FEAT] Request python3-distutils in docker container for pip

### ISSUE THREAD

**Issue by Mikado8231** [flobz/psa_car_controller#660]
**Describe the bug**

Pip not working on docker command interface
Missing lib **python3-distutils**

```
root@cf13ed6f0d72:/config# pip list
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/utils/misc.py", line 44, in <module>
    from pip._internal.locations import get_major_minor_version
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/locations/__init__.py", line 66, in <module>
    from . import _distutils
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/locations/_distutils.py", line 20, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils.cmd'
```

Is it possible to add the lib python3-distutils as requirement in docker file ?

**To Reproduce**

1. Connect inside docker container in bash
2. Run pip list

**Environment (please complete the following information):**

 - OS: Docker 3.0.13

**Additional context**

Workaround (manually):
```
apt update
apt install python3-distutils
```

**Comment by Apollon77** [comment]
Downgrade python :-) this module was removed in python 3.12 ... seems some stuff needs to be adjusted

**Comment by flobz** [comment]
pip isn't needed inside the docker image and image should be as light as possible.
