### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to_dict'

### ISSUE THREAD

**Issue by FlHinrichsen** [flobz/psa_car_controller#681]
"get_vehicleinfo" page shows an error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.7/dist-packages/psa_car_controller/web/view/views.py", line 146, in get_vehicle_info
    response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'NoneType' object has no attribute 'to_dict'

**Comment by thewhale21** [comment]
see #674

**Comment by flobz** [comment]
duplicate
