### ISSUE TITLE
400 - server_error : Internal Server Error ... can't login in 

### ISSUE THREAD

**Issue by MarkTimStafford** [flobz/psa_car_controller#683]
I get a server error when completing the initial UN/PW screen.
I am pretty sure hat the UN/PW I am using is correct as it works on my My Vauxhall App on my phone
So this is before we get to the PSA issues below
Does anyone have any ideas?

Here is top of the to the first error log
The absence of the chc attribute may well point to the login failiure

2023-11-24 16:07:54,780 :: ERROR :: Exception on /charge_control [GET]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 249, in get_charge_control
charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'

**Comment by MarkTimStafford** [comment]
Same problem as #674 ... so closed
