### ISSUE TITLE
Error 400 - Server Error: Vauxhall Corsa E

### ISSUE THREAD

**Issue by AndrewWalls** [flobz/psa_car_controller#686]
My original issue was closed, but this is still occurring on the Vauxhall Corsa E despite the odometer fix.

---

Car: Vauxhall Corsa E

When I attempt to authenticate under 'My Car Details' I get the error message: 400 - server_error : Internal Server Error

Attempted on: Windows 10 PC and HomeAssistant running on a Raspberry Pi 4

I have used this tool for years, but this error has just emerged. I have attempted on older versions and newer versions but the issue is recurring.

**Comment by MarkTimStafford** [comment]
I have the same issue ... it suddenly stopped working

**Comment by MarkTimStafford** [comment]
Email address and password connect fine in my MyVauxhall App ... so I think that they are correct!

Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_views.py", line 133, in connectPSA
res = firstLaunchConfig(app_name, email, password, countrycode)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 95, in firstLaunchConfig
psacc.connect(client_email, client_password)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 35, in connect
self.manager.init_with_user_credentials_realm(user, password, self.realm)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 26, in init_with_user_credentials_realm
self._token_request(self._grant_password_request_realm(login, password, realm), True)
File "/usr/local/lib/python3.9/dist-packages/oauth2_client/credentials_manager.py", line 205, in _token_request
CredentialManager._handle_bad_response(response)
File "/usr/local/lib/python3.9/dist-packages/oauth2_client/credentials_manager.py", line 87, in _handle_bad_response
raise OAuthError(HTTPStatus(response.status_code), error.get('error'), error.get('error_description'))
oauth2_client.credentials_manager.OAuthError: 400 - server_error : Internal Server Error
2023-11-25 15:44:28,547 :: INFO :: 172.30.32.1 - - [25/Nov/2023 15:44:28] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -

**Comment by variance95** [comment]
Same issue here.  Stopped working a few days ago for me.

**Comment by thewhale21** [comment]
Same here. Take it we're all older corsa owners? Wouldnt be supprised if vauxhall messed up the api login for older models :(

**Comment by PhilippCo** [comment]
My Opel Corsa is working again after the modification in the Python file

**Comment by thewhale21** [comment]
Think Opel uses a differnt API to vauxhall, even tho they're the "same"

**Comment by JaySea77** [comment]
Getting error: 400 - invalid_grant : The provided access grant is invalid, expired, or revoked.
In MyCitroën the credentials work.
The python change with odometer is done.
Car: Citroën ë-C4

**Comment by kenzot11** [comment]
Same issue here.

**Comment by fehondo** [comment]
Exactly same issue with my Corsa. Have never used this tool before but tried both with Windows and HA on Pi 4. The MyVauxhall app works but not this - even with the latest release.

**Comment by AndrewWalls** [comment]
My log data on 3.2.0. Definitely an issue with Vauxhall or Corsa E (2000) model.

`2023-11-26 13:23:42,182 :: INFO :: App version 3.2.0
2023-11-26 13:23:42,183 :: ERROR :: No config file
2023-11-26 13:23:42,188 :: WARNING :: Can't get language
2023-11-26 13:23:42,188 :: WARNING :: Can't get language
2023-11-26 13:23:44,031 :: INFO :: update_data
2023-11-26 13:23:44,205 :: INFO :: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2023-11-26 13:24:25,051 :: INFO :: 172.30.32.1 - - [26/Nov/2023 13:24:25] "[37mGET / HTTP/1.1[0m" 200 -
2023-11-26 13:24:25,144 :: INFO :: 172.30.32.1 - - [26/Nov/2023 13:24:25] "[37mGET /assets/99_custom_overides.css HTTP/1.1[0m" 200 -
2023-11-26 13:24:25,150 :: INFO :: 172.30.32.1 - - [26/Nov/2023 13:24:25] "[37mGET /assets/clientside.js HTTP/1.1[0m" 200 -
2023-11-26 13:24:25,352 :: INFO :: 172.30.32.1 - - [26/Nov/2023 13:24:25] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2023-11-26 13:24:25,357 :: INFO :: 172.30.32.1 - - [26/Nov/2023 13:24:25] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2023-11-26 13:24:25,463 :: INFO :: 172.30.32.1 - - [26/Nov/2023 13:24:25] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2023-11-26 13:24:25,551 :: INFO :: 172.30.32.1 - - [26/Nov/2023 13:24:25] "[37mGET /assets/images/settings.svg HTTP/1.1[0m" 200 -
2023-11-26 13:24:25,573 :: INFO :: 172.30.32.1 - - [26/Nov/2023 13:24:25] "[37mGET /config_login HTTP/1.1[0m" 200 -
2023-11-26 13:24:25,735 :: INFO :: 172.30.32.1 - - [26/Nov/2023 13:24:25] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2023-11-26 13:24:25,739 :: INFO :: 172.30.32.1 - - [26/Nov/2023 13:24:25] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2023-11-26 13:24:25,875 :: INFO :: 172.30.32.1 - - [26/Nov/2023 13:24:25] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2023-11-26 13:24:25,992 :: INFO :: 172.30.32.1 - - [26/Nov/2023 13:24:25] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2023-11-26 13:24:25,997 :: INFO :: 172.30.32.1 - - [26/Nov/2023 13:24:25] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 -
2023-11-26 13:24:26,003 :: INFO :: 172.30.32.1 - - [26/Nov/2023 13:24:26] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 -
2023-11-26 13:24:41,260 :: INFO :: Starting analysis on AndroidManifest.xml
2023-11-26 13:24:41,286 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2023-11-26 13:24:41,287 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2023-11-26 13:24:41,290 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2023-11-26 13:24:41,292 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2023-11-26 13:24:41,295 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2023-11-26 13:24:41,305 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2023-11-26 13:24:41,306 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2023-11-26 13:24:41,307 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2023-11-26 13:24:41,308 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2023-11-26 13:24:41,315 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2023-11-26 13:24:41,400 :: INFO :: APK file was successfully validated!
2023-11-26 13:24:41,402 :: WARNING :: Requested API level 33 is larger than maximum we have, returning API level 28 instead.
2023-11-26 13:24:44,513 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2023-11-26 13:24:44,515 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2023-11-26 13:24:44,520 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2023-11-26 13:24:44,529 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2023-11-26 13:24:44,536 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2023-11-26 13:24:44,546 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2023-11-26 13:24:44,549 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2023-11-26 13:24:44,553 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2023-11-26 13:24:44,554 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2023-11-26 13:24:44,557 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2023-11-26 13:24:44,563 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2023-11-26 13:24:48,460 :: ERROR :: 400 - server_error : Internal Server Error
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_views.py", line 133, in connectPSA
res = firstLaunchConfig(app_name, email, password, countrycode)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 95, in firstLaunchConfig
psacc.connect(client_email, client_password)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 35, in connect
self.manager.init_with_user_credentials_realm(user, password, self.realm)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 26, in init_with_user_credentials_realm
self._token_request(self._grant_password_request_realm(login, password, realm), True)
File "/usr/local/lib/python3.9/dist-packages/oauth2_client/credentials_manager.py", line 205, in _token_request
CredentialManager._handle_bad_response(response)
File "/usr/local/lib/python3.9/dist-packages/oauth2_client/credentials_manager.py", line 87, in _handle_bad_response
raise OAuthError(HTTPStatus(response.status_code), error.get('error'), error.get('error_description'))
oauth2_client.credentials_manager.OAuthError: 400 - server_error : Internal Server Error`

**Comment by MarkTimStafford** [comment]
Still a problem with v3.2.0

**Comment by PhilippCo** [comment]
Is there a difference between newer and older Corsa?
My Opel Corsa (11/2020) seems to work fine with v3.2.0
I'm using the docker setup, not a plugin in Home Assistant

**Comment by thewhale21** [comment]
Not sure, But vauxhall is only in the UK (as far as i know) and uses a seperate API than Opel.

**Comment by thewhale21** [comment]
Starting to think this may just be an issue with myvauxhall. 
![image](https://github.com/flobz/psa_car_controller/assets/25723228/7afc29db-bfdb-4b3c-9456-1ce56555a950)
Even if you loginto the myvauxhall site its pulling oAuth errors.

Just created an account with Opel and not getting any of the same errors on login.

**Comment by thewhale21** [comment]
So apperently the latest version is working for one Corsa E owner (Speek to the geek, youtube), So we're going to have to figure out what us lot have in common.

**Comment by bigcalm** [comment]
I am unable to connect to my Vauxhall Mokka-e with the same error.

I think that this issue might best be renamed to just `Error 400 - Server Error: Vauxhall`.

The My Vauxhall app is flaky when it comes to connecting with the car. The My Vauxhall website is even worse just trying to log in.

As much as I love my car, the app is possibly the biggest let down.

Anyway, I'm not here to complain about the app and service. Just to state that I think it's an issue with Vauxhall itself.

I wonder if Opel have the same issues.

Or other UK based brands in the PSA/Stellantis group.

**Comment by videojedi** [comment]
Same here, vauxhall corsa e, was working fine, but not any more. 400 internal server error. Home assistant running on x86

**Comment by MarkTimStafford** [comment]
So guys, ... and patience please, as I am a novice
I think that we all agree that this is a UK Vauxhall problem.
This occurs when people have to re-login to the PSA software following a reboot or re-initialisation which is why a lot of people don't have the problem
This is where I am at ... I have installed the program on a regular PC so that I can mess. I started the program with the debugger on so that I could track through and got the attached file (although password is blanked out) 
[trash.txt](https://github.com/flobz/psa_car_controller/files/13500227/trash.txt)
It seems as thought the username & password verification is fine, but it cannot generate a file cars.json 
I got a copy of my cars.json of a backup of HA and have attached it here (VID blanked out)
[cars.json](https://github.com/flobz/psa_car_controller/files/13500295/cars.json)
I need to find out where it gets this file and if I can overwrite the code somehow????
Any help, as I am only a novice programmer, would be greatly appreciated

**Comment by MarkTimStafford** [comment]
Just struggled to login to the MyVauxhall Login page ... but got in eventually

**Comment by thewhale21** [comment]
Not sure its even validating the credentials, Email is validated, but password is not, any password will also return 400 error

**Comment by MarkTimStafford** [comment]
Hi I am more than willing to pass my Username & Password details to @flobz if that would help diagnose the problem
It is a Vauxhall in the UK problem.

**Comment by MarkTimStafford** [comment]
> Just created an account with Opel and not getting any of the same errors on login.

@thewhale21 ... how did you do this. I am based in GB and going to My Opel insists on knocking me back to Vauxhall

**Comment by thewhale21** [comment]
> > Just created an account with Opel and not getting any of the same errors on login.
> 
> @thewhale21 ... how did you do this. I am based in GB and going to My Opel insists on knocking me back to Vauxhall

You'll need to do it with a new email address, but if you go to myopel.de for example it lets you register there. Admittedly you cant get it working correctly as the MyOpel app wonjt let you enter the VIN of a corsa. But you see the errors associated with not having a car registered to the account.

**Comment by macray76** [comment]
Same problem here on my Vauxhall Corsa-e.

I had to restore from a backup earlier today and that is when the 400 error started appearing.

**Comment by macray76** [comment]
Still not working for me. I've even uninstalled, reinstalled and rebooted my HA server but it is still showing the 400 error.

My password hasn't been changed so I know it is correct (I relogged in using the MyVauxhall app with the same details).

**Comment by robotfishe** [comment]
Seeing the same with my 2022 Mokka-e. I had to try about 6 times to sign in with the Vauxhall app, and even when it worked it was very slow, so maybe the Oauth is just timing out somewhere?

**Comment by MarkTimStafford** [comment]
> OK, my error 400 was my fault. I used the old password I used a while ago. Correct password and everything back to normal here.

Hiya ... I notice that you are driving a Peugeot in Germany (?), and I think that this problem may relate to the Vauxhall server for folk located in the UK (maybe ???) ... but well done in sorting your issues out.

**Comment by agbb** [comment]
Has anyone had any luck getting this working? If not I’d suggest we all email Vauxhall at customercare@vauxhall.co.uk and apply some pressure to get it fixed. I know it’s a long shot but it seems to be affecting the ability to connect to and 3rd party service which is a huge shame.

**Comment by videojedi** [comment]
Logging into my vauxhall on vauxhall.co.uk website does this...... 

<img width="553" alt="image" src="https://github.com/flobz/psa_car_controller/assets/7032506/1b4d6835-3d59-40a9-b523-085b3ec39e83">

**Comment by MarkTimStafford** [comment]
> Has anyone had any luck getting this working? If not I’d suggest we all email Vauxhall at [customercare@vauxhall.co.uk](mailto:customercare@vauxhall.co.uk) and apply some pressure to get it fixed. I know it’s a long shot but it seems to be affecting the ability to connect to and 3rd party service which is a huge shame.

I have always found the Customer Care Team to be unresponsive and I suspect that this is outside of their scope. I found the contact details of the IT Manager at Groupe PSA at Vauxhall Motors Ltd on LinkedIn and wrote him a friendly email requesting his help ... who knows what might happen?

**Comment by ujjbd16** [comment]
I have never been able to make this integration work. Always getting the 400 error. I have the 2022 Corsa E. I’m UK based as well.

**Comment by bbr111** [comment]
Same here

**Comment by btxluke** [comment]
+1 

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_views.py", line 133, in connectPSA
    res = firstLaunchConfig(app_name, email, password, countrycode)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 95, in firstLaunchConfig
    psacc.connect(client_email, client_password)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 35, in connect
    self.manager.init_with_user_credentials_realm(user, password, self.realm)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 26, in init_with_user_credentials_realm
    self._token_request(self._grant_password_request_realm(login, password, realm), True)
  File "/usr/local/lib/python3.9/dist-packages/oauth2_client/credentials_manager.py", line 205, in _token_request
    CredentialManager._handle_bad_response(response)
  File "/usr/local/lib/python3.9/dist-packages/oauth2_client/credentials_manager.py", line 87, in _handle_bad_response
    raise OAuthError(HTTPStatus(response.status_code), error.get('error'), error.get('error_description'))
oauth2_client.credentials_manager.OAuthError: 400  - server_error : Internal Server Error`

**Comment by Hobbit44** [comment]
Just trying to set this up on my 2021 Corsa E. It may be fixed. Just that the response structure has changed:

```
2024-01-19 21:46:50,589 :: ERROR :: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 50, in firstLaunchConfig
    token = res.json()["accessToken"]
KeyError: 'accessToken'
HOST_BRANDID : https://id-dcr.vauxhall.co.uk/mobile-services sitecode: VX_GB_ESP{"returnCode":"OK","token":"TOKEN"}
2024-01-19 21:46:50,589 :: ERROR :: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 50, in firstLaunchConfig
    token = res.json()["accessToken"]
KeyError: 'accessToken'
HOST_BRANDID : https://id-dcr.vauxhall.co.uk/mobile-services sitecode: VX_GB_ESP{"returnCode":"OK","token":"TOKEN"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 50, in firstLaunchConfig
    token = res.json()["accessToken"]
KeyError: 'accessToken'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_views.py", line 133, in connectPSA
    res = firstLaunchConfig(app_name, email, password, countrycode)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 59, in firstLaunchConfig
    raise ConnectionError(msg) from ex
ConnectionError: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 50, in firstLaunchConfig
    token = res.json()["accessToken"]
KeyError: 'accessToken'
HOST_BRANDID : https://id-dcr.vauxhall.co.uk/mobile-services sitecode: VX_GB_ESP{"returnCode":"OK","token":"TOKEN"}
```

**Comment by AndrewWalls** [comment]
The latest update gets me further, but then it asks for an element of a URL and I can't see where to get it in Vauxhall. Anyone had any luck?

**Comment by macray76** [comment]
Yes I have it back up and running. It was a little confusing at first but I used this guide to help:
https://github.com/flobz/psa_car_controller/discussions/779

And specifically for HomeAssistant:
https://github.com/flobz/psa_car_controller/discussions/779#discussioncomment-8601459

**Comment by bigcalm** [comment]
At last, through a combination of the latest release (v3.4.2) and updates to Vauxhall's services, I have been able to connect my 2022 Vauxhall Mokka E!

The web UI shows details about recent trips along with consumption data.

Good work everybody involved :)
