### ISSUE TITLE
Honk horn giving error

### ISSUE THREAD

**Issue by JaySea77** [flobz/psa_car_controller#688]
When trying the "new" horn command:
2023-11-26 13:11:22,450 :: INFO :: topic: psa/RemoteServices/from/cid/AC-ACNTxxxxxxx/Horn: {'nb_horn': 1, 'action': 'activate'}
2023-11-26 13:11:22,450 :: ERROR :: Exception on /horn/<vin>/1 [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 300, in horn
    return jsonify(APP.myp.remote_client.horn(vin, count))
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 213, in horn
    self.mqtt_client.publish(msg)
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 1243, in publish
    if topic is None or len(topic) == 0:
TypeError: object of type 'MQTTRequest' has no len()
2023-11-26 13:11:22,451 :: INFO :: 172.30.32.1 - - [26/Nov/2023 13:11:22] "GET /horn/<vin>/1 HTTP/1.1" 500 -

Is this error because my car doesn't support honking horn or what is happening here?
Car: Citroën ë-C4

When trying the "new" lock doors:
2023-11-26 13:31:31,027 :: INFO :: topic: psa/RemoteServices/from/cid/AC-ACNTxxxxxxx/Doors: {'action': 'lock'}
2023-11-26 13:31:31,028 :: INFO :: 172.30.32.1 - - [26/Nov/2023 13:31:31] "GET /lock_door/<vin>/1 HTTP/1.1" 200 -
2023-11-26 13:31:31,253 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AC-ACNTxxxxxxx/Doors b'{"resp_date":"2023-11-26T12:31:31Z","vin":"xxxxxx","correlation_id":"2881077f481d42209919da1edf020ce820231126123131027","return_code":"400","reason":"[authorization.denied.cvs.response.no.matching.service.key]"}'
2023-11-26 13:31:31,254 :: ERROR :: Can't refresh remote token 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 155, in _refresh_remote_token
    self.manager.refresh_token_now()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
    raise RateLimitException
psa_car_controller.common.utils.RateLimitException

This seems to be an issue with ratelimit, but how that could have triggered is a mystery.

**Comment by s1195523** [comment]
Do you have the ''remote control'' service (not to be confused with e-remote control) or ''connect plus'' service?

**Comment by papageigit** [comment]
Do the lights work? Do you have remote control or connect plus service? (not the same as e-remote control service)

**Comment by JaySea77** [comment]
I don't think there is a remote control service for Citroën

**Comment by papageigit** [comment]
It briefly used to be called remote control before they replaced it with connect plus.

**Comment by sod75** [comment]
Same for me ( Peugeot 3008)
I only have "e-remote control" , navigation and telemaintenace. nothing else available.

```
2023-11-26 15:24:44,588 :: INFO :: topic: psa/RemoteServices/from/cid/AP-ACNT200008553362/Horn: {'nb_horn': 2, 'action': 'activate'}
2023-11-26 15:24:44,589 :: ERROR :: Exception on /horn/VF3M4DGZUPSXXX/2 [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 300, in horn
    return jsonify(APP.myp.remote_client.horn(vin, count))
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 213, in horn
    self.mqtt_client.publish(msg)
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 1243, in publish
    if topic is None or len(topic) == 0:
TypeError: object of type 'MQTTRequest' has no len()
2023-11-26 15:24:44,589 :: ERROR :: Exception on /horn/VF3M4DGZUXXX/2 [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 300, in horn
    return jsonify(APP.myp.remote_client.horn(vin, count))
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 213, in horn
    self.mqtt_client.publish(msg)
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 1243, in publish
    if topic is None or len(topic) == 0:
TypeError: object of type 'MQTTRequest' has no len()
2023-11-26 15:24:44,692 :: INFO :: 172.18.0.1 - - [26/Nov/2023 15:24:44] "[35m[1mGET /horn/VF3M4DGZUXXX/2 HTTP/1.1[0m" 500 -
2023-11-26 15:24:44,803 :: INFO :: 172.18.0.1 - - [26/Nov/2023 15:24:44] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
```

**Comment by papageigit** [comment]
What are your regions? don't worry too much about the rate limit, I just reused the section of code from the wakeup view, I believe any error show up as rate limit issue currently which isn't optimal now that I think about it

**Comment by sod75** [comment]
>What are your regions?
BE

**Comment by JaySea77** [comment]
My region is NL

**Comment by papageigit** [comment]
I live in NL aswell, but for both regions and on the Citroen page aswell I see the connect plus service available. 

I'll create a pull request to add the information to the FAQ.

For anyone else looking here in the meantime: Please make sure you have either the old Remote Control service (not e-remote control) or the new Connect Plus service activated.

**Comment by sod75** [comment]
just as FYI, the lights and horn seem to handle the failing request more gracefully

`2023-11-26 21:07:56,374 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-ACNT200008553362/Lights b'{"resp_date":"2023-11-26T20:07:56Z","vin":"VF3M4DGZUPSxxx","correlation_id":"519b29d4730245558771e9211cd2b44b20231126200756116","return_code":"400","reason":"[authorization.denied.cvs.response.no.matching.service.key]"}'`

`2023-11-26 21:30:50,419 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-ACNT200008553362/Doors b'{"resp_date":"2023-11-26T20:30:50Z","vin":"VF3M4DGZUPxxxx","correlation_id":"20ae8377634e4fa9ae8007d2e549faff20231126203050183","return_code":"400","reason":"[authorization.denied.cvs.response.no.matching.service.key]"}'`

**Comment by JaySea77** [comment]
CN you please link me where I can subscribe to this connect plus function?

**Comment by papageigit** [comment]
https://services-store.peugeot.nl/store/connect-plus-meer-voordelen-voor-jou

**Comment by JaySea77** [comment]
That is for Peugeot. I found a page for the service for Citroen but it said my vin wasn't supported. Not sure if that was the right page though.

**Comment by JaySea77** [comment]
You have got to be kidding. Mine is from may 2023.

**Comment by papageigit** [comment]
Connect Plus is remote control, e-remote control and (partly) connected navigation all merged into one, so yes, all three options are in there.

**Comment by JaySea77** [comment]
So basically my car was produced a few days too early :(

**Comment by sod75** [comment]
>So basically my car was produced a few days too early :(

lol, mine is from May 22, 2023

**Comment by JaySea77** [comment]
Mine may 20th

**Comment by JaySea77** [comment]
Not an issue since the service is not available for me.
