### ISSUE TITLE
POST request fails

### ISSUE THREAD

**Issue by Alexciao** [flobz/psa_car_controller#689]
**Describe the bug**
PSA car controller does not work. All POST requests fail

**To Reproduce**
1. what command did you use: the web dashboard
2. when the bug append ?: when I opened the dashboard
3. Does it persist after restarting the program? : yes
4. Does it persist after recreate config by going to http://server_address:port/config? : yes

**Config file**
Give the anonymize content of the config file
```
 {
    "abrp": {
        "abrp_enable_vin": [],
        "token": ""
    },
    "client_id": "xxxxxx",
    "client_secret": "xxxxxx",
    "co2_signal_api": null,
    "country_code": "IT",
    "customer_id": "AP-xxxxxx",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2CPeugeot",
    "refresh_token": "f8b32fff-72f0-469e-a70b-f8854f93c88b",
    "remote_refresh_token": "f6a5ce79-77ad-4288-b725-9487c6453a77",
    "weather_api": null
}
```

**Environment (please complete the following information):**
 - OS: [e.g. Windows]: Ubuntu 22.04
 - Brand and model of car: Peugeot e2008
 - Application version (commit number, branch or tag): 38ce80f
 - Log from http://server_address:port/log and browser console log
 ```
2023-11-26 16:08:18,426 :: ERROR :: Exception on /get_vehicleinfo/(VIN anonymized) [GET]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 179, in get_vehicle_info
response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'PSACarController' object has no attribute 'myp'
2023-11-26 16:08:18,426 :: ERROR :: Exception on /get_vehicleinfo/(VIN anonymized) [GET]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 179, in get_vehicle_info
response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'PSACarController' object has no attribute 'myp'
2023-11-26 16:08:18,430 :: INFO :: 192.168.1.50 - - [26/Nov/2023 16:08:18] "[35m[1mGET /get_vehicleinfo/(VIN anonymized)?from_cache=1 HTTP/1.1[0m" 500 -
2023-11-26 16:08:18,432 :: INFO :: <Request 'http://192.168.1.50:5000/charge_control?vin=(VIN anonymized)&%3Falways_check=true' [GET]>
```

**Additional context**
I really need to use PSA car controller, but it just stopped working randomly.

**Comment by Alexciao** [comment]
@flobz Really sorry for the ping, this is urgent though, if you have the ability to fix it please do
