### ISSUE TITLE
Error connecting - Any idea?

### ISSUE THREAD

**Issue by Abuelika** [flobz/psa_car_controller#69]
***************# python3 app_decoder.py /srv/psa_car_controller/mypeugeot-1-28.apk
APK loading...
Requested API level 29 is larger than maximum we have, returning API level 28 instead.
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
APK loaded !
MyPeugeot email: ***********************************
MyPeugeot password: **********************
What is your country code ? (ex: FR, GB, DE, ES...)
ES
Traceback (most recent call last):
  File "/srv/psa_car_controller/MyPSACC.py", line 224, in get_vehicles
    res = self.api().get_vehicles_by_device()
  File "/srv/psa_car_controller/psa_connectedcar/api/vehicles_api.py", line 1331, in get_vehicles_by_device
    (data) = self.get_vehicles_by_device_with_http_info(**kwargs)  # noqa: E501
  File "/srv/psa_car_controller/psa_connectedcar/api/vehicles_api.py", line 1414, in get_vehicles_by_device_with_http_info
    collection_formats=collection_formats)
  File "/srv/psa_car_controller/MyPSACC.py", line 118, in call_api
    raise e
  File "/srv/psa_car_controller/MyPSACC.py", line 105, in call_api
    _preload_content, _request_timeout)
  File "/srv/psa_car_controller/psa_connectedcar/api_client.py", line 161, in __call_api
    _request_timeout=_request_timeout)
  File "/srv/psa_car_controller/psa_connectedcar/api_client.py", line 351, in request
    headers=headers)
  File "/srv/psa_car_controller/psa_connectedcar/rest.py", line 238, in GET
    query_params=query_params)
  File "/srv/psa_car_controller/psa_connectedcar/rest.py", line 228, in request
    raise ApiException(http_resp=r)
psa_connectedcar.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'X-Backside-Transport': 'FAIL FAIL', 'Connection': 'close', 'Cache-Control': 'no-store, no-cache, must-revalidate, private', 'Content-Type': 'application/hal+json', 'Date': 'Sun, 04 Apr 2021 09:45:58 GMT', 'Expires': '0', 'X-Global-Transaction-ID': '945fb68f60698ad6edbd09ed', 'Access-Control-Expose-Headers': 'APIm-Debug-Trans-Id, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-Global-Transaction-ID', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET', 'Set-Cookie': 'rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Sat, 03-Apr-2021 09:45:58 GMT, JSESSIONID=s0cFHdUDMu5zJp2FD8TVzynASSBuGKjdWBsdydJd; path=/, PSACountry=ES;Domain=.groupe-psa.com;Path=/'})
HTTP response body: {"uuid":"8aea73f7-cbd5-4874-9832-f770d61f243b","code":40410,"message":"No vehicule found"}

Traceback (most recent call last):
  File "app_decoder.py", line 153, in <module>
    if car.label == "unknown":
AttributeError: 'NoneType' object has no attribute 'label'

**Comment by CalicodesIles** [comment]
Hello. Could you please confirm which car model you are using ?

**Comment by Abuelika** [comment]
New Peugeot 208

**Comment by flobz** [comment]
Close as it doesn't follow the bug template
