### ISSUE TITLE
HTTPSConnectionPool

### ISSUE THREAD

**Issue by stealthhack** [flobz/psa_car_controller#699]
Hi guys, i have a issue from the last update, can't connect the car even if i have every port opened for the addon. 

**To Reproduce**
 **Here is the Log file from PSA Car Controller:**

 rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 191, in get_vehicle_info
    response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'PSACarController' object has no attribute 'myp'
2023-12-03 19:07:31,449 :: INFO :: 172.30.32.1 - - [03/Dec/2023 19:07:31] "[35m[1mGET /get_vehicleinfo/VR3UHZKXZKT119442?from_cache=1 HTTP/1.1[0m" 500 -
2023-12-03 19:07:31,465 :: INFO :: <Request 'http://localhost:5000/charge_control?vin=VR3UHZKXZKT119442&%3Falways_check=true' [GET]>
2023-12-03 19:07:31,472 :: ERROR :: Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 260, in get_charge_control
    charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'
2023-12-03 19:07:31,479 :: INFO :: 172.30.32.1 - - [03/Dec/2023 19:07:31] "[35m[1mGET /charge_control?vin=VR3UHZKXZKT119442&?always_check=true HTTP/1.1[0m" 500 -
2023-12-03 19:08:31,450 :: INFO :: <Request 'http://localhost:5000/charge_control?vin=VR3UHZKXZKT119442&%3Falways_check=true' [GET]>
2023-12-03 19:08:31,452 :: ERROR :: Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 260, in get_charge_control
    charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'
2023-12-03 19:08:31,456 :: INFO :: 172.30.32.1 - - [03/Dec/2023 19:08:31] "[35m[1mGET /charge_control?vin=VR3UHZKXZKT119442&?always_check=true HTTP/1.1[0m" 500 -
2023-12-03 19:08:31,470 :: ERROR :: Exception on /get_vehicleinfo/VR3UHZKXZKT119442 [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 191, in get_vehicle_info
    response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'PSACarController' object has no attribute 'myp'
2023-12-03 19:08:31,473 :: INFO :: 172.30.32.1 - - [03/Dec/2023 19:08:31] "[35m[1mGET /get_vehicleinfo/VR3UHZKXZKT119442?from_cache=1 HTTP/1.1[0m" 500 -
2023-12-03 19:09:31,451 :: INFO :: <Request 'http://localhost:5000/charge_control?vin=VR3UHZKXZKT119442&%3Falways_check=true' [GET]>
2023-12-03 19:09:31,454 :: ERROR :: Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 260, in get_charge_control
    charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'
2023-12-03 19:09:31,458 :: INFO :: 172.30.32.1 - - [03/Dec/2023 19:09:31] "[35m[1mGET /charge_control?vin=VR3UHZKXZKT119442&?always_check=true HTTP/1.1[0m" 500 -
2023-12-03 19:09:31,466 :: ERROR :: Exception on /get_vehicleinfo/VR3UHZKXZKT119442 [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 191, in get_vehicle_info
    response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
AttributeError: 'PSACarController' object has no attribute 'myp'
2023-12-03 19:09:31,469 :: INFO :: 172.30.32.1 - - [03/Dec/2023 19:09:31] "[35m[1mGET /get_vehicleinfo/VR3UHZKXZKT119442?from_cache=1 HTTP/1.1[0m" 500 
![Untitled](https://github.com/flobz/psa_car_controller/assets/28345419/fbeecbe5-c04e-43ce-8605-8ddc1289ded1)

Environment:

OS: HAOS
core-2023.11.3
supervisor-2023.11.6
PSA Car Controller: v3.2.0
Car: Peugeot e208

**Comment by flobz** [comment]
not a PSACC issue you have issue to access to github.
