### ISSUE TITLE
"The add-on seems to not be ready" - No data / loading in home assistant 

### ISSUE THREAD

**Issue by Lawdie** [flobz/psa_car_controller#711]
Since Friday all values reported from the controller have been unavailable in home assistant.

Attempting to access the web interface from the HA app gives the error "The add-on seems to not be ready, it might still be starting. Do you want to try again?"

Trying to access the app direct has nothing loading 

**To Reproduce**
1. what command did you use
No commands just stopped working
3. when the bug append ?
Friday 15th was last known good
5. Does it persist after restarting the program? 
Persists after HA reboot / addon reboot
7. Does it persist after recreate config by going to http://server_address:port/config? 
Unable to access webpage

**Config file**
Give the anonymize content of the config file
Please advise where I can find this in the home assistant version

**Environment (please complete the following information):**
 - OS: HomeAssistant
 - Vauxhall Corsa E
 - Application version (commit number, branch or tag)
v3.2.0
 - Log from http://server_address:port/log and browser console log
No logs from app since it doesn't load

HomeAssistant log
Containerised psa_car_controller loading...
2023-12-17 16:23:29,936 :: INFO :: App version 3.2.0
2023-12-17 16:23:30,990 :: INFO :: ["{'vin': 'MYVIN', 'vehicle_id': 'VECHID', 'label': 'corsa-e', 'brand': 'C', 'abrp_name': 'opel:corsae:20:50', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
2023-12-17 16:23:31,601 :: INFO :: save config change
2023-12-17 16:23:31,738 :: INFO :: ask wakeup to MYVIN
2023-12-17 16:23:31,738 :: INFO :: topic: psa/RemoteServices/from/cid/OV-ACNTNUM/VehCharge/state: {'action': 'state'}
2023-12-17 16:23:31,848 :: INFO :: Connected with result code {'session present': 0}
2023-12-17 16:23:31,848 :: INFO :: subscribe to psa/RemoteServices/to/cid/OV-ACNTNUM/#
2023-12-17 16:23:31,848 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/MYVIN
2023-12-17 16:23:32,043 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-ACNTNUM/VehCharge/state/ProcessManagement b'{"process_date":"2023-12-17T16:23:32Z","vin":"MYVIN","correlation_id":"CORRID","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2023-12-17 16:23:32,202 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-ACNTNUM/VehCharge/state/ProcessManagement b'{"process_date":"2023-12-17T16:23:32Z","vin":"MYVIN","correlation_id":"CORRID","process_code":"901","process_message":"[process.901.vehicle.asleep.key]"}'
2023-12-17 16:23:56,685 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-ACNTNUM/VehCharge/state/ProcessManagement b'{"process_date":"2023-12-17T16:23:56Z","vin":"MYVIN","correlation_id":"CORRID","process_code":"903","process_message":"[process.903.request.forwarded.to.vehicle.key]"}'
2023-12-17 16:23:57,813 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-ACNTNUM/VehCharge/state b'{"resp_date":"2023-12-17T16:23:57Z","vin":"MYVIN","correlation_id":"CORRID","return_code":"0"}'

2023-12-17 15:14:38.209 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://127.0.0.1:5000/charge_control?vin=MYVIN failed with Server disconnected without sending a response.
2023-12-17 15:14:38.209 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://127.0.0.1:5000/get_vehicleinfo/MYVIN failed with Server disconnected without sending a response.
2023-12-17 15:17:38.213 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://127.0.0.1:5000/charge_control?vin=MYVIN failed with All connection attempts failed
2023-12-17 15:17:38.213 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: http://127.0.0.1:5000/get_vehicleinfo/MYVIN failed with All connection attempts failed

**Additional context**

**Comment by Schalmeier** [comment]
Pretty much exactly the same for me. 
Any news?

**Comment by Schalmeier** [comment]
Updated my Home Assistant to the newest version. After 6 hours the addon just started working again :)

**Comment by Lawdie** [comment]
> Updated my Home Assistant to the newest version. After 6 hours the addon just started working again :)

I'll have a look and see but when I raised the issue I made sure to upgrade everything.

One thing I noticed was if I drive the car the addon seems to work for a period of time (aka it detects the changes) and then breaks the day after if it's not driven

**Comment by Lawdie** [comment]
Just done a reinstall to see if it would fix it but now I get hammed with Error 400 when trying to login same as https://github.com/flobz/psa_car_controller/issues/686 (same model of car as well) 

I wonder if this HA error is somehow related to overall apparent brokenness with Vauxhall 

```
2024-01-08 00:15:28,343 :: ERROR :: 400  - server_error : Internal Server Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_views.py", line 133, in connectPSA
    res = firstLaunchConfig(app_name, email, password, countrycode)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 95, in firstLaunchConfig
    psacc.connect(client_email, client_password)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 35, in connect
    self.manager.init_with_user_credentials_realm(user, password, self.realm)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 26, in init_with_user_credentials_realm
    self._token_request(self._grant_password_request_realm(login, password, realm), True)
  File "/usr/local/lib/python3.9/dist-packages/oauth2_client/credentials_manager.py", line 205, in _token_request
    CredentialManager._handle_bad_response(response)
  File "/usr/local/lib/python3.9/dist-packages/oauth2_client/credentials_manager.py", line 87, in _handle_bad_response
    raise OAuthError(HTTPStatus(response.status_code), error.get('error'), error.get('error_description'))
oauth2_client.credentials_manager.OAuthError: 400  - server_error : Internal Server Error
```

**Comment by wormvortex** [comment]
This has just started happening today on mine.....

**Comment by boab21mac** [comment]
Getting this error was working perfectly until last night. 

![image](https://github.com/flobz/psa_car_controller/assets/120062210/f1800e33-be93-41de-84e4-c41325f5b9a8)

**Comment by sod75** [comment]
same for me; looks like our token expired and we now are hit by  : [Error 400](https://github.com/flobz/psa_car_controller/issues/733)


```
2024-02-18 02:44:33,473 :: ERROR :: refresh_vehicle_info:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 76, in call_api
    return self._ApiClient__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 157, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 347, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/rest.py", line 234, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/rest.py", line 228, in request
    raise ApiException(http_resp=r)
psa_car_controller.psa.connected_car_api.rest.ApiException: (401)
Reason: **Unauthorized**
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Client-IP': '10.xxxxxxxxxx', 'X-Global-Transaction-ID': '3248667965d161014ffxxx', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'WWW-Authenticate': "Bearer error=**'invalid_token**'", 'Date': 'Sun, 18 Feb 2024 01:44:33 GMT', 'Connection': 'close', 'Set-Cookie': 'PSACountry=BE; Domain=.groupe-psa.com; Path=/', 'Vary': 'Accept-Encoding'})
HTTP response body: {"httpCode":"401","httpMessage":"Unauthorized","moreInformation":"Cannot pass the security checks that are required by the target API or operation, Enable debug headers for more details."}
```

**Comment by Lawdie** [comment]
Fixed in latest update
