### ISSUE TITLE
not able to login on a fresh install

### ISSUE THREAD

**Issue by wjansenw** [flobz/psa_car_controller#724]
**Describe the bug**
Can't login since yesterday. Used to work perfect.

**To Reproduce**
1. what command did you use
Trying to login with my peugeot userid and password.
2. when the bug happened ?
I am now running a clear install using docker, both with current and previous version of the container. 
3. Does it persist after restarting the program? 
Yes - also after fresh installation.
7. Does it persist after recreate config by going to http://server_address:port/config? 
Yes

**Config file**
Does not get created.

**Environment (please complete the following information):**
 - OS: docker
 - Brand and model of car: Peugeot 3008 hybrid
 - Application version (commit number, branch or tag): latest and previous docker 
 - Log from http://server_address:port/log and browser console log

**Additional context**

```
2024-01-10 12:59:41,807 :: INFO :: App version 3.2.0  <<< but I do get the same on 3.3.1
2024-01-10 12:59:41,808 :: ERROR :: No config file
2024-01-10 12:59:41,816 :: WARNING :: Can't get language
2024-01-10 12:59:41,816 :: WARNING :: Can't get language
2024-01-10 12:59:44,073 :: INFO :: update_data
2024-01-10 12:59:44,235 :: INFO ::  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2024-01-10 13:00:14,786 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:00:14] "[37mGET /config_login HTTP/1.1[0m" 200 -
2024-01-10 13:00:15,189 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:00:15] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-01-10 13:00:15,534 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:00:15] "[37mGET /_favicon.ico?v=2.14.1 HTTP/1.1[0m" 200 -
2024-01-10 13:00:16,413 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:00:16] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2024-01-10 13:00:25,735 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:00:25] "[37mGET / HTTP/1.1[0m" 200 -
2024-01-10 13:00:26,033 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:00:26] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2024-01-10 13:00:26,040 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:00:26] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-01-10 13:00:26,127 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:00:26] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-01-10 13:01:26,379 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:26] "[37mGET / HTTP/1.1[0m" 200 -
2024-01-10 13:01:26,907 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:26] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-01-10 13:01:26,919 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:26] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2024-01-10 13:01:26,937 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:26] "[37mGET /_favicon.ico?v=2.14.1 HTTP/1.1[0m" 200 -
2024-01-10 13:01:27,119 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:27] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-01-10 13:01:44,417 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:44] "[37mGET / HTTP/1.1[0m" 200 -
2024-01-10 13:01:44,430 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:44] "[37mGET /config_login HTTP/1.1[0m" 200 -
2024-01-10 13:01:44,526 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:44] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-01-10 13:01:44,560 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:44] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2024-01-10 13:01:44,563 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:44] "[37mGET /_favicon.ico?v=2.14.1 HTTP/1.1[0m" 200 -
2024-01-10 13:01:44,635 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:44] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-01-10 13:01:44,712 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:44] "[37mGET /config_login HTTP/1.1[0m" 200 -
2024-01-10 13:01:44,811 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:44] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-01-10 13:01:44,837 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:44] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2024-01-10 13:01:44,933 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:44] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-01-10 13:01:45,044 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:45] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-01-10 13:01:45,060 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:45] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 -
2024-01-10 13:01:45,062 :: INFO :: 172.21.0.1 - - [10/Jan/2024 13:01:45] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 -
2024-01-10 13:02:23,492 :: INFO :: Starting analysis on AndroidManifest.xml
2024-01-10 13:02:23,518 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-10 13:02:23,519 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-10 13:02:23,521 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-10 13:02:23,522 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-10 13:02:23,524 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-10 13:02:23,532 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-10 13:02:23,533 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-10 13:02:23,534 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-10 13:02:23,535 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-10 13:02:23,540 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-10 13:02:23,606 :: INFO :: APK file was successfully validated!
2024-01-10 13:02:23,610 :: WARNING :: Requested API level 33 is larger than maximum we have, returning API level 28 instead.
2024-01-10 13:02:29,633 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-10 13:02:37,166 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-10 13:02:37,170 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-10 13:02:37,177 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-10 13:02:37,183 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-10 13:02:37,189 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-10 13:02:37,192 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-10 13:02:37,194 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-10 13:02:37,195 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-10 13:02:37,197 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-10 13:02:37,202 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-10 13:03:07,243 :: ERROR :: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 50, in firstLaunchConfig
    token = res.json()["accessToken"]
KeyError: 'accessToken'

HOST_BRANDID : https://id-dcr.peugeot.com/mobile-services sitecode: AP_BE_ESP{"session":"REDACTED","returnCode":"NEED_AUTHORIZATION","token":"REDACTED"}
2024-01-10 13:03:07,250 :: ERROR :: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 50, in firstLaunchConfig
    token = res.json()["accessToken"]
KeyError: 'accessToken'

HOST_BRANDID : https://id-dcr.peugeot.com/mobile-services sitecode: AP_BE_ESP{"session":"REDACTED","returnCode":"NEED_AUTHORIZATION","token":"REDACTED"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 50, in firstLaunchConfig
    token = res.json()["accessToken"]
KeyError: 'accessToken'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_views.py", line 133, in connectPSA
    res = firstLaunchConfig(app_name, email, password, countrycode)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 59, in firstLaunchConfig
    raise ConnectionError(msg) from ex
ConnectionError: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 50, in firstLaunchConfig
    token = res.json()["accessToken"]
KeyError: 'accessToken'

HOST_BRANDID : https://id-dcr.peugeot.com/mobile-services sitecode: AP_BE_ESP{"session":"REDACTED","returnCode":"NEED_AUTHORIZATION","token":"REDACTED"}

```

**Comment by youradds** [comment]
They seem to be doing work on My Vauxhall ATM:

https://my.vauxhall.co.uk/maintenance.html

Not sure if that's any part of it. I still can't log in since the end of November. Keep getting an "internal server error" went trying to authorize (even though the values are correct). Seems like everyone is having the same issue though, so not sure why its not being looked at :(

**Comment by wjansenw** [comment]
> Seems like everyone is having the same issue though, so not sure why its not being looked at :(

Everyone spends his free time how they want, right? That is a bit the downside of opensource.

**Comment by youradds** [comment]
Unfortunatly, yes. If I knew more about the inners and how the coding worked, I would be looking at it myself. Its funny how when you have a tool you get used to it, and then when it doesn't work, you realise how much you relied on it :/

**Comment by mitasa** [comment]
Problems also here, not able to login, config terminates in 400 - server_error : Internal Server Error. When looking at opel.fi and MyOpel, it ends up in similar maintenance page as the UK Vauxhall site. Has been like that since this morning. Hope it comes back soon.

**Comment by wjansenw** [comment]
Error 400 seems to be something different, as my error clearly gives other messages.

Tried to debug a bit:

https://github.com/flobz/psa_car_controller/blob/4d93f96837e3ec9c317c9ceb93b823799d815d49/psa_car_controller/psa/setup/app_decoder.py#L50

accessToken is not present in the response (which was clear from the error message). Token is present:

`{'session': 'redacted', 'returnCode': 'NEED_AUTHORIZATION', 'token': 'redacted'}`

When changing the code to use token, code goes to the next stage, but gets the following result on this line:
https://github.com/flobz/psa_car_controller/blob/4d93f96837e3ec9c317c9ceb93b823799d815d49/psa_car_controller/psa/setup/app_decoder.py#L61-L79

`{'success': {'language': 'fr', 'country': 'BE', 'profile': {'email': ''}, 'dealers': {}, 'vehicles': [], 'settings_update': 1703849919, 'terms_service': {'cguForValidation': '299', 'lastCguAlreadyValidated': '299'}, 'early_adopter': [], 'service_state': [], 'cgu_validation': False}}`

This does not have the "id" being referenced in the next step, so it gives another error.

**Comment by mattirantakomi** [comment]
Are you able to login to My Peugeot through website? For me it doesn't work either.

**Comment by wjansenw** [comment]
I can - but only on the French it seems (took FR, as I saw somewhere in the logs a reference to FR).

So I switched country from BE to FR, and made progress. Got an accesToken, managed to configure OTP. 
Logged in now, but not getting any data (yet). It successfully got the VIN of my car.

**Comment by wjansenw** [comment]
![image](https://github.com/flobz/psa_car_controller/assets/25421739/8e7edb14-3d76-42de-9bc7-3db262f27854)

And I received data...

So my solution/work-around to this issue is logging in with country code FR.

**Comment by BrunoN17** [comment]
PT is not working. I've tried FR / BE / FI with no luck :(

**Comment by wjansenw** [comment]
Do you get the same error? If not I'll close this issue.

**Comment by BrunoN17** [comment]
@wjansenw You can close it

**Comment by Matssa56** [comment]
Damn changed from my pi4 to a NUC and I need to reconfigure and also got 400 Internal Server Error. However https://my.opel.fr/ goes to Maintenance so might be the reason. Tried to use BE but got another type of error so gonna wait a bit.

**Comment by videojedi** [comment]
I did exactly this a month ago. Pi4 to a PC. Same issue ever since. Internal server 400 error.
