### ISSUE TITLE
charge_control NOT working

### ISSUE THREAD

**Issue by Destroyer061090** [flobz/psa_car_controller#726]
after last update i have resetup the carcontroller.. main part are working but not the part related charge_control

System used:
Core 2024.1.2
Supervisor 2023.12.1

Home assistant configuration which before it was working:
rest:
  # ===============================================================
  # PSA Rest Entities
  - resource: "http://MYIP:MYPORT/charge_control?vin=MYVIN&?always_check=true"
    scan_interval: 60
    sensor:
      - name: "PSA Charge Control"
        unique_id: psa_charge_control
        value_template: "OK"
        json_attributes:
          - _next_stop_hour
          - percentage_threshold

template:
  - sensor:
      - name: "PSA Next Stop Time"
        unique_id: psa_stop_hour
        state: >-
          {{ state_attr('sensor.psa_charge_control','_next_stop_hour') }}

      - name: "PSA Charge Threshold"
        unique_id: psa_charge_threshold
        state: >-
          {{ state_attr('sensor.psa_charge_control','percentage_threshold') }}
        unit_of_measurement: "%"
        state_class: measurement

this is the log:
2024-01-10 16:19:15,071 :: INFO :: <Request 'http://MYIP:MYPORT/charge_control?vin=MYVIN&%3Falways_check=true' [GET]>
2024-01-10 16:19:15,080 :: ERROR :: Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/api.py", line 109, in get_charge_control
    charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'
2024-01-10 16:19:15,087 :: INFO :: 192.168.1.101 - - [10/Jan/2024 16:19:15] "GET /charge_control?vin=MYVIN&?always_check=true HTTP/1.1" 500 -
2024-01-10 16:20:13,833 :: INFO :: 192.168.1.101 - - [10/Jan/2024 16:20:13] "GET /get_vehicleinfo/MYVIN?from_cache=1 HTTP/1.1" 200 -
2024-01-10 16:20:15,089 :: INFO :: <Request 'http://MYIP:MYPORT/charge_control?vin=MYVIN&%3Falways_check=true' [GET]>
2024-01-10 16:20:15,092 :: ERROR :: Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/api.py", line 109, in get_charge_control
    charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'

**Comment by posixx** [comment]
Same here!

**Comment by posixx** [comment]
Tnx! could you also update the psacc-ha version number so the new release will become available for home assistant?

**Comment by Destroyer061090** [comment]
Thankx flobz. I have updated the continer and now on log i have only the error "charge_control not setup check your PSACC configuration and log"... but now is not clear why is not working...  is the above setting correct? maybe that's the issues?
