### ISSUE TITLE
No new trip/charge info after upgrade to 3.3.1

### ISSUE THREAD

**Issue by nicknol** [flobz/psa_car_controller#729]
After I upgraded the add-on to version 3.3.1 there are no new charges or trips recorded. The older ones are still existing and shown.
The information in the control tab are updated properly (SOC, mileage), which means the connection to the PSA servers works, or?

**Comment by flobz** [comment]
Close as it doesn't follow the bug template

**Comment by nicknol** [comment]
ok, I will try to rephrase

**Comment by nicknol** [comment]
@flobz  I hope it's better now

**Describe the bug**
no new charges or trips recorded. The older ones are still existing and shown.
The information in the control tab are updated properly (SOC, mileage), which means the connection to the PSA servers works.

**To Reproduce**
Steps to reproduce the behavior:
1. what command did you use
I opened the page  `http://homeassistant:8123/hassio/ingress/b9f12d83_psacc` in my browser
There I looked at the tabs 'Charge' and 'Trips' and there is no new data show
2. when the bug append ?
since I upgraded to version 3.3.1
3. Does it persist after restarting the program? 
yes, neither restarting the add-on nor homeassistant changed the behaviour.
4. Does it persist after recreate config by going to http://server_address:port/config? 
I don't know how to do this in particular. But I re-created my user-config and OTP-config.

**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
Version | core-2024.1.3
Installationstyp | Home Assistant OS
Entwicklung | false
Supervisor | true
Docker | true
Benutzer | root
Virtuelle Umgebung | false
Python-Version | 3.11.6
Betriebssystemfamilie | Linux
Betriebssystem-Version | 6.1.71-haos
CPU-Architektur | x86_64
Zeitzone | Europe/Berlin
Konfigurationsverzeichnis | /config

 - Brand and model of car
 Citroen ec4
 - Application version (commit number, branch or tag)
 3.3.1
 - Log from http://server_address:port/log and browser console log
```
2024-01-14 11:22:38,756 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:22:38] "GET /charge_control?vin=<myVIN>&?always_check=true HTTP/1.1" 500 -
2024-01-14 11:23:38,753 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:23:38] "GET /get_vehicleinfo/<myVIN>?from_cache=1 HTTP/1.1" 200 -
2024-01-14 11:23:38,755 :: INFO :: <Request 'http://172.30.32.1:5000/charge_control?vin=<myVIN>&%3Falways_check=true' [GET]>
2024-01-14 11:23:38,756 :: ERROR :: Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/api.py", line 109, in get_charge_control
    charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'
2024-01-14 11:23:38,756 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:23:38] "GET /charge_control?vin=<myVIN>&?always_check=true HTTP/1.1" 500 -
2024-01-14 11:24:38,752 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:24:38] "GET /get_vehicleinfo/<myVIN>?from_cache=1 HTTP/1.1" 200 -
2024-01-14 11:24:38,753 :: INFO :: <Request 'http://172.30.32.1:5000/charge_control?vin=<myVIN>&%3Falways_check=true' [GET]>
2024-01-14 11:24:38,754 :: ERROR :: Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/api.py", line 109, in get_charge_control
    charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'
2024-01-14 11:24:38,755 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:24:38] "GET /charge_control?vin=<myVIN>&?always_check=true HTTP/1.1" 500 -
2024-01-14 11:25:38,756 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:25:38] "GET /get_vehicleinfo/<myVIN>?from_cache=1 HTTP/1.1" 200 -
2024-01-14 11:25:38,757 :: INFO :: <Request 'http://172.30.32.1:5000/charge_control?vin=<myVIN>&%3Falways_check=true' [GET]>
2024-01-14 11:25:38,758 :: ERROR :: Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/api.py", line 109, in get_charge_control
    charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'
2024-01-14 11:25:38,759 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:25:38] "GET /charge_control?vin=<myVIN>&?always_check=true HTTP/1.1" 500 -
2024-01-14 11:26:21,572 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:21] "GET / HTTP/1.1" 200 -
2024-01-14 11:26:21,690 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:21] "GET /assets/clientside.js?m=1704703293.0 HTTP/1.1" 200 -
2024-01-14 11:26:22,239 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:22] "GET /_dash-layout HTTP/1.1" 200 -
2024-01-14 11:26:22,241 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:22] "GET /_dash-dependencies HTTP/1.1" 200 -
2024-01-14 11:26:22,314 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:22] "POST /_dash-update-component HTTP/1.1" 200 -
2024-01-14 11:26:22,370 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:22] "GET /assets/images/settings.svg HTTP/1.1" 200 -
2024-01-14 11:26:22,379 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:22] "GET /assets/images/consumption.svg HTTP/1.1" 200 -
2024-01-14 11:26:22,400 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:22] "GET /assets/images/pollution.svg HTTP/1.1" 200 -
2024-01-14 11:26:22,402 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:22] "GET /assets/images/battery-charge-line.svg HTTP/1.1" 200 -
2024-01-14 11:26:22,408 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:22] "GET /assets/images/electricity%20bill.svg HTTP/1.1" 200 -
2024-01-14 11:26:22,450 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:22] "GET /control?header=false HTTP/1.1" 200 -
2024-01-14 11:26:22,633 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:22] "GET /assets/clientside.js?m=1704703293.0 HTTP/1.1" 200 -
2024-01-14 11:26:22,878 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:22] "GET /_dash-layout HTTP/1.1" 200 -
2024-01-14 11:26:22,880 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:22] "GET /_dash-dependencies HTTP/1.1" 200 -
2024-01-14 11:26:22,936 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:22] "POST /_dash-update-component HTTP/1.1" 200 -
2024-01-14 11:26:22,980 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:22] "GET /assets/images/sync.svg HTTP/1.1" 200 -
2024-01-14 11:26:23,006 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:23] "GET /assets/images/battery-charge.svg HTTP/1.1" 200 -
2024-01-14 11:26:23,011 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:23] "GET /assets/images/battery-soh.svg HTTP/1.1" 200 -
2024-01-14 11:26:23,014 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:23] "GET /assets/images/mileage.svg HTTP/1.1" 200 -
2024-01-14 11:26:38,759 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:38] "GET /get_vehicleinfo/<myVIN>?from_cache=1 HTTP/1.1" 200 -
2024-01-14 11:26:38,761 :: INFO :: <Request 'http://172.30.32.1:5000/charge_control?vin=<myVIN>&%3Falways_check=true' [GET]>
2024-01-14 11:26:38,761 :: ERROR :: Exception on /charge_control [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/api.py", line 109, in get_charge_control
    charge_control = APP.chc.get(vin)
AttributeError: 'PSACarController' object has no attribute 'chc'
2024-01-14 11:26:38,763 :: INFO :: 172.30.32.1 - - [14/Jan/2024 11:26:38] "GET /charge_control?vin=<myVIN>&?always_check=true HTTP/1.1" 500 -
```
**Additional context**
Add any other context about the problem here.
