### ISSUE TITLE
Configuration non work properly

### ISSUE THREAD

**Issue by Destroyer061090** [flobz/psa_car_controller#735]
**Describe the bug**
I have disintalled and reinstalled PSA Car Controller for having last version. I have properly perform the configuration result with success result from system but no data shown. I can access to the web page but seems no data get from PSA.

**Config file**
Give the anonymize content of the config file

**Environment (please complete the following information):**
 - OS: Synology docker (installed from HA)
 - Brand and model of car: Peogeout
 - Application version (commit number, branch or tag): 3.3.2
 - Log from http://server_address:port/log and browser console log
```
2024-01-19 09:01:17,977 :: ERROR :: Error during activation: {'newversion': None, 'newversionurl': None, 'err': 'NOK:MAXNBTOOLS'}
2024-01-19 09:01:18,360 :: ERROR :: remote_refresh_token isn't defined
2024-01-19 09:01:18,862 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'}
2024-01-19 09:01:18,862 :: ERROR :: get_otp_code:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 193, in get_otp_code
    otp_code = self.otp.get_otp_code()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/otp/otp.py", line 279, in get_otp_code
    raise ConfigException("Can't get otp code")
psa_car_controller.psa.otp.otp.ConfigException: Can't get otp code
2024-01-19 09:01:18,895 :: ERROR :: Please redo otp config
2024-01-19 09:01:19,408 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'}
2024-01-19 09:01:19,409 :: ERROR :: start_remote_control failed redo otp config
2024-01-19 09:01:19,411 :: INFO :: 172.30.32.1 - - [19/Jan/2024 09:01:19] "POST /_dash-update-component HTTP/1.1" 200 -
2024-01-19 09:01:20,832 :: INFO :: 172.30.32.1 - - [19/Jan/2024 09:01:20] "GET / HTTP/1.1" 200 -
2024-01-19 09:01:21,028 :: INFO :: 172.30.32.1 - - [19/Jan/2024 09:01:21] "GET /_dash-layout HTTP/1.1" 200 -
2024-01-19 09:01:21,032 :: INFO :: 172.30.32.1 - - [19/Jan/2024 09:01:21] "GET /_dash-dependencies HTTP/1.1" 200 -
2024-01-19 09:01:21,161 :: WARNING :: Failed to generate figure, there is probably not enough data yet
2024-01-19 09:01:21,169 :: INFO :: 172.30.32.1 - - [19/Jan/2024 09:01:21] "POST /_dash-update-component HTTP/1.1" 200 -
2024-01-19 09:01:21,310 :: INFO :: 172.30.32.1 - - [19/Jan/2024 09:01:21] "GET /control?header=false HTTP/1.1" 200 -
2024-01-19 09:01:21,530 :: INFO :: 172.30.32.1 - - [19/Jan/2024 09:01:21] "GET /_dash-layout HTTP/1.1" 200 -
2024-01-19 09:01:21,534 :: INFO :: 172.30.32.1 - - [19/Jan/2024 09:01:21] "GET /_dash-dependencies HTTP/1.1" 200 -
2024-01-19 09:01:21,633 :: INFO :: 172.30.32.1 - - [19/Jan/2024 09:01:21] "POST /_dash-update-component HTTP/1.1" 200 -
2024-01-19 09:01:37,425 :: INFO :: save config change
```

**Comment by Destroyer061090** [comment]
In addition, the different sensor don’t update automatically.., I should redo otp config to update the actual status… it seems something is not working properly…

**Comment by flobz** [comment]
read the FAQ
