### ISSUE TITLE
400 - server_error : Internal Server Error when trying to submit the configuration 

### ISSUE THREAD

**Issue by malbertone** [flobz/psa_car_controller#752]
Hi,

tried to fresh install v3.3.2 on Home Assistant  (Core 2024.1.6, Supervisor 2024.01.1).
The add on starts properly but cannot Submit the Configuration for:
Brand: Peugeot
Country Code: IT
User and Password tested on MyPeugeot application
When clicking on Submit after a few seconds i get:
400 - server_error : Internal Server Error
Logs reporting:

2024-02-06 10:11:51,727 :: INFO :: Starting analysis on AndroidManifest.xml
2024-02-06 10:11:51,728 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-06 10:11:51,728 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-06 10:11:51,729 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-06 10:11:51,730 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-06 10:11:51,730 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-06 10:11:51,733 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-06 10:11:51,733 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-06 10:11:51,733 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-06 10:11:51,733 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-06 10:11:51,735 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-06 10:11:51,755 :: INFO :: APK file was successfully validated!
2024-02-06 10:11:51,755 :: WARNING :: Requested API level 33 is larger than maximum we have, returning API level 28 instead.
2024-02-06 10:11:53,420 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-06 10:11:53,420 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-06 10:11:53,422 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-06 10:11:53,423 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-06 10:11:53,425 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-06 10:11:53,426 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-06 10:11:53,427 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-06 10:11:53,428 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-06 10:11:53,428 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-06 10:11:53,429 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-06 10:11:53,430 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-06 10:11:56,015 :: ERROR :: 400 - server_error : Internal Server Error
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_views.py", line 133, in connectPSA
res = firstLaunchConfig(app_name, email, password, countrycode)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 95, in firstLaunchConfig
psacc.connect(client_email, client_password)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 35, in connect
self.manager.init_with_user_credentials_realm(user, password, self.realm)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 26, in init_with_user_credentials_realm
self._token_request(self._grant_password_request_realm(login, password, realm), True)
File "/usr/local/lib/python3.9/dist-packages/oauth2_client/credentials_manager.py", line 205, in _token_request
CredentialManager._handle_bad_response(response)
File "/usr/local/lib/python3.9/dist-packages/oauth2_client/credentials_manager.py", line 87, in _handle_bad_response
raise OAuthError(HTTPStatus(response.status_code), error.get('error'), error.get('error_description'))
oauth2_client.credentials_manager.OAuthError: 400 - server_error : Internal Server Error
2024-02-06 10:11:56,025 :: INFO :: 172.30.32.1 - - [06/Feb/2024 10:11:56] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-02-06 10:12:48,059 :: INFO :: 172.30.32.1 - - [06/Feb/2024 10:12:48] "[37mGET / HTTP/1.1[0m" 200 -
2024-02-06 10:12:48,177 :: INFO :: 172.30.32.1 - - [06/Feb/2024 10:12:48] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-02-06 10:12:48,179 :: INFO :: 172.30.32.1 - - [06/Feb/2024 10:12:48] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2024-02-06 10:12:48,201 :: INFO :: 172.30.32.1 - - [06/Feb/2024 10:12:48] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-02-06 10:12:48,232 :: INFO :: 172.30.32.1 - - [06/Feb/2024 10:12:48] "[37mGET /config_login HTTP/1.1[0m" 200 -
2024-02-06 10:12:48,330 :: INFO :: 172.30.32.1 - - [06/Feb/2024 10:12:48] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-02-06 10:12:48,332 :: INFO :: 172.30.32.1 - - [06/Feb/2024 10:12:48] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -

Thanks a lot!
Mike

**Comment by mspearey** [comment]
See #733

**Comment by malbertone** [comment]
Thanks, yep it looks exactly the same, not really familiar with this architecture so guess will have for the time being to hope someone in the community will find a way to integrate the new APIs from Stellantis.

Appreciated!
Mike

**Comment by hans19560** [comment]
Same here: 400 - server_error : Internal Server Error (peugeot, PSA v.3.3.2)

**Comment by crazystress** [comment]
+1

**Comment by mdkeil** [comment]
+1 since today (peugeot, PSA v.3.3.2)

**Comment by hans19560** [comment]
+1

**Comment by Nitro56** [comment]
+1

**Comment by Sunsurfer89** [comment]
+1 same here

**Comment by mafde2023** [comment]
+1 Same here since yesterday

**Comment by bommel947** [comment]
+1 same here

**Comment by hans19560** [comment]
+1

**Comment by Geko2108** [comment]
+1

**Comment by kyokai000** [comment]
+1

**Comment by flobz** [comment]
duplicate #733
