### ISSUE TITLE
No Preconditioning with new API

### ISSUE THREAD

**Issue by toha79** [flobz/psa_car_controller#769]
With the help of the instructions in @[733 ](https://github.com/flobz/psa_car_controller/issues/733#issuecomment-1931515174) my installation is running again. Soc etc. are read out again and I can process them further in the Smarthome. However, pre-conditioning cannot yet be reactivated via the (PSACC) API or the web interface.

**To Reproduce**
1. what command did you use
   Via API: http://192.168.4.7:5000/preconditioning/VXXXX..../1
   or the pre-conditioning button in the GUI
2. when the bug append ?
3. Does it persist after restarting the program? 
   Yes.
4. Does it persist after recreate config by going to http://server_address:port/config? 
   Not tried.

**Config file**
```
{
    "abrp": {
        "abrp_enable_vin": [],
        "token": ""
    },
    "client_id": "07364655-93cb-0000-0000-000000000000",
    "client_secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "co2_signal_api": null,
    "country_code": "DE",
    "customer_id": "OP-ACNT000000000000",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2COpel",
    "refresh_token": "90e42044-00000-0000-0000-000000000000",
    "remote_refresh_token": null,
    "weather_api": null
}
```

**Environment (please complete the following information):**
 - OS: Raspian OS
 - Brand and model: Opel Corsa
 - Application version: https://github.com/0x3dlux/psa_car_controller.git
 - Log:
```
2024-02-21 07:36:35,616 :: INFO :: Preconditioning: topic: psa/RemoteServices/from/cid/OV-ACNT200000000000/ThermalPrecond: {'asap': 'activate', 'programs': {'program1': {'day': [0, 0, 0, 0, 0, 0, 0], 'hour': 34, 'minute': 7, 'on': 0}, 'program2': {'day': [0, 0, 0, 0, 0, 0, 0], 'hour': 34, 'minute': 7, 'on': 0}, 'program3': {'day': [0, 0, 0, 0, 0, 0, 0], 'hour': 34, 'minute': 7, 'on': 0}, 'program4': {'day': [0, 0, 0, 0, 0, 0, 0], 'hour': 34, 'minute': 7, 'on': 0}}}
2024-02-21 07:36:36,017 :: ERROR :: remote_refresh_token isn't defined
2024-02-21 07:36:36,020 :: ERROR :: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/psa/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psa/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psa/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/psa/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psa/lib/python3.11/site-packages/dash/dash.py", line 1310, in dispatch
    ctx.run(
  File "/psa/lib/python3.11/site-packages/dash/_callback.py", line 442, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psa/lib/python3.11/site-packages/psa_car_controller/web/tools/Switch.py", line 28, in call
    self._fct(self._element_id, value)
  File "/psa/lib/python3.11/site-packages/psa_car_controller/psa/RemoteClient.py", line 250, in preconditioning
    self.publish(msg)
  File "/psa/lib/python3.11/site-packages/psa_car_controller/psa/RemoteClient.py", line 138, in publish
    self._refresh_remote_token()
  File "/psa/lib/python3.11/site-packages/psa_car_controller/psa/RemoteClient.py", line 173, in _refresh_remote_token
    otp_code = self.get_otp_code()
               ^^^^^^^^^^^^^^^^^^^
  File "/psa/lib/python3.11/site-packages/psa_car_controller/common/utils.py", line 17, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/psa/lib/python3.11/site-packages/psa_car_controller/psa/RemoteClient.py", line 193, in get_otp_code
    otp_code = self.otp.get_otp_code()
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_otp_code'
2024-02-21 07:36:36,020 :: ERROR :: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/psa/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psa/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psa/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/psa/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psa/lib/python3.11/site-packages/dash/dash.py", line 1310, in dispatch
    ctx.run(
  File "/psa/lib/python3.11/site-packages/dash/_callback.py", line 442, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psa/lib/python3.11/site-packages/psa_car_controller/web/tools/Switch.py", line 28, in call
    self._fct(self._element_id, value)
  File "/psa/lib/python3.11/site-packages/psa_car_controller/psa/RemoteClient.py", line 250, in preconditioning
    self.publish(msg)
  File "/psa/lib/python3.11/site-packages/psa_car_controller/psa/RemoteClient.py", line 138, in publish
    self._refresh_remote_token()
  File "/psa/lib/python3.11/site-packages/psa_car_controller/psa/RemoteClient.py", line 173, in _refresh_remote_token
    otp_code = self.get_otp_code()
               ^^^^^^^^^^^^^^^^^^^
  File "/psa/lib/python3.11/site-packages/psa_car_controller/common/utils.py", line 17, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/psa/lib/python3.11/site-packages/psa_car_controller/psa/RemoteClient.py", line 193, in get_otp_code
    otp_code = self.otp.get_otp_code()
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_otp_code'
```

**Comment by mdkeil** [comment]
`2024-02-21 07:36:36,017 :: ERROR :: remote_refresh_token isn't defined`

`"remote_refresh_token": null,`

Thats your problem..did you finished the "otp-dance"?

**Comment by ritschi86** [comment]
Same Problem here…

"remote_refresh_token": null,

**Comment by zutislo** [comment]
I can also confirm, that preconditioning works again with 3.4.1.
