### ISSUE TITLE
3.4.0: Error: CredentialManager.generate_authorize_url() got an unexpected keyword argument 'code_challenge'

### ISSUE THREAD

**Issue by RlfSt** [flobz/psa_car_controller#776]
Car: Opel Corsa-e (2022)
App: PSA-Car-Controller 3.4.0
Env: Ubuntu 22.04.4 LTS (lxc-Container on Proxmox)

My configuration was broken on OAuth-Changes. I had do redo the authentication.

With v3.4.0 I followed the instructions and got the following error:

CredentialManager.generate_authorize_url() got an unexpected keyword argument 'code_challenge'

The error is reproducable with old otp.bin and without otp.bin.

Console output:
root@psa-car-controller:~# psa-car-controller --web-conf -l 192.168.7.31 -p 5000
2024-02-25 07:22:28,692 :: INFO :: App version 3.4.0
2024-02-25 07:22:28,826 DEBUG Starting new HTTPS connection (1): idpcvs.opel.com:443
send: b'POST /am/oauth2/access_token HTTP/1.1\r\nHost: idpcvs.opel.com\r\nUser-Agent: python-requests/2.28.1\r\nAccept-Encoding: gzip, deflate, br\r\nAccept: */*\r\nConnection: keep-alive\r\nAuthorization: Basic xxx\r\nContent-Length: 96\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n'
send: b'grant_type=refresh_token&scope=openid+profile&refresh_token=xxx-xxx-xxx-xxx-xxx'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Strict-Transport-Security: max-age=16070400;includeSubDomains
header: X-Frame-Options: SAMEORIGIN
header: X-Content-Type-Options: nosniff
header: X-XSS-Protection: 1; mode=block
header: Cache-Control: no-store
header: Date: Sun, 25 Feb 2024 06:22:29 GMT
header: Accept-Ranges: bytes
header: Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept
header: Pragma: no-cache
header: Content-Type: application/json
header: Connection: close
header: Set-Cookie: BIGipServerBE_IDPCLI_CVS_PROD_HTTPS_VIRTUAL.app~BE_IDPCLI_CVS_PROD_HTTPS_VIRTUAL_pool=26378250.47873.0000; path=/; Httponly; Secure
header: Set-Cookie: PSACountry=DE; Domain=.opel.com; Path=/
header: Content-Encoding: gzip
2024-02-25 07:22:29,058 DEBUG https://idpcvs.opel.com:443 "POST /am/oauth2/access_token HTTP/1.1" 400 None
2024-02-25 07:22:29,060 :: ERROR :: Please reconnect by going to config web page
2024-02-25 07:22:29,060 :: INFO :: save config change
2024-02-25 07:22:29,062 :: WARNING :: Can't get language
2024-02-25 07:22:29,188 :: INFO :: NumExpr defaulting to 1 threads.
2024-02-25 07:22:29,509 :: INFO :: update_data
2024-02-25 07:22:29,513 :: INFO :: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://192.168.7.31:5000
2024-02-25 07:22:29,513 :: INFO :: Press CTRL+C to quit
2024-02-25 07:22:35,156 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:35] "GET / HTTP/1.1" 200 -
2024-02-25 07:22:35,319 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:35] "GET /assets/99_custom_overides.css?m=1708840750.0899796 HTTP/1.1" 304 -
2024-02-25 07:22:35,326 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:35] "GET /assets/clientside.js?m=1708840750.0939798 HTTP/1.1" 304 -
2024-02-25 07:22:35,530 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:35] "GET /_dash-dependencies HTTP/1.1" 200 -
2024-02-25 07:22:35,531 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:35] "GET /_dash-layout HTTP/1.1" 200 -
2024-02-25 07:22:35,568 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:35] "POST /_dash-update-component HTTP/1.1" 200 -
2024-02-25 07:22:35,647 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:35] "GET /config_login HTTP/1.1" 200 -
2024-02-25 07:22:35,651 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:35] "GET /assets/images/settings.svg HTTP/1.1" 304 -
2024-02-25 07:22:35,759 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:35] "GET /assets/99_custom_overides.css?m=1708840750.0899796 HTTP/1.1" 304 -
2024-02-25 07:22:35,776 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:35] "GET /assets/clientside.js?m=1708840750.0939798 HTTP/1.1" 304 -
2024-02-25 07:22:35,903 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:35] "GET /_dash-layout HTTP/1.1" 200 -
2024-02-25 07:22:35,904 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:35] "GET /_dash-dependencies HTTP/1.1" 200 -
2024-02-25 07:22:35,954 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:35] "POST /_dash-update-component HTTP/1.1" 200 -
2024-02-25 07:22:35,998 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:35] "GET /assets/images/settings.svg HTTP/1.1" 304 -
2024-02-25 07:22:36,063 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:36] "POST /_dash-update-component HTTP/1.1" 200 -
2024-02-25 07:22:36,064 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:36] "POST /_dash-update-component HTTP/1.1" 204 -
2024-02-25 07:22:36,068 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:22:36] "POST /_dash-update-component HTTP/1.1" 204 -
2024-02-25 07:22:38,319 :: ERROR :: Exception on /get_vehicleinfo/VX... [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/dist-packages/psa_car_controller/web/view/api.py", line 43, in get_vehicle_info
    response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
  File "/usr/local/lib/python3.10/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 106, in get_vehicle_info
    res = self.api().get_vehicle_status(car.vehicle_id)
  File "/usr/local/lib/python3.10/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1229, in get_vehicle_status
    (data) = self.get_vehicle_status_with_http_info(id, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.10/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1293, in get_vehicle_status_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.10/dist-packages/psa_car_controller/psa/oauth.py", line 109, in call_api
    return self._ApiClient__call_api(resource_path, method,
  File "/usr/local/lib/python3.10/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 147, in __call_api
    self.update_params_for_auth(header_params, query_params, auth_settings)
  File "/usr/local/lib/python3.10/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 504, in update_params_for_auth
    auth_setting = self.configuration.auth_settings().get(auth)
  File "/usr/local/lib/python3.10/dist-packages/psa_car_controller/psa/connected_car_api/configuration.py", line 241, in auth_settings
    'value': 'Bearer ' + self.access_token
TypeError: can only concatenate str (not "NoneType") to str
2024-02-25 07:22:38,321 :: INFO :: 192.168.7.29 - - [25/Feb/2024 07:22:38] "GET /get_vehicleinfo/VX...?from_cache=0 HTTP/1.0" 500 -
2024-02-25 07:22:58,588 DEBUG Starting new HTTPS connection (1): api.github.com:443
send: b'GET /repos/flobz/psa_apk/git/trees/main: HTTP/1.1\r\nHost: api.github.com\r\nUser-Agent: python-requests/2.28.1\r\nAccept-Encoding: gzip, deflate, br\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: GitHub.com
header: Date: Sun, 25 Feb 2024 06:22:58 GMT
header: Content-Type: application/json; charset=utf-8
header: Cache-Control: public, max-age=60, s-maxage=60
header: Vary: Accept, Accept-Encoding, Accept, X-Requested-With
header: ETag: W/"xxx"
header: Last-Modified: Sat, 06 Jan 2024 09:27:19 GMT
header: X-GitHub-Media-Type: github.v3; format=json
header: x-github-api-version-selected: 2022-11-28
header: Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
header: Access-Control-Allow-Origin: *
header: Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
header: X-Frame-Options: deny
header: X-Content-Type-Options: nosniff
header: X-XSS-Protection: 0
header: Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
header: Content-Security-Policy: default-src 'none'
header: Content-Encoding: gzip
header: X-RateLimit-Limit: 60
header: X-RateLimit-Remaining: 55
header: X-RateLimit-Reset: 1708844510
header: X-RateLimit-Resource: core
header: X-RateLimit-Used: 5
header: Accept-Ranges: bytes
header: Content-Length: 452
header: X-GitHub-Request-Id: DD36:356EE0:BD1FF7B:BF7D848:65DADCC2
2024-02-25 07:22:58,802 DEBUG https://api.github.com:443 "GET /repos/flobz/psa_apk/git/trees/main: HTTP/1.1" 200 452
2024-02-25 07:22:59,012 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-25 07:22:59,012 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-25 07:22:59,013 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-25 07:22:59,014 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-25 07:22:59,014 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-25 07:22:59,017 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-25 07:22:59,017 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-25 07:22:59,018 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-25 07:22:59,018 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-25 07:22:59,020 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-02-25 07:22:59,043 :: WARNING :: Requested API level 33 is larger than maximum we have, returning API level 28 instead.
2024-02-25 07:23:00,795 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-25 07:23:00,795 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-25 07:23:00,797 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-25 07:23:00,799 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-25 07:23:00,801 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-25 07:23:00,803 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-25 07:23:00,804 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-25 07:23:00,805 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-25 07:23:00,805 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-25 07:23:00,806 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-25 07:23:00,807 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-02-25 07:23:01,900 DEBUG Starting new HTTPS connection (1): id-dcr.opel.com:443
send: b'POST /mobile-services/GetAccessToken?jsonRequest=%7B%22siteCode%22%3A+%22OP_DE_ESP%22%2C+%22culture%22%3A+%22fr-FR%22%2C+%22action%22%3A+%22authenticate%22%2C+%22fields%22%3A+%7B%22USR_EMAIL%22%3A+%7B%22value%22%3A+%2xxx%22%7D%2C+%22USR_PASSWORD%22%3A+%7B%22value%22%3A+%22xxx%22%7D%7D%7D HTTP/1.1\r\nHost: id-dcr.opel.com\r\nUser-Agent: okhttp/2.3.0\r\nAccept-Encoding: gzip, deflate, br\r\nAccept: */*\r\nConnection: Keep-Alive\r\nContent-Type: application/json\r\nContent-Length: 0\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sun, 25 Feb 2024 06:23:02 GMT
header: X-Frame-Options: sameorigin
header: X-Content-Type-Options: nosniff
header: Set-Cookie: DCROPENIDOP=9c73029244b3cb3f05059b788c4e0801; path=/
header: Expires: Thu, 19 Nov 1981 08:52:00 GMT
header: Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
header: Pragma: no-cache
header: Vary: Accept-Encoding,User-Agent
header: X-XSS-Protection: 1; mode=block
header: Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
header: X-Permitted-Cross-Domain-Policies: none
header: Referrer-Policy: no-referrer
header: X-Content-Security-Policy: default-src 'self'
header: Content-Length: 143
header: Keep-Alive: timeout=5, max=100
header: Connection: Keep-Alive
header: Content-Type: application/json
header: Set-Cookie: BIGipServerAPAC_DCR_FEND_PROD_HTTPS.app~APAC_DCR_FEND_PROD_HTTPS_pool=2618327050.47873.0000; path=/; Httponly; Secure
header: Set-Cookie: PSACountry=DE; Domain=.opel.com; Path=/
2024-02-25 07:23:02,400 DEBUG https://id-dcr.opel.com:443 "POST /mobile-services/GetAccessToken?jsonRequest=%7B%22siteCode%22%3A+%22OP_DE_ESP%22%2C+%22culture%22%3A+%22fr-FR%22%2C+%22action%22%3A+%22authenticate%22%2C+%22fields%22%3A+%7B%22USR_EMAIL%22%3A+%7B%22value%22%3A+%22xxx%22%7D%2C+%22USR_PASSWORD%22%3A+%7B%22value%22%3A+%22xxx%22%7D%7D%7D HTTP/1.1" 200 143
2024-02-25 07:23:02,402 DEBUG Starting new HTTPS connection (1): mw-op-m2c.mym.awsmpsa.com:443
send: b'POST /api/v1/user?culture=de_DE&width=1080&version=1.33.0 HTTP/1.1\r\nHost: mw-op-m2c.mym.awsmpsa.com\r\nUser-Agent: okhttp/4.8.0\r\nAccept-Encoding: gzip, deflate, br\r\nAccept: */*\r\nConnection: Keep-Alive\r\nContent-Type: application/json;charset=UTF-8\r\nSource-Agent: App-Android\r\nToken: xxx\r\nVersion: 1.33.0\r\nContent-Length: 104\r\n\r\n'
send: b'{"site_code": "OP_DE_ESP", "ticket": "xxx"}'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Sun, 25 Feb 2024 06:23:03 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: PHPSESSID=t210tqlck3u966a06l81tvlv84; path=/; HttpOnly
header: Cache-Control: no-cache
header: Content-Encoding: gzip
header: Strict-Transport-Security: max-age=31536000; includeSubDomains
header: X-Frame-Options: SAMEORIGIN
2024-02-25 07:23:03,582 DEBUG https://mw-op-m2c.mym.awsmpsa.com:443 "POST /api/v1/user?culture=de_DE&width=1080&version=1.33.0 HTTP/1.1" 200 None
2024-02-25 07:23:03,585 :: ERROR :: CredentialManager.generate_authorize_url() got an unexpected keyword argument 'code_challenge'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/psa_car_controller/web/view/config_views.py", line 139, in connectPSA
    res = firstLaunchConfig(app_name, email, password, countrycode)
  File "/usr/local/lib/python3.10/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 95, in firstLaunchConfig
    psacc.connect()
  File "/usr/local/lib/python3.10/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 35, in connect
    self.manager.init_with_oauth2_redirect(realm_info[self.realm]["scheme"], self.country_code)
  File "/usr/local/lib/python3.10/dist-packages/psa_car_controller/psa/oauth.py", line 43, in init_with_oauth2_redirect
    url = self.generate_authorize_url(redir_uri, secrets.token_urlsafe(16),
TypeError: CredentialManager.generate_authorize_url() got an unexpected keyword argument 'code_challenge'
2024-02-25 07:23:03,586 :: INFO :: 10.0.0.176 - - [25/Feb/2024 07:23:03] "POST /_dash-update-component HTTP/1.1" 200 -
^CTraceback (most recent call last):
  File "/usr/local/bin/psa-car-controller", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/psa_car_controller/__main__.py", line 25, in main
    t1.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()

what command did you use
/usr/bin/python3 /usr/local/bin/psa-car-controller --web-conf -l 192.168.7.31 -p 5000

when the bug append ?
After hitting "Submit" in the web-conf-page

Does it persist after restarting the program?
Yes.

Does it persist after recreate config by going to http://server_address:port/config?
Yes.

**Comment by SabatoArdolino** [comment]
in HA configuration How do you connect in CLI ? I've the same problem

**Comment by Aelbaert** [comment]
Same problem here; how do you connect in CLI?
In the logfile, there is a web address and when you enter that, you will have to authorize. Once authorized, I can find the line with 'oauth2redirect' in the F12-screen, but how to 'and paste it into the command line interface'....

**Comment by flobz** [comment]
please upgrade oauth2-client >= 1.3.0
 pip3 install -U 'oauth2-client>=1.3.0'

**Comment by RlfSt** [comment]
> please upgrade oauth2-client >= 1.3.0 pip3 install -U 'oauth2-client>=1.3.0'

Thank you - that did the trick!

**Comment by SabatoArdolino** [comment]
I try but 

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.


where can I start the command ?
