### ISSUE TITLE
[Citroen e-Spacetourer] Can't get car model please check cars.json

### ISSUE THREAD

**Issue by jaltek** [flobz/psa_car_controller#78]
Hi,
like #65 I get the following warning for a Citroen e-Spacetourer:

```WARNING :: Can't get car model please check cars.json```

cars.json:
```
[
    {
        "battery_power": 46,
        "brand": "Citro\u00ebn",
        "fuel_capacity": 0,
        "label": "SPACETOURER",
        "max_elec_consumption": 70,
        "max_fuel_consumption": 0,
        "vehicle_id": "XXXXXXXXXX",
        "vin": "XXXXXXX"
    }
]
```
Thanks for your awesome work!

**Comment by flobz** [comment]
Hello
Can you give me the 10 first character of your car VIN? 
Like this you car model could be detected automatically. 
Thanks

**Comment by flobz** [comment]
What's the size of the battery ? 50 or 75kw ?

**Comment by jaltek** [comment]
50 in this case ;)

**Comment by flobz** [comment]
Ok your model should be finded with the last version.

**Comment by jaltek** [comment]
Well...not really :D

```
$ python3 server.py -f test.json -c charge_config1.json
2021-04-13 11:52:15,600 :: INFO :: server start
Traceback (most recent call last):
  File "server.py", line 56, in <module>
    web.app.myp = MyPSACC.load_config(name=config_name)
  File "/home/pi/psa/psa_car_controller/MyPSACC.py", line 493, in load_config
    psacc = MyPSACC(**config)
  File "/home/pi/psa/psa_car_controller/MyPSACC.py", line 141, in __init__
    self.vehicles_list = Cars.load_cars(CARS_FILE)
  File "/home/pi/psa/psa_car_controller/Car.py", line 114, in load_cars
    cars=Cars.from_json(json.loads(json_str))
  File "/home/pi/psa/psa_car_controller/Car.py", line 98, in from_json
    cars = list(map(Car.from_json, data))
  File "/home/pi/psa/psa_car_controller/Car.py", line 50, in from_json
    return cls(**data)
  File "/home/pi/psa/psa_car_controller/Car.py", line 24, in __init__
    self.abrp_name = abrp_name or model.abrp_name
AttributeError: 'NoneType' object has no attribute 'abrp_name'

**Comment by flobz** [comment]
And now ?

**Comment by jaltek** [comment]
Works like a charm :) Thanks a lot!

**Comment by jaltek** [comment]
Well I actually get a new error:

```
2021-04-13 16:22:31,939 :: INFO :: update_data
2021-04-13 16:22:31,975 :: ERROR :: update_trips (slider): Traceback (most recent call last):
  File "/home/pi/psa/psa_car_controller/web/views.py", line 187, in update_trips
    min_date = trips[0].start_at
IndexError: list index out of range

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/psa/psa_car_controller/web/app.py", line 42, in start_app
    import web.views
  File "/home/pi/psa/psa_car_controller/web/views.py", line 267, in <module>
    dash_app.layout = serve_layout
  File "/home/pi/.local/lib/python3.7/site-packages/dash/dash.py", line 510, in layout
    layout_value = self._layout_value()
  File "/home/pi/.local/lib/python3.7/site-packages/dash/dash.py", line 476, in _layout_value
    return self._layout() if self._layout_is_function else self._layout
  File "/home/pi/psa/psa_car_controller/web/views.py", line 222, in serve_layout
    figures.get_figures(trips, chargings)
  File "/home/pi/psa/psa_car_controller/web/figures.py", line 98, in get_figures
    consumption_fig = px.line(consumption_df, x="date", y="consumption", title='Consumption of the car')
  File "/home/pi/.local/lib/python3.7/site-packages/plotly/express/_chart_types.py", line 252, in line
    return make_figure(args=locals(), constructor=go.Scatter)
  File "/home/pi/.local/lib/python3.7/site-packages/plotly/express/_core.py", line 1861, in make_figure
    args = build_dataframe(args, constructor)
  File "/home/pi/.local/lib/python3.7/site-packages/plotly/express/_core.py", line 1378, in build_dataframe
    args, wide_mode, var_name, value_name
  File "/home/pi/.local/lib/python3.7/site-packages/plotly/express/_core.py", line 1183, in process_args_into_dataframe
    raise ValueError(err_msg)
ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of [] but received: date
```
If it's related to the latest commit...

**Comment by flobz** [comment]
it's normal, its because you have no trips yet.

**Comment by jaltek** [comment]
However, in my opinion, I did not have this problem before the changes were made. In addition, I can no longer reach the "web gui" so I think the "webserver" does not start?

**Comment by flobz** [comment]
The web gui shows statistics, if you don't don't do trips, no statistics can be made.

**Comment by jaltek** [comment]
No - I mean there is nothing listening on port 5000. So I'm also not able to reach e.g.  ```http://localhost:5000/get_vehicleinfo/YOURVIN```.

Or I'm doing something wrong :)
Anyway, it worked before. Even if I had no trips.

**Comment by jaltek** [comment]
Here is the full output (is stripped the json responses):

```
$ python3 server.py -f test.json -c charge_config1.json
2021-04-15 13:20:08,404 :: INFO :: server start
2021-04-15 13:20:08,814 :: INFO :: save config change
2021-04-15 13:20:09,802 :: INFO :: ["{'vin': 'VF7VXXXXXXXXXXXXX', [...]
2021-04-15 13:20:10,146 :: INFO :: save config change
2021-04-15 13:20:10,667 :: INFO :: ask state to VF7VXXXXXXXXXXXXX
2021-04-15 13:20:10,911 :: INFO :: Connected with result code {'session present': 0}
2021-04-15 13:20:10,913 :: INFO :: subscribe to psa/RemoteServices/to/cid/AC-XXXXXXXXXXXXXXXX/#
2021-04-15 13:20:10,915 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VF7VXXXXXXXXXXXXX
2021-04-15 13:20:11,008 :: INFO :: save config change
2021-04-15 13:20:11,011 :: INFO :: {"access_token": [...]
2021-04-15 13:20:11,323 :: INFO :: mqtt msg psa/RemoteServices/to/cid/AC-XXXXXXXXXXXXXXXX/VehicleState/ProcessManagement [...]
2021-04-15 13:20:11,360 :: INFO :: mqtt msg psa/RemoteServices/to/cid/AC-XXXXXXXXXXXXXXXX/VehicleState [...]
2021-04-15 13:20:14,730 :: INFO :: update_data
2021-04-15 13:20:14,763 :: ERROR :: update_trips (slider): Traceback (most recent call last):
  File "/home/pi/psa/psa_car_controller/web/views.py", line 187, in update_trips
    min_date = trips[0].start_at
IndexError: list index out of range

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/psa/psa_car_controller/web/app.py", line 42, in start_app
    import web.views
  File "/home/pi/psa/psa_car_controller/web/views.py", line 267, in <module>
    dash_app.layout = serve_layout
  File "/home/pi/.local/lib/python3.7/site-packages/dash/dash.py", line 510, in layout
    layout_value = self._layout_value()
  File "/home/pi/.local/lib/python3.7/site-packages/dash/dash.py", line 476, in _layout_value
    return self._layout() if self._layout_is_function else self._layout
  File "/home/pi/psa/psa_car_controller/web/views.py", line 222, in serve_layout
    figures.get_figures(trips, chargings)
  File "/home/pi/psa/psa_car_controller/web/figures.py", line 98, in get_figures
    consumption_fig = px.line(consumption_df, x="date", y="consumption", title='Consumption of the car')
  File "/home/pi/.local/lib/python3.7/site-packages/plotly/express/_chart_types.py", line 252, in line
    return make_figure(args=locals(), constructor=go.Scatter)
  File "/home/pi/.local/lib/python3.7/site-packages/plotly/express/_core.py", line 1861, in make_figure
    args = build_dataframe(args, constructor)
  File "/home/pi/.local/lib/python3.7/site-packages/plotly/express/_core.py", line 1378, in build_dataframe
    args, wide_mode, var_name, value_name
  File "/home/pi/.local/lib/python3.7/site-packages/plotly/express/_core.py", line 1183, in process_args_into_dataframe
    raise ValueError(err_msg)
ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of [] but received: date
```

So I think the 
```
Running on http://localhost:5000/ (Press CTRL+C to quit)
```
is missing.

**Comment by flobz** [comment]
can you retry with the last version ?

**Comment by jaltek** [comment]
Again: Perfect :+1: Thanks a lot. Great work BTW!

**Comment by flobz** [comment]
thanks
