### ISSUE TITLE
Invalid code length in login-procedure with opel mokka-e

### ISSUE THREAD

**Issue by jove01** [flobz/psa_car_controller#792]
After Update the Addon in Homeassistant to 3.4.1 fom 3.2.2 with the procedure discribed before, I must restart the login Procedure.

I tried the option with and without the option "--web-conf"

I startet the addon with the start-button in the addon-site. It stopped their. But I can start the login-procedure  with myIP:5000. After the first site I must fill "PSA code from step above"
![image](https://github.com/flobz/psa_car_controller/assets/116289742/ce3857d7-edf9-4a6f-8ffb-d7118c129044)
My login code are 8 digits and i controlles it in the myopel-site.

Is it correct to start the AddOn from the AddOn-Site or must I go to the console start psacc in the docker. I think no. But what is my/the error? And what ist the correct way. 
```
`rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/api.py", line 43, in get_vehicle_info
    response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 107, in get_vehicle_info
    res = self.api().get_vehicle_status(car.vehicle_id)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1229, in get_vehicle_status
    (data) = self.get_vehicle_status_with_http_info(id, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1293, in get_vehicle_status_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 107, in call_api
    return self._ApiClient__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 147, in __call_api
    self.update_params_for_auth(header_params, query_params, auth_settings)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 504, in update_params_for_auth
    auth_setting = self.configuration.auth_settings().get(auth)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/configuration.py", line 241, in auth_settings
    'value': 'Bearer ' + self.access_token
TypeError: can only concatenate str (not "NoneType") to str
2024-02-28 23:40:19,139 :: INFO :: 192.168.178.91 - - [28/Feb/2024 23:40:19] "GET /get_vehicleinfo/VXKxxxxxxxxxxxxxxxxx?from_cache=1 HTTP/1.1" 500 -
2024-02-28 23:40:19,141 :: INFO :: <Request 'http://192.168.178.91:5000/charge_control?vin=VXKxxxxxxxxxxxxxxxxx&%3Falways_check=true' [GET]>
2024-02-28 23:40:19,142 :: ERROR :: Charge control not setup check your PSACC configuration and logs
2024-02-28 23:40:19,143 :: INFO :: 192.168.178.91 - - [28/Feb/2024 23:40:19] "GET /charge_control?vin=VXKxxxxxxxxxxxxxxxxx&?always_check=true HTTP/1.1" 200 -
2024-02-28 23:41:19,139 :: ERROR :: Exception on /get_vehicleinfo/VXKxxxxxxxxxxxxxxxxx [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/api.py", line 43, in get_vehicle_info
    response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 107, in get_vehicle_info
    res = self.api().get_vehicle_status(car.vehicle_id)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1229, in get_vehicle_status
    (data) = self.get_vehicle_status_with_http_info(id, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1293, in get_vehicle_status_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 107, in call_api
    return self._ApiClient__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 147, in __call_api
    self.update_params_for_auth(header_params, query_params, auth_settings)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 504, in update_params_for_auth
    auth_setting = self.configuration.auth_settings().get(auth)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/configuration.py", line 241, in auth_settings
    'value': 'Bearer ' + self.access_token
TypeError: can only concatenate str (not "NoneType") to str
2024-02-28 23:41:19,141 :: INFO :: 192.168.178.91 - - [28/Feb/2024 23:41:19] "GET /get_vehicleinfo/VXKxxxxxxxxxxxxxxxxx?from_cache=1 HTTP/1.1" 500 -
2024-02-28 23:41:19,142 :: INFO :: <Request 'http://192.168.178.91:5000/charge_control?vin=VXKxxxxxxxxxxxxxxxxx&%3Falways_check=true' [GET]>
2024-02-28 23:41:19,143 :: ERROR :: Charge control not setup check your PSACC configuration and logs
2024-02-28 23:41:19,144 :: INFO :: 192.168.178.91 - - [28/Feb/2024 23:41:19] "GET /charge_control?vin=VXKxxxxxxxxxxxxxxxxx&?always_check=true HTTP/1.1" 200 -
2024-02-28 23:42:19,138 :: ERROR :: Exception on /get_vehicleinfo/VXKxxxxxxxxxxxxxxxxx [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/api.py", line 43, in get_vehicle_info
    response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 107, in get_vehicle_info
    res = self.api().get_vehicle_status(car.vehicle_id)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1229, in get_vehicle_status
    (data) = self.get_vehicle_status_with_http_info(id, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1293, in get_vehicle_status_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 107, in call_api
    return self._ApiClient__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 147, in __call_api
    self.update_params_for_auth(header_params, query_params, auth_settings)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 504, in update_params_for_auth
    auth_setting = self.configuration.auth_settings().get(auth)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/configuration.py", line 241, in auth_settings
    'value': 'Bearer ' + self.access_token
TypeError: can only concatenate str (not "NoneType") to str
2024-02-28 23:42:19,140 :: INFO :: 192.168.178.91 - - [28/Feb/2024 23:42:19] "GET /get_vehicleinfo/VXKxxxxxxxxxxxxxxxxx?from_cache=1 HTTP/1.1" 500 -
2024-02-28 23:42:19,142 :: INFO :: <Request 'http://192.168.178.91:5000/charge_control?vin=VXKxxxxxxxxxxxxxxxxx&%3Falways_check=true' [GET]>
2024-02-28 23:42:19,143 :: ERROR :: Charge control not setup check your PSACC configuration and logs
2024-02-28 23:42:19,144 :: INFO :: 192.168.178.91 - - [28/Feb/2024 23:42:19] "GET /charge_control?vin=VXKxxxxxxxxxxxxxxxxx&?always_check=true HTTP/1.1" 200 `
```

**Comment by antoniochacon** [comment]
I have the same problem

**Comment by crohot** [comment]
Same issue with a Mokka-e.

**Comment by antoniochacon** [comment]
Fixed, followig: https://github.com/flobz/psa_car_controller/discussions/779#discussioncomment-8601459
