### ISSUE TITLE
Stop working version v3.4.1

### ISSUE THREAD

**Issue by antoniochacon** [flobz/psa_car_controller#800]
Stop working version v3.4.1. I tried restarting PSA and Home Assistant.
My car is Peugeot 2008e

Logs:
 auth_setting = self.configuration.auth_settings().get(auth)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/configuration.py", line 241, in auth_settings
    'value': 'Bearer ' + self.access_token
TypeError: can only concatenate str (not "NoneType") to str
2024-03-05 05:45:48,007 :: INFO :: 192.168.1.201 - - [05/Mar/2024 05:45:48] "GET /get_vehicleinfo/VR3UKxxxxxxx8 HTTP/1.1" 500 -
2024-03-05 05:45:48,137 :: INFO :: <Request 'http://192.168.1.201:5000/charge_control?vin=VR3UKxxxxxxx8' [GET]>
2024-03-05 05:45:48,139 :: ERROR :: Charge control not setup check your PSACC configuration and logs
2024-03-05 05:45:48,141 :: INFO :: 192.168.1.201 - - [05/Mar/2024 05:45:48] "GET /charge_control?vin=VR3UKxxxxxxx8 HTTP/1.1" 200 -
2024-03-05 05:46:15,442 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:15] "GET / HTTP/1.1" 200 -
2024-03-05 05:46:15,479 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:15] "GET /assets/99_custom_overides.css?m=1708954152.0 HTTP/1.1" 304 -
2024-03-05 05:46:15,484 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:15] "GET /assets/clientside.js?m=1708954152.0 HTTP/1.1" 304 -
2024-03-05 05:46:15,685 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:15] "GET /_dash-layout HTTP/1.1" 200 -
2024-03-05 05:46:15,690 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:15] "GET /_dash-dependencies HTTP/1.1" 200 -
2024-03-05 05:46:15,713 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:15] "POST /_dash-update-component HTTP/1.1" 200 -
2024-03-05 05:46:15,747 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:15] "GET /assets/images/settings.svg HTTP/1.1" 200 -
2024-03-05 05:46:15,754 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:15] "GET /config_login HTTP/1.1" 200 -
2024-03-05 05:46:15,816 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:15] "GET /_dash-layout HTTP/1.1" 200 -
2024-03-05 05:46:15,821 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:15] "GET /_dash-dependencies HTTP/1.1" 200 -
2024-03-05 05:46:15,871 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:15] "POST /_dash-update-component HTTP/1.1" 200 -
2024-03-05 05:46:15,942 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:15] "POST /_dash-update-component HTTP/1.1" 200 -
2024-03-05 05:46:15,947 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:15] "POST /_dash-update-component HTTP/1.1" 204 -
2024-03-05 05:46:15,953 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:15] "POST /_dash-update-component HTTP/1.1" 204 -
2024-03-05 05:46:19,575 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:19] "POST /_dash-update-component HTTP/1.1" 200 -
2024-03-05 05:46:19,641 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:19] "POST /_dash-update-component HTTP/1.1" 200 -
2024-03-05 05:46:19,646 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:19] "POST /_dash-update-component HTTP/1.1" 204 -
2024-03-05 05:46:19,651 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:19] "POST /_dash-update-component HTTP/1.1" 204 -
2024-03-05 05:46:21,399 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:21] "POST /_dash-update-component HTTP/1.1" 200 -
2024-03-05 05:46:21,577 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:21] "POST /_dash-update-component HTTP/1.1" 200 -
2024-03-05 05:46:21,582 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:21] "POST /_dash-update-component HTTP/1.1" 204 -
2024-03-05 05:46:21,587 :: INFO :: 172.30.32.1 - - [05/Mar/2024 05:46:21] "POST /_dash-update-component HTTP/1.1" 204 -
2024-03-05 05:46:48,004 :: ERROR :: Exception on /get_vehicleinfo/VR3UKxxxxxxx8 [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/api.py", line 43, in get_vehicle_info
    response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 107, in get_vehicle_info
    res = self.api().get_vehicle_status(car.vehicle_id)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1229, in get_vehicle_status
    (data) = self.get_vehicle_status_with_http_info(id, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1293, in get_vehicle_status_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 107, in call_api
    return self._ApiClient__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 147, in __call_api
    self.update_params_for_auth(header_params, query_params, auth_settings)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 504, in update_params_for_auth
    auth_setting = self.configuration.auth_settings().get(auth)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/configuration.py", line 241, in auth_settings
    'value': 'Bearer ' + self.access_token
TypeError: can only concatenate str (not "NoneType") to str
2024-03-05 05:46:48,007 :: INFO :: 192.168.1.201 - - [05/Mar/2024 05:46:48] "GET /get_vehicleinfo/VR3UKxxxxxxx8 HTTP/1.1" 500 -
2024-03-05 05:46:48,137 :: INFO :: <Request 'http://192.168.1.201:5000/charge_control?vin=VR3UKxxxxxxx8' [GET]>
2024-03-05 05:46:48,139 :: ERROR :: Charge control not setup check your PSACC configuration and logs
2024-03-05 05:46:48,142 :: INFO :: 192.168.1.201 - - [05/Mar/2024 05:46:48] "GET /charge_control?vin=VR3UKxxxxxxx8 HTTP/1.1" 200 -
2024-03-05 05:47:48,003 :: ERROR :: Exception on /get_vehicleinfo/VR3UKxxxxxxx8 [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/api.py", line 43, in get_vehicle_info
    response=json.dumps(APP.myp.get_vehicle_info(vin, from_cache).to_dict(), default=str),
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 107, in get_vehicle_info
    res = self.api().get_vehicle_status(car.vehicle_id)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1229, in get_vehicle_status
    (data) = self.get_vehicle_status_with_http_info(id, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1293, in get_vehicle_status_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 107, in call_api
    return self._ApiClient__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 147, in __call_api
    self.update_params_for_auth(header_params, query_params, auth_settings)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 504, in update_params_for_auth
    auth_setting = self.configuration.auth_settings().get(auth)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/configuration.py", line 241, in auth_settings
    'value': 'Bearer ' + self.access_token
TypeError: can only concatenate str (not "NoneType") to str
2024-03-05 05:47:48,005 :: INFO :: 192.168.1.201 - - [05/Mar/2024 05:47:48] "GET /get_vehicleinfo/VR3UKxxxxxxx8 HTTP/1.1" 500 -
2024-03-05 05:47:48,134 :: INFO :: <Request 'http://192.168.1.201:5000/charge_control?vin=VR3UKxxxxxxx8' [GET]>
2024-03-05 05:47:48,136 :: ERROR :: Charge control not setup check your PSACC configuration and logs
2024-03-05 05:47:48,137 :: INFO :: 192.168.1.201 - - [05/Mar/2024 05:47:48] "GET /charge_control?vin=VR3UKxxxxxxx8 HTTP/1.1" 200 -

**Comment by mj1985** [comment]
`2024-03-05 05:47:48,136 :: ERROR :: Charge control not setup check your PSACC configuration and logs`
Configure your car and otp again. Make sure to change psacc-options to
`-f config.json -c charge_config.json -r`

**Comment by antoniochacon** [comment]
Thanks a lot, I´ve done both tasks and its working again.
