### ISSUE TITLE
"sqlite3.OperationalError: database is locked" after short runtime on Raspberry Pi 3

### ISSUE THREAD

**Issue by gernot-h** [flobz/psa_car_controller#807]
I tested psacc successfully some weeks ago on my Laptop and finally installed it on a Raspi 3 B.

Since it's installed on the Raspi, I didn't manage to get recording trips etc. working reliably. After some runtime, it stops writing to the database, printing this error:

```
2024-03-08 20:16:52,012 :: ERROR :: refresh_vehicle_info:
Traceback (most recent call last):
  File "/root/psa_car_controller/lib/python3.11/site-packages/psa_car_controller/psacc/application/psa_client.py", line 128, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/root/psa_car_controller/lib/python3.11/site-packages/psa_car_controller/psacc/application/psa_client.py", line 111, in get_vehicle_info
    self.record_info(car)
  File "/root/psa_car_controller/lib/python3.11/site-packages/psa_car_controller/psacc/application/psa_client.py", line 197, in record_info
    Database.record_position(self.weather_api, car.vin, mileage, latitude, longitude, altitude, date, level,
  File "/root/psa_car_controller/lib/python3.11/site-packages/psa_car_controller/psacc/repository/db.py", line 269, in record_position
    conn.execute("INSERT INTO position(Timestamp,VIN,longitude,latitude,altitude,mileage,level,level_fuel,"
sqlite3.OperationalError: database is locked
```

I tried re-creating the database again and again and it always works for a few minutes or hours and then ends up in this state again. I've no clue where and how to start debugging this, any hint greatly appreciated. :-)

**Config file**
kept detault settings

**Environment (please complete the following information):**
 - OS: Raspbian 12/Bookworm.
 - Brand and model of car: Opel Astra L PHEV
 - Application version: 3.4.1

**Comment by DPO99** [comment]
Same Here with 3.5.3

**Comment by LilSlippinJimmy** [comment]
Yep same here with 3.5.6.

**Comment by elgeniskogen** [comment]
Thank you so much for a great container @flobz  :-) I am using version 3.5.6 as a container in Docker and pull data from cache every 5 mintes. I get the below "database is locked" messages a lot. Would highly appreciate if you are able to address this in a new version :-) 

`2025-04-29 16:28:59,165 :: ERROR :: refresh_vehicle_info: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 128, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 111, in get_vehicle_info
    self.record_info(car)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 216, in record_info
    Database.record_battery_soh(car.vin, charge_date, soh)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/repository/db.py", line 285, in record_battery_soh
    conn.execute("INSERT INTO battery_soh(date, VIN, level) VALUES(?,?,?)", (date, vin, level))
sqlite3.OperationalError: database is locked
2025-04-29 16:30:00,243 :: INFO :: 172.23.0.1 - - [29/Apr/2025 16:30:00] "GET /get_vehicleinfo/MYVIN?from_cache=1 HTTP/1.1" 200 -
2025-04-29 16:30:59,168 :: ERROR :: refresh_vehicle_info: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 128, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 111, in get_vehicle_info
    self.record_info(car)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 216, in record_info
    Database.record_battery_soh(car.vin, charge_date, soh)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/repository/db.py", line 285, in record_battery_soh
    conn.execute("INSERT INTO battery_soh(date, VIN, level) VALUES(?,?,?)", (date, vin, level))
sqlite3.OperationalError: database is locked
2025-04-29 16:32:59,181 :: ERROR :: refresh_vehicle_info: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 128, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 111, in get_vehicle_info
    self.record_info(car)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 216, in record_info
    Database.record_battery_soh(car.vin, charge_date, soh)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/repository/db.py", line 285, in record_battery_soh
    conn.execute("INSERT INTO battery_soh(date, VIN, level) VALUES(?,?,?)", (date, vin, level))
sqlite3.OperationalError: database is locked
2025-04-29 16:35:00,202 :: INFO :: 172.23.0.1 - - [29/Apr/2025 16:35:00] "GET /get_vehicleinfo/MYVIN?from_cache=1 HTTP/1.1" 200 -
2025-04-29 16:36:59,417 :: ERROR :: refresh_vehicle_info: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 128, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 111, in get_vehicle_info
    self.record_info(car)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 216, in record_info
    Database.record_battery_soh(car.vin, charge_date, soh)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/repository/db.py", line 285, in record_battery_soh
    conn.execute("INSERT INTO battery_soh(date, VIN, level) VALUES(?,?,?)", (date, vin, level))
sqlite3.OperationalError: database is locked
2025-04-29 16:38:59,236 :: ERROR :: refresh_vehicle_info: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 128, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 111, in get_vehicle_info
    self.record_info(car)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 216, in record_info
    Database.record_battery_soh(car.vin, charge_date, soh)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/repository/db.py", line 285, in record_battery_soh
    conn.execute("INSERT INTO battery_soh(date, VIN, level) VALUES(?,?,?)", (date, vin, level))
sqlite3.OperationalError: database is locked
2025-04-29 16:40:00,199 :: INFO :: 172.23.0.1 - - [29/Apr/2025 16:40:00] "GET /get_vehicleinfo/MYVIN?from_cache=1 HTTP/1.1" 200 -
2025-04-29 16:40:30,099 :: INFO :: <Request 'http://192.168.1.2:5050/charge_control?vin=MYVIN' [GET]>
2025-04-29 16:40:30,101 :: INFO :: 172.23.0.1 - - [29/Apr/2025 16:40:30] "GET /charge_control?vin=MYVIN HTTP/1.1" 200 -
2025-04-29 16:40:59,194 :: ERROR :: refresh_vehicle_info: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 128, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 111, in get_vehicle_info
    self.record_info(car)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 216, in record_info
    Database.record_battery_soh(car.vin, charge_date, soh)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/repository/db.py", line 285, in record_battery_soh
    conn.execute("INSERT INTO battery_soh(date, VIN, level) VALUES(?,?,?)", (date, vin, level))
sqlite3.OperationalError: database is locked
2025-04-29 16:44:59,263 :: ERROR :: refresh_vehicle_info: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 128, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 111, in get_vehicle_info
    self.record_info(car)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 216, in record_info
    Database.record_battery_soh(car.vin, charge_date, soh)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/repository/db.py", line 285, in record_battery_soh
    conn.execute("INSERT INTO battery_soh(date, VIN, level) VALUES(?,?,?)", (date, vin, level))
sqlite3.OperationalError: database is locked
2025-04-29 16:45:00,362 :: INFO :: 172.23.0.1 - - [29/Apr/2025 16:45:00] "GET /get_vehicleinfo/MYVIN?from_cache=1 HTTP/1.1" 200 -
2025-04-29 16:46:59,752 :: ERROR :: refresh_vehicle_info: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 128, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 111, in get_vehicle_info
    self.record_info(car)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 216, in record_info
    Database.record_battery_soh(car.vin, charge_date, soh)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/repository/db.py", line 285, in record_battery_soh
    conn.execute("INSERT INTO battery_soh(date, VIN, level) VALUES(?,?,?)", (date, vin, level))
sqlite3.OperationalError: database is locked
2025-04-29 16:49:00,999 :: ERROR :: refresh_vehicle_info: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 128, in __refresh_vehicle_info
    self.get_vehicle_info(car.vin)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 111, in get_vehicle_info
    self.record_info(car)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 216, in record_info
    Database.record_battery_soh(car.vin, charge_date, soh)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/repository/db.py", line 285, in record_battery_soh
    conn.execute("INSERT INTO battery_soh(date, VIN, level) VALUES(?,?,?)", (date, vin, level))
sqlite3.OperationalError: database is locked
2025-04-29 16:49:03,510 :: INFO :: save config change
2025-04-29 16:50:00,202 :: INFO :: 172.23.0.1 - - [29/Apr/2025 16:50:00] "GET /get_vehicleinfo/MYVIN?from_cache=1 HTTP/1.1" 200 -
`

**Comment by gwgittrash** [comment]
Same here, since change to version 3.5.6 in HACS Implementation.
Support would be very helpful... :(

**Comment by SabatoArdolino** [comment]
From few weeks I've same problem on my instance

**Comment by Bushrider** [comment]
Upgrading to 3.5.7 fixed the issue for me 
https://github.com/flobz/psa_car_controller/releases/tag/v3.5.7

**Comment by Bushrider** [comment]
Try to redo OTP config

**Comment by Scarry1990** [comment]
I have the same problem with version v3.5.7
