### ISSUE TITLE
Setting night_hour_start through web API breaks configuration and controller cannot start

### ISSUE THREAD

**Issue by grahamrjuk** [flobz/psa_car_controller#816]
**Describe the bug**
Trying to set `night_hour_start` in the `electricity_config` using the api. e.g. `http://localhost:5000/settings/electricity_config?night_hour_start=23h30` the configuration becomes unusable and I have had to re-install the PSA controller a couple of times.
I am using the controller within Home Assistant OS on a Raspberry Pi.

**To Reproduce**
1. what command did you use
  http://localhost:5000/settings/electricity_config?night_hour_start=23h30
2. when the bug append ?
3. Does it persist after restarting the program? 
  The bug became apparent when restarting the software after changing the configuration.
4. Does it persist after recreate config by going to http://server_address:port/config? 
  When the config is unusable the app will not run and I cannot access the config to correct it.

**Config file**
Give the anonymize content of the config file
`{"General": {"currency": "\u00a3", "length_unit": "km", "minimum_trip_length": 10.0, "export_format": "csv"}, "Electricity_config": {"day_price": 0.31, "night_price": 0.075, "night_hour_start": "23h30", "night_hour_end": null, "dc_charge_price": null, "high_speed_dc_charge_price": null, "high_speed_dc_charge_threshold": null, "charger_efficiency": 0.8942}}`

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
     Home Assistant OS running on Raspberry Pi
 - Brand and model of car
     Vauxhall Corsa-E
 - Application version (commit number, branch or tag)
    3.4.2
 - Log from http://server_address:port/log and browser console log
```
Containerised psa_car_controller loading...
2024-03-14 13:20:49,998 :: INFO :: App version 3.4.2
2024-03-14 13:20:51,187 :: INFO :: ["{'vin': 'XXXXXXXXXXXXXX', 'vehicle_id': 'XXXXXXXXXXXXX', 'label': 'corsa-e', 'brand': None, 'abrp_name': 'opel:corsae:20:50', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
2024-03-14 13:20:51,942 :: INFO :: save config change
2024-03-14 13:20:52,098 :: INFO :: ask wakeup to XXXXXXXXXXXXXX
2024-03-14 13:20:52,099 :: INFO :: topic: psa/RemoteServices/from/cid/XXXXXXXXXXXXXX/VehCharge/state: {'action': 'state'}
2024-03-14 13:20:52,190 :: INFO :: Connected with result code {'session present': 0}
2024-03-14 13:20:52,191 :: INFO :: subscribe to psa/RemoteServices/to/cid/XXXXXXXXXXXXXX/#
2024-03-14 13:20:52,192 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/XXXXXXXXXXXXXX
2024-03-14 13:20:52,419 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/XXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2024-03-14T13:20:52Z","vin":"XXXXXXXXXXXXXX","correlation_id":"XXXXXXXXXXXXXX","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2024-03-14 13:20:52,463 :: WARNING :: Can't get language
2024-03-14 13:20:52,542 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/XXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2024-03-14T13:20:52Z","vin":"XXXXXXXXXXXXXX","correlation_id":"XXXXXXXXXXXXXX","process_code":"901","process_message":"[process.901.vehicle.asleep.key]"}'
2024-03-14 13:20:55,527 :: INFO :: update_data
2024-03-14 13:20:58,104 :: INFO ::  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2024-03-14 13:20:58,190 :: ERROR :: Exception on /settings [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/api.py", line 187, in settings
    return json_response(APP.config.json())
  File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 504, in json
    return self.__config__.json_dumps(data, default=encoder, **dumps_kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/json.py", line 90, in pydantic_encoder
    raise TypeError(f"Object of type '{obj.__class__.__name__}' is not JSON serializable")
TypeError: Object of type 'Hour' is not JSON serializable
2024-03-14 13:20:58,209 :: INFO :: 192.168.1.178 - - [14/Mar/2024 13:20:58] "GET /settings HTTP/1.1" 500 -
2024-03-14 13:21:01,708 :: ERROR :: Exception on /settings [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/api.py", line 187, in settings
    return json_response(APP.config.json())
  File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 504, in json
    return self.__config__.json_dumps(data, default=encoder, **dumps_kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/json.py", line 90, in pydantic_encoder
    raise TypeError(f"Object of type '{obj.__class__.__name__}' is not JSON serializable")
TypeError: Object of type 'Hour' is not JSON serializable
2024-03-14 13:21:01,713 :: INFO :: 192.168.1.178 - - [14/Mar/2024 13:21:01] "GET /settings HTTP/1.1" 500 -
```

**Additional context**
I have looked in other issues and in the FAQ and can't see anything like this - apologies if an answer is already available.
So far I haven't managed to use ssh to get to the admin port on the Pi (22222) to get access to the docker container directly.

**Comment by zazazouthecat** [comment]
I confirm,
Same issue.

After set  night_hour_start 
Api return "Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

Log :
```
2024-03-16 17:04:11,138 :: ERROR :: Exception on /settings/electricity_config [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/api.py", line 182, in settings_section
    return json_response(config_section.json())
  File "pydantic/main.py", line 504, in pydantic.main.BaseModel.json
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "pydantic/json.py", line 90, in pydantic.json.pydantic_encoder
TypeError: Object of type 'Hour' is not JSON serializable
2024-03-16 17:04:11,138 :: ERROR :: Exception on /settings/electricity_config [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/api.py", line 182, in settings_section
    return json_response(config_section.json())
  File "pydantic/main.py", line 504, in pydantic.main.BaseModel.json
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "pydantic/json.py", line 90, in pydantic.json.pydantic_encoder
TypeError: Object of type 'Hour' is not JSON serializable
2024-03-16 17:04:11,144 :: INFO :: 172.30.32.1 - - [16/Mar/2024 17:04:11] "[35m[1mGET /settings/electricity_config HTTP/1.1[0m" 500 -
```

**Comment by grahamrjuk** [comment]
I have confirmed that the app doesn't crash anymore for me when `night hour start` is set.
Thank you :-)
