### ISSUE TITLE
Old data from trips/charges api call

### ISSUE THREAD

**Issue by vineethktpla** [flobz/psa_car_controller#829]
I got these values when i called the charges api call after the update. 
same for trips api as well
Its very old data. How to get the latest one
![image](https://github.com/flobz/psa_car_controller/assets/146456863/c92928ba-7286-4e96-9417-ce2c21ee57fa)

This is in home assistant adon

In windows cli I get

2024-03-26 10:22:13,514 :: ERROR :: Exception on /vehicles/trips [GET]
Traceback (most recent call last):
  File "C:\Users\vipaz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vipaz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vipaz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vipaz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vipaz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\psa_car_controller\web\view\api.py", line 195, in get_trips
    trips = trips_by_vin[car.vin]
            ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'VR***XZNJ****3'

**Comment by vineethktpla** [comment]
Found the issue
 in HA use json_attributes_path: $.[-1:] to get the last value from the response
 
  - resource: "http://localhost:5000/vehicles/chargings"
    scan_interval: 10
    sensor:
    - name: e2008_chargings
      unique_id: e2008_chargings
      value_template: 'OK'
      json_attributes_path: $.[-1:]
      json_attributes:
         - start_at
         - stop_at
         - duration_min
         - duration_str
         - start_level
         - end_level
         - kw
         - price
         - charging_mode
         - mileage
