### ISSUE TITLE
Can not get it to run

### ISSUE THREAD

**Issue by GeyerA** [flobz/psa_car_controller#868]
Dear all,
I am on PI4 Debian (Openhabian) and followed installation instructions. When I do start using

`psa-car-controller --web-conf`

I see

`2024-04-30 13:43:41,041 :: INFO :: App version 3.5.0
2024-04-30 13:43:41,042 :: ERROR :: No config file
/home/openhabian/.local/lib/python3.7/site-packages/pandas/compat/_optional.py:138: UserWarning:

Pandas requires version '2.7.0' or newer of 'numexpr' (version '2.6.9' currently installed).

2024-04-30 13:43:44,184 :: INFO :: update_data
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/openhabian/.local/lib/python3.7/site-packages/psa_car_controller/web/app.py", line 51, in start_app
    run(config_flask(*args, **kwargs))
  File "/home/openhabian/.local/lib/python3.7/site-packages/psa_car_controller/web/app.py", line 86, in config_flask
    importlib.import_module(view)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/openhabian/.local/lib/python3.7/site-packages/psa_car_controller/web/view/views.py", line 366, in <module>
    update_trips()
  File "/home/openhabian/.local/lib/python3.7/site-packages/psa_car_controller/web/view/views.py", line 181, in update_trips
    conn = Database.get_db(update_callback=False)
  File "/home/openhabian/.local/lib/python3.7/site-packages/psa_car_controller/psacc/repository/db.py", line 148, in get_db
    Database.init_db(conn)
  File "/home/openhabian/.local/lib/python3.7/site-packages/psa_car_controller/psacc/repository/db.py", line 122, in init_db
    Database.clean_battery(conn)
  File "/home/openhabian/.local/lib/python3.7/site-packages/psa_car_controller/psacc/repository/db.py", line 160, in clean_battery
    conn.execute("DELETE FROM battery WHERE start_level >= end_level-1;")
sqlite3.OperationalError: attempt to write a readonly database
`

Any idea?

**Comment by GeyerA** [comment]
Update, found this in the FAQ.

`sudo chown openhabian: -R .`

Now looks like this

`2024-04-30 13:49:20,648 :: INFO :: App version 3.5.0
2024-04-30 13:49:20,649 :: ERROR :: No config file
/home/openhabian/.local/lib/python3.7/site-packages/pandas/compat/_optional.py:138: UserWarning:

Pandas requires version '2.7.0' or newer of 'numexpr' (version '2.6.9' currently installed).

2024-04-30 13:49:22,651 :: INFO :: update_data
2024-04-30 13:49:23,781 :: INFO :: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
2024-04-30 13:49:23,783 :: INFO :: Press CTRL+C to quit
`

**Comment by Waxolunist** [comment]
Per default it only listens to the local ip. To have a more general solution try -l 0.0.0.0
