### ISSUE TITLE
ERROR beim starten

### ISSUE THREAD

**Issue by Geri-G93** [flobz/psa_car_controller#885]
folgende Meldung kommt bei mir beim start

> 2024-05-22 16:54:16,590 :: ERROR :: on_mqtt_message:
Traceback (most recent call last):
  File "C:\PY\Lib\site-packages\psa_car_controller\psa\RemoteClient.py", line 96, in _fix_not_updated_api
    if car and car.status.get_energy('Electric').charging.status != INPROGRESS:
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_energy'

<
nach dem Fehler scheint er auch keine mqtt Nachichten zu erhalten was ich die letzten Tage beobachtet habe
komplette log nach start:

> 2024-05-22 16:53:18,238 :: INFO :: App version 3.5.1
2024-05-22 16:53:24,972 :: INFO :: ["{'vin': 'FAHRGESTELLNUMMER', 'vehicle_id': 'GIBT ES NICHT', 'label': 'corsa-e', 'brand': None, 'abrp_name': 'opel:corsae:20:50', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
2024-05-22 16:53:31,347 :: INFO :: ask wakeup to FAHRGESTELLNUMMER
2024-05-22 16:53:31,347 :: INFO :: topic: psa/RemoteServices/from/cid/OV-ACNT200009197715/VehCharge/state: {'action': 'state'}
2024-05-22 16:53:31,456 :: INFO :: Connected with result code {'session present': 0}
2024-05-22 16:53:31,456 :: INFO :: subscribe to psa/RemoteServices/to/cid/OV-ACNT200009197715/#
2024-05-22 16:53:31,456 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/FAHRGESTELLNUMMER
2024-05-22 16:53:37,146 :: INFO :: save config change
2024-05-22 16:53:37,269 :: WARNING :: Can't get language
2024-05-22 16:53:37,378 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-ACNT200009197715/VehCharge/state b'{"resp_date":"2024-05-22T14:52:56Z","vin":"FAHRGESTELLNUMMER","correlation_id":"9c3fff27eace49bc93b37b34dfb0ba1420240522145337146","return_code":"400","reason":"[authorization.denied.cvs.from.uin.response.ko.key]"}'
2024-05-22 16:53:46,259 :: WARNING :: last request is send again, token was expired
2024-05-22 16:53:47,925 :: INFO :: update_data
2024-05-22 16:53:52,628 :: INFO :: ←[31m←[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.←[0m
  Running on http://127.0.0.1:5000
2024-05-22 16:53:52,628 :: INFO :: ←[33mPress CTRL+C to quit←[0m
2024-05-22 16:53:53,269 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-ACNT200009197715/VehCharge/state/ProcessManagement b'{"process_date":"2024-05-22T14:53:12Z","vin":"FAHRGESTELLNUMMER","correlation_id":"be0253b86eba4692866060830e0b561a20240522145353019","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2024-05-22 16:53:53,426 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-ACNT200009197715/VehCharge/state/ProcessManagement b'{"process_date":"2024-05-22T14:53:12Z","vin":"FAHRGESTELLNUMMER","correlation_id":"be0253b86eba4692866060830e0b561a20240522145353019","process_code":"901","process_message":"[process.901.vehicle.asleep.key]"}'
2024-05-22 16:54:07,184 :: INFO :: save config change
2024-05-22 16:54:16,587 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/FAHRGESTELLNUMMER b'{"date":"2024-05-22T14:53:20Z","etat_res_elec":0,"precond_state":{"available":1,"programs":{"program1":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program2":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0,"aff":1},"charging_state":{"program":{"hour":0,"minute":0},"available":1,"remaining_time":635,"rate":0,"cable_detected":1,"soc_batt":85,"autonomy_zev":278,"type":0,"aff":1,"hmi_state":0,"mode":2},"stolen_state":0,"vin":"FAHRGESTELLNUMMER","reason":0,"signal_quality":5,"sev_stop_date":"2024-05-22T03:20:34Z","fds":["NDR01","NAE01","NBM01","NAU01","NCG01","NAO01","NAS01"],"sev_state":0,"obj_counter":1,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2024-05-22 16:54:16,590 :: ERROR :: on_mqtt_message:
Traceback (most recent call last):
  File "C:\PY\Lib\site-packages\psa_car_controller\psa\RemoteClient.py", line 96, in _fix_not_updated_api
    if car and car.status.get_energy('Electric').charging.status != INPROGRESS:
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_energy'
2024-05-22 16:54:16,785 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-ACNT200009197715/VehCharge/state/ProcessManagement b'{"process_date":"2024-05-22T14:53:35Z","vin":"FAHRGESTELLNUMMER","correlation_id":"be0253b86eba4692866060830e0b561a20240522145353019","process_code":"903","process_message":"[process.903.request.forwarded.to.vehicle.key]"}'
2024-05-22 16:54:16,847 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/FAHRGESTELLNUMMER b'{"date":"2024-05-22T14:53:22Z","etat_res_elec":0,"precond_state":{"available":1,"programs":{"program1":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program2":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0,"aff":1},"charging_state":{"program":{"hour":0,"minute":0},"available":1,"remaining_time":635,"rate":0,"cable_detected":1,"soc_batt":85,"autonomy_zev":278,"type":0,"aff":1,"hmi_state":0,"mode":2},"stolen_state":0,"vin":"FAHRGESTELLNUMMER","reason":3,"signal_quality":5,"sev_stop_date":"2024-05-22T03:20:34Z","fds":["NDR01","NAE01","NBM01","NAU01","NCG01","NAO01","NAS01"],"sev_state":0,"obj_counter":2,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2024-05-22 16:54:16,847 :: ERROR :: on_mqtt_message:
Traceback (most recent call last):
  File "C:\PY\Lib\site-packages\psa_car_controller\psa\RemoteClient.py", line 96, in _fix_not_updated_api
    if car and car.status.get_energy('Electric').charging.status != INPROGRESS:
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_energy'
2024-05-22 16:54:17,019 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/FAHRGESTELLNUMMER b'{"date":"2024-05-22T14:53:23Z","etat_res_elec":0,"precond_state":{"available":1,"programs":{"program1":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program2":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0,"aff":1},"charging_state":{"program":{"hour":0,"minute":0},"available":1,"remaining_time":635,"rate":0,"cable_detected":1,"soc_batt":85,"type":0,"aff":1,"hmi_state":0,"mode":2},"stolen_state":0,"vin":"FAHRGESTELLNUMMER","reason":4,"signal_quality":5,"sev_stop_date":"2024-05-22T03:20:34Z","fds":["NDR01","NAE01","NBM01","NAU01","NCG01","NAO01","NAS01"],"sev_state":0,"obj_counter":3,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2024-05-22 16:54:17,019 :: ERROR :: on_mqtt_message:
Traceback (most recent call last):
  File "C:\PY\Lib\site-packages\psa_car_controller\psa\RemoteClient.py", line 96, in _fix_not_updated_api
    if car and car.status.get_energy('Electric').charging.status != INPROGRESS:
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_energy'
2024-05-22 16:54:17,863 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-ACNT200009197715/VehCharge/state b'{"resp_date":"2024-05-22T14:53:36Z","vin":"FAHRGESTELLNUMMER","correlation_id":"be0253b86eba4692866060830e0b561a20240522145353019","return_code":"0"}'
2024-05-22 16:54:21,050 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/FAHRGESTELLNUMMER b'{"date":"2024-05-22T14:53:31Z","etat_res_elec":0,"precond_state":{"available":1,"programs":{"program1":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program2":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0,"aff":1},"charging_state":{"program":{"hour":0,"minute":0},"available":1,"remaining_time":635,"rate":0,"cable_detected":1,"soc_batt":85,"autonomy_zev":280,"type":0,"aff":1,"hmi_state":0,"mode":2},"stolen_state":0,"vin":"FAHRGESTELLNUMMER","reason":4,"signal_quality":5,"sev_stop_date":"2024-05-22T03:20:34Z","fds":["NDR01","NAE01","NBM01","NAU01","NCG01","NAO01","NAS01"],"sev_state":0,"obj_counter":4,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2024-05-22 16:54:21,050 :: ERROR :: on_mqtt_message:
Traceback (most recent call last):
  File "C:\PY\Lib\site-packages\psa_car_controller\psa\RemoteClient.py", line 96, in _fix_not_updated_api
    if car and car.status.get_energy('Electric').charging.status != INPROGRESS:
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_energy'
2024-05-22 16:57:01,459 :: INFO :: 127.0.0.1 - - [22/May/2024 16:57:01] "GET /get_vehicleinfo/FAHRGESTELLNUMMER HTTP/1.1" 200 -

config:
>{
    "abrp": {
        "abrp_enable_vin": [],
        "token": ""
    },
    "client_id": "07364655-ZENS-4194-8158-6b035ac2c24c",
    "client_secret": "****7lC5kF5qN7tM0wT8kE3cW1dP0wC5pI6vC0sQ5iP5cN8cJ8",
    "co2_signal_api": null,
    "country_code": "DE",
    "customer_id": "OP-ACNT200009ZENS",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2COpel",
    "refresh_token": "d0b013be-3513-ZENS-b6ea-c327b3c85ad4",
    "remote_refresh_token": "ZENS-656a-4907-8d88-3dd349eb97de",
    "weather_api": null
}

**Comment by flobz** [comment]
Close as it doesn't follow the bug template
