### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_energy' at startup

### ISSUE THREAD

**Issue by grahamrjuk** [flobz/psa_car_controller#893]
**Describe the bug**

At start-up, at least with Home Assistant, the following error is received:
```
2024-05-28 20:52:45,283 :: ERROR :: on_mqtt_message:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 96, in _fix_not_updated_api
    if car and car.status.get_energy('Electric').charging.status != INPROGRESS:
AttributeError: 'NoneType' object has no attribute 'get_energy'
```

**To Reproduce**
1. what command did you use
    Start PSACC in Home Assistant, with a vehicle configured and the OTP process successfully completed
2. when the bug append ?
   Only seen from release 3.5.1
3. Does it persist after restarting the program?
   Yes
4. Does it persist after recreate config by going to http://server_address:port/config?
   Yes 

**Config file**
config.json:
```
{
    "abrp": {
        "abrp_enable_vin": [],
        "token": ""
    },
    "client_id": "removed",
    "client_secret": "removed",
    "co2_signal_api": null,
    "country_code": "GB",
    "customer_id": "VX-ACNTXXXXXXXXXXXXX",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2CVauxhall",
    "refresh_token": "removed",
    "remote_refresh_token": "removed",
    "weather_api": null
}
```

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
   Raspberry Pi with Home Assistant
 - Brand and model of car
    Vauxhall Corsa E
 - Application version (commit number, branch or tag)
    3.5.1
 - Log from http://server_address:port/log and browser console log
```
Containerised psa_car_controller loading...
2024-05-28 20:52:16,909 :: INFO :: App version 3.5.1
2024-05-28 20:52:19,869 :: INFO :: ["{'vin': 'removed', 'vehicle_id': 'removed', 'label': 'corsa-e', 'brand': None, 'abrp_name': 'opel:corsae:20:50', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
2024-05-28 20:52:20,864 :: INFO :: ask wakeup to removed
2024-05-28 20:52:20,865 :: INFO :: topic: psa/RemoteServices/from/cid/OV-removed/VehCharge/state: {'action': 'state'}
2024-05-28 20:52:20,953 :: INFO :: Connected with result code {'session present': 0}
2024-05-28 20:52:20,954 :: INFO :: subscribe to psa/RemoteServices/to/cid/OV-removed/#
2024-05-28 20:52:20,958 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/removed
2024-05-28 20:52:21,539 :: INFO :: save config change
2024-05-28 20:52:21,590 :: WARNING :: Can't get language
2024-05-28 20:52:21,778 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-removed/VehCharge/state/ProcessManagement b'{"process_date":"2024-05-28T19:52:21Z","vin":"removed","correlation_id":"removed","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2024-05-28 20:52:21,938 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-removed/VehCharge/state/ProcessManagement b'{"process_date":"2024-05-28T19:52:21Z","vin":"removed","correlation_id":"removed","process_code":"901","process_message":"[process.901.vehicle.asleep.key]"}'
2024-05-28 20:52:26,413 :: INFO :: update_data
2024-05-28 20:52:31,044 :: INFO ::  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2024-05-28 20:52:45,184 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/removed b'{"date":"2024-05-28T19:52:31Z","etat_res_elec":0,"precond_state":{"available":1,"programs":{"program1":{"hour":9,"minute":20,"on":0,"day":[0,0,0,0,0,0,1]},"program2":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0,"aff":1},"charging_state":{"program":{"hour":4,"minute":0},"available":1,"remaining_time":635,"rate":0,"cable_detected":1,"soc_batt":34,"autonomy_zev":92,"type":0,"aff":1,"hmi_state":0,"mode":2},"stolen_state":0,"vin":"removed","reason":0,"signal_quality":2,"sev_stop_date":"2024-05-28T19:32:07Z","fds":["NDR01","NBM01","NCG01","NAO01","NAS01"],"sev_state":0,"obj_counter":1,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2024-05-28 20:52:45,237 :: ERROR :: on_mqtt_message:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 96, in _fix_not_updated_api
    if car and car.status.get_energy('Electric').charging.status != INPROGRESS:
AttributeError: 'NoneType' object has no attribute 'get_energy'
2024-05-28 20:52:45,279 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/removed b'{"date":"2024-05-28T19:52:34Z","etat_res_elec":0,"precond_state":{"available":1,"programs":{"program1":{"hour":9,"minute":20,"on":0,"day":[0,0,0,0,0,0,1]},"program2":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0,"aff":1},"charging_state":{"program":{"hour":4,"minute":0},"available":1,"remaining_time":635,"rate":0,"cable_detected":1,"soc_batt":34,"autonomy_zev":92,"type":0,"aff":1,"hmi_state":0,"mode":2},"stolen_state":0,"vin":"removed","reason":3,"signal_quality":2,"sev_stop_date":"2024-05-28T19:32:07Z","fds":["NDR01","NBM01","NCG01","NAO01","NAS01"],"sev_state":0,"obj_counter":2,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2024-05-28 20:52:45,281 :: ERROR :: on_mqtt_message:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 96, in _fix_not_updated_api
    if car and car.status.get_energy('Electric').charging.status != INPROGRESS:
AttributeError: 'NoneType' object has no attribute 'get_energy'
2024-05-28 20:52:45,282 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/removed b'{"date":"2024-05-28T19:52:34Z","etat_res_elec":0,"precond_state":{"available":1,"programs":{"program1":{"hour":9,"minute":20,"on":0,"day":[0,0,0,0,0,0,1]},"program2":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0,"aff":1},"charging_state":{"program":{"hour":4,"minute":0},"available":1,"remaining_time":635,"rate":0,"cable_detected":2,"soc_batt":34,"type":0,"aff":1,"hmi_state":0,"mode":2},"stolen_state":0,"vin":"removed","reason":4,"signal_quality":2,"sev_stop_date":"2024-05-28T19:32:07Z","fds":["NDR01","NBM01","NCG01","NAO01","NAS01"],"sev_state":0,"obj_counter":3,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2024-05-28 20:52:45,283 :: ERROR :: on_mqtt_message:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 96, in _fix_not_updated_api
    if car and car.status.get_energy('Electric').charging.status != INPROGRESS:
AttributeError: 'NoneType' object has no attribute 'get_energy'
2024-05-28 20:52:45,284 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-removed/VehCharge/state/ProcessManagement b'{"process_date":"2024-05-28T19:52:45Z","vin":"removed","correlation_id":"removed","process_code":"903","process_message":"[process.903.request.forwarded.to.vehicle.key]"}'
2024-05-28 20:52:45,286 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/OV-removed/VehCharge/state b'{"resp_date":"2024-05-28T19:52:45Z","vin":"removed","correlation_id":"removed","return_code":"0"}'
2024-05-28 20:52:48,225 :: INFO :: mqtt msg received: psa/RemoteServices/events/MPHRTServices/removed b'{"date":"2024-05-28T19:52:47Z","etat_res_elec":0,"precond_state":{"available":1,"programs":{"program1":{"hour":9,"minute":20,"on":0,"day":[0,0,0,0,0,0,1]},"program2":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program3":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]},"program4":{"hour":34,"minute":7,"on":0,"day":[0,0,0,0,0,0,0]}},"asap":0,"status":0,"aff":1},"charging_state":{"program":{"hour":4,"minute":0},"available":1,"remaining_time":0,"rate":0,"cable_detected":0,"soc_batt":34,"autonomy_zev":92,"type":0,"aff":1,"hmi_state":0,"mode":2},"stolen_state":0,"vin":"removed","reason":4,"signal_quality":2,"sev_stop_date":"2024-05-28T19:32:07Z","fds":["NDR01","NBM01","NCG01","NAO01","NAS01"],"sev_state":0,"obj_counter":4,"privacy_customer":0,"privacy_applicable":0,"privacy_applicable_max":2,"superlock_state":0}'
2024-05-28 20:54:08,302 :: INFO :: new position recorded for removed
2024-05-28 20:54:08,304 :: INFO :: update_data
2024-05-28 20:54:09,726 :: INFO :: 192.168.1.173 - - [28/May/2024 20:54:09] "GET /get_vehicleinfo/removed?from_cache=1 HTTP/1.1" 200 -
```

**Additional context**
At the point the error occurs it looks like car is not None, but car.status is still None and the call fails.

I don't know if this is related to the problem refreshing data.

**Comment by hannesmeinlschmidt** [comment]
The issue has popped up for me as well on version 3.7.9.
