### ISSUE TITLE
Email address not accepted

### ISSUE THREAD

**Issue by shaft8472** [flobz/psa_car_controller#899]
**Describe the bug**
My email address contains xxxxxxxx+peugeot@xxxx.com
As far as I can tell the addon in Home Assistant does not like this. Peugeot-app works fine with it.

Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 59, in __init__ self.token = res.json()["accessToken"] KeyError: 'accessToken' HOST_BRANDID : https://id-dcr.peugeot.com/mobile-services sitecode: AP_NL_ESP{"returnCode":"FIELDS_ERROR","fields":{"USR_EMAIL":"FORM_ERROR_USR_EMAIL"}}

**To Reproduce**
1. Tried to login through the webinterface.

**Environment (please complete the following information):**
 - OS: Home Assistant
 - Peugeot 3008
 - Application version: v3.5.1

Log:
`2024-06-16 15:51:19,238 :: INFO :: 172.30.32.1 - - [16/Jun/2024 15:51:19] "POST /_dash-update-component HTTP/1.1" 200 -
Containerised psa_car_controller loading...
2024-06-16 15:53:03,032 :: INFO :: App version 3.5.1
2024-06-16 15:53:03,032 :: ERROR :: No config file
2024-06-16 15:53:03,035 :: WARNING :: Can't get language
2024-06-16 15:53:04,070 :: INFO :: update_data
2024-06-16 15:53:04,104 :: INFO ::  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2024-06-16 15:53:10,625 :: INFO :: 172.30.32.1 - - [16/Jun/2024 15:53:10] "GET / HTTP/1.1" 200 -
2024-06-16 15:53:10,713 :: INFO :: 172.30.32.1 - - [16/Jun/2024 15:53:10] "GET /_dash-layout HTTP/1.1" 200 -
2024-06-16 15:53:10,720 :: INFO :: 172.30.32.1 - - [16/Jun/2024 15:53:10] "GET /_dash-dependencies HTTP/1.1" 200 -
2024-06-16 15:53:10,744 :: INFO :: 172.30.32.1 - - [16/Jun/2024 15:53:10] "POST /_dash-update-component HTTP/1.1" 200 -
2024-06-16 15:53:10,768 :: INFO :: 172.30.32.1 - - [16/Jun/2024 15:53:10] "GET /config_login HTTP/1.1" 200 -
2024-06-16 15:53:10,858 :: INFO :: 172.30.32.1 - - [16/Jun/2024 15:53:10] "GET /_dash-layout HTTP/1.1" 200 -
2024-06-16 15:53:10,860 :: INFO :: 172.30.32.1 - - [16/Jun/2024 15:53:10] "GET /_dash-dependencies HTTP/1.1" 200 -
2024-06-16 15:53:10,884 :: INFO :: 172.30.32.1 - - [16/Jun/2024 15:53:10] "POST /_dash-update-component HTTP/1.1" 200 -
2024-06-16 15:53:10,903 :: INFO :: 172.30.32.1 - - [16/Jun/2024 15:53:10] "GET /assets/images/settings.svg HTTP/1.1" 200 -
2024-06-16 15:53:10,915 :: INFO :: 172.30.32.1 - - [16/Jun/2024 15:53:10] "POST /_dash-update-component HTTP/1.1" 204 -
2024-06-16 15:53:10,919 :: INFO :: 172.30.32.1 - - [16/Jun/2024 15:53:10] "POST /_dash-update-component HTTP/1.1" 204 -
2024-06-16 15:53:10,921 :: INFO :: 172.30.32.1 - - [16/Jun/2024 15:53:10] "POST /_dash-update-component HTTP/1.1" 200 -
2024-06-16 15:53:30,094 :: INFO :: Initial setup...
2024-06-16 15:53:37,830 :: ERROR :: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 59, in __init__
    self.token = res.json()["accessToken"]
KeyError: 'accessToken'

HOST_BRANDID : https://id-dcr.peugeot.com/mobile-services sitecode: AP_NL_ESP{"returnCode":"FIELDS_ERROR","fields":{"USR_EMAIL":"FORM_ERROR_USR_EMAIL"}}
2024-06-16 15:53:37,831 :: ERROR :: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 59, in __init__
    self.token = res.json()["accessToken"]
KeyError: 'accessToken'

HOST_BRANDID : https://id-dcr.peugeot.com/mobile-services sitecode: AP_NL_ESP{"returnCode":"FIELDS_ERROR","fields":{"USR_EMAIL":"FORM_ERROR_USR_EMAIL"}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 59, in __init__
    self.token = res.json()["accessToken"]
KeyError: 'accessToken'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_views.py", line 137, in connectPSA
    INITIAL_SETUP = InitialSetup(app_name, email, password, countrycode)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 68, in __init__
    raise ConnectionError(msg) from ex
ConnectionError: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 59, in __init__
    self.token = res.json()["accessToken"]
KeyError: 'accessToken'

HOST_BRANDID : https://id-dcr.peugeot.com/mobile-services sitecode: AP_NL_ESP{"returnCode":"FIELDS_ERROR","fields":{"USR_EMAIL":"FORM_ERROR_USR_EMAIL"}}
2024-06-16 15:53:37,835 :: INFO :: 172.30.32.1 - - [16/Jun/2024 15:53:37] "POST /_dash-update-component HTTP/1.1" 200 -`

**Comment by rburgst** [comment]
same problem here.

**Comment by jurahudak** [comment]
Got sick of this today, lowered my head and went on with e-mail address change from xyz+peugeot@gmail to just xyz@gmail, and not-so-much-surprisingly it started working. On one hand I'm happy I got it working (and my car integrated into HA), on the other hand sad with the state of IT/programming on PSA side...

**Comment by rburgst** [comment]
I managed to get a access and refresh token from evcc, is there a way to simply skip the ui configuration and create a valid `config.json` myself?

**Comment by jurahudak** [comment]
Droid app restart, or something, but the first re-login was with the still with the +, changed to without, and I got successfully logged in again. Despite that (czech) support mentioned it's not possible, hm.

I went through the UI config.
