### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by larronni** [flobz/psa_car_controller#908]
**Describe the bug**
No data in the dashboard
All I get is the SOC, and charge data. No summary info, no trips or no map data. 
In the log, all I get is "new position recorded" and it says it update data

**To Reproduce**
I have reinstalled the plugin, I have tried the plugin on two different Home Assistant installations, I have tried to configure/OTP configure several times

**Config file**
Can't access the config file on Home Assistant... ?

**Environment (please complete the following information):**
 - OS: Home Assistant
 - Brand and model of car: DS3
 - Application version (commit number, branch or tag) : 3.5.1
 - Log from http://server_address:port/log and browser console log
2024-07-04 11:45:24,447 :: INFO :: new position recorded for VRxxxxxxxxxxxx
2024-07-04 11:45:24,457 :: INFO :: update_data
2024-07-04 11:47:24,464 :: INFO :: new position recorded for VRxxxxxxxxxxxx
2024-07-04 11:47:24,473 :: INFO :: update_data
2024-07-04 11:49:24,317 :: INFO :: new position recorded for VRxxxxxxxxxxxx
2024-07-04 11:49:24,327 :: INFO :: update_data

**Comment by larronni** [comment]
Did a reinstall of the add-on, and now I get this errors in the log (tried OTP several times)


2024-07-05 07:41:52,927 :: ERROR :: Error during activation: {'newversion': None, 'newversionurl': None, 'err': 'NOK:CODE'}
2024-07-05 07:41:55,501 :: WARNING :: remote_refresh_token isn't defined
2024-07-05 07:41:56,649 :: ERROR :: Error during activation: {'err': 'NOK:FORBIDDEN'}
2024-07-05 07:41:56,972 :: ERROR :: Can't refresh remote token, please redo otp procedure
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 177, in _refresh_remote_token
self._get_remote_access_token(otp_code)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 208, in _get_remote_access_token
self.remoteCredentials.access_token = data["access_token"]
KeyError: 'access_token'
2024-07-05 07:41:56,973 :: ERROR :: Can't configure MQTT Client

**Comment by thsa759** [comment]
I have exactly the same issue.

I'm not an expert about all this login oauth stuff but for me it looks like that PSA has changed something regarding the oauth code.

**Comment by thsa759** [comment]
> I have exactly the same issue.
> 
> I'm not an expert about all this login oauth stuff but for me it looks like that PSA has changed something regarding the oauth code.

Tried again today with a different browser and it worked for me!

**Comment by larronni** [comment]
Two things that solved this for me
1) OTP part - the code, is the same code you have in the APP (the first code comes from the WEB, and the second is your PIN in the app)
2) I installed EEVEE app on my phone and connected my car to this. Then almost everything came to live (trips, maps, charging info etc)
