### ISSUE TITLE
"EOFError: Ran out of Input" after trying new login method

### ISSUE THREAD

**Issue by der-peer** [flobz/psa_car_controller#914]
**Describe the bug**
I tried the new login method, input everything. When saving, there came "Ran out of input". Retried several times.
Then I tried to update the docker container, maybe there had been something new? But after that, the container does not come up. Log says:
```
Containerised psa_car_controller loading...
2024-07-11 09:40:02,348 :: INFO :: App version 3.5.1
2024-07-11 09:40:07,652 :: INFO :: ["{'vin': 'V[...]3', 'vehicle_id': '1[...]6', 'label': 'e-208', 'brand': 'Peugeot', 'abrp_name': 'peugeot:e208:20:50', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
Traceback (most recent call last):
  File "/usr/local/bin/psa-car-controller", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/__main__.py", line 20, in main
    app.load_app()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/car_controller.py", line 116, in load_app
    self.start_remote_control()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/car_controller.py", line 65, in start_remote_control
    self.myp.remote_client.start()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 105, in start
    if self.load_otp():
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 256, in load_otp
    otp_session = load_otp()                                                                                                                                                                                       File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/otp/otp.py", line 321, in load_otp
    return pickle.load(input_file)                                                                                                                                                                               EOFError: Ran out of input
2024-07-11 09:40:07,653 :: INFO :: save config change
```

**To Reproduce**
1. what command did you use
`docker restart psa_car_controller`
3. when the bug append ?
4. Does it persist after restarting the program? 
`yes`
6. Does it persist after recreate config by going to http://server_address:port/config? 
`Does not apply since container does not start`

**Config file**
```
{
    "abrp": {
        "abrp_enable_vin": [],
        "token": ""
    },
    "client_id": "1[...]0",
    "client_secret": "T[...]1",
    "co2_signal_api": null,
    "country_code": "DE",
    "customer_id": "AP-ACNT2[...]9",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2CPeugeot",
    "refresh_token": "a[...]3",
    "remote_refresh_token": null,
    "weather_api": "f[...]1"
}
```

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 `Docker on Debian 12`
 - Brand and model of car
 `Peugeot e208 2020`
 - Application version (commit number, branch or tag)
 `3.5.1`
 - Log from http://server_address:port/log and browser console log
 `see above`

**Comment by danros3** [comment]
Also Here... Till friday all was running, but now, on container log I can see this

EOFError: Ran out of input
2024-07-14 19:10:46,539 :: INFO :: save config change
Containerised psa_car_controller loading...
2024-07-14 19:11:13,395 :: INFO :: App version 3.5.1
2024-07-14 19:11:14,211 :: INFO :: ["{'vin': '*********************', 'vehicle_id': '*************', 'label': 'corsa-e', 'brand': 'C', 'abrp_name': 'opel:corsae:20:50', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
Traceback (most recent call last):
  File "/usr/local/bin/psa-car-controller", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/__main__.py", line 20, in main
    app.load_app()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/car_controller.py", line 116, in load_app
    self.start_remote_control()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/car_controller.py", line 65, in start_remote_control
    self.myp.remote_client.start()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 105, in start
    if self.load_otp():
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 256, in load_otp
    otp_session = load_otp()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/otp/otp.py", line 321, in load_otp
    return pickle.load(input_file)
EOFError: Ran out of input
2024-07-14 19:11:14,215 :: INFO :: save config change

Thank you

**Comment by der-peer** [comment]
Hello,
could please someone try to give a hint on this? The problem still persists.

Thanks!

![grafik](https://github.com/user-attachments/assets/cc2b270a-7826-4e0c-a58a-29cdfd2b7d3a)

**Comment by danros3** [comment]
Hi. No one have any hint regarding this?
Appreciate it.

Thank you.

**Comment by danros3** [comment]
Hi
I think i found the problem.
Mine errore saw: 
 File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/

But on my linux machine I have

 File "/usr/local/lib/python3.12/dist-packages/

without folder psa_car_controller/.....

So I think I need to change code to (1 option) point at folder I have, (point 2) change folder were psa_car save files.

So I'm asking to @flobz how can I change or solve this issue.

I'm sorry, I'm pretty new on pyton.

Thanks.
