### ISSUE TITLE
No vehicle in your account is compatible with this API, you vehicle is probably too old...

### ISSUE THREAD

**Issue by DavidFFerreira** [flobz/psa_car_controller#917]
Does not make anysense, I have the eC4 2020 in my citroen account. It was working before the update

![image](https://github.com/user-attachments/assets/7a34bc38-123d-4cd9-a368-e133510c00b0)

**Comment by DavidFFerreira** [comment]
@flobz can you check this please?

**Comment by robinalden** [comment]
I am trying to register a new vehicle for the first time, a new 2024 Citroen C3, and I also get a 'No vehicle in your account is compatible with this API, you vehicle is probably too old' message.  I too see a 404 in the logs.
```
2024-07-22 12:14:51,626 :: INFO :: save config change
2024-07-22 12:14:52,049 :: ERROR :: get_vehicles:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 140, in get_vehicles
res = self.api().get_vehicles_by_device()
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1331, in get_vehicles_by_device
(data) = self.get_vehicles_by_device_with_http_info(**kwargs) # noqa: E501
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1400, in get_vehicles_by_device_with_http_info
return self.api_client.call_api(
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 125, in call_api
raise e
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 107, in call_api
return self._ApiClient__call_api(resource_path, method,
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 157, in __call_api
response_data = self.request(
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 347, in request
return self.rest_client.GET(url,
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/rest.py", line 234, in GET
return self.request("GET", url,
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/rest.py", line 228, in request
raise ApiException(http_resp=r)
psa_car_controller.psa.connected_car_api.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Connection': 'close', 'Date': 'Mon, 22 Jul 2024 11:14:52 GMT', 'Content-Type': 'application/hal+json', 'Expires': '0', 'Cache-Control': 'no-store, no-cache, must-revalidate, private', 'Set-Cookie': 'rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Sun, 21-Jul-2024 11:14:51 GMT, JSESSIONID=YcXC53tWuIfZMYyXX2afmNZAgyL_131n2dMOnEJV; path=/, PSACountry=GB; Domain=.groupe-psa.com; Path=/', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Global-Transaction-ID': '08f333a5669e3f2b747b2f41'})
HTTP response body: {"uuid":"7130f23e-208a-49c2-8861-528b010a9ff1","code":40400,"message":"No vehicle found","timestamp":"2024-07-22T11:14:52.016Z"}

2024-07-22 12:14:52,052 :: ERROR :: finish_oauth:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_oauth.py", line 56, in finish_oauth
config_views.INITIAL_SETUP.connect(code)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 117, in connect
raise ValueError(
ValueError: No vehicle in your account is compatible with this API, you vehicle is probably too old...
````

**Comment by matthewturner** [comment]
I'm getting the same error when trying to connect to a new Vauxhall Corsa E 2024. In my case the car doesn't seem to be compatible with the My Vauxhall app as the app isn't showing battery status (or any other options).

I have opened a ticket with Vauxhall to see if the API needs updating.

**Comment by Blauenfeldt** [comment]
I have the same issue with my Citroën C3

**Comment by HiQual** [comment]
> I'm getting the same error when trying to connect to a new Vauxhall Corsa E 2024. In my case the car doesn't seem to be compatible with the My Vauxhall app as the app isn't showing battery status (or any other options).
> 
> I have opened a ticket with Vauxhall to see if the API needs updating.
> 
> Update: I've had a response back from Vauxhall. They said in my case it's to do with the global component shortage which forced them to swap out a specific component which is not currently supported by the API. They are working on an OTA update which will be installed automatically. No ETA on this, but I'll update here when I find out more.

Also for me with a new 2024 UK Corsa-e ..
![image](https://github.com/user-attachments/assets/15fadf6c-8ab9-41e6-956e-25d1fdf785ae)
(Using Docker)
I will also open a ticket with Vauxhall - thanks for the information.

**Comment by codeclinic** [comment]
I'm also getting this error when trying to setup the HASS plugin for my 2022 Peugeot e-Traveller.

The plugin used to work without issues when I last used Home Assistant / this add-on a few months ago.

**Comment by codeclinic** [comment]
@flobz It looks like this issue is caused simply because the car_models.yml file doesn't contain an exact match.

For example, I have the Peugeot e-Traveller 75Kwh but the car_models.yml file only has the 50KWh version.

How can we get all the relevant info to add the 75KWh version to the yml?

**Comment by harvindhillon** [comment]
Hi,

I am getting the same with a 2024 Peugeot e308

`2024-09-20 08:49:07,310 :: ERROR :: get_vehicles:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 140, in get_vehicles
    res = self.api().get_vehicles_by_device()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1331, in get_vehicles_by_device
    (data) = self.get_vehicles_by_device_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1400, in get_vehicles_by_device_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 125, in call_api
    raise e
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 107, in call_api
    return self._ApiClient__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 157, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 347, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/rest.py", line 234, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/rest.py", line 228, in request
    raise ApiException(http_resp=r)
psa_car_controller.psa.connected_car_api.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Connection': 'close', 'Date': 'Fri, 20 Sep 2024 08:49:07 GMT', 'Content-Type': 'application/hal+json', 'Expires': '0', 'Cache-Control': 'no-store, no-cache, must-revalidate, private', 'Set-Cookie': 'rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Thu, 19-Sep-2024 08:49:07 GMT, JSESSIONID=fS8EQ_N97XJsV4tKFnQDNGo14vLtoN1wsW_8eDSw; path=/, PSACountry=IE; Domain=.groupe-psa.com; Path=/', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Global-Transaction-ID': '08f333a566ed37031c687eaf'})
HTTP response body: {"uuid":"29743b78-cacb-4140-934b-674f3aaf31f7","code":40400,"message":"No vehicle found","timestamp":"2024-09-20T08:49:07.272Z"}

2024-09-20 08:49:07,317 :: ERROR :: finish_oauth:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_oauth.py", line 56, in finish_oauth
    config_views.INITIAL_SETUP.connect(code)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 117, in connect
    raise ValueError(
ValueError: No vehicle in your account is compatible with this API, you vehicle is probably too old...`

**Comment by HiQual** [comment]
Hello @matthewturner @Blauenfeldt @frostworx @robinalden @harvindhillon   Did any of you make any progress resolving the wrong telematics module?  Is so please share your experience.
Many thanks.

**Comment by kerozen54** [comment]
Hi all
I got the same problem with e fresh (well from 02/2024) new DS DS 3 Etense (not the crossback, but the new model).
The car was not listed in car_models.yml.
So i added it and restarted tne addon, but without any more success.

in fact, i realize that i installed portainer as an addon in homeassistant to be able to login to the container of this addon.
then i installed nano to edit the file in /usr/local/lib/python3.9/dist-package/psa_car_controller/psacc/resources/car_models.yml.
i added a name for DS 3 Etense, the battery power and the vin, but after the restart, the file has return to the original one.
Maybe the file isn't really saved in the container ?

**Comment by Markil78** [comment]
Same problem here, C4 Grand Spacetourer diesel 2019 2.0 hdi 163hp.

**Comment by haabe** [comment]
I also experience this issue with an 2024 Opel Astra Sports Tourer. If I log into my.opel.com, I see some files that might be relevant - but I don't know...

https://api-sp4web.mym.awsmpsa.com/me/vehicles
```
{
    "success": [
        {
            "vin": "VXKFNZKW9RXXXXXXX",
            "lcdv": "1GO5C5TZIFC0A0D2M0VLX7FX",
            "visual": "https:\/\/visual3d-secure.opel-vauxhall.com\/V3DImage.ashx?client=MyMarque&vin=VXKFNZKW9RXXXXXXX&format=png&width=&view=001",
            "short_label": "New Astra",
            "warranty_start_date": XXXXXXXXXX,
            "command": ""
        }
    ]
}
```

https://api-sp4web.mym.awsmpsa.com/me/vehicle-info/VXKFNZKW9RXXXXXXX
```
{
    "success": {
        "vehicleInfo": {
            "vin": "VXKFNZKW9RXXXXXXX",
            "lcdv": "1GO5C5TZIFC0A0D2M0VLX7FX",
            "visual": "https:\/\/visual3d-secure.opel-vauxhall.com\/V3DImage.ashx?client=MyMarque&vin=VXKFNZKW9RXXXXXXX&format=png&width=&view=001",
            "short_label": "New Astra",
            "warranty_start_date": XXXXXXXXXX,
            "attributes": [
                "XXD00XX",
                "XXX01XX",
                "XX201XX",
                "XXY11XX",
                "XXX47XX",
                "XXW11XX",
                "XX901XX",
                "XXC71XX",
                "XXE07XX",
                "XXQ71XX",
                "XXD04XX",
                "XXZ01XX"
            ],
            "type_vehicle": 4,
            "mileage": {
                "value": 701,
                "timestamp": XXXXXXXXXX,
                "source": 5
            }
        },
        "eligibility": [
            "bsrf",
            "device_nac",
            "cea",
            "update_software_nac",
            "update_carto_nac",
            "iap2"
        ],
        "vehicleProducts": {
            "productsCatalog": [],
            "purchasedProducts": [],
            "productGroupNameStatus": []
        }
    }
}
```

**Comment by pxsx** [comment]
Same for my Opel Corsa F-1.2 (2024)

**Comment by codeclinic** [comment]
> Same for my Opel Corsa F-1.2 (2024)

That's not a very informative statementwhen it comes to trying to debug issues.

Also, the latest version appears to no longer have this issue for my setup.

**Comment by pxsx** [comment]
@codeclinic you may look into #1035 i've posted my logs and everything to reproduce the issue 🫡

**Comment by madogharvey** [comment]
Facing the same issue on my 2020 e-208, completely reinstalled everything on my docker container and I still get the error

nt HTTP/1.1" 200 -
2025-05-13 18:33:55,278 :: INFO :: 192.168.65.1 - - [13/May/2025 18:33:55] "GET /config_connect?url=https%3A//idpcvs.peugeot.com/am/oauth2/authorize%3Fclient_id%3D1eebc2d5-5df3-459b-a624-20abfcf82530%26redirect_uri%3Dmymap%253A%252F%252Foauth2redirect%252Fgb%26response_type%3Dcode%26scope%3Dopenid%2520profile%26state%3DP4Q_C4nfEeQC3J8OeHzJEg%26code_challenge%3DZn4F-3FCOl4cJNjn1le1uJCtLcQChduI_zAIpiQIDfQ%26code_challenge_method%3DS256 HTTP/1.1" 200 -
2025-05-13 18:33:55,290 :: INFO :: 192.168.65.1 - - [13/May/2025 18:33:55] "GET /assets/99_custom_overides.css?m=1744213889.0 HTTP/1.1" 304 -
2025-05-13 18:33:55,291 :: INFO :: 192.168.65.1 - - [13/May/2025 18:33:55] "GET /assets/clientside.js?m=1744213889.0 HTTP/1.1" 304 -
2025-05-13 18:33:55,318 :: INFO :: 192.168.65.1 - - [13/May/2025 18:33:55] "GET /_dash-layout HTTP/1.1" 200 -
2025-05-13 18:33:55,319 :: INFO :: 192.168.65.1 - - [13/May/2025 18:33:55] "GET /_dash-dependencies HTTP/1.1" 200 -
2025-05-13 18:33:55,325 :: INFO :: 192.168.65.1 - - [13/May/2025 18:33:55] "POST /_dash-update-component HTTP/1.1" 200 -
2025-05-13 18:33:55,328 :: INFO :: 192.168.65.1 - - [13/May/2025 18:33:55] "GET /assets/images/settings.svg HTTP/1.1" 304 -
2025-05-13 18:33:55,331 :: INFO :: 192.168.65.1 - - [13/May/2025 18:33:55] "POST /_dash-update-component HTTP/1.1" 204 -
2025-05-13 18:37:08,536 :: ERROR :: finish_oauth:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/web/view/config_oauth.py", line 56, in finish_oauth
    config_views.INITIAL_SETUP.connect(code)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 117, in connect
    self.psacc.connect(code)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 35, in connect
    self.manager.connect_with_code(code)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/oauth.py", line 54, in connect_with_code
    assert len(code) == 36, "Invalid code length"
           ^^^^^^^^^^^^^^^
AssertionError: Invalid code length
2025-05-13 18:37:08,539 :: INFO :: 192.168.65.1 - - [13/May/2025 18:37:08] "POST /_dash-update-component HTTP/1.1" 200 -
2025-05-13 18:38:25,565 :: ERROR :: finish_oauth:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/web/view/config_oauth.py", line 56, in finish_oauth
    config_views.INITIAL_SETUP.connect(code)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 117, in connect
    self.psacc.connect(code)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 35, in connect
    self.manager.connect_with_code(code)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/oauth.py", line 55, in connect_with_code
    self._token_request({"grant_type": 'authorization_code', "code": code,
  File "/usr/local/lib/python3.11/dist-packages/oauth2_client/credentials_manager.py", line 205, in _token_request
    CredentialManager._handle_bad_response(response)
  File "/usr/local/lib/python3.11/dist-packages/oauth2_client/credentials_manager.py", line 87, in _handle_bad_response
    raise OAuthError(HTTPStatus(response.status_code), error.get('error'), error.get('error_description'))
oauth2_client.credentials_manager.OAuthError: 400  - invalid_grant : The provided access grant is invalid, expired, or revoked.
2025-05-13 18:38:25,568 :: INFO :: 192.168.65.1 - - [13/May/2025 18:38:25] "POST /_dash-update-component HTTP/1.1" 200 -
2025-05-13 18:38:30,192 :: ERROR :: finish_oauth:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/web/view/config_oauth.py", line 56, in finish_oauth
    config_views.INITIAL_SETUP.connect(code)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 117, in connect
    self.psacc.connect(code)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 35, in connect
    self.manager.connect_with_code(code)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/oauth.py", line 55, in connect_with_code
    self._token_request({"grant_type": 'authorization_code', "code": code,
  File "/usr/local/lib/python3.11/dist-packages/oauth2_client/credentials_manager.py", line 205, in _token_request
    CredentialManager._handle_bad_response(response)
  File "/usr/local/lib/python3.11/dist-packages/oauth2_client/credentials_manager.py", line 87, in _handle_bad_response
    raise OAuthError(HTTPStatus(response.status_code), error.get('error'), error.get('error_description'))
oauth2_client.credentials_manager.OAuthError: 400  - invalid_grant : The provided access grant is invalid, expired, or revoked.
2025-05-13 18:38:30,194 :: INFO :: 192.168.65.1 - - [13/May/2025 18:38:30] "POST /_dash-update-component HTTP/1.1" 200 -
2025-05-13 18:38:59,059 :: INFO :: save config change
2025-05-13 18:38:59,977 :: ERROR :: get_vehicles:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 140, in get_vehicles
    res = self.api().get_vehicles_by_device()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1331, in get_vehicles_by_device
    (data) = self.get_vehicles_by_device_with_http_info(**kwargs)  # noqa: E501
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1400, in get_vehicles_by_device_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/oauth.py", line 125, in call_api
    raise e
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/oauth.py", line 107, in call_api
    return self._ApiClient__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 157, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 347, in request
    return self.rest_client.GET(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/connected_car_api/rest.py", line 234, in GET
    return self.request("GET", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/connected_car_api/rest.py", line 228, in request
    raise ApiException(http_resp=r)
psa_car_controller.psa.connected_car_api.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Connection': 'close', 'Date': 'Tue, 13 May 2025 18:39:01 GMT', 'Content-Type': 'application/hal+json', 'Expires': '0', 'Cache-Control': 'no-store, no-cache, must-revalidate, private', 'Set-Cookie': 'rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Mon, 12-May-2025 18:39:01 GMT, JSESSIONID=aJ74NwnyCmrAqsu5bSueZvplDNgdvoHsTP-1MeLR; path=/, PSACountry=GB; Domain=.groupe-psa.com; Path=/', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Global-Transaction-ID': 'fdaf9590682391c43950ffcf'})
HTTP response body: {"uuid":"16780c4c-85ce-470e-877f-5d6762b3364a","code":40400,"message":"No vehicle found","timestamp":"2025-05-13T18:39:01.213Z"}

2025-05-13 18:38:59,984 :: ERROR :: finish_oauth:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/web/view/config_oauth.py", line 56, in finish_oauth
    config_views.INITIAL_SETUP.connect(code)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 122, in connect
    raise ValueError(
ValueError: No vehicle in your account is compatible with this API, you vehicle is probably too old...
2025-05-13 18:38:59,986 :: INFO :: 192.168.65.1 - - [13/May/2025 18:38:59] "POST /_dash-update-component HTTP/1.1" 200 -
2025-05-13 18:44:36,768 :: INFO :: save config change
2025-05-13 18:44:37,588 :: ERROR :: get_vehicles:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 140, in get_vehicles
    res = self.api().get_vehicles_by_device()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1331, in get_vehicles_by_device
    (data) = self.get_vehicles_by_device_with_http_info(**kwargs)  # noqa: E501
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1400, in get_vehicles_by_device_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/oauth.py", line 125, in call_api
    raise e
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/oauth.py", line 107, in call_api
    return self._ApiClient__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 157, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 347, in request
    return self.rest_client.GET(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/connected_car_api/rest.py", line 234, in GET
    return self.request("GET", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/connected_car_api/rest.py", line 228, in request
    raise ApiException(http_resp=r)
psa_car_controller.psa.connected_car_api.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Connection': 'close', 'Date': 'Tue, 13 May 2025 18:44:38 GMT', 'Content-Type': 'application/hal+json', 'Expires': '0', 'Cache-Control': 'no-store, no-cache, must-revalidate, private', 'Set-Cookie': 'rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Mon, 12-May-2025 18:44:38 GMT, JSESSIONID=TlNxYIwy_wNIGBLXdEG0qsGUwYK7leQfxNAOxfXq; path=/, PSACountry=GB; Domain=.groupe-psa.com; Path=/', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Global-Transaction-ID': 'fdaf9590682393161744bcfd'})
HTTP response body: {"uuid":"7524aeb5-3184-433f-8c86-b2eed3aea265","code":40400,"message":"No vehicle found","timestamp":"2025-05-13T18:44:38.943Z"}

2025-05-13 18:44:37,596 :: ERROR :: finish_oauth:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/web/view/config_oauth.py", line 56, in finish_oauth
    config_views.INITIAL_SETUP.connect(code)
  File "/usr/local/lib/python3.11/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 122, in connect
    raise ValueError(
ValueError: No vehicle in your account is compatible with this API, you vehicle is probably too old...
2025-05-13 18:44:37,598 :: INFO :: 192.168.65.1 - - [13/May/2025 18:44:37] "POST /_dash-update-component HTTP/1.1" 200 -
^C

**Comment by HansGeorgWillyHuebscher** [comment]
Where is this car_models.yml? Can´t find it in my configuration files.
