### ISSUE TITLE
psa-car-controller - error from pandas function

### ISSUE THREAD

**Issue by axelrathey** [flobz/psa_car_controller#923]
Hi, I got some problems running psa_car_controller in Windows 11 with Python 3.12.
There were no errors when installing 'pip3 install psa-car-controller'. But when I run 'psa-car-controller --web-conf I get some error with pandas. See listing below. Can you help me? Thanks Axel

`C:\Users\axel.Axels_Dell_9430>psa-car-controller --web-conf
2024-07-25 07:29:13,281 :: INFO :: App version 3.5.1
2024-07-25 07:29:13,282 :: ERROR :: No config file
2024-07-25 07:29:13,298 :: WARNING :: Can't get language
2024-07-25 07:29:13,740 :: ERROR :: Error importing optional module pandas
Traceback (most recent call last):
  File "C:\Users\axel.Axels_Dell_9430\AppData\Local\Programs\Python\Python312\Lib\site-packages\_plotly_utils\optional_imports.py", line 28, in get_module
    return import_module(name)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\axel.Axels_Dell_9430\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\axel.Axels_Dell_9430\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\axel.Axels_Dell_9430\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\compat\__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "C:\Users\axel.Axels_Dell_9430\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\compat\numpy\__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "C:\Users\axel.Axels_Dell_9430\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\util\__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "C:\Users\axel.Axels_Dell_9430\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\util\_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "C:\Users\axel.Axels_Dell_9430\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\_libs\__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas\_libs\interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
Exception in thread Thread-1 (start_app):
Traceback (most recent call last):
  File "C:\Users\axel.Axels_Dell_9430\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\axel.Axels_Dell_9430\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\axel.Axels_Dell_9430\AppData\Local\Programs\Python\Python312\Lib\site-packages\psa_car_controller\web\app.py", line 51, in start_app
    run(config_flask(*args, **kwargs))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\axel.Axels_Dell_9430\AppData\Local\Programs\Python\Python312\Lib\site-packages\psa_car_controller\web\app.py", line 86, in config_flask
    importlib.import_module(view)
  File "C:\Users\axel.Axels_Dell_9430\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\axel.Axels_Dell_9430\AppData\Local\Programs\Python\Python312\Lib\site-packages\psa_car_controller\web\view\views.py", line 20, in <module>
    from psa_car_controller.web import figures
  File "C:\Users\axel.Axels_Dell_9430\AppData\Local\Programs\Python\Python312\Lib\site-packages\psa_car_controller\web\figures.py", line 6, in <module>
    import plotly.express as px
  File "C:\Users\axel.Axels_Dell_9430\AppData\Local\Programs\Python\Python312\Lib\site-packages\plotly\express\__init__.py", line 9, in <module>
    raise ImportError(
ImportError: Plotly express requires pandas to be installed.`

Thanks Axel

**Comment by rburgst** [comment]
same problem here according to https://stackoverflow.com/questions/78634235/numpy-dtype-size-changed-may-indicate-binary-incompatibility-expected-96-from there is an incompatibility for newer numpy versions

**Comment by HiQual** [comment]
.... and me also. Exact same scenario.
