### ISSUE TITLE
Can't refresh remote token, please redo otp procedure

### ISSUE THREAD

**Issue by vineethktpla** [flobz/psa_car_controller#925]
Im getting this error 
Can't refresh remote token, please redo otp procedure
Even after multiple auth procedures.
Issue started from yesterday.
Sensors on HA are not updating instantly. Battery level is not updating during charging even with automation to wake it every 10 minutes

and raise RateLimitException also there.

was working fine till yesterday

**Comment by zackslash** [comment]
I have a similar issue issue with no data being updated. The official PSA app also is not updating any of the data, is this the same in your case? Initially I thought it was due the rate limit but after 24 hours I still have no updates

**Comment by vineethktpla** [comment]
Issue resolved on its own after couple of days

**Comment by Jordan87** [comment]
I also have this error message.
Status is updated if car is on the way or I will open it but im not able to start stop charging from addon, android app is working.

And here is the loge few minutes after otp redo.

``2024-09-06 18:35:16,750 :: ERROR :: Can't refresh remote token, please redo otp procedure
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 176, in _refresh_remote_token
otp_code = self.get_otp_code()
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
raise RateLimitException
psa_car_controller.common.utils.RateLimitException
2024-09-06 18:35:16,751 :: ERROR :: Can't configure MQTT Client
2024-09-06 18:35:17,140 :: INFO :: save config change
2024-09-06 18:35:18,158 :: WARNING :: remote_refresh_token isn't defined
2024-09-06 18:35:18,158 :: ERROR :: Can't refresh remote token, please redo otp procedure
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 176, in _refresh_remote_token
otp_code = self.get_otp_code()
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
raise RateLimitException
psa_car_controller.common.utils.RateLimitException
2024-09-06 18:35:18,158 :: ERROR :: Can't configure MQTT Client
2024-09-06 18:35:18,160 :: INFO :: 172.30.32.1 - - [06/Sep/2024 18:35:18] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-09-06 18:35:19,663 :: INFO :: 172.30.32.1 - - [06/Sep/2024 18:35:19] "[37mGET /config_otp HTTP/1.1[0m" 200 -
2024-09-06 18:35:19,749 :: INFO :: 172.30.32.1 - - [06/Sep/2024 18:35:19] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2024-09-06 18:35:19,753 :: INFO :: 172.30.32.1 - - [06/Sep/2024 18:35:19] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-09-06 18:35:19,780 :: INFO :: 172.30.32.1 - - [06/Sep/2024 18:35:19] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-09-06 18:35:19,815 :: INFO :: 172.30.32.1 - - [06/Sep/2024 18:35:19] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-09-06 18:35:19,818 :: INFO :: 172.30.32.1 - - [06/Sep/2024 18:35:19] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 -
2024-09-06 18:35:19,821 :: INFO :: 172.30.32.1 - - [06/Sep/2024 18:35:19] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 -
2024-09-06 18:35:22,059 :: INFO :: 172.30.32.1 - - [06/Sep/2024 18:35:22] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-09-06 18:35:26,252 :: INFO :: save config change
2024-09-06 18:35:35,879 :: ERROR :: Error during activation: {'newversion': None, 'newversionurl': None, 'err': 'NOK:MAXNBTOOLS'}
2024-09-06 18:35:36,360 :: WARNING :: remote_refresh_token isn't defined
2024-09-06 18:35:36,361 :: ERROR :: Can't refresh remote token, please redo otp procedure
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 176, in _refresh_remote_token
otp_code = self.get_otp_code()
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
raise RateLimitException
psa_car_controller.common.utils.RateLimitException
2024-09-06 18:35:36,361 :: ERROR :: Can't configure MQTT Client``
