### ISSUE TITLE
HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /flobz/psa_apk/raw/main/mypeugeot.apk 

### ISSUE THREAD

**Issue by ionutfdumitru** [flobz/psa_car_controller#929]
Worked for me for several days but after a modification on a config file I restarted the container and I am not able to log back again.  

Max retries exceeded with url: /flobz/psa_apk/raw/main/mypeugeot.apk

**To Reproduce**
1. reinstalled  the container
2. Peugeot user pass reset
3. http://192.168.1.204:5000/
4. Container logs below
5. repeted the same steps after 12 hours . Same result.

**Container logs**

Containerised psa_car_controller loading...
2024-08-04 05:31:45,437 :: INFO :: App version 3.5.1
2024-08-04 05:31:45,437 :: ERROR :: No config file
2024-08-04 05:31:45,439 :: WARNING :: Can't get language
2024-08-04 05:31:45,970 :: INFO :: update_data
2024-08-04 05:31:46,002 :: INFO ::  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2024-08-04 05:31:56,395 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:31:56] "GET / HTTP/1.1" 200 -
2024-08-04 05:31:56,534 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:31:56] "GET /_dash-layout HTTP/1.1" 200 -
2024-08-04 05:31:56,536 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:31:56] "GET /_dash-dependencies HTTP/1.1" 200 -
2024-08-04 05:31:56,553 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:31:56] "POST /_dash-update-component HTTP/1.1" 200 -
2024-08-04 05:31:56,571 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:31:56] "GET /config_login HTTP/1.1" 200 -
2024-08-04 05:31:56,630 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:31:56] "GET /_dash-layout HTTP/1.1" 200 -
2024-08-04 05:31:56,631 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:31:56] "GET /_dash-dependencies HTTP/1.1" 200 -
2024-08-04 05:31:56,644 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:31:56] "POST /_dash-update-component HTTP/1.1" 200 -
2024-08-04 05:31:56,679 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:31:56] "POST /_dash-update-component HTTP/1.1" 200 -
2024-08-04 05:31:56,680 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:31:56] "POST /_dash-update-component HTTP/1.1" 204 -
2024-08-04 05:31:56,681 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:31:56] "POST /_dash-update-component HTTP/1.1" 204 -
2024-08-04 05:32:14,460 :: INFO :: Initial setup...
2024-08-04 05:32:34,484 :: ERROR :: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /flobz/psa_apk/raw/main/mypeugeot.apk (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fff2faa02e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fff2faa02e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /flobz/psa_apk/raw/main/mypeugeot.apk (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fff2faa02e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_views.py", line 137, in connectPSA
    INITIAL_SETUP = InitialSetup(app_name, email, password, countrycode)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 35, in __init__
    apk_parser = get_content_from_apk(filename, country_code)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 26, in get_content_from_apk
    urlretrieve_from_github(GITHUB_USER, GITHUB_REPO, "", apk_parser.filename)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/github.py", line 42, in urlretrieve_from_github
    r = requests.get(url,
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /flobz/psa_apk/raw/main/mypeugeot.apk (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fff2faa02e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2024-08-04 05:32:34,487 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:32:34] "POST /_dash-update-component HTTP/1.1" 200 -
2024-08-04 05:35:49,119 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:49] "POST /_dash-update-component HTTP/1.1" 200 -
2024-08-04 05:35:49,166 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:49] "GET /config_login HTTP/1.1" 200 -
2024-08-04 05:35:49,293 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:49] "GET /_dash-layout HTTP/1.1" 200 -
2024-08-04 05:35:49,295 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:49] "GET /_dash-dependencies HTTP/1.1" 200 -
2024-08-04 05:35:49,312 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:49] "POST /_dash-update-component HTTP/1.1" 200 -
2024-08-04 05:35:49,348 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:49] "POST /_dash-update-component HTTP/1.1" 200 -
2024-08-04 05:35:49,350 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:49] "POST /_dash-update-component HTTP/1.1" 204 -
2024-08-04 05:35:49,351 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:49] "POST /_dash-update-component HTTP/1.1" 204 -
2024-08-04 05:35:51,937 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:51] "POST /_dash-update-component HTTP/1.1" 200 -
2024-08-04 05:35:51,953 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:51] "GET /config_login HTTP/1.1" 200 -
2024-08-04 05:35:52,011 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:52] "GET /_dash-layout HTTP/1.1" 200 -
2024-08-04 05:35:52,012 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:52] "GET /_dash-dependencies HTTP/1.1" 200 -
2024-08-04 05:35:52,026 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:52] "POST /_dash-update-component HTTP/1.1" 200 -
2024-08-04 05:35:52,053 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:52] "POST /_dash-update-component HTTP/1.1" 200 -
2024-08-04 05:35:52,054 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:52] "POST /_dash-update-component HTTP/1.1" 204 -
2024-08-04 05:35:52,055 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:52] "POST /_dash-update-component HTTP/1.1" 204 -
2024-08-04 05:35:53,652 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:53] "POST /_dash-update-component HTTP/1.1" 200 -
2024-08-04 05:35:53,676 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:53] "POST /_dash-update-component HTTP/1.1" 200 -
2024-08-04 05:35:53,677 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:53] "POST /_dash-update-component HTTP/1.1" 204 -
2024-08-04 05:35:53,679 :: INFO :: 192.168.1.158 - - [04/Aug/2024 05:35:53] "POST /_dash-update-component HTTP/1.1" 204 -

**Comment by ionutfdumitru** [comment]
Tried with different user - same issue.

**Comment by ionutfdumitru** [comment]
resolved

1. deleted the container
2. deleted the network ip 
3. using chrome in incognito , start over with the container setup
