### ISSUE TITLE
my peugeot cannot log in

### ISSUE THREAD

**Issue by rburgst** [flobz/psa_car_controller#932]
**Describe the bug**
The app does not get past the initial setup step. I am constantly getting FORM_ERROR_USR_EMAIL. 
Note that I do have a "+" in my email (see also #899).
Then I tried to replicate the request via postman and played around with various ways of encoding my email: 
https://id-dcr.peugeot.com:443/mobile-services/GetAccessToken?jsonRequest=%7B%22siteCode%22%3A%2B%22AP_DE_ESP%22%2C%2B%22culture%22%3A%2B%22fr-FR%22%2C%2B%22action%22%3A%2B%22authenticate%22%2C%2B%22fields%22%3A%2B%7B%22USR_EMAIL%22%3A%2B%7B%22value%22%3A%2B%22rburgst%2Bpeugeot%40gmail.com%22%7D%2C%2B%22USR_PASSWORD%22%3A%2B%7B%22value%22%3A%2B%22MYPASSWORD%22%7D%7D%7D
However, also here I am constantly getting `FORM_ERROR_USR_EMAIL`.

Next, I downloaded a newer version of mypeugeot on the android emulator, logged in (it is using oauth2 via browser redirect), copied the access token from logcat and pasted it into `InitialSetup::__init__` (and commented out the actual http request.

There, I get an error when trying the next request
https://mw-ap-m2c.mym.awsmpsa.com/api/v1/user?culture=de_AT&width=1000&version=1.33.0
(where the token is sent in the header)

There I am getting 
```
{"errors":{"112":"error.user.token"}}
```
So I am guessing my access token from the newer (1.40.3) android app did not work after all.

So in essence it appears to me as if the way the app is 

**To Reproduce**
1. what command did you use: ran the app in the vscode debugger with the following launch config
   ```
  {
            "name": "psacc",
            "type": "debugpy",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "module": "psa_car_controller",
            "args": ["--web-conf", "-d", "-r", "-p 5002"]
        }
```
3. when the bug append ?
???
5. Does it persist after restarting the program? 
YES
7. Does it persist after recreate config by going to http://server_address:port/config? 

**Config file**
Give the anonymize content of the config file
none yet, still in the initial setup phase

**Environment (please complete the following information):**
 - OS: Mac OSX
 - Brand and model of car: Peugeot e2008 2020
 - Application version (commit number, branch or tag): 1179ec39aa5be6f1ecdf7138751e5c31e32f66e1
 - Log from http://server_address:port/log and browser console log

```
2024-08-07 20:23:42,332 :: DEBUG :: https://api.github.com:443 "GET /repos/flobz/psa_apk/git/trees/main: HTTP/1.1" 200 452
2024-08-07 20:23:42,335 :: DEBUG :: locale file is the latest version
2024-08-07 20:24:07,007 :: DEBUG :: Starting new HTTPS connection (1): mw-ap-m2c.mym.awsmpsa.com:443
2024-08-07 20:24:07,762 :: DEBUG :: https://mw-ap-m2c.mym.awsmpsa.com:443 "POST /api/v1/user?culture=de_AT&width=1080&version=1.33.0 HTTP/1.1" 200 None
2024-08-07 20:24:07,770 :: ERROR :: Traceback (most recent call last):
  File "/Users/rainer/git/psa_car_controller/psa_car_controller/psa/setup/app_decoder.py", line 102, in __fetch_user_info
    res_dict = res2.json()["success"]
               ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'success'
{"errors":{"112":"error.user.token"}}
2024-08-07 20:25:00,260 :: ERROR :: Traceback (most recent call last):
  File "/Users/rainer/git/psa_car_controller/psa_car_controller/psa/setup/app_decoder.py", line 102, in __fetch_user_info
    res_dict = res2.json()["success"]
               ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'success'
{"errors":{"112":"error.user.token"}}
Traceback (most recent call last):
  File "/Users/rainer/git/psa_car_controller/psa_car_controller/psa/setup/app_decoder.py", line 102, in __fetch_user_info
    res_dict = res2.json()["success"]
               ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'success'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rainer/git/psa_car_controller/psa_car_controller/web/view/config_views.py", line 137, in connectPSA
    INITIAL_SETUP = InitialSetup(app_name, email, password, countrycode)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rainer/git/psa_car_controller/psa_car_controller/psa/setup/app_decoder.py", line 73, in __init__
    self.user_info = self.__fetch_user_info()
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rainer/git/psa_car_controller/psa_car_controller/psa/setup/app_decoder.py", line 110, in __fetch_user_info
    raise ConnectionError(msg) from ex
ConnectionError: Traceback (most recent call last):
  File "/Users/rainer/git/psa_car_controller/psa_car_controller/psa/setup/app_decoder.py", line 102, in __fetch_user_info
    res_dict = res2.json()["success"]
               ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'success'
{"errors":{"112":"error.user.token"}}
```

**Additional context**

**Comment by rburgst** [comment]
I managed to get evcc to login and would have a access and refresh token, can I somehow create the config.json manually?
