### ISSUE TITLE
Peugeot: AttributeError: 'NoneType' object has no attribute 'embedded' on new login

### ISSUE THREAD

**Issue by Apollon77** [flobz/psa_car_controller#946]
**Describe the bug**
When doing a new login with 3.5.3 I got the following error after entering the oauth code from web dev tools

```
2024-09-02 14:18:11,509 :: INFO :: save config change
2024-09-02 14:18:11,509 :: INFO :: App version 3.5.3
2024-09-02 14:18:13,050 :: ERROR :: finish_oauth:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_oauth.py", line 56, in finish_oauth
    config_views.INITIAL_SETUP.connect(code)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 134, in connect
    app.load_app()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/car_controller.py", line 104, in load_app
    logger.info(str(self.myp.get_vehicles()))
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 141, in get_vehicles
    for vehicle in res.embedded.vehicles:
AttributeError: 'NoneType' object has no attribute 'embedded'
```

**Environment (please complete the following information):**
 - OS: Proxmox LXC with Docker in it
 - Brand and model of car: Peugeot
 - Application version (commit number, branch or tag): 3.5.3
 - Log from http://server_address:port/log and browser console log -  see above

**Comment by Apollon77** [comment]
PS: Interestingly the APP also shows an error ... lets see ... maybe thy have issues

**Comment by Apollon77** [comment]
Ok, got that error now again after the app was back ... then it worked, band also OTP flow worked, but I still have 

```
psacc-1  | 2024-09-02 16:05:50,140 :: INFO :: subscribe to psa/RemoteServices/to/cid/AP-ACNT200001088381/#
psacc-1  | 2024-09-02 16:05:50,140 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VR3XXXXXXXX
psacc-1  | 2024-09-02 16:05:50,140 :: WARNING :: Disconnected with result code 5
psacc-1  | 2024-09-02 16:05:50,140 :: WARNING :: The connection was refused.
psacc-1  | 2024-09-02 16:05:58,323 :: INFO :: Connected with result code {'session present': 0}
psacc-1  | 2024-09-02 16:05:58,323 :: INFO :: subscribe to psa/RemoteServices/to/cid/AP-ACNT200001088381/#
psacc-1  | 2024-09-02 16:05:58,323 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VR3XXXXXXXX
psacc-1  | 2024-09-02 16:05:58,323 :: WARNING :: Disconnected with result code 5
psacc-1  | 2024-09-02 16:05:58,323 :: WARNING :: The connection was refused.
psacc-1  | 2024-09-02 16:06:14,483 :: INFO :: Connected with result code {'session present': 0}
psacc-1  | 2024-09-02 16:06:14,483 :: INFO :: subscribe to psa/RemoteServices/to/cid/AP-ACNT200001088381/#
psacc-1  | 2024-09-02 16:06:14,484 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VR3XXXXXXXX
psacc-1  | 2024-09-02 16:06:14,484 :: WARNING :: Disconnected with result code 5
psacc-1  | 2024-09-02 16:06:14,484 :: WARNING :: The connection was refused.
psacc-1  | 2024-09-02 16:06:46,616 :: INFO :: Connected with result code {'session present': 0}
psacc-1  | 2024-09-02 16:06:46,616 :: INFO :: subscribe to psa/RemoteServices/to/cid/AP-ACNT200001088381/#
psacc-1  | 2024-09-02 16:06:46,616 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VR3XXXXXXXX
psacc-1  | 2024-09-02 16:06:46,616 :: WARNING :: Disconnected with result code 5
psacc-1  | 2024-09-02 16:06:46,616 :: WARNING :: The connection was refused.
psacc-1  | 2024-09-02 16:07:51,003 :: INFO :: Connected with result code {'session present': 0}
psacc-1  | 2024-09-02 16:07:51,003 :: INFO :: subscribe to psa/RemoteServices/to/cid/AP-ACNT200001088381/#
psacc-1  | 2024-09-02 16:07:51,003 :: INFO :: subscribe to psa/RemoteServices/events/MPHRTServices/VR3XXXXXXXX
psacc-1  | 2024-09-02 16:07:51,003 :: WARNING :: Disconnected with result code 5
psacc-1  | 2024-09-02 16:07:51,003 :: WARNING :: The connection was refused.
...
````

in the log now

**Comment by Antyrael** [comment]
I'm having the same issue, also for Peugeot, using country code NL.

Relevant part of my logs:
> 024-09-03 17:48:21,320 :: INFO :: App version 3.5.3
> 2024-09-03 17:48:22,515 :: ERROR :: finish_oauth:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_oauth.py", line 56, in finish_oauth
>     config_views.INITIAL_SETUP.connect(code)
>   File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 134, in connect
>     app.load_app()
>   File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/car_controller.py", line 104, in load_app
>     logger.info(str(self.myp.get_vehicles()))
>   File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 141, in get_vehicles
>     for vehicle in res.embedded.vehicles:
> AttributeError: 'NoneType' object has no attribute 'embedded'

**Comment by vinc-vo** [comment]
I'm getting the same error.

OS: Debian running Docker
Brand and model of car: Peugeot e2008 (2020)
Application version (commit number, branch or tag): 3.5.3

 ```
2024-09-05 16:04:28,494 :: INFO :: 192.168.xxx.xxx - - [05/Sep/2024 16:04:28] "GET /config_connect?url=https%3A//idpcvs.peugeot.com/am/oauth2/authorizXXXXXXX HTTP/1.0" 200 -
2024-09-05 16:04:28,755 :: INFO :: 192.168.xxx.xxx - - [05/Sep/2024 16:04:28] "GET /_dash-layout HTTP/1.0" 200 -
2024-09-05 16:04:28,761 :: INFO :: 192.168.xxx.xxx - - [05/Sep/2024 16:04:28] "GET /_dash-dependencies HTTP/1.0" 200 -
2024-09-05 16:04:29,024 :: INFO :: 192.168.xxx.xxx - - [05/Sep/2024 16:04:29] "POST /_dash-update-component HTTP/1.0" 200 -
2024-09-05 16:04:29,073 :: INFO :: 192.168.xxx.xxx - - [05/Sep/2024 16:04:29] "POST /_dash-update-component HTTP/1.0" 204 -
2024-09-05 16:05:29,274 :: INFO :: save config change
2024-09-05 16:05:29,816 :: INFO :: 
Your vehicles: ["{'vin': 'xxxxxxxxxxxxxxxxxxxxxxx', 'vehicle_id': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'label': 'xxxxxxx', 'brand': 'Peugeot', 'abrp_name': 'peugeot:xxxxxxx', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
2024-09-05 16:05:29,817 :: INFO :: save config change
2024-09-05 16:05:29,818 :: INFO :: App version 3.5.3
2024-09-05 16:05:31,735 :: ERROR :: finish_oauth:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_oauth.py", line 56, in finish_oauth
    config_views.INITIAL_SETUP.connect(code)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 134, in connect
    app.load_app()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/car_controller.py", line 104, in load_app
    logger.info(str(self.myp.get_vehicles()))
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 141, in get_vehicles
    for vehicle in res.embedded.vehicles:
AttributeError: 'NoneType' object has no attribute 'embedded'
2024-09-05 16:05:31,738 :: INFO :: 192.168.xxx.xxx - - [05/Sep/2024 16:05:31] "POST /_dash-update-component HTTP/1.0" 200 -
2024-09-05 16:05:54,860 :: INFO :: save config change
 ```

**Comment by vinc-vo** [comment]
Just updated again to v3.5.3. I still got the error on the first try, but tried again and it finally works :)

**Comment by vineethktpla** [comment]
I have the same issue
