### ISSUE TITLE
Problems using unlock / horn /lights

### ISSUE THREAD

**Issue by cristi092024** [flobz/psa_car_controller#959]
I can get this to work. The rest shows ok ( ------- is cid and VIN )
2024-09-16 15:26:26,912 :: INFO :: topic: psa/RemoteServices/from/cid/----------/Doors: {'action': 'unlock'}
2024-09-16 15:26:27,511 :: WARNING :: remote_refresh_token isn't defined
2024-09-16 15:26:27,511 :: ERROR :: Can't refresh remote token, please redo otp procedure
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 176, in _refresh_remote_token
    otp_code = self.get_otp_code()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
    raise RateLimitException
psa_car_controller.common.utils.RateLimitException
2024-09-16 15:26:27,513 :: INFO :: 172.30.32.1 - - [16/Sep/2024 15:26:27] "GET /lock_door/-----------/0 HTTP/1.1" 200 -

**Comment by D4v3R4v3** [comment]
Did you ever get this to work? I still have the same errors using version 3.5.6
