### ISSUE TITLE
PSA SoC not actual, EVCC actua

### ISSUE THREAD

**Issue by jove01** [flobz/psa_car_controller#960]
I use the PSACC add-on in Homeassistant also the EVCC-Add-On.

Today I want to charge my Opel Mokka-e.  Before I did not controll the PSACC .

A time later the SoC in PSACC did not change, but the SoC in EVCC ist ok.

![Screenshot_20240918-161901](https://github.com/user-attachments/assets/e10820a7-b73a-4603-9c73-f3fb50784b43)
![Screenshot_20240918-161940](https://github.com/user-attachments/assets/b9001b12-15d3-4d82-adef-401523e091e4)

`vehicles:
  - name: opel_mokka_e
    type: template
    template: flobz
    title: Mokka E
    url: http://192.168.178.91:5000
    vin: VXKUKZKXZxxxxxxx
    capacity: 50`

`2024-09-18 17:07:23,438 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:07:23] "GET /charge_control?vin=VXKUxxxxxx&?always_check=true HTTP/1.1" 200 -
2024-09-18 17:07:47,800 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:07:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:07:47,808 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:07:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:08:23,436 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:08:23] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:08:23,438 :: INFO :: <Request 'http://192.168.178.91:5000/charge_control?vin=VXKUxxxxxx&%3Falways_check=true' [GET]>
2024-09-18 17:08:23,439 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:08:23] "GET /charge_control?vin=VXKUxxxxxx&?always_check=true HTTP/1.1" 200 -
2024-09-18 17:08:47,793 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:08:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:08:47,799 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:08:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:09:14,011 :: INFO :: charging status of VXKUxxxxxx is InProgress, battery level: 33
2024-09-18 17:09:14,011 :: ERROR :: force_update:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/charge_control.py", line 70, in force_update
    self.psacc.remote_client.wakeup(self.vin)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
    raise RateLimitException
psa_car_controller.common.utils.RateLimitException
2024-09-18 17:09:23,437 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:09:23] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:09:23,438 :: INFO :: <Request 'http://192.168.178.91:5000/charge_control?vin=VXKUxxxxxx&%3Falways_check=true' [GET]>
2024-09-18 17:09:23,440 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:09:23] "GET /charge_control?vin=VXKUxxxxxx&?always_check=true HTTP/1.1" 200 -
2024-09-18 17:09:47,724 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:09:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:09:47,731 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:09:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:10:23,437 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:10:23] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:10:23,439 :: INFO :: <Request 'http://192.168.178.91:5000/charge_control?vin=VXKUxxxxxx&%3Falways_check=true' [GET]>
2024-09-18 17:10:23,441 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:10:23] "GET /charge_control?vin=VXKUxxxxxx&?always_check=true HTTP/1.1" 200 -
2024-09-18 17:10:47,691 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:10:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:10:47,698 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:10:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:11:14,011 :: INFO :: charging status of VXKUxxxxxx is InProgress, battery level: 33
2024-09-18 17:11:14,012 :: ERROR :: force_update:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/charge_control.py", line 70, in force_update
    self.psacc.remote_client.wakeup(self.vin)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
    raise RateLimitException
psa_car_controller.common.utils.RateLimitException
2024-09-18 17:11:23,438 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:11:23] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:11:23,440 :: INFO :: <Request 'http://192.168.178.91:5000/charge_control?vin=VXKUxxxxxx&%3Falways_check=true' [GET]>
2024-09-18 17:11:23,442 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:11:23] "GET /charge_control?vin=VXKUxxxxxx&?always_check=true HTTP/1.1" 200 -
2024-09-18 17:11:47,717 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:11:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:11:47,723 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:11:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:12:23,442 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:12:23] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:12:23,444 :: INFO :: <Request 'http://192.168.178.91:5000/charge_control?vin=VXKUxxxxxx&%3Falways_check=true' [GET]>
2024-09-18 17:12:23,446 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:12:23] "GET /charge_control?vin=VXKUxxxxxx&?always_check=true HTTP/1.1" 200 -
2024-09-18 17:12:49,813 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:12:49] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:12:49,818 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:12:49] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:13:14,688 :: INFO :: charging status of VXKUxxxxxx is InProgress, battery level: 33
2024-09-18 17:13:14,688 :: ERROR :: force_update:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/charge_control.py", line 70, in force_update
    self.psacc.remote_client.wakeup(self.vin)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
    raise RateLimitException
psa_car_controller.common.utils.RateLimitException
2024-09-18 17:13:23,441 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:13:23] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:13:23,443 :: INFO :: <Request 'http://192.168.178.91:5000/charge_control?vin=VXKUxxxxxx&%3Falways_check=true' [GET]>
2024-09-18 17:13:23,445 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:13:23] "GET /charge_control?vin=VXKUxxxxxx&?always_check=true HTTP/1.1" 200 -
2024-09-18 17:13:47,842 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:13:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:13:47,844 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:13:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:14:23,443 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:14:23] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:14:23,445 :: INFO :: <Request 'http://192.168.178.91:5000/charge_control?vin=VXKUxxxxxx&%3Falways_check=true' [GET]>
2024-09-18 17:14:23,447 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:14:23] "GET /charge_control?vin=VXKUxxxxxx&?always_check=true HTTP/1.1" 200 -
2024-09-18 17:14:47,797 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:14:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:14:47,803 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:14:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:15:14,150 :: INFO :: charging status of VXKUxxxxxx is InProgress, battery level: 33
2024-09-18 17:15:14,150 :: ERROR :: force_update:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/charge_control.py", line 70, in force_update
    self.psacc.remote_client.wakeup(self.vin)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
    raise RateLimitException
psa_car_controller.common.utils.RateLimitException
2024-09-18 17:15:23,442 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:15:23] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:15:23,444 :: INFO :: <Request 'http://192.168.178.91:5000/charge_control?vin=VXKUxxxxxx&%3Falways_check=true' [GET]>
2024-09-18 17:15:23,445 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:15:23] "GET /charge_control?vin=VXKUxxxxxx&?always_check=true HTTP/1.1" 200 -
2024-09-18 17:15:47,945 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:15:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:15:47,952 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:15:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:16:23,442 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:16:23] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:16:23,444 :: INFO :: <Request 'http://192.168.178.91:5000/charge_control?vin=VXKUxxxxxx&%3Falways_check=true' [GET]>
2024-09-18 17:16:23,446 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:16:23] "GET /charge_control?vin=VXKUxxxxxx&?always_check=true HTTP/1.1" 200 -
2024-09-18 17:16:47,795 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:16:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:16:47,798 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:16:47] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:17:14,919 :: INFO :: charging status of VXKUxxxxxx is InProgress, battery level: 33
2024-09-18 17:17:14,920 :: INFO :: ask wakeup to VXKUxxxxxx
2024-09-18 17:17:14,920 :: INFO :: topic: psa/RemoteServices/from/cid/OV-ACNT200008056525/VehCharge/state: {'action': 'state'}
2024-09-18 17:17:18,784 :: INFO :: save config change
2024-09-18 17:17:23,444 :: INFO :: 192.168.178.91 - - [18/Sep/2024 17:17:23] "GET /get_vehicleinfo/VXKUxxxxxx?from_cache=1 HTTP/1.1" 200 -
2024-09-18 17:17:23,446 :: INFO :: <Request 'http://192.168.178.91:5000/charge_control?vin=VXKUxxxxxx&%3Falways_check=true' [GET]>

In EVCC I use the "template: flobz" so I thaught, EVCC will get the Information over PSACC. Can you explain the difference.

(All modules are actual.)

**Comment by mdkeil** [comment]
The displayed soc during charge in evcc is calculated, if the soc doesnt get updated from the car,

**Comment by jove01** [comment]
> The displayed soc during charge in evcc is calculated, if the soc doesnt get updated from the car,

Thanks for the information. Now EVCC stoppt charging and PSACC is actual,
