### ISSUE TITLE
'End of central directory record (EOCD) signature not found

### ISSUE THREAD

**Issue by dtpartridge** [flobz/psa_car_controller#964]
I am trying to set the PSA Car Controller add-on for the first time for my Citroen e-Berlingo.

When I go to complete the user configuration with my details I am getting this error message:

'End of central directory record (EOCD) signature not found'

I've tried restarting multiple times (both the add in, Home Assistant, and the host machine) all to no avail.

Does anyone have any suggestions as to how to fix this?

Thanks,

Dave

---

The log file says:

2024-09-22 22:25:09,868 :: INFO :: Initial setup...
2024-09-22 22:25:10,570 :: ERROR :: End of central directory record (EOCD) signature not found
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_views.py", line 137, in connectPSA
INITIAL_SETUP = InitialSetup(app_name, email, password, countrycode)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 35, in __init__
apk_parser = get_content_from_apk(filename, country_code)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 27, in get_content_from_apk
apk_parser.retrieve_content_from_apk()
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/apk_parser.py", line 37, in retrieve_content_from_apk
a = APK(self.filename)
File "/usr/local/lib/python3.9/dist-packages/androguard/core/apk/__init__.py", line 319, in __init__
self.zip = ZipEntry.parse(filename, False)
File "/usr/local/lib/python3.9/dist-packages/apkInspector/headers.py", line 408, in parse
eocd = EndOfCentralDirectoryRecord.parse(apk_file)
File "/usr/local/lib/python3.9/dist-packages/apkInspector/headers.py", line 59, in parse
raise ValueError("End of central directory record (EOCD) signature not found")
ValueError: End of central directory record (EOCD) signature not found
2024-09-22 22:25:10,575 :: INFO :: 172.30.32.1 - - [22/Sep/2024 22:25:10] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-09-22 22:25:22,186 :: INFO :: 172.30.32.1 - - [22/Sep/2024 22:25:22] "[37mGET / HTTP/1.1[0m" 200 -
2024-09-22 22:25:22,317 :: INFO :: 172.30.32.1 - - [22/Sep/2024 22:25:22] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-09-22 22:25:22,319 :: INFO :: 172.30.32.1 - - [22/Sep/2024 22:25:22] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2024-09-22 22:25:22,364 :: INFO :: 172.30.32.1 - - [22/Sep/2024 22:25:22] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-09-22 22:25:22,424 :: INFO :: 172.30.32.1 - - [22/Sep/2024 22:25:22] "[37mGET /config_login HTTP/1.1[0m" 200 -
2024-09-22 22:25:22,516 :: INFO :: 172.30.32.1 - - [22/Sep/2024 22:25:22] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-09-22 22:25:22,519 :: INFO :: 172.30.32.1 - - [22/Sep/2024 22:25:22] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -

 - OS: Windows 10 using Home Assistant within VMWare Workstation 17..6
 - Brand and model of car: Citroen e-Berlingo
 - Application version (commit number, branch or tag): 3.5.3

**Comment by Bk67210** [comment]
hello, I have exactly the same problem for an Opel Mokka-e, in home assistant directly.

**Comment by on4ami** [comment]
Same here

**Comment by Oles68** [comment]
Same for me, with Peugeot e208, country FR. 
Anyone have a solution ?

**Comment by Snailboy2** [comment]
It seems that the problem is because the service does not have access to enough RAM. I gave my Home Assistant VM 2gb from 1.5 and then it all worked and i could go through with the auth process.

**Comment by Destroyer061090** [comment]
> It seems that the problem is because the service does not have access to enough RAM. I gave my Home Assistant VM 2gb from 1.5 and then it all worked and i could go through with the auth process.

Hi, I never got this issues on docker but now it pop up also to me. I have more than 3GB RAM free on my synology NAS. :-(

**Comment by Destroyer061090** [comment]
looking on internet the error seems related to a corrupted database. based on this i unistall the PSA (so, delete all related data) and re-install it from scratch. everhing work now propery after the new setup

**Comment by Bk67210** [comment]
> looking on internet the error seems related to a corrupted database. based on this i unistall the PSA (so, delete all related data) and re-install it from scratch. everhing work now propery after the new setup

I'll give it a try!
What did you delete?

**Comment by dtpartridge** [comment]
By following the good advice here I have managed to get this set up.  It took a few attempts, but now appears to be working.

The key thing was to increase the memory for my virtual machine from 1 Gb to 2 Gb, then to remove the PSA Car Controller add-in from Home Assistant, then re-install it (which I had done before).

Those two steps, combined with a bit of patience fixed it for me.

Thanks everyone!

**Comment by Destroyer061090** [comment]
> > looking on internet the error seems related to a corrupted database. based on this i unistall the PSA (so, delete all related data) and re-install it from scratch. everhing work now propery after the new setup
> 
> I'll give it a try! What did you delete?

I have Uninstall the container… doing this all the data related will be automatically deleted… when you install it again you have a fresh installation..

**Comment by Bk67210** [comment]
> > > looking on internet the error seems related to a corrupted database. based on this i unistall the PSA (so, delete all related data) and re-install it from scratch. everhing work now propery after the new setup
> > 
> > 
> > I'll give it a try! What did you delete?
> 
> I have Uninstall the container… doing this all the data related will be automatically deleted… when you install it again you have a fresh installation..

Thanks, 
I deleted everything up to the repository address, unfortunately it didn't work and I'm still stuck with the EOCD error. 
Being limited to 1 GB of RAM, I can't try to increase it 🤐
