### ISSUE TITLE
"Can't refresh remote token" and "RateLimitException" visible in log and not able to dtart/stop charging or refresh status

### ISSUE THREAD

**Issue by Jordan87** [flobz/psa_car_controller#967]
For a quite long time start/stop charging, preconditioning and othere features are not working at all. 
Im able to do those from android MyPeugeot app.

Today I even reinstalled psacc addon in HA but still with the same result.

1. i.e. http://homeassistant.local:5000/wakeup/MyVIN
2. when the bug append ? Over two months ago
3. Does it persist after restarting the program? Yes
4. Does it persist after recreate config by going to http://server_address:port/config? Yes

**Environment (please complete the following information):**
 - OS: HAOS
 - Peugeot 308 Plug-In Hybrid
 - Application version  v3.5.3
 - Log from http://server_address:port/log and browser console log

`2024-09-28 15:56:10,206 :: INFO :: ask wakeup to MyVIN
2024-09-28 15:56:10,207 :: INFO :: topic: psa/RemoteServices/from/cid/AP-ACNT200003476968/VehCharge/state: {'action': 'state'}
2024-09-28 15:56:10,207 :: ERROR :: Can't refresh remote token, please redo otp procedure
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 157, in _refresh_remote_token
    self.manager.refresh_token_now()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
    raise RateLimitException
psa_car_controller.common.utils.RateLimitException
2024-09-28 15:56:10,208 :: INFO :: 192.168.1.76 - - [28/Sep/2024 15:56:10] "GET /wakeup/MyVIN HTTP/1.1" 200 -
2024-09-28 15:56:10,247 :: INFO :: 192.168.1.76 - - [28/Sep/2024 15:56:10] "GET /favicon.ico HTTP/1.1" 200 -
2024-09-28 15:56:27,693 :: INFO :: <Request 'http://localhost:5000/charge_control?vin=MyVIN' [GET]>
2024-09-28 15:56:27,694 :: INFO :: save config change
2024-09-28 15:56:27,695 :: INFO :: 172.30.32.1 - - [28/Sep/2024 15:56:27] "GET /charge_control?vin=MyVIN HTTP/1.1" 200 -
2024-09-28 15:56:27,697 :: INFO :: 172.30.32.1 - - [28/Sep/2024 15:56:27] "GET /get_vehicleinfo/MyVIN?from_cache=1 HTTP/1.1" 200 -
2024-09-28 15:56:44,406 :: INFO :: Preconditioning: topic: psa/RemoteServices/from/cid/AP-ACNT200003476968/ThermalPrecond: {'asap': 'activate', 'programs': {'program1': {'day': [0, 0, 0, 0, 0, 0, 0], 'hour': 34, 'minute': 7, 'on': 0}, 'program2': {'day': [0, 0, 0, 0, 0, 0, 0], 'hour': 34, 'minute': 7, 'on': 0}, 'program3': {'day': [0, 0, 0, 0, 0, 0, 0], 'hour': 34, 'minute': 7, 'on': 0}, 'program4': {'day': [0, 0, 0, 0, 0, 0, 0], 'hour': 34, 'minute': 7, 'on': 0}}}
2024-09-28 15:56:44,407 :: ERROR :: Can't refresh remote token, please redo otp procedure
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 157, in _refresh_remote_token
    self.manager.refresh_token_now()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
    raise RateLimitException
psa_car_controller.common.utils.RateLimitException
2024-09-28 15:56:44,408 :: INFO :: 172.30.32.1 - - [28/Sep/2024 15:56:44] "GET /preconditioning/MyVIN/1 HTTP/1.1" 200 -`

**Comment by R-dehaan** [comment]
Same issue here

**Comment by altbla** [comment]
Same here, started about 1.5 months ago..

**Comment by weirdo1971** [comment]
same here; cant' get it to work in HA or docker

**Comment by altbla** [comment]
> Problem solved with de- and reinstalling PSA_car_controller

Tried it and didnt help, check your logs. It works about half the time, the other half it isnt and you have RateLimit in the log.

**Comment by Jordan87** [comment]
I also tried reinstalling whole addon in HA, and right after installation and whole OTP process same issue is present.
Status is updating if I use car or start charging from my charging station, but im not able to start/postpone charge or precondition from psacc

**Comment by altbla** [comment]
my guess is Stelantis servers are limiting us, because the addon makes too many connections to them every day. I know the addon uses local cache so it doesnt query the server every few minutes, but it seems like its still too often, maybe Stelantis reduced the daily limit recently?

**Comment by Jordan87** [comment]
For me no change after removing or reinstalling MyPeugeot app.
Can you try to use i.e. this command if you will see those errors in logs after it?
http://homeassistant.local:5000/wakeup/YourVIN (of course with proper link for HA and your VIN)

**Comment by Jordan87** [comment]
It seems that it started to work again from last Sunday evenig. No change from my side in psacc or MyPeugeot android app.

I see from time to time "please redo OTP" in logs but it is sporadic and code 401 visible before that error

```
2024-10-29 01:29:08,149 :: INFO :: save config change
2024-10-29 01:29:09,190 :: INFO :: token expired, renew
2024-10-29 01:29:09,191 :: ERROR :: can't refresh_remote_token: {'httpCode': '401', 'httpMessage': 'Unauthorized', 'moreInformation': 'Cannot pass the security checks that are required by the target API or operation, Enable debug headers for more details.'}
Create a new one
2024-10-29 01:29:10,957 :: INFO :: token expired, renew
2024-10-29 01:29:10,958 :: ERROR :: Can't refresh remote token, please redo otp procedure
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 177, in _refresh_remote_token
self._get_remote_access_token(otp_code)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 208, in _get_remote_access_token
self.remoteCredentials.access_token = data["access_token"]
KeyError: 'access_token'
2024-10-29 01:29:10,958 :: WARNING :: last request is send again, token was expired
```

So at least for now we can consider that it is working again for me :)

**Comment by Jordan87** [comment]
Today I remembered that I did one more thing over the weekend, I performed system reset in my Peugeot 308 (to factory settings in menu). It was done because my Tomtom traffic services stoped to work (subsription has ended long time ago but it was still working ;) ) and I wanted to check it after reset.
This shouldnt affect psacc but maybe you can try if you have same problems in psacc logs.

**Comment by altbla** [comment]
psa_car_controller.common.utils.RateLimitException
2024-11-02 23:19:49,530 :: INFO :: charging status of VR7xxxxxxxxxxxx14 is InProgress, battery level: 13
2024-11-02 23:19:49,531 :: ERROR :: force_update:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/charge_control.py", line 70, in force_update
self.psacc.remote_client.wakeup(self.vin)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
raise RateLimitException
psa_car_controller.common.utils.RateLimitException

i still keep getting these errors, a bunch of times per day.

**Comment by libertyx82** [comment]
Also here the same Error, OTP was done twice but no change

```
2024-11-06 11:22:28,061 :: ERROR :: Can't refresh remote token, please redo otp procedure
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 177, in _refresh_remote_token
self._get_remote_access_token(otp_code)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 208, in _get_remote_access_token
self.remoteCredentials.access_token = data["access_token"]
KeyError: 'access_token
```

**Comment by jorrevanmunster** [comment]
I got the same issue, which causes the data from the car being out of date. My log:
```
2024-11-19 12:36:55,854 :: INFO :: charging status of [VIN] is InProgress, battery level: 28
2024-11-19 12:36:55,854 :: ERROR :: force_update:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/charge_control.py", line 70, in force_update
    self.psacc.remote_client.wakeup(self.vin)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
    raise RateLimitException
psa_car_controller.common.utils.RateLimitException

```

**Comment by libertyx82** [comment]
I guess that it is an issue on the API Side, the App does also not working

**Comment by Jordan87** [comment]
App for me is working fine but in psacc I see again those errors and all actions from psacc are not working (also status update during charging)

**Comment by rexasso** [comment]
Hi there,
Best wishes!
Same issue since couple of days. Accessing data is ok but remote control for preconditioning or charge fails. Logs still the same "Can't refresh remote token".
I try resinstalling add on in HA, install fix version in HAV from https://github.com/raphaelbarreiros/psacc-ha, create my own CT in proxmox and then setup fresh new docker version. Everytime the same issue in logs.

I have noticed 2 things:
1. While making the enrollement process and when we have to get the code for oauth2 in the network tab: the request is red and mentionned "canceled": is it normal ? Size is also 0
![image](https://github.com/user-attachments/assets/faf5aae6-a3a0-443c-a863-375e9ed0ba9c)

2. I looked at Stellantis web side, it looks like they strongly improved security as it is now necessary to enroll app and then generate CSR (SSL certificate). Is it something new ?

Any help is welcome
Thanks

**Comment by JaySea77** [comment]
"Can't refresh remote token, please redo otp procedure"
This happens every other couple weeks. After redoing it, it just comes back after a couple weeks again.
How can we make it keep working?

**Comment by altbla** [comment]
how long has it been working for you now?
usually it works for a few days and then starts throwing up token errors and rate limit exception..

> steps I did to solve it:
> 
> * in the app on my phone, I removed all data/cache related to the app
> * logged in in the app on the phone; it asked me to reset the number of linked apps (which was above 20)
> * did try to login via the psa_car_controller which worked, but I was now getting rate_limit exceptions
> * decided to turn off psa_car_controller for an hour, and also remove all data/cache from the app on the phone
> * restarted psa_car_controller, and I now have a working set-up again; can't use the phone app for now, but managing via HA is much easier compared to the phone anyway...

**Comment by rexasso** [comment]
Hi guys,
Thanks for your response. Just to check but I am afraid we are mixing two topics here :
1. reaching maximum number of connection / linked apps (above 20)
2. having only few connections (in my case I have mobile apps on 3 mobile devices + 1 psa controller)

In my case I can still "read info" (battery, mileage,...) but no command accepted.

Do you mean both situation are linked ? Does that mean when my container restart and I have to reconnect I "burn" a token so afer 20 reconnect even with same containrized PSA, i reach the 20 max? Thus how to clean this listed registered apps? What do you mean "It asked me to reset the number of linked apps"?

Other question : when you retrieve token in the "id=XXXXXX&scope" oauth2 logs, do you see that the oauth request is failing in Chrome network logs ?

Thanks

**Comment by wjansenw** [comment]
I indeed think they are connected.

I was getting mileage info, battery status, but only in a push-mode. Never in a pull mode. Eg. if the car was charging, I would only get the update when charging started, and when it finished. While the car was driving, i would get regular battery levels and mileage info.
But start/stop of charge and/or preconditioning or getting battery charge levels while charging: no updates - unless I refreshed the battery status in the app on my phone.

I indeed think that if you need to enter the received text message, it burns one of the 20 connected devices.
The only way to reset it, is to remove all data related to the app on the phone and go through the login and reset procedure. And afterwards, reconfigure the container.

Not sure how long it will now continue to work. Will update when it stops.

Regards,

**Comment by altbla** [comment]
I for one tried to re-install (also clear app data) a few times, never received the "clear all connected devices".
But i am running the old version of the app, from mid summer, before the update that broke everything.
Will not update, unless this reset connection feature is added in the newest version from october?

**Comment by wjansenw** [comment]
No idea - I am running the october version apparently.

**Comment by wjansenw** [comment]
FYI - since I cleared all the logins via the app, I haven't had an issue anymore. Aside from 2 moments where I was no longer receiving updates - but no pattern observed yet, so might be related to issue on the psa-side.

**Comment by Knarfgm** [comment]
Hi,
is there any news about this topic ?
I noticed I have this problem at least once a month and always when I'm charging the car.
During the charging process, communication with car get stuck. Data refreshment is no more available for 2 or 3 days and communication comes back. When it happens, I stop the app : I have the feeling that the communication comes back faster. I restart when communication is back with my mobile app.
It seems application sends a lot of requests till it reachs the rate limit and block the car.
I paste here an extract of my log file in case it may help somebody :

2025-03-11 08:02:29,826 :: INFO :: charging status of MyVIN is InProgress, battery level: 33
2025-03-11 08:04:28,399 :: INFO :: charging status of MyVIN is InProgress, battery level: 33
2025-03-11 08:06:28,351 :: INFO :: charging status of MyVIN is InProgress, battery level: 33
2025-03-11 08:08:28,681 :: INFO :: charging status of MyVIN is InProgress, battery level: 33
2025-03-11 08:10:28,735 :: INFO :: charging status of MyVIN is InProgress, battery level: 33
2025-03-11 08:10:59,259 :: INFO :: 192.168.1.43 - - [11/Mar/2025 08:10:59] "[37mGET /get_vehicleinfo/MyVIN HTTP/1.1[0m" 200 -
2025-03-11 08:10:59,269 :: INFO :: 192.168.1.43 - - [11/Mar/2025 08:10:59] "[37mGET /vehicles/chargings HTTP/1.1[0m" 200 -
2025-03-11 08:10:59,271 :: INFO :: <Request 'http://192.168.1.41:5010/charge_control?vin=MyVIN' [GET]>
2025-03-11 08:10:59,272 :: INFO :: 192.168.1.43 - - [11/Mar/2025 08:10:59] "[37mGET /charge_control?vin=MyVIN HTTP/1.1[0m" 200 -
2025-03-11 08:10:59,451 :: INFO :: 192.168.1.43 - - [11/Mar/2025 08:10:59] "[37mGET /vehicles/trips HTTP/1.1[0m" 200 -
2025-03-11 08:12:28,397 :: INFO :: charging status of MyVIN is InProgress, battery level: 33
2025-03-11 08:12:28,398 :: INFO :: ask wakeup to MyVIN
2025-03-11 08:12:28,398 :: INFO :: topic: psa/RemoteServices/from/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state: {'action': 'state'}
2025-03-11 08:12:32,729 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:12:32Z","vin":"MyVIN","correlation_id":"55a7c1b9a5854d858fcadc80e114a27520250311071232398","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2025-03-11 08:12:33,063 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:12:33Z","vin":"MyVIN","correlation_id":"55a7c1b9a5854d858fcadc80e114a27520250311071232398","process_code":"901","process_message":"[process.901.vehicle.asleep.key]"}'
2025-03-11 08:12:34,280 :: INFO :: save config change
2025-03-11 08:12:43,243 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:12:43Z","vin":"MyVIN","correlation_id":"55a7c1b9a5854d858fcadc80e114a27520250311071232398","process_code":"903","process_message":"[process.903.request.forwarded.to.vehicle.key]"}'
2025-03-11 08:12:46,762 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state b'{"resp_date":"2025-03-11T07:12:46Z","vin":"MyVIN","correlation_id":"55a7c1b9a5854d858fcadc80e114a27520250311071232398","return_code":"0","resp_data":{}}'
2025-03-11 08:14:28,832 :: INFO :: new position recorded for MyVIN
2025-03-11 08:14:28,832 :: INFO :: update_data
2025-03-11 08:14:29,640 :: INFO :: update_data
2025-03-11 08:14:30,310 :: INFO :: charging status of MyVIN is InProgress, battery level: 39
2025-03-11 08:16:28,370 :: INFO :: charging status of MyVIN is InProgress, battery level: 39
2025-03-11 08:18:28,448 :: INFO :: charging status of MyVIN is InProgress, battery level: 39
2025-03-11 08:20:30,085 :: INFO :: charging status of MyVIN is InProgress, battery level: 39
2025-03-11 08:20:59,232 :: INFO :: 192.168.1.43 - - [11/Mar/2025 08:20:59] "[37mGET /get_vehicleinfo/MyVIN HTTP/1.1[0m" 200 -
2025-03-11 08:20:59,243 :: INFO :: 192.168.1.43 - - [11/Mar/2025 08:20:59] "[37mGET /vehicles/chargings HTTP/1.1[0m" 200 -
2025-03-11 08:20:59,245 :: INFO :: <Request 'http://192.168.1.41:5010/charge_control?vin=MyVIN' [GET]>
2025-03-11 08:20:59,246 :: INFO :: 192.168.1.43 - - [11/Mar/2025 08:20:59] "[37mGET /charge_control?vin=MyVIN HTTP/1.1[0m" 200 -
2025-03-11 08:20:59,440 :: INFO :: 192.168.1.43 - - [11/Mar/2025 08:20:59] "[37mGET /vehicles/trips HTTP/1.1[0m" 200 -
2025-03-11 08:22:28,354 :: INFO :: charging status of MyVIN is InProgress, battery level: 39
2025-03-11 08:24:28,361 :: INFO :: charging status of MyVIN is InProgress, battery level: 39
2025-03-11 08:24:28,361 :: INFO :: ask wakeup to MyVIN
2025-03-11 08:24:28,361 :: INFO :: topic: psa/RemoteServices/from/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state: {'action': 'state'}
2025-03-11 08:24:29,730 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:24:29Z","vin":"MyVIN","correlation_id":"e567af75bc584a86b1a56a69c82bb12020250311072429521","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2025-03-11 08:24:30,030 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:24:30Z","vin":"MyVIN","correlation_id":"e567af75bc584a86b1a56a69c82bb12020250311072429521","process_code":"901","process_message":"[process.901.vehicle.asleep.key]"}'
2025-03-11 08:24:34,293 :: INFO :: save config change
2025-03-11 08:24:40,258 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:24:40Z","vin":"MyVIN","correlation_id":"e567af75bc584a86b1a56a69c82bb12020250311072429521","process_code":"903","process_message":"[process.903.request.forwarded.to.vehicle.key]"}'
2025-03-11 08:24:43,461 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state b'{"resp_date":"2025-03-11T07:24:43Z","vin":"MyVIN","correlation_id":"e567af75bc584a86b1a56a69c82bb12020250311072429521","return_code":"0","resp_data":{}}'
2025-03-11 08:26:29,310 :: INFO :: charging status of MyVIN is InProgress, battery level: 39
2025-03-11 08:26:29,311 :: INFO :: ask wakeup to MyVIN
2025-03-11 08:26:29,311 :: INFO :: topic: psa/RemoteServices/from/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state: {'action': 'state'}
2025-03-11 08:26:34,149 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:26:34Z","vin":"MyVIN","correlation_id":"f92ac2163ae34bc99d2d342e49608cab20250311072633919","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2025-03-11 08:26:34,181 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:26:34Z","vin":"MyVIN","correlation_id":"f92ac2163ae34bc99d2d342e49608cab20250311072633919","process_code":"901","process_message":"[process.901.vehicle.asleep.key]"}'
2025-03-11 08:26:34,296 :: INFO :: save config change
2025-03-11 08:28:03,345 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state b'{"resp_date":"2025-03-11T07:28:03Z","vin":"MyVIN","correlation_id":"f92ac2163ae34bc99d2d342e49608cab20250311072633919","return_code":"300"}'
2025-03-11 08:28:03,345 :: ERROR :: 300 : ?
2025-03-11 08:28:28,355 :: INFO :: charging status of MyVIN is InProgress, battery level: 39
2025-03-11 08:28:28,355 :: INFO :: ask wakeup to MyVIN
2025-03-11 08:28:28,355 :: INFO :: topic: psa/RemoteServices/from/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state: {'action': 'state'}
2025-03-11 08:28:30,165 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:28:30Z","vin":"MyVIN","correlation_id":"a0f299b7fe9842abb0a721b69d3dc8ec20250311072829919","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2025-03-11 08:28:30,464 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:28:30Z","vin":"MyVIN","correlation_id":"a0f299b7fe9842abb0a721b69d3dc8ec20250311072829919","process_code":"901","process_message":"[process.901.vehicle.asleep.key]"}'
2025-03-11 08:28:34,298 :: INFO :: save config change
2025-03-11 08:28:40,440 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:28:40Z","vin":"MyVIN","correlation_id":"a0f299b7fe9842abb0a721b69d3dc8ec20250311072829919","process_code":"903","process_message":"[process.903.request.forwarded.to.vehicle.key]"}'
2025-03-11 08:28:43,633 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state b'{"resp_date":"2025-03-11T07:28:43Z","vin":"MyVIN","correlation_id":"a0f299b7fe9842abb0a721b69d3dc8ec20250311072829919","return_code":"0","resp_data":{}}'
2025-03-11 08:30:29,933 :: INFO :: charging status of MyVIN is InProgress, battery level: 39
2025-03-11 08:30:29,933 :: INFO :: ask wakeup to MyVIN
2025-03-11 08:30:29,934 :: INFO :: topic: psa/RemoteServices/from/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state: {'action': 'state'}
2025-03-11 08:30:31,187 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:30:31Z","vin":"MyVIN","correlation_id":"4c66959d489147a9a1c25c9c0a11de4a20250311073030962","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2025-03-11 08:30:31,206 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:30:31Z","vin":"MyVIN","correlation_id":"4c66959d489147a9a1c25c9c0a11de4a20250311073030962","process_code":"903","process_message":"[process.903.request.forwarded.to.vehicle.key]"}'
2025-03-11 08:30:34,299 :: INFO :: save config change
2025-03-11 08:30:35,214 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state b'{"resp_date":"2025-03-11T07:30:35Z","vin":"MyVIN","correlation_id":"4c66959d489147a9a1c25c9c0a11de4a20250311073030962","return_code":"0","resp_data":{}}'
2025-03-11 08:30:59,167 :: INFO :: 192.168.1.43 - - [11/Mar/2025 08:30:59] "[37mGET /get_vehicleinfo/MyVIN HTTP/1.1[0m" 200 -
2025-03-11 08:30:59,177 :: INFO :: 192.168.1.43 - - [11/Mar/2025 08:30:59] "[37mGET /vehicles/chargings HTTP/1.1[0m" 200 -
2025-03-11 08:30:59,180 :: INFO :: <Request 'http://192.168.1.41:5010/charge_control?vin=MyVIN' [GET]>
2025-03-11 08:30:59,181 :: INFO :: 192.168.1.43 - - [11/Mar/2025 08:30:59] "[37mGET /charge_control?vin=MyVIN HTTP/1.1[0m" 200 -
2025-03-11 08:30:59,426 :: INFO :: 192.168.1.43 - - [11/Mar/2025 08:30:59] "[37mGET /vehicles/trips HTTP/1.1[0m" 200 -
2025-03-11 08:32:28,374 :: INFO :: charging status of MyVIN is InProgress, battery level: 39
2025-03-11 08:32:28,375 :: INFO :: ask wakeup to MyVIN
2025-03-11 08:32:28,375 :: INFO :: topic: psa/RemoteServices/from/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state: {'action': 'state'}
2025-03-11 08:32:29,615 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:32:29Z","vin":"MyVIN","correlation_id":"d370dcdcca8e443e835ddf90a249bdb720250311073229392","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2025-03-11 08:32:29,925 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:32:29Z","vin":"MyVIN","correlation_id":"d370dcdcca8e443e835ddf90a249bdb720250311073229392","process_code":"901","process_message":"[process.901.vehicle.asleep.key]"}'
2025-03-11 08:32:34,302 :: INFO :: save config change
2025-03-11 08:32:40,243 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:32:40Z","vin":"MyVIN","correlation_id":"d370dcdcca8e443e835ddf90a249bdb720250311073229392","process_code":"903","process_message":"[process.903.request.forwarded.to.vehicle.key]"}'
2025-03-11 08:32:43,483 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state b'{"resp_date":"2025-03-11T07:32:43Z","vin":"MyVIN","correlation_id":"d370dcdcca8e443e835ddf90a249bdb720250311073229392","return_code":"0","resp_data":{}}'
2025-03-11 08:34:28,440 :: INFO :: charging status of MyVIN is InProgress, battery level: 39
2025-03-11 08:34:28,440 :: INFO :: ask wakeup to MyVIN
2025-03-11 08:34:28,440 :: INFO :: topic: psa/RemoteServices/from/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state: {'action': 'state'}
2025-03-11 08:34:28,441 :: ERROR :: Can't refresh remote token, please redo otp procedure
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 157, in _refresh_remote_token
    self.manager.refresh_token_now()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
    raise RateLimitException
psa_car_controller.common.utils.RateLimitException
2025-03-11 08:34:28,961 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:34:28Z","vin":"MyVIN","correlation_id":"7ed5158823434f68a4e96e18e30ad0d920250311073428447","process_code":"900","process_message":"[process.900.request.accepted.key]"}'
2025-03-11 08:34:28,982 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state/ProcessManagement b'{"process_date":"2025-03-11T07:34:28Z","vin":"MyVIN","correlation_id":"7ed5158823434f68a4e96e18e30ad0d920250311073428447","process_code":"903","process_message":"[process.903.request.forwarded.to.vehicle.key]"}'
2025-03-11 08:34:32,999 :: INFO :: mqtt msg received: psa/RemoteServices/to/cid/AP-XXXXXXXXXXXXXXXX/VehCharge/state b'{"resp_date":"2025-03-11T07:34:32Z","vin":"MyVIN","correlation_id":"7ed5158823434f68a4e96e18e30ad0d920250311073428447","return_code":"0","resp_data":{}}'
2025-03-11 08:36:28,448 :: INFO :: charging status of MyVIN is InProgress, battery level: 39
2025-03-11 08:36:28,449 :: ERROR :: force_update:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/charge_control.py", line 70, in force_update
    self.psacc.remote_client.wakeup(self.vin)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
    raise RateLimitException
psa_car_controller.common.utils.RateLimitException
2025-03-11 08:38:29,503 :: INFO :: charging status of MyVIN is InProgress, battery level: 39
2025-03-11 08:38:29,504 :: ERROR :: force_update:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/charge_control.py", line 70, in force_update
    self.psacc.remote_client.wakeup(self.vin)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
    raise RateLimitException
psa_car_controller.common.utils.RateLimitException
2025-03-11 08:40:29,607 :: INFO :: charging status of MyVIN is InProgress, battery level: 39
2025-03-11 08:40:29,607 :: ERROR :: force_update:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/charge_control.py", line 70, in force_update
    self.psacc.remote_client.wakeup(self.vin)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
    raise RateLimitException
psa_car_controller.common.utils.RateLimitException
