### ISSUE TITLE
PSACC installing as a addon on homeassistant and unable to activate

### ISSUE THREAD

**Issue by markoku** [flobz/psa_car_controller#983]
Hi!

I have installed psacc earlier and it worked ok for some time. Updated it once, got broken and after reactivation it worked fine.

Now situation is so that psacc didn't open at all and in logs were some errors and when restarted said that there are 177 trips that needs to load it might take a while. So I uninstalled psacc and tried to reinstall as a addon. Not so big a surprise is that I cannot activate this. I open myhaip:5000, screen opens and asks for brand (I give Citroen), my email (I provide it) and password for MyCitroen-site and Countrycode (in my case FI). After that it takes quite a while and after that I get long error list (below).

Last time I found some site that had some solution for activating (needed to press show network and to stop page loading at some point and provide some code so somewhere) and now I cannot find it.

Info about system:  
HAOS
Core 2024.10.3
Supervisor 2024.10.2
Operating System 13.2
Käyttöliittymä 20241002.3

`Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 468, in _make_request six.raise_from(e, None) File "<string>", line 3, in raise_from File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 463, in _make_request httplib_response = conn.getresponse() File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse response.begin() File "/usr/lib/python3.9/http/client.py", line 307, in begin version, status, reason = self._read_status() File "/usr/lib/python3.9/http/client.py", line 268, in _read_status line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") File "/usr/lib/python3.9/socket.py", line 704, in readinto return self._sock.recv_into(b) File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into return self.read(nbytes, buffer) File "/usr/lib/python3.9/ssl.py", line 1099, in read return self._sslobj.read(len, buffer) socket.timeout: The read operation timed out During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 667, in send resp = conn.urlopen( File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 802, in urlopen retries = retries.increment( File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 552, in increment raise six.reraise(type(error), error, _stacktrace) File "/usr/local/lib/python3.9/dist-packages/urllib3/packages/six.py", line 770, in reraise raise value File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 716, in urlopen httplib_response = self._make_request( File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 470, in _make_request self._raise_timeout(err=e, url=url, timeout_value=read_timeout) File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 358, in _raise_timeout raise ReadTimeoutError( urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='mw-ap-m2c.mym.awsmpsa.com', port=443): Read timed out. (read timeout=10) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 80, in __fetch_user_info res2 = requests.post( File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 115, in post return request("post", url, data=data, json=json, **kwargs) File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 713, in send raise ReadTimeout(e, request=request) requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='mw-ap-m2c.mym.awsmpsa.com', port=443): Read timed out. (read timeout=10)`

**Comment by markoku** [comment]
Newer mind, for some reason it got working.
