### ISSUE TITLE
No data from Peugeot e-Rifter

### ISSUE THREAD

**Issue by floppybl** [flobz/psa_car_controller#989]
Describe the bug
Getting no data from my Peugeot e-Rifter (2024 before facelift).
After checking the logs I don't get it why there is no data. Found some errors that I don't understand. Maybe some of you can make this clear. 

`2024-11-10 17:26:39,580 :: ERROR :: refresh_vehicle_info:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 128, in __refresh_vehicle_info
self.get_vehicle_info(car.vin)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 109, in get_vehicle_info
car.status = res
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car.py", line 81, in status
self._status.correct(self.is_electric())
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car_status.py", line 38, in correct
if len(self._energy) == 2 and self._energy[0].type != 'Electric':
TypeError: object of type 'NoneType' has no len()
2024-11-10 17:28:39,705 :: ERROR :: refresh_vehicle_info:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 128, in __refresh_vehicle_info
self.get_vehicle_info(car.vin)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 109, in get_vehicle_info
car.status = res
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car.py", line 81, in status
self._status.correct(self.is_electric())
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car_status.py", line 38, in correct
if len(self._energy) == 2 and self._energy[0].type != 'Electric':
TypeError: object of type 'NoneType' has no len()
2024-11-10 17:30:20,422 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:20] "[37mGET / HTTP/1.1[0m" 200 -
2024-11-10 17:30:20,437 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:20] "[36mGET /assets/99_custom_overides.css?m=1725110333.0 HTTP/1.1[0m" 304 -
2024-11-10 17:30:20,438 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:20] "[36mGET /assets/clientside.js?m=1725110333.0 HTTP/1.1[0m" 304 -
2024-11-10 17:30:20,528 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:20] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-11-10 17:30:20,529 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:20] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2024-11-10 17:30:20,544 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:20] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-11-10 17:30:20,561 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:20] "[37mGET /control?header=false HTTP/1.1[0m" 200 -
2024-11-10 17:30:20,563 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:20] "[36mGET /assets/images/settings.svg HTTP/1.1[0m" 304 -
2024-11-10 17:30:20,563 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:20] "[36mGET /assets/images/consumption.svg HTTP/1.1[0m" 304 -
2024-11-10 17:30:20,564 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:20] "[36mGET /assets/images/pollution.svg HTTP/1.1[0m" 304 -
2024-11-10 17:30:20,564 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:20] "[36mGET /assets/images/battery-charge-line.svg HTTP/1.1[0m" 304 -
2024-11-10 17:30:20,565 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:20] "[36mGET /assets/images/electricity%20bill.svg HTTP/1.1[0m" 304 -
2024-11-10 17:30:20,608 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:20] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-11-10 17:30:20,608 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:20] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2024-11-10 17:30:20,614 :: ERROR :: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/dash/dash.py", line 1373, in dispatch
ctx.run(
File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 465, in add_context
output_value = _invoke_callback(func, *func_args, **func_kwargs)
File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 40, in _invoke_callback
return func(*args, **kwargs) # %% callback invoked %%
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 88, in display_page
page = get_control_tabs(APP)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/control.py", line 41, in get_control_tabs
car.status.get_energy('Electric').level))],
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car_status.py", line 56, in get_energy
for energy in self._energy:
TypeError: 'NoneType' object is not iterable
2024-11-10 17:30:20,614 :: ERROR :: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/dash/dash.py", line 1373, in dispatch
ctx.run(
File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 465, in add_context
output_value = _invoke_callback(func, *func_args, **func_kwargs)
File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 40, in _invoke_callback
return func(*args, **kwargs) # %% callback invoked %%
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 88, in display_page
page = get_control_tabs(APP)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/control.py", line 41, in get_control_tabs
car.status.get_energy('Electric').level))],
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car_status.py", line 56, in get_energy
for energy in self._energy:
TypeError: 'NoneType' object is not iterable
2024-11-10 17:30:20,631 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:20] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
2024-11-10 17:30:38,458 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:38] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-11-10 17:30:38,762 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:38] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-11-10 17:30:38,763 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:38] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 -
2024-11-10 17:30:38,763 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:38] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 -
2024-11-10 17:30:39,948 :: ERROR :: refresh_vehicle_info:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 128, in __refresh_vehicle_info
self.get_vehicle_info(car.vin)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 109, in get_vehicle_info
car.status = res
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car.py", line 81, in status
self._status.correct(self.is_electric())
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car_status.py", line 38, in correct
if len(self._energy) == 2 and self._energy[0].type != 'Electric':
TypeError: object of type 'NoneType' has no len()
2024-11-10 17:30:50,267 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:50] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-11-10 17:30:50,289 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:50] "[37mGET /control?header=false HTTP/1.1[0m" 200 -
2024-11-10 17:30:50,367 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:50] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-11-10 17:30:50,367 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:50] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2024-11-10 17:30:50,382 :: ERROR :: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/dash/dash.py", line 1373, in dispatch
ctx.run(
File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 465, in add_context
output_value = _invoke_callback(func, *func_args, **func_kwargs)
File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 40, in _invoke_callback
return func(*args, **kwargs) # %% callback invoked %%
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 88, in display_page
page = get_control_tabs(APP)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/control.py", line 41, in get_control_tabs
car.status.get_energy('Electric').level))],
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car_status.py", line 56, in get_energy
for energy in self._energy:
TypeError: 'NoneType' object is not iterable
2024-11-10 17:30:50,382 :: ERROR :: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/dash/dash.py", line 1373, in dispatch
ctx.run(
File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 465, in add_context
output_value = _invoke_callback(func, *func_args, **func_kwargs)
File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 40, in _invoke_callback
return func(*args, **kwargs) # %% callback invoked %%
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 88, in display_page
page = get_control_tabs(APP)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/control.py", line 41, in get_control_tabs
car.status.get_energy('Electric').level))],
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car_status.py", line 56, in get_energy
for energy in self._energy:
TypeError: 'NoneType' object is not iterable
2024-11-10 17:30:50,383 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:50] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
2024-11-10 17:30:55,864 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:55] "[37mGET / HTTP/1.1[0m" 200 -
2024-11-10 17:30:55,913 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:55] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-11-10 17:30:55,913 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:55] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2024-11-10 17:30:55,923 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:55] "[37mGET /_favicon.ico?v=2.17.1 HTTP/1.1[0m" 200 -
2024-11-10 17:30:55,927 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:55] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-11-10 17:30:55,942 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:55] "[37mGET /control?header=false HTTP/1.1[0m" 200 -
2024-11-10 17:30:58,962 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:30:58] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-11-10 17:31:01,966 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:31:01] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-11-10 17:31:01,967 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:31:01] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-11-10 17:31:01,967 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:31:01] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
2024-11-10 17:31:01,968 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:31:01] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 -
2024-11-10 17:31:01,969 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:31:01] "[37mGET /style.json HTTP/1.1[0m" 200 -
2024-11-10 17:31:01,969 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:31:01] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
2024-11-10 17:31:01,970 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:31:01] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
2024-11-10 17:31:01,988 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:31:01] "[36mGET /assets/sprites/osm-liberty@2x.json HTTP/1.1[0m" 304 -
2024-11-10 17:31:01,988 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:31:01] "[36mGET /assets/sprites/osm-liberty@2x.png HTTP/1.1[0m" 304 -
2024-11-10 17:31:02,001 :: ERROR :: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/dash/dash.py", line 1373, in dispatch
ctx.run(
File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 465, in add_context
output_value = _invoke_callback(func, *func_args, **func_kwargs)
File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 40, in _invoke_callback
return func(*args, **kwargs) # %% callback invoked %%
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 88, in display_page
page = get_control_tabs(APP)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/control.py", line 41, in get_control_tabs
car.status.get_energy('Electric').level))],
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car_status.py", line 56, in get_energy
for energy in self._energy:
TypeError: 'NoneType' object is not iterable
2024-11-10 17:31:02,001 :: ERROR :: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.9/dist-packages/dash/dash.py", line 1373, in dispatch
ctx.run(
File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 465, in add_context
output_value = _invoke_callback(func, *func_args, **func_kwargs)
File "/usr/local/lib/python3.9/dist-packages/dash/_callback.py", line 40, in _invoke_callback
return func(*args, **kwargs) # %% callback invoked %%
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/views.py", line 88, in display_page
page = get_control_tabs(APP)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/control.py", line 41, in get_control_tabs
car.status.get_energy('Electric').level))],
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/model/car_status.py", line 56, in get_energy
for energy in self._energy:
TypeError: 'NoneType' object is not iterable
2024-11-10 17:31:02,001 :: INFO :: 10.27.5.70 - - [10/Nov/2024 17:31:02] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -`

Environment (please complete the following information):
 - Docker standard setup without any manually set psacc_options
 - Peugeot e-Rifter
 - 3.5.3
 - Log from http://server_address:port/log and browser console log

Do I have some settings missing? Car setup worked without any problems.

Thanks and have a nice day.

**Comment by floppybl** [comment]
After a couple of days now data is showing. Will close this issue.
