### ISSUE TITLE
Controller crashes with ConnectionError in Home Assistant.

### ISSUE THREAD

**Issue by grahamrjuk** [flobz/psa_car_controller#999]
**Describe the bug**
I don't like adding to the list of difficulties with the PSA controller, but I can't start the controller in Home Assistant, always getting:
`ConnectionError`, see log below. The controller tries to start several times and gives up. Since the controller fails to start I can't try to configure it again.

**To Reproduce**
1. what command did you use - `Home Assistant`
2. when the bug happend ? - about a week ago (around 2024-11-10)
3. Does it persist after restarting the program? - Yes
4. Does it persist after recreate config by going to http://server_address:port/config? - The system doesn't start so I can't go and recreate the config. I have cleared the config file I had, in case it was preventing the system starting.

**Config file**
Config file is essentially empty:
```
{
    "abrp": {
        "abrp_enable_vin": [],
        "token": ""
    },
    "client_id": "",
    "client_secret": "",
    "co2_signal_api": null,
    "country_code": "GB",
    "customer_id": "",
    "proxies": {
        "http": "",
        "https": ""
    },
    "realm": "clientsB2CVauxhall",
    "refresh_token": null,
    "remote_refresh_token": "",
    "weather_api": ""
}
```

**Environment (please complete the following information):**
 - OS: [e.g. Windows] - Home Assisrtant OS
 - Brand and model of car - Vauxhall Corsa-E
 - Application version (commit number, branch or tag) - 3.5.3
 - Log from http://server_address:port/log and browser console log
```
Containerised psa_car_controller loading...
2024-11-16 16:49:48,012 :: INFO :: App version 3.5.3
2024-11-16 16:49:48,763 :: ERROR :: Connection need to be updated, Please redo authentication process.
Traceback (most recent call last):
  File "/usr/local/bin/psa-car-controller", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/__main__.py", line 20, in main
    app.load_app()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/car_controller.py", line 118, in load_app
    raise ConnectionError
ConnectionError
2024-11-16 16:49:48,777 :: INFO :: save config change
```

**Additional context**

**Comment by grahamrjuk** [comment]
OK, I had time to do a complete re-install and PSACC is working again for me :-)
